### ISSUE TITLE
Infuse cannot currently play BD Folder 

### ISSUE THREAD

**Issue by Turingrun** [jellyfin/jellyfin#10047]
I use Infuse to connect jellyfin Server 10.8.10 On Debian 11 X64,Infuse can normally play any videos except BDMV Folder. I want to ensure if jellyfin 10.8.10 can analyze bd folder or not,because i try to use swiftfin on my iPad,and it can correctly play bd folder.
![IMG_0405](https://github.com/jellyfin/jellyfin/assets/125971533/9098aeb2-a348-400b-b360-6e4195d46885)

/**Media Info of the file**

![IMG_0404](https://github.com/jellyfin/jellyfin/assets/125971533/7c1a21e0-57fe-43d1-9427-be8efa731d9b)

**Logs**

 `2023-07-28 09:13:30.214 +08:00] [ERR] [48] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "Could not find file '/data/dev-disk-by-uuid-bc9a41a7-65ef-4f63-b80c-de9166f06da7/data2/电影/Weathering With You 2019 2160p UHD Blu-ray HEVC DTS-HD MA 5.1-DIY@PTHome'". URL "GET" "/Videos/cac7cb5eab56fe8f64e7b368fa0eb295/stream". `

**Client System (please complete the following information):**
 - Device: iPad Air 2020
 - OS: iOS
 - Client:  Infuse Pro 7.5.8
 - Client and Browser Version: 7.5.8
 - Jellyfin: 10.8.10 amd64

**Comment by Shadowghost** [comment]
Should be fixed in master by #9254

**Comment by Turingrun** [comment]
> Should be fixed in master by #9254

Ok thanks,i will wait for jellyfin 10.9.

**Comment by marcoxyz123** [comment]
Hi All

I pulled the Docker  jellyfin/jellyfin:unstable (10.9.0)
![Jellyfin](https://github.com/jellyfin/jellyfin/assets/95569770/77f48a47-515e-40f8-829a-70a4a2e96b53)
. The Problem still persists. There is no fix. Please advise if it is not in the current Docker image of unstable.

ISO UHD: 
[2024-01-05 11:48:28.772 +01:00] [ERR] [40] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "Could not find file '/Media/Movies/Spider-Man 2 (2004)'". URL "GET" "/Videos/fe4aa81d40e9643855f3fe9dd643dac0/stream".

BDMV UHD: 
[2024-01-05 11:49:56.193 +01:00] [ERR] [30] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: "Could not find file '/Media/Movies/Alita Battle Angel (2019)'". URL "GET" "/Videos/739dde7150ba287625657b76f623b878/stream".

DVD ISO & Video-TS are working.

Best regards,
Marco

Best regards,
Marco
