### ISSUE TITLE
[Issue]: [414 URI Too Long] while clicking music in album

### ISSUE THREAD

**Issue by libook** [jellyfin/jellyfin#10058]
### Please describe your bug

Steps to reproduce:
1. Open Jellyfin Client, Web or mobile App.
2. Go to Music, and enter detail page of a album.
3. Click a music to play.
4. The loading icon may keep spinning.
5. Open development tools of browser, there may be a "Request URI Too Long" error with response status 414.

The URL is super long. Here is an example Gist: https://gist.github.com/libook/ad0d9500c33a0abd807d4b1cf0d2fea0
I have tested this without reverse proxy server. Issue was still.

But not all musics have this issue. There are some musics in the same album can be played successfully. And all music can be played if I directly click the play button of the album.

### Jellyfin Version

Other

### if other:

10.8.10

### Environment

```markdown
- OS: Debian 11
- Linux Kernel: 5.10.0-23-amd64
- Virtualization: Docker
- Clients: Browser, Android
- Browser: Firefox 115, Chrome 115
- FFmpeg Version: 5.1.3-Jellyfin
- Playback Method: Direct Stream, Transcode
- Hardware Acceleration: NVENC
- GPU Model: RTX2080S
- Plugins: AudioDB, Cover Art Archive, MusicBrainz, OMDb, Open Subtitles, Studio Images, TMDb, TheTVDB
- Reverse Proxy: nginx, none
- Base URL: none
- Networking: Host
- Storage: local for config and metatdata, NFS for media files
```

### Jellyfin logs

```shell
No error in Jellyfin logs.
```

### Please attach any browser or client logs here

browser log: https://gist.github.com/libook/ad0d9500c33a0abd807d4b1cf0d2fea0

### Please attach any screenshots here

![2023-07-31_12-27](https://github.com/jellyfin/jellyfin/assets/3395610/b0bcb387-6c64-414e-bb11-670ac1b6ad84)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bond-009** [comment]
Fixed by https://github.com/jellyfin/jellyfin-web/pull/4221

**Comment by AlexStormwood** [comment]
This is not fixed.

Had to laugh when I saw this post of this issue though - was trying to play an updated version of that same soundtrack. Happens in a few other albums too;

- albums have multiple discs
- albums with 229 tracks or less DON'T have this error
  - Splatune 3 plus fan-assembled tracks -- 229 tracks
  - The Legend of Zelda - Breath of the Wild Original Soundtrack [Limited Edition] (2018) - 211 tracks
- albums with 230 tracks or more DO have this error
  - The Legend of Zelda - Skyward Sword Expanded Video Game Soundtrack (2012) -- 230 tracks
  - Animal Crossing New Horizons Official Soundtrack [Limited Edition] (2021) (this version combines Animal Crossing: New Horizons K.K. Slider Soundtrack Collection (2021) within it as well) -- 268 tracks
  - The Legend of Zelda - Tears of the Kingdom fan-assembled soundtrack (2023) -- 320 tracks
- not all tracks (or specifically, discs) within the album have this error, but it's usually lower-numbered discs or tracks without a disc number that have this error 
  - eg. tracks not part of a disc and tracks from disc 1 of the above Tears of the Kingdom soundtrack don't play, but tracks from disc 2 onwards do play.

The audio files themselves are fine and play in other software, and play on all hardware that I can test it on when downloading the tracks through the Jellyfin client as well.

And as previous others noted, those same tracks play just fine when searched for & played via the search results menu. 

The error is just happening within the album's page that contains these tracks.

When recreating this error in the browser, here's the logged message from when I click on a track to play it from the album page:

```
Request failed to http://SomeIpAndPortWasHere/Users/SomeUserIDWasHere/Items?Ids=dbd828921ff010828572f6c179423fa3%2C59379b0815722d5c84deff602438e890%2C40b0c845e95d4e8c98f4c3985eb38471%2C33e24ac68c67deb0228c8d1e3a6be767%2C4ae6d543194b397ceaece40c58aeb824%2Cd4be3861a0a04b402da5426a02363977%2C44cb0a449311ccc050c571b31c74b455%2C76184b05e27bd299319a8cab51a4210e%2C312d72cc9b37471b684460ef39cbf67a%2C094fbbca3651c1ce22540c54be6033e8%2Cf79d6ca7003738f38ead313591651d49%2Cd2c165d5667009ea1cf1dc3d5d12f6f1%2C00e94cdccd95d2ab4b7cf61e66e36f9e%2C40c6e21acc9d57e640142862fac694ab%2Cb605062fc3824ccfa9721514b95a8894%2C0ef96cffb51dd68a8f4c2fb41e8d2b07%2C6b17098d96b81f6066a3958f184bbb1b%2C65baeeef48f01e678188a0f494f167a8%2C539eb742f6f00c28ff183ac8dceb17f8%2C903ba260e7c134a99de97b7452d86a45%2C2f6fc15dcb5f1554fb76198b033f41bb%2C4bc87d983a8de286c7f6719c29246027%2Cc2d09335e9cfaffdbd7e5be086c10cef%2Cded608904c4b41b77a86641953af97b0%2Ce1d9288553ca908d99d430ae5a3e84f2%2C73a3ff070a03118a7d0999c10a11be87%2C28c8464f4e56bdfcf54849639b58f47a%2C1ad85931a22558fe1ac210e0628f2603%2Ce61f3f25156f562a705aaaee44dbcf6d%2C3ae0e410fbb864de43a3afc61632c103%2C27c5df2da92936ee9924eac7aa0c452a%2C9e323901be184945a64c429b5671cb92%2Ca9576c6a8f9d655a154bdded07a0d85e%2Cd3deaff91d1b7ad18fa9e7a998806c67%2C20fa2614360e969b2bf40bdd9b4de2dd%2Ce7b67faadc548236b359ef447aef8244%2Cdc16e4416b0629293076fea54c4e5531%2C1e39996eb62320f49e068a1fe279e056%2C938d2dbd73957bb5cece562ed75ddc8e%2C1b07023d1695eb3bf20a17768d97581f%2C590d78caa8074ab33ba0baf15bc96224%2C15466c048f9521aa14b41071a2ea242e%2C69a36a8feea174c648007855639f6f17%2Cc7cb6cf103ec80984354a21379e790a7%2C2c51e34de2b7fa140a7ee6014a4e79a3%2C0bd7efeaeffaca7d036ed940de583670%2Ccb9d2e4c15855c551c532f28552fb8cf%2C3e492ec5102975a6b20f6c70f7376590%2C90d12fb5d778fc86ec8807ae7f8fd9e7%2Cfcccdd5dc6b8531b16b4c1d23df7089d%2C07a93ba96afe0f29cd5dc4314b07126f%2Ce8c7202b4f08d72fb8f4fdc8564d2b4f%2C94d0bd63f33c50319251ac433fffad0e%2C032c6c586247a4d4309116cbe13980db%2C7c102961aaa14146ef318feef2b6ce4b%2C6567dd10d7e17ff5ad61d3bac2045f94%2C9c3ea95bec6d00db440e477b3443829b%2C705bb552e849dc4ad8021dcfd1fa05db%2C62d85228155b7eff837682b8be923b58%2C8d5299e16146b7fe862b5ea0d2f3533e%2C6c33b95c3978f2b1a268a99d84d9c6e3%2Cd48cf6092f95b59beea171d4c6d3e27f%2C9af3eea47f34fc16b37c85742e45e2aa%2C1faddb27568d59c8f57023458f424076%2Ca543265d538a347c900687017f568347%2Cd509942244f1d4a0cc54d7815139eb6e%2C005bc2f704dc242c9d657a3e69a71dda%2Cf77767807162694c020c170301b470af%2C7da709b7023f02f405d10871cedbe102%2Cc16f5bd96226d327f4934010f87f17c3%2Cb42cc20792e22fe30310ec55f7812670%2C5b6aee4e8828beb3f13c641760a13b0e%2C885a972f299979537f65835d39ff3dd2%2Ca672dfbb4aac4bf4a87532d95e18dd9c%2Ce3c566bae3750432fff7baf73b18520e%2Caba70d7d8260a81c5be3adc607bdf4d2%2Cd52e2c4b307af079c8a7b904becefe51%2C2d2c6c2c6469e3049bdcda41bd3b9dd1%2Cd2178a58748f6a93e84be1a949227549%2C8d89be2e1d0c674703f21c1aab0da6f4%2C2ee4a8ab2f8f527dcd04645d5bcf1995%2C91287cf514ba6d46a333096c59a22955%2C6fedae9ae3d790d712c22bf00c797a0b%2C1281097771d8dbc054cf5b2f93571332%2C06ffbd5189ee52b36398dc745d32a9c2%2C63fcf4022027b2873b2045fac71a08b0%2C1a6b85a09cafff73baa60ec16f181210%2Ca173744dc3408f24f96c435f800e531d%2C41bc7535dbbab7ca3c63c2000bb11c4e%2Cab1599b72fea25ea2c10e4b243a9767c%2C28963b97f5934f750efc49f7eab44bb4%2Cde9b8662bff51fb108f03f2c2ffa8f24%2C6fe20894ff5a607e8931623479566082%2Cf16af6657ae65a7402ea26312badf19d%2Cd3c15d5b7a71d0911fe6d9db1708da7a%2C873b9474c2c97fb72b4235c8c33737e1%2C498d03d25b6cc42d68848c90a05f256c%2Cb127a7dc9f2447422480b35d50a74e2c%2Ca284b9c653bf2a930066b774cc0f4bae%2C55f6df740c3281e6f4bc4cc8ef7f5b79%2Cccb660bf0dd0fe3b58a774da2fe7cbb5%2C5366b1e0687ded088997e647a009e3e3%2Ccc3d9cc1141e5e641c3aef3acbf904fc%2C64af2c889df9ac06bafd75af766bdd27%2C0c8f89ab8323a30e8dd2c33a0dbdc8ac%2C35825691fb574cf9f28a3f0f1b4f1379%2C2322925e0f3a9871b6cddff87ec285c6%2C2379ba4929515e9dad0d153561cabc62%2C8e2da3765f17110011406bb0a72efa38%2C3557d7a1d2aa46cc4067ebd4f0a9bed3%2C1b83b5c6739ac3d674745d4de113a2a6%2C7c1384d5bb8182791b68ca5ccccb868f%2Cc4fc29f1bd30780691cd91a69d06e30a%2C7ab7351619c880db7fa0817d8551b45e%2Ca21941966de6bde7c6dcf6ace843f615%2Cef3189525df7b164c23eb6dd7da1b3c6%2Cd1876fc129d7523ade71f619d2e7790e%2C0c82e85bd3cfaf98342db79a708a35a3%2C42468bbf0571b63c44cc2a55c6cdbaea%2Ca24ff6c9a1cecfdbe733d27521d0ab69%2C1da9848ebe00d84cf9e116032ba7c64d%2C838ca545491aa0a973ebe95577a18d5a%2Cd2d6ef0c04a45de7ed07ffec18c138e0%2Ccab6e61b1f5ef64b35f166eaa261b721%2Cd187e11584f175e353d914c0dedb64cf%2Cb9e67b827a4253e6b30f8876463859f3%2Cd9d6c73675c642ae14df2e802c850670%2Cb444fac42d6e20f2d66d2b5e01efd5c7%2Cd6076a39f328a5ba0075ca1f7bc99052%2C8823af65725ede9489d7d45d8ca340d6%2Cc2cb17a4810b01b25bb4e4813483cbdd%2C3c7caecc39cbf4c4b1717f79331364ec%2C63c30bac43d1ffad36352c5cb4d5e4ea%2C733b640034f8c31010abc11677f7b573%2Ca9a822e0870ac725e9c53368ec1deb7b%2Cf02ee91fe44fdec77ef2b41d7283bb4a%2C50821a4d9afb90a367b794279f7c7ceb%2C6a5eef38b5f5507ff690b53cd0d39a7d%2C13608e05129af8cac11d203a982403de%2Cca1273be8f12bda205287c91e03a1892%2Cc08281a6bb2484d6e90fd89139fda514%2Cbfa10bc1c959e9b0c048eef35327ab4c%2C726819861a01e828f611e11713e3e5b5%2C11887449c347e44b7520ef6eec5c3e94%2Ce3c2b9a4aa8ce8a02e2b195cddd07f8a%2C45cd9ecb89e2afc87c679317f42d417f%2C461ff6c38786c6fba82518da19cd6981%2C3f8c15d1b6cdb9ed30972c4973b31754%2C5a4f62e2adb223475c7323dbea2cbab9%2C8905b5bb78b143d0e19eae70f945e5ca%2Cb67abe0400c0aab3ce25ccbc13a1a25d%2C2734d3f0c2b49148bf2576fbeb35556f%2C94b77b5688cd665e9a18db8819f3ee36%2C05bb1acf891689e546209e26d2940858%2Ccdbdef14364320e800ad20d163a22b47%2C50b6fcaae62139a65b770e9799198857%2C2fa207fbafad56f8efc254a7bb441e5e%2Ce89bbca05be8af3298173a4a6cad7bc0%2C5b7802e7bd5a3f71ca233c3339829f50%2C9121b27a3242f7687a3d2edc804a7076%2C22e3819dc86f6e58f777ebe4b40b0722%2Ca9fc7c7695d5ede52b5a494e4e8bffa4%2Ca02796ccdb1c91cb873a5cb15191745c%2C86fc1f2e161570a506396f0d647fa9d6%2C9cad8a165882cb9c7e0340a19cb839d6%2C99a5c80ec689ae93de7948663d45f088%2C9492e2db54a97ccb125ef2e3f01a3323%2C1561ba9caafe3df4b2d7edc5789e8d28%2C821d5a9ac55303a475cb4d3aaa072c49%2Cfb8d70898b33e552f71bbf60482c1f2b%2Cd99f6cdb45e3fe99b8be7329d1a0e270%2C476d8d0403f8391900e844facfa47bf2%2C7741ef05585e0cc9d94adf2f7cd30f13%2C0e3d6c106669e5ee6d4bdfccd53f517b%2C4f3b20f6cb4116f8f06f41d836248ee6%2Cdaf381f0b382c60303be4665041526aa%2C0316a82c69b575b3567e2dc35f741050%2Cd3538ebeb9c87b858ce775e32568542c%2Cfd26e95dea2d724739dd95ccf193185d%2Cfcc8924a4561e72582071769b41e84e5%2C934822d2e27317865a9e8c47bf067401%2C100baf925be02ea7a81145fdcb1c798a%2C3b0c94e8770b99990a87182928b80343%2C1c9f3a9e13323e7c842ee656de44ecfc%2Cf3565c3ab78c99e9412cfd436e2a8ade%2C6c29c243f82353d360082592b8d16198%2C97920400c6ab81ef6c72ed5394874dbb%2Cd181a21dcc3de35d674b06b6d13f50b9%2Cfe83f6a558f0bd2838f35c9f70378187%2C1e14e8b49e01764909bee05b7bf7d514%2C9103dfef2715eba25ed57c404adcc7f8%2C82c51f5b376ec901437a8d57dd1cd63d%2C2ece1d62595bcdd87882831370930114%2C808758b6ff3a046c04ff06b76cfbe7c2%2C3944872e217cc93191aa41169167ffef%2C3319c459588eefa61807bcc94e603977%2Cad67a090a2376753a3754de4121fc2b3%2C28f8edcc33e0f7fb98d4f646f0ccfdfb%2C6828fc08873bc204fe1e2e7900400e73%2C7a521b670d2ceae7a5c40718b5ec4a9e%2Ceb6d3b8a36b76a3d55cedf9aaf7cd542%2Cd0d7d981e515247cc0203adf9e07df47%2C2426aee541e8548e9c18d274a7265b56%2Cef34af946510027fe4459d80404dd81c%2C33a1e83b781b0ef931b03522e157814a%2C2070e3bfc8d719bfabbd572034ae30bb%2C26128c0a66a4f1a198460e26ac5c6ab9%2C602440dbc6da85a923054b12e3d910b5%2C5d072ef53b2f3103c1b9ba1e521f8fd8%2Cebbbe8d6a518d8aef37fc925025ece77%2C3c72f9fe01a8067b8911a8ec1273106d%2C99f9eb42d420c1bb321543c5a241cbe7%2C8dc374a3c79c533b65a6860605296f41%2C88355d67964ab61aaf3405d857436561%2Ca3b501d9de84a9eeed86cac9ae717998%2C5068491ede51a5d2a49c8ba419f320fd%2Cc6b518e5b6a5772f15386270ab01ee34%2C04268d3dd717d22f60f0ba8b0a1a0a4f%2C0e43adf6c1ab7cdc63c03deb1aa48b35%2C74be35d6ea439c526e647f24c3538456%2Cf63c0b2cf62825811f6d7023155a85cb%2C1dd5f0a044c93a35325e7e3e8fd23179%2C5684ac5e5bba97e945afaafe111ddbff%2C6ce10229cdd9b74355ab8fc860c22d8d%2Cd420c1e743178f980751ff204177f392%2C15472da10d7c131b4de360c62d44b590%2C083a124ede6f630800142cf71a2836e2%2C637914ac9bb6f1d36219335a34e3cba7%2C3e50bc0fd295b84b67f919c22a6badf5%2Cbcf11ea30d37a5241c96e5d0243475fb%2C6e35fc7c74c01a028a218a08ae340d41%2C283e91f810e7dafa901abfc2c7f418d1%2Ccf88fb761485bea00970ef9ab5be68cd%2C171a1f8be026dd89eddb1a68f13cb218%2Cb357adaa87f3ba14a26509719b77f239%2Ca44015a88096f200df5fdc7c1bd99594%2Cd694a23ec0b76784737349e43d7803c4%2C42f7cc05d1f4e75d331084d8d8368952%2Cb89d2bba915ec9ae0217628c7a095c30%2Cf57e8018fa7819cb6c849d9e4776cf47%2Ce5537af3e763e51825db79439d0c0adb%2C6c2a18901be1cd81f725ae33d47f478f%2C3171bc341d36e86456af726be0f1fd07%2C12589b0c1a9525afe425c6c190272680%2C90c332e1918a55c5e0de3ab7abedd681%2C4aae0cc91dd05c1ada965775fdb9130f%2C909eace4257aa93896989d3ba0410135%2C00bbc56bd032b9d08e9a853976b4cd07%2C9d5427c933717eb8a4a8df28d82f3d29%2Cd5241179f6d2af8eedce6820ff764850%2Ca9ceb550b4a2b633df1d867f0120e45d%2C91b282aa3925dc078a11e97bc38ebef5%2C9e93c188ff1d0002241162dcb4b48433%2Cbf4a063aecb7c7d67ff8d1d334849c92%2Cb9f15796e9c75eb819ca4d643ff97cca%2C9bb3493eefe517b1f3aabb7b658e6b80%2Cc1fd39e1c7bdd74a328267988ae95d36%2C281cc59fdff617e5a52fcd107508b298%2Cbf263492dafa7ad9d5f7fc86b94c78f1%2C8015b581cebf415ec27221fa8465ee6e%2C2944de0f2421d14a4e2f4c45da20f610%2Cafed87dc2c2705af59ddd05244f99581%2Cea43e675a0cc0c3d0981faa378ba7907%2Cc060b448a4018710c6518ef4044402ea%2C007b42bf566de1272bf8c0dff27fba99%2C6894b0beb5d5f48d43fbebe9ad7864f9%2Cfbe77ab408b70c3c070e201be9c453a2%2C1b52dba9b06ee238e51ddd2e484c7f23%2C9e38342e4a3dd0b9c451561f2ac7616d%2C18f2ea901b67bf9b0ed38d7048abf4c7%2C2aa3ee8983c822b068f615a005858534%2C9f0befbd8599abf511d6158e5659f48b%2Cca481c14c3b2f8fc16cfb5667c6944a9%2C3ebb84a152fcee455adee389443a94b3%2C1572a899ea6d0a7f114e7fb388e639f4%2C4a475505c36062142fe55ca6c87cec53%2C34ce8df9c81b2082e3f1ce7abe857d4b%2C5af5d1b74e67e2422cd83899993cb908%2Cef6d2a33357c02d5ff71b9f753a7c817%2Cc01036cd498746fd4b7e4f1f0ad43e32%2Cef5081dc7a13e0d82f81fcd2ccda3d8b%2C1bcd10d2824b9e79b9d68b233400d789%2Cfc90e83187a0b1d6bf0379efdd869319%2Cd8bd57caa657767b8b2f511b71be8dfa%2C840f9e3a2c265b1d56e13423b94f8510%2Ccb519644c5ff03b786a0e3c7a058594f%2C7aa766868e8a477161bcbdd10df96354%2C9b3992b9a455046e75d83ccbd47f43cd%2Cff3e01aabdb825265c3c7cb11f5af43b%2Cc33f732c1cfc9dc2fcfd30e1fe52a21d%2C1ba62f624a3211f476ba4fa12dae1e01%2C70f91dbeab67e8c43eb3488af2e8618b%2C3b0221d86e681a511ac3e7e798ed378a%2C065fd027733ca2171ac0b3eb46b6eb4c%2C77bf80bb12546b76f39b03073804b46b%2C044fcd903f2af2a3c3209e819d022c50%2C5ebae501a65825fc7bfcc99748f172d3%2Cbdc0ac964a73523568e65bdad06ef80c%2C39b402b11b9a87be5597ddbc7b975334%2C569bc4c4b574c0188c2326d34aeb9318%2Cd96916495bb90f076e6d471376b9e7d6%2Cb028c0261cff43167cb0bbb65fdf5d0e%2C7ddb2032ae11730c35cbc768dfc78edb%2C31c91b4f895f955c02ed8964a804cf67%2C2f0a6f0017471963720768baed09b261%2C4d9e435a13ad5a224c14c4ee7ae18cec%2C9b29d9a90e6d96e4efde0a87b042d8f2%2Cd8cf817931aa340d834b54bb4e2bb6b4%2C402f12e0a95bfb9e8bce3cec250d9d42%2Cab0b788e123b41c01e8d84c67539c597%2C0bfa73bae755ac0d35f456261d702fde%2C3717f9513e6668dad4da6786b7d319f1%2C74cbfbfbedd355df949f9d5e1d4f299a%2Cab72e3608b76316d4da3ed15004a0fa2%2C01e0ff428ded2deceb60401759bdf9a9%2C583ac7714d3b8575bfa517564941da3a%2C43653dae5af9fef264c9af942b9f6490%2Ca0bb78885902b3dec508f94a2cd0d99e%2C57dddf9078dd9ade1423952654e2ce4d%2Cca0b8462db21d822d54ced65b5b8f6c7&Limit=300&Fields=Chapters&ExcludeLocationTypes=Virtual&EnableTotalRecordCount=false&CollapseBoxSetItems=false [object Response]
```

The error that gets logged immediately after that is a response that doesn't copy as nicely, but just adds that the response status for that request is 414 URI Too Long.

**Comment by felix920506** [comment]
@AlexStormwood there hasn't been a release containing those fixes yet. They should come out with 10.9 in late April.

**Comment by elendil7** [comment]
Still waiting for this fix.

**Comment by AlexStormwood** [comment]
Can confirm that 10.9 has the fix, tested with affected albums mentioned in my earlier comment.

Thankyou, team! :D
