### ISSUE TITLE
Non-admin users without deletion rights can still modify and delete collections

### ISSUE THREAD

**Issue by bamnoru** [jellyfin/jellyfin#1056]
**Describe the bug**
Feature to add movie or create new collections are available to non-admin users.

**To Reproduce**
Use a non-admin user (uncheck "allow this user to manage the server")
without deletion right (uncheck all libraries, and also the collection library of course).
User is still able to :
- Add movie in an existing collection
- Add movie in a new collection
- Remove movie from a collection
- Delete a collection

**Expected behavior**
Non-admin users should not have the right to modified, create or delete collections.

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Jellyfin Version: 10.2.2

**Comment by JustAMan** [comment]
@bamnoru I've fixed issue title, please check if I summarized the issue correctly.

**Comment by bamnoru** [comment]
I don't know how collections should be managed.
Maybe there are two bugs :
- Users without deletion right can still delete collection
- Non-admin users can manage collection (add and modify).

**Comment by orfeas0** [comment]
I see 2 ways this can be solved.
1 (easy): Checkbox that allows user to manage collections. Collections remain global.
2 (harder): Collection are user-based, meaning one user can only see/edit their collections.
Extension of 2: Collection can be shared, as read-only or R/W to other users.

I'd love to help, if someone can give me a pointer on where to start, and which method to implement.

**Comment by bamnoru** [comment]
From my point of view, as an user of Jellyfin, keep it as simple as possible.
Collections managed by users already exists, it's "playlist".

Collection is a library (almost) like others.
So, only administrators could manage libraries, so, only administrators should manage libraries of collections.
And, as the libraries of collections are present in the list of "Allow media deletion from" of an user profil,
deletion should be authorized only for users with the right authorisation.

**Comment by andyguerra** [comment]
I'm experiencing this issue right now

**Comment by tamburra** [comment]
This should be reopened as this is still an issue on the newest Jellyfin release.  All my users are able to edit collections no matter what permissions seem to be granted to that user.

**Comment by crobibero** [comment]
I would file this as a feature request, so it belongs at https://features.jellyfin.org/

**Comment by VigibotDev** [comment]
Still present. it's crap:(

**Comment by Shadowghost** [comment]
I's already fixed in master with a new permission on a per user level.

**Comment by hadiph** [comment]
This problem still exist in Jellyfin Version: 10.8.13
User with no deletion access still possible delete collection

**Comment by brunoherrera** [comment]
why are comments being minimized? it's still an issue in 10.8.13

**Comment by felix920506** [comment]
The fix will be out in 10.9, please stop commenting about it being broken in 10.8.x
