### ISSUE TITLE
[Issue]: "Recently Added" sections do not contain metadata information, and items within are not sized correctly.

### ISSUE THREAD

**Issue by pokkst** [jellyfin/jellyfin#10657]
### Please describe your bug

After updating my jellyfin-git install, Jellyfin's home page does not display metadata info and items are not sized correctly in the "Recently Added" sections. Music albums should be squares, and I think with the year below them. Movies/TV shows should be posters with the years below them. Currently they are all rectangles with no additional info.

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: Linux (Manjaro)
- Linux Kernel: 6.1.63-1-MANJARO
- Virtualization:
- Clients: Android, Web, Roku
- Browser: Firefox, Mullvad Browser, Tor Browser, Brave, Chrome
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: Nginx
- Base URL:
- Networking:
- Storage:
```

### Please attach any screenshots here

![3](https://github.com/jellyfin/jellyfin/assets/47200567/088e29ad-ccbb-4da8-b010-d76e6c66d82b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thornbill** [comment]
This is a regression introduced by https://github.com/jellyfin/jellyfin/pull/9764.

**Comment by Obamium69** [comment]
I have the same issue. For me it uses the thumbnail or the background instead of the poster
![Screenshot_20231202_003417](https://github.com/jellyfin/jellyfin/assets/61025357/46403a40-dd16-4220-85b6-df900607f2b7)

**Comment by thornbill** [comment]
Should be fixed by Should be fixed by https://github.com/jellyfin/jellyfin/pull/10702

**Comment by Ewillian9** [comment]
I'm still having this issue or a similar one. "recently added" does not display at all. they are if all libriries in "Librairies Folders" are selected but even with this, they are displayed same as above, with recangle horizontal images. from any 10.9 version since a while

**Comment by pokkst** [comment]
@thornbill This bug was fixed for a bit, but in some recent commit this issue occurs again.

**Comment by felix920506** [comment]
@pokkst please open new issue reports

**Comment by pokkst** [comment]
You could also just... reopen this issue.

**Comment by felix920506** [comment]
I have confirmed with devs and they say this is unlikely to be the same issue. If you believe this is the same issue, please provide the relevant documentation such as logs.

**Comment by pokkst** [comment]
![image](https://github.com/jellyfin/jellyfin/assets/47200567/5883f6db-0d66-43f4-85a0-d6f0fcf11346)

Here's your proof. Same exact issue as before.

**Comment by pokkst** [comment]
I do not see the point in creating an exact duplicate of this GitHub issue when it's the exact same bug that occurred before. That would just waste everyone's time.
