### ISSUE TITLE
[Issue]: Transcoding slowly decreases FPS and speed over time for large files

### ISSUE THREAD

**Issue by gitdeath** [jellyfin/jellyfin#10799]
### Please describe your bug

I do not know if this was happening in earlier versions of Jellyfin.
Throttle Transcodes is enabled - I've disabled this and will monitor.
I'm not sure what is helpful that isn't found in the logs, but happy to answer questions. 

### Jellyfin Version

10.8.z

### if other:

10.8.13

### Environment

```markdown
- OS: Ubuntu 
- Linux Kernel: 5.15.0-91-generic
- Virtualization: Docker
- Clients: Roku, Chromecast, Chrome browser, Android App
- Browser: n/a
- FFmpeg Version: ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
- Playback Method: Transcode
- Hardware Acceleration: QSV
- GPU Model: none
- Plugins: none
- Reverse Proxy: nginx (swag)
- Base URL: none
- Networking: bridge
- Storage: NFS
```

### Jellyfin logs

```shell
[2024-01-02 09:45:26.212 -06:00] [INF] [8] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Username". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-01-02 09:45:26.212 -06:00] [INF] [8] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 20000000, RemoteIp: "128.92.18.179", IsInLocalNetwork: False
[2024-01-02 09:45:26.213 -06:00] [INF] [8] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Official Roku Client", Path="/FolderName/Filename.mkv.1][HEVC]-FGT.mkv", AudioStreamIndex=1, SubtitleStreamIndex=10 ) => ( PlayMethod=Transcode, TranscodeReason=ContainerBitrateExceedsLimit ) "media:/videos/5e8a6f5e-01dd-7c27-3a2d-0c29a613c335/master.m3u8?MediaSourceId=5e8a6f5e01dd7c273a2d0c29a613c335&VideoCodec=h264,h264&AudioCodec=aac,mp3&AudioStreamIndex=1&VideoBitrate=19616000&AudioBitrate=384000&MaxFramerate=23.976025&MaxWidth=1920&MaxHeight=1080&api_key=<token>&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=9704ee2e4562063859e2e22173665c68&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&hevc-level=153&hevc-videobitdepth=10&hevc-profile=main10&TranscodeReasons=ContainerBitrateExceedsLimit"
[2024-01-02 09:45:27.648 -06:00] [INF] [8] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Roku" "2.0.0" playing "Movie Name". Stopped at "10000" ms
[2024-01-02 09:45:28.245 -06:00] [INF] [38] Jellyfin.Api.Helpers.TranscodingJobHelper: "/usr/local/bin/ffmpeg" "-analyzeduration 200M -ss 00:00:09.000 -init_hw_device vaapi=va:,kernel_driver=i915,driver=iHD -init_hw_device qsv=qs@va -filter_hw_device qs -hwaccel qsv -hwaccel_output_format qsv -c:v hevc_qsv -autorotate 0 -i file:\"/FolderName/Filename.mkv.1][HEVC]-FGT.mkv\" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_qsv -preset 7 -look_ahead 0 -b:v 19616000 -maxrate 19616000 -bufsize 39232000 -g:v:0 72 -keyint_min:v:0 72 -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_qsv=w=1920:h=1080:format=nv12\" -codec:a:0 libfdk_aac -ac 2 -ab 384000 -af \"volume=2\" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 3 -hls_segment_filename \"/transcodes/e4d7851624560835b26787283dfd7b94%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/transcodes/e4d7851624560835b26787283dfd7b94.m3u8\""
[2024-01-02 10:47:47.271 -06:00] [WRN] [94] Jellyfin.Server.Middleware.ExceptionMiddleware: The response has already started, the exception middleware will not be executed.
[2024-01-02 10:47:47.288 -06:00] [ERR] [94] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HN070EA64HIF"", Request id ""0HN070EA64HIF:00000002"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (547773 of 547692).
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WritePipeAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionBody.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.StreamCopyOperationInternal.CopyToAsync(Stream source, Stream destination, Nullable`1 count, Int32 bufferSize, CancellationToken cancel)
   at Microsoft.AspNetCore.Internal.FileResultHelper.WriteFileAsync(HttpContext context, Stream fileStream, RangeItemHeaderValue range, Int64 rangeLength)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileResultExecutorBase.WriteFileAsync(HttpContext context, Stream fileStream, RangeItemHeaderValue range, Int64 rangeLength)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor.ExecuteAsync(ActionContext context, FileStreamResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Jellyfin.Server.Middleware.BaseUrlRedirectionMiddleware.Invoke(HttpContext httpContext, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[2024-01-02 10:51:42.258 -06:00] [INF] [59] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-01-02 11:25:29.662 -06:00] [INF] [63] Jellyfin.Api.Helpers.TranscodingJobHelper: Stopping ffmpeg process with q command for "/transcodes/e4d7851624560835b26787283dfd7b94.m3u8"
[2024-01-02 11:25:29.977 -06:00] [INF] [63] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 0
[2024-01-02 11:25:29.977 -06:00] [INF] [63] Jellyfin.Api.Helpers.TranscodingJobHelper: Deleting partial stream file(s) "/transcodes/e4d7851624560835b26787283dfd7b94.m3u8"
[2024-01-02 11:25:32.546 -06:00] [INF] [104] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Roku" "2.0.0" playing "Movie Name". Stopped at "5777000" ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gitdeath** [comment]
### FFmpeg logs

[ffmpeglogs.txt](https://github.com/jellyfin/jellyfin/files/13812670/ffmpeglogs.txt)

**Comment by solidsnake1298** [comment]
What are the hardware specs of your Jellyfin server?

**Comment by nyanmisaka** [comment]
```
    Metadata:
      BPS             : 65604596
      DURATION        : 04:23:17.719000000
      NUMBER_OF_FRAMES: 378766
      NUMBER_OF_BYTES : 129550372940
```

129550372940 => 120.7 GB

This is quilte a large video file. If the video source (`/FolderName/FileName.mkv.1][HEVC]-FGT.mkv`) is located on the network, please check the network speed. Otherwise, please copy the source file from HDD to a SSD and try again.

**Comment by felix920506** [comment]
Does it happen if throttle transcodes is disabled?

**Comment by gitdeath** [comment]
> What are the hardware specs of your Jellyfin server?

- Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz / Intel UHD Graphics 630
- Transcode directory is on an SSD
- NFS for the storage. 2 gig wired from NAS to Unifi switch and 1 gig wired to clients. 

>Does it happen if throttle transcodes is disabled?

I have not witnessed the behavior with throttle transcode disabled, but proving a negative is obviously not something I can do.

**Comment by gitdeath** [comment]
> This seems more like an issue with how the metrics are calculated than an actual bug with any core functions, as playback is working as intended.

It does slow to the point the playback is impacted.

**Comment by nyanmisaka** [comment]
@IzanagisBurden What you are experiencing is a fault caused by AMD GPU firmware on Renoir/Cezcanne APU. I reported this issue to AMD staff earlier last year and it was fixed. However, the fixed firmware was only uploaded to the upstream repo at the end of September last year, so it is unlikely that Ubuntu 22.04 will contain the latest firmware. You can refer to this post to update it manually.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/8313

**Comment by gitdeath** [comment]
Difficult to be certain as a lot is going on in the thread, but #8744 does seem to imply they've found and merged a fix for this that would be in 10.9.

**Comment by KloWhrhyde** [comment]
I have exactly the same issue, on a Intel I9 12900KS. So the issue still persist, i don't know if it is on jellyfin side or FFMPEG side.

Throttle transcode is disabled.

Happens only on very large files.
