### ISSUE TITLE
[Issue]: Can't manually add or delete subtitles

### ISSUE THREAD

**Issue by Simsala91** [jellyfin/jellyfin#11318]
### Please describe your bug

When editing external subtitles of a movie, it is neither possible to manually add a subtitle nor is it possible to manually delete subtitles as a non-admin user with the permission "Allow user to edit subtitles".

Adding subtitles with the OpenSubtitlesPlugin works fine.

### Reproduction Steps

(Scenario A) Have a movie with external subtitles. Try to remove them as a non-admin user with permission "Allow user to edit subtitles". Subtitle does not get deleted. (This works as admin.)

(Scenario B) Try to manually upload a subtitle file either as admin or as non-admin with permission "Allow user to edit subtitles". The subtitle does not get created. (Also after refresh).

### Jellyfin Version

Unstable (master branch)

### Environment

```markdown
- OS: Unraid
- Linux Kernel: unknown
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: -
- Playback Method: -
- Hardware Acceleration: -
- GPU Model: -
- Plugins: OpenSubtitles
- Reverse Proxy: none
- Base URL: none
- Networking:  Bridge
- Storage: local
- Build: 2024040805
```

### Jellyfin logs

```shell
[16:09:45] [INF] [31] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.178.25 closed
[16:09:45] [ERR] [36] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Unexpected end of request content. URL POST /Videos/8194315094fc0ce43369e0d71eac34b0/Subtitles.
[16:09:46] [INF] [50] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.178.25 request
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ch1nkara** [comment]
Hi, thanks for the feedback. Indeed, I overlooked that part in https://github.com/jellyfin/jellyfin-web/pull/4883. I will happily dig into it and offer a fix. Might not have time to work on it before the end of this month so if someone else wants to step up, don't hesitate

**Comment by nielsvanvelzen** [comment]
The backend change is not as simple as adding the right policy to the delete endpoint though. We should only allow the deletion of remote subtitles with the EnableSubtitleManagement policy, subtitles already in the media directory should be left untouched.

**Comment by Ch1nkara** [comment]
To be honest, I don't really agree with that. I think the EnableSubtitleManagement is there to give administrator rigths over the subtitles without giving full administrator rights. What you"re suggesting seems more confusing. And more complex to implement.

**Comment by Simsala91** [comment]
Personally, I also think this should also allow the deletion of external subtitle files. If I give another user that permission, I trust that user to pick the correct subtitles. Sometimes automatic subtitle downloader will download a subtitle that is out of sync, and I would like users (that I trust) to be able to fix that without having to contact me.

**Comment by Ch1nkara** [comment]
I made a PR to propose a fix. it allows a non-admin user and admin users to delete any external subtitle. As discussed, it is the approach I prefer. I'll let the jellyfin core team decide if they accept it or not.

This would solve (Scenario A) of this issue. 

@Simsala91, I was unable to reproduce (Senario B) issue. I had no trouble manually importing subtitles as both admin and non-admin user, via click and drop and browsing

**Comment by Simsala91** [comment]
@Ch1nkara Thanks for the work! Also can't reproduce Scenario B on current branch. Might have been fixed by #11310 or #11321
or #11373

**Comment by Ch1nkara** [comment]
Issue still being discussed in https://github.com/jellyfin/jellyfin/pull/11507
