### ISSUE TITLE
[Issue]: After upgrading to 10.9.1, the Android client cannot connect to the server（Fixed in version 10.9.3）

### ISSUE THREAD

**Issue by as4134** [jellyfin/jellyfin#11658]
### Please describe your bug

  Upgrade Jellfyin to version 10.9.1 (including 10.9.0). The Android Jellyfin client can no longer connect to the server, but it can be accessed normally in the browser. I guarantee that my URL is correct and there are no firewall interception issues involved;
    The Jellyfin server works through HTTPS, certificates are issued by trusted institutions, and the intermediate certificate chain is complete. Now, there is only one way to use the Jellyfin Android client to connect to the server:
Clear all application data and reopen it, fill in the server URL, in order to access it normally. However, once the client is closed and opened again, the problem will reappear, making it impossible to connect to the server.
  The server only has one network card, and Jellyifn works in Windows, not in a Docker or virtual machine environment. The routing port mapping settings are correct.
  I have also seen feedback from users on the forum regarding this issue, and the situation is consistent

### Reproduction Steps

1. Open the Android client, client version v2.6.1
2. Enter server URL (HTTPS)
3. Connect to the server

### Jellyfin Version

10.9.0

### if other:

android client 2.6.1

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Log service prompt error, unable to provide at the moment
```

### Please attach any screenshots here

![cedcdeb12ea78df94f1684caf23b12f](https://github.com/jellyfin/jellyfin/assets/125622960/39839b18-52ef-410c-af8a-00e84d767e75)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cohortcw179** [comment]
I too have similar issues. Both Android and Jellyfin Media Player (Windows) works well on first login. However, if I logged out of those apps, I can no longer log back in until I clear the apps data or reinstall. Tried the below or set server to bind to my local address. Even then nothing works. 

<IgnoreVirtualInterfaces>false</IgnoreVirtualInterfaces>

**Comment by tumbly** [comment]
Same issue for me on android (server is running 
10.9.1 on linux):
`[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[ERR] Error processing request: "Invalid token". URL "GET" "/socket".
[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."`

A temporary solution I found is force stopping the android app and deleting its storage.
This way I can login **once** and use the app normally, **until** I stop force it and try to start it again, this time I get a "_Connection cannot be established_" error.

**Comment by btou1902** [comment]
i have the same issues. please fix it bro

**Comment by fengzhengxaiowanzi** [comment]
10.9.2 also has this problem. I had this problem on both my Android devices, the first time I logged in fine, then I had to clear the data to get it to work, and the console logs showed everything was fine, so I had to roll back to 10.8.13

**Comment by Alliyance** [comment]
The new update is a outta mess :(:(:(:(

**Comment by as4134** [comment]
> 新的更新是一个混乱的:(:(:(:(

Yes, 10.9.2 didn't fix this

**Comment by svenlindekugel** [comment]
Can confirm as well starting with 10.9.1, running genuine docker image, the Jellyfin app needs clear data after app restart.

**Comment by CatSamaDD** [comment]
The issue is still found in version 10.9.2. I believe the problem lies in the token verification mechanism added in the updates after version 10.9 to address the longstanding security concerns. However, the Android version 2.6.1 has not been updated simultaneously to adapt to this change.

**Comment by as4134** [comment]
> 版本 10.9.3 仍然存在同样的问题

I tested it and this has been fixed in 10.9.3, you can reinstall it after partial server data.

**Comment by VigibotDev** [comment]
Jellyfin Server 10.9.3 solve the Android Mobile App login problem for me ! Thanks for the work

**Comment by umataro** [comment]
Multiple people are saying this is still present (it's still present in 10.9.6), so why is this getting closed?
