### ISSUE TITLE
[Issue]: API Endpoint "/System/Info" publicly accessible and potentially leaking private config information

### ISSUE THREAD

**Issue by hlinden** [jellyfin/jellyfin#11763]
### Please describe your bug

I am running Jellyfin on a public machine behind a reverse proxy which accesses my actual installation at home via some internal routing in my private vpn setup.

curl https://subdomain.mytld.org/System/Info
{
  "OperatingSystemDisplayName": "nobodies business, removed",
  "HasPendingRestart": false,
  "IsShuttingDown": false,
  "SupportsLibraryMonitor": true,
  "WebSocketPortNumber": 8096,
  "CompletedInstallations": [],
  "CanSelfRestart": true,
  "CanLaunchWebBrowser": false,
  "ProgramDataPath": "/var/lib/jellyfin",
  "WebPath": "/usr/share/jellyfin/web",
  "ItemsByNamePath": "/var/lib/jellyfin/metadata",
  "CachePath": "/var/cache/jellyfin",
  "LogPath": "/var/log/jellyfin",
  "InternalMetadataPath": "/var/lib/jellyfin/metadata",
  "TranscodingTempPath": "/var/cache/jellyfin/transcodes",
  "CastReceiverApplications": [
    {
      "Id": "removed",
      "Name": "Stable"
    },
    {
      "Id": "removed",
      "Name": "Unstable"
    }
  ],
  "HasUpdateAvailable": false,
  "EncoderLocation": "System",
  "SystemArchitecture": "X64",
  "LocalAddress": "http://[my internal, slaac based ipv6 address including the mac of the device at home]:8096",
  "ServerName": "nobodies business as well, therefore removed",
  "Version": "no one except for me needs to see this",
  "OperatingSystem": "",
  "Id": "nobodies business, therefore removed"
}

https://media.7183.org/System/Info/Public

{
  "LocalAddress": "http://[my internal, slaac based ipv6 address including the mac of the device at home]:8096",
  "ServerName": "nobodies business as well, therefore removed",
  "Version": "no one except for me needs to see this",
  "ProductName": "Jellyfin Server",
  "OperatingSystem": "",
  "Id": "nobodies business as well, therefore removed",
  "StartupWizardCompleted": true
}

None of this information is relevant for an unauthenticated user, but it disturbs me especially that a strong connection between my public frontend and my private, at home ipv6 subnet is established.

### Reproduction Steps

Install.

Complete initial setup.

Call API.

### Jellyfin Version

10.9.0

### if other:

10.9.1

### Environment

```markdown
not really relevant
```

### Jellyfin logs

```shell
not really relevant
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
This was already fixed by https://github.com/jellyfin/jellyfin/pull/11651 and is available in 10.9.2

**Comment by hlinden** [comment]
> This was already fixed by #11651 and is available in 10.9.2

Right, I see. I still think "LocalAdress" shouldn't be visible in "System/Info/Public". Should I adress that issue in a seperate ticket as a feature request?

**Comment by gnattu** [comment]
> > This was already fixed by #11651 and is available in 10.9.2
> 
> Right, I see. I still think "LocalAdress" shouldn't be visible in "System/Info/Public". Should I adress that issue in a seperate ticket as a feature request?

For 99.99% of time this address is a LAN only address unless the user has  a direct WAN interface or explicitly configured that. We still have some stupid client relies on that field being available so it is hard to remove for now.

**Comment by hlinden** [comment]
>this address is a LAN only address

...which usually contains the current dynamically assigned IPv6 prefix and likely the MAC-adress of the machine because of SLAAC.

>For 99.99% of time

Okay, that actually made me scratch my head so I went and took some measurements. With my quickly collected dataset of 10000 random, online-ish Jellyfin servers, 6.3% published an IPv6 address with a public prefix as of right now. So, if I look at that situation in the most pessimistic way I can: In general there are users affected by this and someone might find themselves on the pointy end of a connection made between their public facing host and their home internet connection.

>We still have some stupid client relies on that field being available so it is hard to remove for now.

Understood. Would it maybe be a good compromise to make this endpoint configurable? I would like my instance to expose as little information as possible, by default. Or at least by choice.

**Comment by gnattu** [comment]
> Understood. Would it maybe be a good compromise to make this endpoint configurable?

It is already configurable. You set environment variable JELLYFIN_PublishedServerUrl=example.com and this address will be override to your configured url.

**Comment by zynexiz** [comment]
Just a notice, this is still an issue with version 10.9.10. I also fond a private IP in /web/en-us-json.72295a24638e8a565dda.chunk.js; `"LabelServerHost":"Host","LabelServerHostHelp":"192.168.1.100:8096 or https://myserver.com"` (could be help thing?).

The data found in /System/Info/Public reveals the internal hostname, IP and server version and could be used for reconnaissance attack toward a public server.

**Comment by gnattu** [comment]
Those texts are helper strings and does not mean anything, if you are hosting on myserver.com or that IP then I'm very sorry but that is inevitable.

**Comment by charlesomer** [comment]
Hi, I;m running 10.10.0 and I can see System/Logs without needing to log in. Is this supposed to be configurable now?

**Comment by felix920506** [comment]
@charlesomer please open a new report if you believe it is a security concern.

**Comment by gnattu** [comment]
> Hi, I'm running 10.10.0 and I can see System/Logs without needing to log in. Is this supposed to be configurable now?

It requires login: 

```
curl -v localhost:8096/System/Logs
* Host localhost:8096 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8096...
* Connected to localhost (::1) port 8096
> GET /System/Logs HTTP/1.1
> Host: localhost:8096
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 401 Unauthorized
< Content-Length: 0
< Date: Mon, 28 Oct 2024 02:17:28 GMT
< Server: Kestrel
< X-Response-Time-ms: 16.8401
<
* Connection #0 to host localhost left intact
```
