### ISSUE TITLE
[Issue]: database table locked when refreshing library

### ISSUE THREAD

**Issue by bleriaf** [jellyfin/jellyfin#11957]
### Please describe your bug

i'm trying to refresh my library however it keeps failing, after checking the console there is a sqlite error 6 error saying database table is locked

### Reproduction Steps

in unraid, open jellyfin and refresh your library

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Unraid
- Linux Kernel:
- Virtualization: Docker
- Clients: 
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
[08:30:40] [ERR] [200] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText, SqliteParameter[] parameters)
   at Microsoft.Data.Sqlite.SqliteTransaction..ctor(SqliteConnection connection, IsolationLevel isolationLevel, Boolean deferred)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveImages(BaseItem item)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
   at Emby.Server.Implementations.Library.LibraryManager.RunMetadataSavers(BaseItem item, ItemUpdateType updateReason)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, Boolean removeOnFailure)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
   at Emby.Server.Implementations.Library.LibraryManager.RunMetadataSavers(BaseItem item, ItemUpdateType updateReason)
   at Emby.Server.Implementations.Library.LibraryManager.SavePeopleMetadataAsync(IEnumerable`1 people, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdatePeopleAsync(BaseItem item, List`1 people, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
```

### Please attach any screenshots here

![brave_gpJibAk460](https://github.com/jellyfin/jellyfin/assets/109803937/49a5e57f-da34-4e9d-a8d0-555b9fa10a04)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Simsala91** [comment]
Update to 10.9.4 if you use 10.9.0, this is fixed

**Comment by derterboy** [comment]
> Update to 10.9.4 (or 10.9.3 or wait 10.9.5 since 10.9.4 has some bugs of its own) if you use 10.9.0, this is fixed

Error also occurs on 10.9.3 and 10.9.4

**Comment by Simsala91** [comment]
Interesting, there was a very big thread about database lockups (#11624) which was supposedly fixed in 10.9.2, and since thread was saying it was running on 10.9.0 I thought it's probably just that bug.

You could try the following setting:

Administrator -> General -> Performance -> Set "Parallel library scan tasks limit" and "Parallel image encoding limit" both to 1. This might help with lockups.

**Comment by derterboy** [comment]
> Interesting, there was a very big thread about database lockups (#11624) which was supposedly fixed in 10.9.2, and since thread was saying it was running on 10.9.0 I thought it's probably just that bug.
> 
> You could try the following setting:
> 
> Administrator -> General -> Performance -> Set "Parallel library scan tasks limit" and "Parallel image encoding limit" both to 1. This might help with lockups.

Yes, error still occurs with parallel scan tasks. For further info:
https://github.com/jellyfin/jellyfin/issues/11839

**Comment by bleriaf** [comment]
i'm on version 10.10.0 and it's still happening. im gonna try the parellel library scan limit

**Comment by holow29** [comment]
Seems like dupe of #11589

**Comment by felix920506** [comment]
Duplicate of #11589
