### ISSUE TITLE
Library thumbs are not created in 10.3.0-rc1

### ISSUE THREAD

**Issue by cesalo** [jellyfin/jellyfin#1200]
**Describe the bug**
In 10.3 these are how the libraries look:
![image](https://user-images.githubusercontent.com/16859916/55643135-64db7a80-57a0-11e9-96bc-988b86d19e88.png)
In 10.2:
![image](https://user-images.githubusercontent.com/16859916/55643162-745ac380-57a0-11e9-93df-3ee2b7a54403.png)
**Expected behavior**
Same as 10.2.
**System (please complete the following information):**
Centos rpm.

**Comment by Matt07211** [comment]
I believe on all current versions you'll need to force a library rescan before it's created. Let's say I have a fresh install and add my library, it scans all my files in, I've in the past had to hit the scan library button again and then that time it would create the covers

**Comment by cesalo** [comment]
I've run several, there is even a job I created to do that every hour. No luck.
![image](https://user-images.githubusercontent.com/16859916/55677108-df46f000-58af-11e9-9acb-782de0045027.png)
and from the dashboard:
![image](https://user-images.githubusercontent.com/16859916/55677119-0e5d6180-58b0-11e9-8367-02b6102800ff.png)

**Comment by Matt07211** [comment]
I ran rc-1 a few days ago and library thumb's got created on my end, I'm having trouble reproducing

**Comment by joshuaboniface** [comment]
What @Matt07211 said is correct, the library thumbnails don't get generated until the *second* library scan for a given library. Rescanning the library should fix it for you immediately.

We'll keep this issue around as the master tracking for this however, since it should probably be determined why this is occurring.

**Comment by cesalo** [comment]
@Matt07211 @joshuaboniface I've done several re-scans and nothing has changed .. I've installed 10.3.0-rc2 and the issue persists. I did create a new library to confirm and again same issue (you can see here the extra library):
![image](https://user-images.githubusercontent.com/16859916/56084688-a99c8c80-5e04-11e9-9c9b-da1932348d8a.png)
I have 2 parallel instances 10.2 (Docker) and 10.3 (Centos rpm) accessing the same directories, there is definitive something off in 10.3 with regards the thumbs (at least in my install):
![image](https://user-images.githubusercontent.com/16859916/56084706-e49ec000-5e04-11e9-9674-8522662020f1.png)
I've been adding tv-shows episodes and movies since these were created so for sure it did few library scans also I have a job running this every 2h since real-time monitoring sometimes doesn't catch the changes. 
This is not an issue of the first library scan, my screenshots are from today, as I mentioned these are Jellyfin instances that I'm using constantly adding with my active tv-shows so I'm adding new files every day.
Something I noticed is that when I created the new library after installing 10.3 RC2 the creation window didn't close on its own. It got kind of stuck when I pressed "Ok". I had to refresh the browser and was indeed adding the media to that library, not sure if this is related but I found it odd.

**Comment by Matt07211** [comment]
I'll have to check if this is still a problem or not

**Comment by cesalo** [comment]
so honestly I switched to custom Library thumbs so not sure if since the last updates this has been solved also now I'm just using docker so no more Centos :( .. which was the one having issues. Sorry about that.

**Comment by anthonylavado** [comment]
@cesalo That's okay. If it comes up otherwise, then we can look at it again.
@Matt07211 Let us know what you find out 👍

**Comment by azumukupoe** [comment]
I want an option to use the default library thums but should an create a separate ticket?

**Comment by yllekz** [comment]
I've made an interesting observation as of late: While the Jellyfin web interface/official app fail to show thumbnails for media entries, the third party "Infuse" app is able to show them without issue. I'm not sure if Infuse is generating thumbnails on its own (unlikely) within its own separate database or what (also unlikely), but it seems to be a bug in the Jellyfin interface from what I can tell.

**Comment by anthonylavado** [comment]
@yllekz That I can actually comment on. Infuse does generate its own database and downloads separate thumbnails (except in specific circumstances). It simply uses Jellyfin/others as a backend file provider (for now).
