### ISSUE TITLE
[Issue]: Jellyfin 10.9.6 - m3u music playlists are empty and do not work

### ISSUE THREAD

**Issue by MattBlackOnly** [jellyfin/jellyfin#12110]
### Please describe your bug

The .m3u music playlist is visible in the library but shows no items and does not play.

The playlist worked in 10.9.3

### Reproduction Steps

Hit play on any m3u playlist

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS: Debian 
- Linux Kernel: 6.1.0-21
- Virtualization: Docker
- Storage: local
```

### Jellyfin logs

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by frandj99** [comment]
I have the same problem me too.
I just did a new installation as Proxmox LXC and I checked 584156418 times to have all right path in my m3u playlists.
I even tried making another installation as docker, still from scratch, but still same issue.
At least now I know to not be alone with this issue 😅

I checked also the log, but there's no relevant information about the m3u I have
I had a docker running over Unraid and all playlists were working fine there, so I'm thinking there may be something with new installations

**Comment by Shadowghost** [comment]
Should be fixed by #12053

**Comment by frandj99** [comment]
> Should be fixed by #12053

Ohh nice, I hope to see this bugfix soon in the next Jellyfin update!
Living without my music playlists is horrible
Is there anything we can do to help push your fix?
I'm still not very familiar with the GitHub workflow, sorry. However, I did try to add an approved review with my account.

**Comment by dmurphydrtc** [comment]
Any ideas when this will be fixed? Thanks

**Comment by dmurphydrtc** [comment]
Is it possible to convert my m3u playlists to an xml format and get around this issue? Thanks

**Comment by felix920506** [comment]
@dmurphydrtc please ask for help on our forum or in our chat rooms. https://jellyfin.org/contact

**Comment by MattBlackOnly** [comment]
> @dmurphydrtc please ask for help on our forum or in our chat rooms. https://jellyfin.org/contact

@dmurphydrtc @felix920506 
Here's the forum post:
https://forum.jellyfin.org/t-music-playlists-no-longer-working


It's just waiting on the PR #12053 to be merged..

**Comment by vortex91** [comment]
a bit more details.  If m3u was scanned in prior version then that playlist works fine.  however adding new playlist or editing current playlist results in blanks in GUI.

**Comment by pixel24** [comment]
I have also been having issues with playlists since version 10.9.6. This might be the same problem.

I have a share called "Audio" on my file server (UCS 5.0.8). Jellyfin is running on a VM with Debian 12.5 and mounts this share. Under "Audio," there is a folder called "Musik," which is added as a library in Jellyfin.

The automatic start of Jellyfin is disabled. I start the VM and check if the mounts are correctly integrated, which they are. Then, as user jellyfin, I do:

```
su jellyfin
cd /data01/Musik (Mountpoint)
ls
touch test.txt
rm test.txt
```

No problem. The "jellyfin" user has full access.

Finally, I start Jellyfin and observe the log file. I see that Jellyfin believes all items in my playlists are missing, which is nonsense. Jellyfin then empties all my playlists.

The second VM with Jellyfin 10.8.13 uses the same share and the same entries in the fstab, and this problem does not occur.

I'm slowly getting desperate.

**Comment by MattBlackOnly** [comment]
Seems to be fixed in 10.9.7

**Comment by PLK2** [comment]
I've installed 10.9.7 but my m3u playlists still show up empty.

**Comment by MattBlackOnly** [comment]
> I've installed 10.9.7 but my m3u playlists still show up empty.

I had to rescan and refresh all metadata to get the playlists to show up.

**Comment by vortex91** [comment]
for those still having issues on 10.9.7 if your playlist are m3u's in your music library path then they show up in music/playlist section of GUI. However if you go to PLAYLIST in home directly they are empty. Also you are not able to create new playlist. However to solve this you can just create a new playlist in /data/playlist folder of config.

**Comment by hardwareadictos** [comment]
Well i am on 10.10.3 and from time to time playlists get empty also, i've not deleted any files or something, all media is there but with time they got empty... It's a pitta to recreate the playlists every time... That's what i get on the empty playlists xml files:

```
</Item>I have no name!@Jellyfin-PRO:/$ cat /config/data/playlists/Bass\ Boosted/playlist.xml
﻿<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Item>
  <Added>11/26/2024 21:06:53</Added>
  <LockData>false</LockData>
  <LocalTitle>Bass Boosted</LocalTitle>
  <RunningTime>907</RunningTime>
  <OwnerUserId>ab594e01f63c490f8356edc1481cf174</OwnerUserId>
  <Shares />
  <PlaylistMediaType>Audio</PlaylistMediaType>
```

And before someone asks... Yes, that is present since 10.9.X and seems to affecto 10.10.X
