### ISSUE TITLE
[Issue]: Broken subtitles: Multiple languages and timestamps mixing up on screen when using chromecast

### ISSUE THREAD

**Issue by cchristchurch** [jellyfin/jellyfin#12113]
### Please describe your bug

The issue started happening when upgrading from 10.8.13-1 to 10.9.x (I've confirmed 10.9.3 and 10.9.6 are affected).

Most movies with multiple subtitle tracks are affected, even if there is a bit of randomness to the issue and it does seem to depend, to some extent, on the size of the subtitle files (more details below).

Affected movies work just fine in a web browser or in the Android Client (web player). When playing on these platforms the players display the shiny new "Secondary Subtitle" option introduced in https://github.com/jellyfin/jellyfin-web/pull/3906 ; I have not tested the secondary subtitle feature extensively but it seems to work overall.

*However* when casting from my Android phone to my chromecast, the subtitles are completly broken. It generally starts fine for the first couple of subtitles, then quickly subtitles from multiple language tracks (and generally completely different timestamps) are overlayed directly on top of each other making them unreadable.

Note than when casting I have to select *one* language, and the "Secondary Subtitle" option is not available in the remote control. I suspect this is by design as the secondary subtitle feature was only introduced in the HTML player. However the fact that the bug started appearing on 10.9.x and that it only happens when the secondary subtitle feature is unavailable makes me wonder if this bug could be a side effect of introducing secondary subtitles?

Things I have tried to help gather more information:

- I have tried enabling and disabling the "Allow subtitle extraction on the fly" option on the server. This seems to have no effect on the bug.
- I have ran some experiments by modifying the subtitle files of one particular affected movie. I have not found any particular character or sequence of characters causing the bug. However it seems the issue does not happen (or very rarely) if I almost empty the subtitle files to contain only about 10 subtitles each, it happens very often (though not every time) with the complete subtitle files (about 1100 to 1300 subtitles depending on the language), and it seems somewhat random with intermediary sizes.
- The bug seems very strongly correlated (99 if not 100% of occurrences) with the display of a particular error in the logs: `[ERR] 163 errors encountered while parsing '"srt"' subtitle using the "SubRip" format parser`. I am pasting more complete logs below for the same movie, both when it works and when it does not work.

### Reproduction Steps

1. Environment and config: see below
2. Choose a movie with at least two subtitle tracks, for instance two SRT external subtitle files. Make sure those subtitle files have at least 1500 subtitles each.
3. Open the Android client, connect to a google chrome cast
4. Go to the movie on the Android client, select the first subtitle track
5. Hit play
6. Wait for 1-2 minutes after the first dialogues. Subtitles should break rapidly (randomly not showing, multiple languages and timestamps being overlayed).

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS:Debian Bookworm
- Linux Kernel: Linux 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
- Virtualization: None, running directly on Intel NUC
- Clients: Android
- Browser: N/A
- FFmpeg Version: jellyfin-ffmpeg6 6.0.1-7-bookworm
- Hardware Acceleration: Intel QSV
- GPU Model: 
- Plugins: None
- Reverse Proxy: None
- Base URL: N/A
- Networking: Local home network (IPv6)
- Storage: Local NAS
```

### Jellyfin logs

```shell
*** When it works: ***

[2024-06-15 22:59:31.300 +01:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-06-15 22:59:31.311 +01:00] [DBG] charset "utf-8" detected for "/path/to/library/MovieName.720p.x264.en.srt"
[2024-06-15 22:59:31.316 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser
[2024-06-15 22:59:31.336 +01:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-06-15 22:59:31.347 +01:00] [DBG] charset "utf-8" detected for "/path/to/library/MovieName.720p.x264.fr.srt"
[2024-06-15 22:59:31.359 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser


*** When the bug happens: ***

[2024-06-15 23:03:00.361 +01:00] [DBG] charset "utf-8" detected for "/path/to/library/MovieName.720p.x264.en.srt"
[2024-06-15 23:03:00.364 +01:00] [DBG] charset "utf-8" detected for "/path/to/library/MovieName.720p.x264.fr.srt"
[2024-06-15 23:03:00.411 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser
[2024-06-15 23:03:00.412 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser
[2024-06-15 23:03:00.449 +01:00] [ERR] 163 errors encountered while parsing '"srt"' subtitle using the "SubRip" format parser
[2024-06-15 23:03:00.453 +01:00] [ERR] 163 errors encountered while parsing '"srt"' subtitle using the "SubRip" format parser
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cchristchurch** [comment]
So I've been scratching my head for a couple of hours tonight trying to figure this out. I'm trying to confirm my suspicion that the issue was introduced by https://github.com/jellyfin/jellyfin-web/pull/3906

However I'm not getting very far as I lack the most basic understanding of the Jellyfin architecture :cry:  The first thing I tried to confirm is whether the PR introduced some changes to the API, but I'm completely baffled by the fact that the whole secondary subtitle feature seems fully self-contained in jellyfin-web and does not seem to affect the server at all? How is that possible when it seems to involve passing an extra parameter to the POST API call [here](https://github.com/jellyfin/jellyfin-web/pull/3906/files#diff-b338dd22dfaa8db18edede53fe56aabb5d911c5e611cc33ad3c914410d021cbfR506) ?? :face_with_diagonal_mouth:  Note that the chrome cast code does seem to use the [same API call](https://github.com/jellyfin/jellyfin-chromecast/blob/562df52d9b5cdf1a6bf126e494e06b0db217d54a/src/components/jellyfinActions.ts#L289C51-L289C63) (or at least something with a similar name). But if the underlying API wasn't changed there would be no reason for this to break...

It would probably help if @is343 or @thornbill could take a quick look here as I suspect they would be able to almost instantly confirm whether it is indeed possible that the secondary subtitle change introduced the issue or not.

**Comment by is343** [comment]
Hey @cchristchurch, I'm not sure if this would be terribly helpful but that if clause to add a param in `getPlaybackInfo` that eventually returns `apiClient.getPlaybackInfo(itemId, query, deviceProfile)` isn't actually sending anything off to the server for processing.

When I was building out this feature I was also learning as I went. Essentially just poking around at calls and reverse engineering stuff. You're right to say that the scope of this feature was really limited to the html player and client-side subtitles.

It's been awhile but if I remember correctly, that code you referenced was mainly for fetching after a stream change or coming back after navigating away. If I remember correctly this was involved in saving some sort of state for that? I might be misremembering if `getPlayerState` was just stored locally and maybe `getPlaybackInfo` was used for after returning in a new browser/client session?

It could also be a remnant of the whole dev process and trying figuring stuff out. Maybe I was going down a path and backtracked but ended up leaving that behind? Either way, I can tell you that this was not added with the intent of the server using it, but only for passing back to the client on initial load of the player for some edge case scenarios.

As you mentioned, this is not (to my knowledge) used in the backend code at all.

**Comment by felix920506** [comment]
Is it transcoding, remuxing or direct playing?

**Comment by cchristchurch** [comment]
I have run my little example again tonight to check the play method, with my example above (`MovieName.720p.x264.mkv`) the movie is being transcoded:

```
[2024-06-20 22:12:16.811 +01:00] [INF] User policy for "jellyfin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-06-20 22:12:16.817 +01:00] [DBG] Profile: "Unknown Profile", Path: "/path/to/library/MovieName.720p.x264.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: False
[2024-06-20 22:12:16.868 +01:00] [DBG] DirectPlay Result for Profile: "Anonymous Profile", Path: "/path/to/library/MovieName.720p.x264.mkv", PlayMethod: null, AudioStreamIndex: 3, SubtitleStreamIndex: 0, Reasons: ContainerNotSupported
[2024-06-20 22:12:16.895 +01:00] [DBG] Transcode Result for Profile: "Anonymous Profile", Path: "/path/to/library/MovieName.720p.x264.mkv", PlayMethod: Transcode, AudioStreamIndex: 3, SubtitleStreamIndex: 0, Reasons: ContainerNotSupported
[2024-06-20 22:12:16.900 +01:00] [DBG] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/path/to/library/MovieName.720p.x264.mkv", AudioStreamIndex=3, SubtitleStreamIndex=0 ) => ( PlayMethod=Transcode, TranscodeReason=ContainerNotSupported ) "media:/videos/7530c472-3a7e-5a58-7e94-222629ef8f97/master.m3u8?MediaSourceId=7530c4723a7e5a587e94222629ef8f97&VideoCodec=h264,h264&AudioCodec=aac&AudioStreamIndex=3&VideoBitrate=18453078&AudioBitrate=640000&AudioSampleRate=48000&MaxFramerate=23.976025&MaxWidth=1280&api_key=<token>&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=b4014865b2da28be01cd0e0c424680c0&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&h264-level=31&h264-videobitdepth=8&h264-profile=high&h264-audiochannels=2&aac-profile=lc&aac-audiochannels=2&TranscodeReasons=ContainerNotSupported"
```

I have not been able to find any example in my library where the movie is *not* being transcoded when sent to the chromecast, but I'll keep looking.

In the meantime I have observed that the issue seems **not** to affect (or at least very rarely) movies where the second subtitle track is using exotic encodings such as windows-1252 or iso-8859-1.

```
[2024-06-20 22:45:06.880 +01:00] [DBG] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/path/to/library/MovieName2.x264.mp4", AudioStreamIndex=3, SubtitleStreamIndex=0 ) => ( PlayMethod=Transcode, TranscodeReason=VideoResolutionNotSupported ) "media:/videos/26cd9145-db0c-c4ad-1138-d239419e4d9a/master.m3u8?MediaSourceId=26cd9145db0cc4ad1138d239419e4d9a&VideoCodec=h264,h264&AudioCodec=aac&AudioStreamIndex=3&VideoBitrate=20048796&AudioBitrate=95994&AudioSampleRate=48000&MaxFramerate=23.976025&MaxWidth=1280&api_key=<token>&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=b3912b6c361e53a19cb31c06e8a44cff&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&h264-level=40&h264-videobitdepth=8&h264-profile=high&h264-audiochannels=2&aac-profile=lc&aac-audiochannels=2&TranscodeReasons=VideoResolutionNotSupported"
[2024-06-20 22:45:11.045 +01:00] [DBG] charset "utf-8" detected for "/path/to/library/MovieName2.x264.en.srt"
[2024-06-20 22:45:11.058 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser
[2024-06-20 22:45:11.221 +01:00] [DBG] charset "iso-8859-1" detected for "/path/to/library/MovieName2.x264.fr.srt"
[2024-06-20 22:45:11.240 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser
=> works fine

[2024-06-20 22:57:12.426 +01:00] [DBG] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/path/to/library/MovieName3.x264.mp4", AudioStreamIndex=3, SubtitleStreamIndex=0 ) => ( PlayMethod=Transcode, TranscodeReason=VideoResolutionNotSupported, AudioChannelsNotSupported ) "media:/videos/caa3e19a-3c58-4af4-34b8-69b5499bcbe2/master.m3u8?MediaSourceId=caa3e19a3c584af434b869b5499bcbe2&VideoCodec=h264,h264&AudioCodec=aac&AudioStreamIndex=3&VideoBitrate=24664924&AudioBitrate=384000&AudioSampleRate=48000&MaxFramerate=23.976025&MaxWidth=1280&api_key=<token>&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=389a09452e31c502c2cb9389f887982a&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&h264-level=40&h264-videobitdepth=8&h264-profile=high&h264-audiochannels=6&aac-profile=lc&aac-audiochannels=2&TranscodeReasons=VideoResolutionNotSupported,%20AudioChannelsNotSupported"
[2024-06-20 22:57:17.053 +01:00] [DBG] charset "utf-8" detected for "/path/to/library/MovieName3.x264.en.srt"
[2024-06-20 22:57:17.069 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser
[2024-06-20 22:57:17.168 +01:00] [DBG] PingTranscodingJob PlaySessionId="53153cfafd264a679520f47188f098dd" isUsedPaused: False
[2024-06-20 22:57:17.175 +01:00] [DBG] charset "windows-1252" detected for "/path/to/library/MovieName3.x264.fr.srt"
[2024-06-20 22:57:17.183 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser
=> works fine

[2024-06-20 23:03:36.884 +01:00] [DBG] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/path/to/library/MovieName4.x264.mp4", AudioStreamIndex=3, SubtitleStreamIndex=0 ) => ( PlayMethod=Transcode, TranscodeReason=VideoResolutionNotSupported, AudioChannelsNotSupported ) "media:/videos/c1a76414-fb5c-cc79-7c67-7668d545ab55/master.m3u8?MediaSourceId=c1a76414fb5ccc797c677668d545ab55&VideoCodec=h264,h264&AudioCodec=aac&AudioStreamIndex=3&VideoBitrate=24664924&AudioBitrate=384000&AudioSampleRate=48000&MaxFramerate=23.976025&MaxWidth=1280&api_key=<token>&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=a416084529cec9c904303b22320e1f38&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&h264-level=41&h264-videobitdepth=8&h264-profile=high&h264-audiochannels=6&aac-profile=lc&aac-audiochannels=2&TranscodeReasons=VideoResolutionNotSupported,%20AudioChannelsNotSupported"
[2024-06-20 23:03:40.725 +01:00] [DBG] charset "utf-8" detected for "/path/to/library/MovieName4.x264.en.srt"
[2024-06-20 23:03:40.745 +01:00] [DBG] charset "utf-8" detected for "/path/to/library/MovieName4.x264.fr.srt"
[2024-06-20 23:03:40.756 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser
[2024-06-20 23:03:40.759 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser
[2024-06-20 23:03:40.802 +01:00] [ERR] 250 errors encountered while parsing '"srt"' subtitle using the "SubRip" format parser
[2024-06-20 23:03:40.828 +01:00] [ERR] 250 errors encountered while parsing '"srt"' subtitle using the "SubRip" format parser
=> broken subtitles 
```

From the examples above one may be tempted to extrapolate that the issue only affects movies with more than one subtitle track in utf-8, but it may be too early to jump to that conclusion. I'll attach more complete logs for the original example, in case I've missed something in there that could be relevant.
[full_logs_original_example.log](https://github.com/user-attachments/files/15920779/full_logs_original_example.log)

**Comment by felix920506** [comment]
What is the reason for it to transcode?

**Comment by cchristchurch** [comment]
In the first example, the transcode reason given in the logs is `ContainerNotSupported`, as it seems chromecast doesn't like the mkv format.

That seems a bit odd as I would expect only remuxing to be needed in that case? However I don't think that's related to the problem. In the three other examples I pasted after that using mp4 (2 working, 1 affected) the transcode reason is logged as `VideoResolutionNotSupported`.

**Comment by dpad** [comment]
I'm seeing the exact same issue as described by @cchristchurch. It's almost as if all the subtitle streams are getting mixed together and played simultaneously. Sometimes a subtitle will appear in English, then the next line in Dutch, then the next line will appear in 3 different languages overlaid on top of each other, then no subtitles will appear for a few lines, etc.

In my case too, this also seems to have started after upgrading from 10.8.x to 10.9.x. 

PR #10884 caught my eye in that it was merged in 10.9.0 and introduced the ability to extract all subtitle streams simultaneously. Although it could be pure coincidence (and I don't want to imply fault or anything like that), I got a little suspicious just based on the behaviour and description of that PR. I wonder if the author (@alltilla) might have any thoughts or be able to help in any way? (Sorry if there is no connection at all @alltilla , at the very least you might know a bit about the internals of subtitle extraction and could maybe point us in the right direction?)

**Comment by alltilla** [comment]
I have just glanced through the issue. I am not an expert in the whole jellyfin infrastructure, so take everything I say with a grain of salt.

#10884 affects only the extraction of the subtitles from the container. Before the PR, all subtitle streams were extracted in separate `ffmpeg` process calls, after it, it is done with one. We need subtitle extraction, because some clients expect the subtitles to be sent separately, so it can do its own rendering, formatting, etc.

The problem you are experiencing can be caused by multiple layers of this process, I can imagine that there could be a problem in the client's subtitle rendering, but it is possible that the extraction step produced the wrong subtitle file, and the client just renders its content as it was given to it, and other places can be problematic as well, but I am not sure. On the extraction side, I can imagine if we somehow set the output file path to be the same for multiple subtitle streams, this could happen. Before my PR, if the `ffmpeg` commands were executed serially, you would just end up with a fully overwritten subtitle file, but if multiple threads are writing the same file concurrently things like this can happen. It is possible that I have implemented something wrong, or my change surfaced a problem that already existed, or the problem can be somewhere else entirely, sorry if it is the former.

What could really help this investigation is if you could find the extracted and cached subtitle file yourself on your server and could check if it has the correct data or not. I am not sure where the cached files are, but there should be `ffmpeg` logs, which show the path of them. If you find problematic subtitle files, the next step would be to find the log entry about the generation of that file, maybe you can observe the same path for multiple streams problem I mentioned above. However, if the subtitles themselves look like what you would expect it is safe to assume that the problem rises from somewhere else. In the issue description I can see that the subtitles themselves are working with some clients, but not with others, so I think the problem is probably not caused during extraction, but checking these things would help to isolate for sure.

I don't think that I will have the time to reproduce and investigate this problem in the near future, but I can follow the investigation and give hints.

Cheers,
Attila

**Comment by dpad** [comment]
@alltilla Thank you very much for your quick response and very helpful tips! Sorry to pull you in here, I very much appreciate the expertise.

Just as a quick report, I was able to find the seemingly extracted subtitle files (for me on Windows, in `C:\ProgramData\Jellyfin\Server\data\subtitles\`). It appears that the individual languages are extracted into individual files correctly.

**Comment by cchristchurch** [comment]
The plot thickens... 

I've continued experiments with my first example movie above, but I've manually re-encoded the second subtitle track srt file to **ISO-8859-1** instead of **UTF-8**.... and the issue does **not** happen anymore.... :exploding_head: 

```
[2024-06-23 10:29:17.042 +01:00] [INF] User policy for "jellyfin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-06-23 10:29:17.043 +01:00] [DBG] Profile: "Unknown Profile", Path: "/path/to/library/MovieName.720p.x264.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: False
[2024-06-23 10:29:17.044 +01:00] [DBG] DirectPlay Result for Profile: "Anonymous Profile", Path: "/path/to/library/MovieName.720p.x264.mkv", PlayMethod: null, AudioStreamIndex: 3, SubtitleStreamIndex: 0, Reasons: ContainerNotSupported
[2024-06-23 10:29:17.044 +01:00] [DBG] Transcode Result for Profile: "Anonymous Profile", Path: "/path/to/library/MovieName.720p.x264.mkv", PlayMethod: Transcode, AudioStreamIndex: 3, SubtitleStreamIndex: 0, Reasons: ContainerNotSupported
[2024-06-23 10:29:17.045 +01:00] [DBG] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/path/to/library/MovieName.720p.x264.mkv", AudioStreamIndex=3, SubtitleStreamIndex=0 ) => ( PlayMethod=Transcode, TranscodeReason=ContainerNotSupported ) "media:/videos/7530c472-3a7e-5a58-7e94-222629ef8f97/master.m3u8?MediaSourceId=7530c4723a7e5a587e94222629ef8f97&VideoCodec=h264,h264&AudioCodec=aac&AudioStreamIndex=3&VideoBitrate=13671270&AudioBitrate=640000&AudioSampleRate=48000&MaxFramerate=23.976025&MaxWidth=1280&api_key=<token>&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=b4014865b2da28be01cd0e0c424680c0&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=False&h264-level=31&h264-videobitdepth=8&h264-profile=high&h264-audiochannels=2&aac-profile=lc&aac-audiochannels=2&TranscodeReasons=ContainerNotSupported"
[2024-06-23 10:29:18.338 +01:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-06-23 10:29:18.338 +01:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-06-23 10:29:18.341 +01:00] [DBG] Starting transcoding because currentTranscodingIndex=null
[2024-06-23 10:29:18.342 +01:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -fflags +genpts  -i file:\"/path/to/library/MovieName.720p.x264.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/var/lib/jellyfin/transcodes/57e569f503d8c47e6ccd739dc1fce9a6%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/57e569f503d8c47e6ccd739dc1fce9a6.m3u8\""
[2024-06-23 10:29:18.351 +01:00] [DBG] Launched FFmpeg process
[2024-06-23 10:29:18.386 +01:00] [DBG] Waiting for the creation of "/var/lib/jellyfin/transcodes/57e569f503d8c47e6ccd739dc1fce9a60.ts"
[2024-06-23 10:29:19.290 +01:00] [DBG] File "/var/lib/jellyfin/transcodes/57e569f503d8c47e6ccd739dc1fce9a60.ts" created or transcoding has finished
[2024-06-23 10:29:19.291 +01:00] [DBG] StartFfMpeg() finished successfully
[2024-06-23 10:29:19.291 +01:00] [DBG] returning "/var/lib/jellyfin/transcodes/57e569f503d8c47e6ccd739dc1fce9a60.ts" [general case]
[2024-06-23 10:29:19.292 +01:00] [DBG] serving up "/var/lib/jellyfin/transcodes/57e569f503d8c47e6ccd739dc1fce9a60.ts" as transcode index 1 is past requested point 0
[2024-06-23 10:29:19.305 +01:00] [DBG] Finished serving "/var/lib/jellyfin/transcodes/57e569f503d8c47e6ccd739dc1fce9a60.ts"
[2024-06-23 10:29:19.306 +01:00] [DBG] OnTranscodeEndRequest job.ActiveRequestCount=0
[2024-06-23 10:29:19.306 +01:00] [DBG] Starting kill timer at 60000ms. JobId "c429eac6474349d08004ad7392d694f4" PlaySessionId "77694aed39884f2b837b4976289c2544"
[2024-06-23 10:29:19.641 +01:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-06-23 10:29:19.641 +01:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-06-23 10:29:19.644 +01:00] [DBG] returning "/var/lib/jellyfin/transcodes/57e569f503d8c47e6ccd739dc1fce9a61.ts" [it exists, try 1]
[2024-06-23 10:29:19.644 +01:00] [DBG] serving up "/var/lib/jellyfin/transcodes/57e569f503d8c47e6ccd739dc1fce9a61.ts" as transcode index 7 is past requested point 1
[2024-06-23 10:29:19.980 +01:00] [DBG] Finished serving "/var/lib/jellyfin/transcodes/57e569f503d8c47e6ccd739dc1fce9a61.ts"
[2024-06-23 10:29:19.980 +01:00] [DBG] OnTranscodeEndRequest job.ActiveRequestCount=0
[2024-06-23 10:29:19.980 +01:00] [DBG] Changing kill timer to 60000ms. JobId "c429eac6474349d08004ad7392d694f4" PlaySessionId "77694aed39884f2b837b4976289c2544"
[2024-06-23 10:29:20.315 +01:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-06-23 10:29:20.315 +01:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-06-23 10:29:20.761 +01:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-06-23 10:29:20.775 +01:00] [DBG] charset "utf-8" detected for "/path/to/library/MovieName.720p.x264.en.srt"
[2024-06-23 10:29:20.781 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser
[2024-06-23 10:29:20.828 +01:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-06-23 10:29:20.858 +01:00] [DBG] charset "iso-8859-1" detected for "/path/to/library/MovieName.720p.x264.fr.srt"
[2024-06-23 10:29:20.862 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser
[2024-06-23 10:29:20.961 +01:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2024-06-23 10:29:20.961 +01:00] [DBG] AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
```

Note that I did the re-encoding using python and initially got errors like `'latin-1' codec can't encode character '\u0153' in position 30541: ordinal not in range(256)` so I had to skip these characters. 

I'm wondering if it's certain specific characters that cause the issue, but I really don't understand how it is possible. I would understand if some characters were not displayed properly or maybe if the subtitle track containing these characters could not be displayed, but it is really weird that it is affecting other subtitle tracks. I'm wondering if it could have something to do with variable-length characters and maybe the decoding logic getting confused and processing everything with an offset?

**Comment by BarbUk** [comment]
I have the same issue when casting to chromecast.
I can confirm that I have the same error in the log:

```
Jul 12 12:20:15 jellyfin[99]: [12:20:15] [ERR] 547 errors encountered while parsing 'srt' subtitle using the SubRip format parser
```

Note that to mitigate the issue, I do the following:
 - configure `Minimum resume percentage` to a low value (1) to be able to continue the media
 - play the media (stream to chromecast)
 - wait to see the first bad subtitles (several languages mixed / merged together)
 - stop the stream
 - launch the stream from the `continue` tab

The media will continue with the correct subtitle without issue.

**Comment by cchristchurch** [comment]
I see this is still marked as Needs triage / Insufficient data / Probably a client issue.

Regarding that last point it seems that the ERR log we are observing is coming from [here](https://github.com/jellyfin/jellyfin/blob/2b0082bf15c8ea0c4248c1fcd2d2558c047e237f/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs#L59), is this not a sufficient indication that the error is on the server side?

**Comment by BarbUk** [comment]
There are changes that can have an impact:
 - an old commit from 2 years ago:
[38eefbbaf Backport pull request #8087 from jellyfin/release-10.8.z <Joshua Boniface>  2022-08-01 14h25 (2 years ago)](https://github.com/jellyfin/jellyfin/commit/38eefbbafa381ea2d87efaa3328c5e273b902732)

 - multiple updates to libse:
[3.6.10 -> 3.6.11](https://github.com/jellyfin/jellyfin/pull/9473)
[3.6.11 -> 3.6.13](https://github.com/jellyfin/jellyfin/pull/9766)
[3.6.13 -> 4.0.5](https://github.com/jellyfin/jellyfin/pull/11353)

Libse has a [4.0.7](https://github.com/SubtitleEdit/subtitleedit/releases) release on github, but not published on [nuget](https://www.nuget.org/packages/libse/).

I [submitted an issue](https://github.com/SubtitleEdit/subtitleedit/issues/8661) to ask if the new release can be made available on nuget.

I tried rolling back to 3.6.13, still the same issue.

**Comment by BarbUk** [comment]
Rolling back to libse `3.6.10` fix the issue.

```patch
diff --git a/Directory.Packages.props b/Directory.Packages.props
index 825301bfc..8233d0f49 100644
--- a/Directory.Packages.props
+++ b/Directory.Packages.props
@@ -22,7 +22,7 @@
     <PackageVersion Include="ICU4N.Transliterator" Version="60.1.0-alpha.356" />
     <PackageVersion Include="IDisposableAnalyzers" Version="4.0.8" />
     <PackageVersion Include="Jellyfin.XmlTv" Version="10.8.0" />
-    <PackageVersion Include="libse" Version="4.0.5" />
+    <PackageVersion Include="libse" Version="3.6.10" />
     <PackageVersion Include="LrcParser" Version="2023.524.0" />
     <PackageVersion Include="MetaBrainz.MusicBrainz" Version="6.1.0" />
     <PackageVersion Include="Microsoft.AspNetCore.Authorization" Version="8.0.7" />
```

**Comment by BarbUk** [comment]
Tested a new build with libse 4.0.7, the subtitle issue is resolved with this new version.
cf: https://github.com/jellyfin/jellyfin/pull/12329#issuecomment-2247879761

**Comment by cchristchurch** [comment]
I've upgraded to 10.9.9 which has the libse version bump but unfortunately I'm still seeing the issue :disappointed: exact same symptoms and error logs as before on the same media.

**Comment by dpad** [comment]
I confirm what @cchristchurch said. In addition, I've tried downgrading Jellyfin server to 10.9.7, but the issue persists. I'm still running the latest Android app and web versions, so this implies to me that it might be a problem on the `jellyfin-chromecast` client side? (Maybe https://github.com/jellyfin/jellyfin-chromecast/issues/576 ?)

**Comment by BarbUk** [comment]
I can confirm this too.
My test with rollbacking to `libse` 3.6.10 or upgrading to 4.0.7 were not accurate.

I don't know how to reproduce the problem consistently.
A lot of already played media don't have the issue anymore, with the new or old `libse` version.

But I still have the issue on never played before media.

The only constant is the log.
When I have the issue, the log always encounter error while parsing the subtitle.

```
Aug 15 17:34:06 jellyfin[115]: [17:34:06] [ERR] 312 errors encountered while parsing 'srt' subtitle using the SubRip format parser
Aug 15 17:34:06 jellyfin[115]: [17:34:06] [ERR] 312 errors encountered while parsing 'srt' subtitle using the SubRip format parser
```

Looking [at the code](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs#L46-L63), the issue seem to be that if a sub has an error, multiple subtitle are loaded in the `subtitle` object via `subtitleFormat.LoadSubtitle(subtitle, lines, fileExtension);`

If I instantiate a new subtitle object when the loop have a subtitle with error, I don't have the issue with multiple subtitle loaded anymore.
```patch
diff --git a/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs b/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
index fd55db4ba..c729991ef 100644
--- a/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
+++ b/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
@@ -55,6 +55,8 @@ namespace MediaBrowser.MediaEncoding.Subtitles
                     break;
                 }
 
+                subtitle = new Subtitle();
+
                 _logger.LogError(
                     "{ErrorCount} errors encountered while parsing '{FileExtension}' subtitle using the {SubtitleFormatParser} format parser",
                     subtitleFormat.ErrorCount,
```

But now I don't have the english sub in a lot of case.

So the issue is why streaming a media never played before produce error when loading the subtitle, but stopping and relaunching the same media, the subtitles are loaded fine without error.

**Comment by cchristchurch** [comment]
From @BarbUk 's experiment above it definitely seems that the `Parse` function [here](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs#L46-L63) is flawed in some way. Surely a failure during the call to `LoadSubtitle` should not result in the `subtitle` object being reused in this way.

However I don't understand how this could result in **languages** being mixed up. I don't think this loop iterates over multiple languages, but multiple formats. I suspect that in most cases there is a single format for a given subtitle track? The original implementation of the Parse function did not have this loop (it was introduced in https://github.com/jellyfin/jellyfin/pull/8087).

The sequence of logs in failure cases suggests that there are two parallel / asynchronous executions of this loop, but each execution iterates a single time through the loop body, for instance:
[2024-06-28 09:30:42.116 +01:00] [DBG] charset "utf-8" detected for "/path/to/library/MovieName.720p.x264.en.srt"
[2024-06-28 09:30:42.122 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser [**Loop body begins, line 48**]
[2024-06-28 09:30:42.129 +01:00] [DBG] charset "iso-8859-1" detected for "/path/to/library/MovieName.720p.x264.fr.srt"
[2024-06-28 09:30:42.133 +01:00] [DBG] Trying to parse '"srt"' subtitle using the "SubRip" format parser [**Again, loop body begins, line 48**]
[2024-06-28 09:30:42.150 +01:00] [ERR] 120 errors encountered while parsing '"srt"' subtitle using the "SubRip" format parser [**Loop body ends, line 58**]
[2024-06-28 09:30:42.156 +01:00] [ERR] 120 errors encountered while parsing '"srt"' subtitle using the "SubRip" format parser [**Again loop body ends at line 58**]

I'm wondering if there is something in the code of this `Parse` method (or within the code of libse that it calls) that does not support multithreaded / asynchronous execution correctly?

**Comment by BarbUk** [comment]
> I don't think this loop iterates over multiple languages, but multiple formats. I suspect that in most cases there is a single format for a given subtitle track?

Yes.

Using the recommandation from the libse developper from https://github.com/SubtitleEdit/subtitleedit/issues/8661#issuecomment-2246422256, I remove the loop, don't have any error in the log, but still have the same issue:

```patch
diff --git a/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs b/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
index fd55db4ba..7b96bdcdd 100644
--- a/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
+++ b/MediaBrowser.MediaEncoding/Subtitles/SubtitleEditParser.cs
@@ -35,31 +35,11 @@ namespace MediaBrowser.MediaEncoding.Subtitles
         /// <inheritdoc />
         public SubtitleTrackInfo Parse(Stream stream, string fileExtension)
         {
-            var subtitle = new Subtitle();
             var lines = stream.ReadAllLines().ToList();
-
-            if (!_subtitleFormats.TryGetValue(fileExtension, out var subtitleFormats))
+            var subtitle = Subtitle.Parse(lines, fileExtension);
+            if (subtitle == null)
             {
-                throw new ArgumentException($"Unsupported file extension: {fileExtension}", nameof(fileExtension));
-            }
-
-            foreach (var subtitleFormat in subtitleFormats)
-            {
-                _logger.LogDebug(
-                    "Trying to parse '{FileExtension}' subtitle using the {SubtitleFormatParser} format parser",
-                    fileExtension,
-                    subtitleFormat.Name);
-                subtitleFormat.LoadSubtitle(subtitle, lines, fileExtension);
-                if (subtitleFormat.ErrorCount == 0)
-                {
-                    break;
-                }
-
-                _logger.LogError(
-                    "{ErrorCount} errors encountered while parsing '{FileExtension}' subtitle using the {SubtitleFormatParser} format parser",
-                    subtitleFormat.ErrorCount,
-                    fileExtension,
-                    subtitleFormat.Name);
+              throw new ArgumentException("Invalid subtitle with file extension: " + fileExtension);
             }
 
             if (subtitle.Paragraphs.Count == 0)
```

The libse `Subtitle.Parse(lines, fileExtension)` find the correct parser for extension, but I still have a mangled subtitle, indicating that the subtitle in cache or in memory is not right.

If I check the subtitle cache dir `/var/lib/jellyfin/data/subtitles`, the subtitle is valid.
If I play a media which has already extracted and cached the subtitles, the subtitle play without issue.

> I'm wondering if there is something in the code of this Parse method (or within the code of libse that it calls) that does not support multithreaded / asynchronous execution correctly?

I tried to check the file [`SubtitleEncoder.cs`](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs#L83) that call the `Parse()` function, and rollback to the commit before this one [Extract all subtitle streams simultaneously](https://github.com/jellyfin/jellyfin/commit/8fea819b5152f6a38febb9435df18c2fa26d3273), but I still have the problem.

**Comment by nickdurante** [comment]
I think I found a workaround:

Admin panel -> Playback -> Transcoding -> Uncheck: Allow subtitle extraction on the fly
Install plugin Subtitle Extract (v4.0.0.0) -> plugin settings -> Check: Extract subtitles during library scan

This solves the issue on my Chromecast gen 2.

**Comment by dpad** [comment]
> **UPDATE**: after some additional testing, this configuration doesn't solve the issue all the time. Nevertheless, I noticed an improvement in the frequency in which the issue appears. Sometimes using the track downloaded from openSubtitles fixes the problem for the file I'm trying to watch.

Yeah, I confirm this. It seems to have improved the situation a little, but there's still cases where the subtitles are all mixed up. Thanks for trying to find a workaround. Sadly I will have to downgrade back to 10.8.13 again... :(

**Comment by matthiasvegh** [comment]
I upgraded to 10.10 from 10.9 and observed similar behavior but only when using Jellyfin on my Nvidia Shield. Other devices appear unaffected. As the new version of jellyfin-android-tv mentioned no longer needing the subtitles extract plugin, I removed and purged all subtitles from my instance (`for f in data/subtitles; do rm $f/*.srt; done`) this appeared to help at the expense of delaying playback but did not resolve it completely. It appeared that the first time something was played it was alright, but resuming playback would exhibit the same mix-up.

I then considered that maybe the new mechanism for extracting subtitles might mean extraction would need to be rerun so I reinstalled subtitles-extract and reran it but it also didn't help. That said, I was pleasantly surprised by the faster extraction speed due to extracting all subtitles concurrently.

My current resolution has been to rollback jellyfin-android-tv (to 0.17.9) and keep the server running 10.10.

**Comment by Mk555** [comment]
> I think I found a workaround:
> 
> Admin panel -> Playback -> Transcoding -> Uncheck: Allow subtitle extraction on the fly Install plugin Subtitle Extract (v4.0.0.0) -> plugin settings -> Check: Extract subtitles during library scan
> 
> This solves the issue on my Chromecast gen 2.
> 
> **UPDATE**: after some additional testing, this configuration doesn't solve the issue all the time. Nevertheless, I noticed an improvement in the frequency in which the issue appears. Sometimes using the track downloaded from openSubtitles fixes the problem for the file I'm trying to watch.

It's improving the situation when casting on a smart TV running on Android TV (I don't have the exact model, sorry for the lack of details)

**Comment by allandcda** [comment]
I have this problem too, it's extremely annoying. I continue to follow the dismemberment

**Comment by khellste** [comment]
I have this problem as well, also on the Android TV Jellyfin app.

I was able to work around it (at least, that's how it seems for now) by doing the following:
1. Disabling the builtin on-the-fly subtitle extraction in the Admin panel as described in https://github.com/jellyfin/jellyfin/issues/12113#issuecomment-2553583428
2. *Disabling* (not enabling) the Subtitle Extract plugin, which I already had installed.
3. Manually deleting the subtitle cache at `$JELLYFIN_DATA_DIR/subtitles`.
4. Restarting the server.

This seems to have fixed it for me, though at the cost of a small delay (~10s) on video startup.

I wonder if the only reason this works is because the subtitle cache miss triggers some better behaved code path, and I suspect that replaying the same video would repro the bug again, but I haven't been able to verify this.

**Comment by DeusFacticius** [comment]
Came here to say +1; this has become a very annoying, borderline deal-breaker bug for me since I have no (satisfactory) workarounds, and working subtitles often aren't optional for my family and I. As time goes on, I'm becoming more desperate for a solution, but it's a shame really because I love Jellyfin, and this _used_ to work flawlessly.

I discovered this issue _around_ the same time this issue was posted, maybe a bit earlier. I first thought maybe it was just a sporadic quirk possibly stemming from corrupt media or transient resource contention issues, but after I realized it was becoming consistent and affecting all media, I started searching and found this issue. I can't recall for certain if it was introduced by upgrading to 10.9.x, but it aligns with the timeline.

I'm currently running 10.10.3, and this is still an issue.

A while back, I attempted to downgrade from 10.9.x (which was current at the time) to 10.8.x as a workaround, only to find out that it was not practical (nothing was backwards compatible, neither server data nor clients, between 10.9.x and 10.8.x).

The only (unsatisfactory) workarounds I've found are:

1. Playing / streaming jellyfin on my android phone, and screencasting (e.g. screen-mirroring) to my TV + Chromecast. The android client is capable of natively decoding and rendering embedded subtitles, and so isn't impacted by this issue. This works better than I would have anticipated, but it still has many flaws that make it unsatisfactory.
2. Preemptively re-encoding media using tools like Handbrake with subtitle burn-in enabled. This does make the playback experience as good as it was before this bug, but at the cost of being very tedious / time-consuming to perform manually, and (since I like to preserve originals) doubles the storage requirements.


> I have this problem as well, also on the Android TV Jellyfin app.
> 
> I was able to work around it (at least, that's how it seems for now) by doing the following:
> 
>     1. Disabling the builtin on-the-fly subtitle extraction in the Admin panel as described in [[Issue]: Broken subtitles: Multiple languages and timestamps mixing up on screen when using chromecast #12113 (comment)](https://github.com/jellyfin/jellyfin/issues/12113#issuecomment-2553583428)
> 
>     2. _Disabling_ (not enabling) the Subtitle Extract plugin, which I already had installed.
> 
>     3. Manually deleting the subtitle cache at `$JELLYFIN_DATA_DIR/subtitles`.
> 
>     4. Restarting the server.
> 
> 
> This seems to have fixed it for me, though at the cost of a small delay (~10s) on video startup.
> 
> I wonder if the only reason this works is because the subtitle cache miss triggers some better behaved code path, and I suspect that replaying the same video would repro the bug again, but I haven't been able to verify this.

Doesn't this trigger transcoding (to burn-in the subtitles, since you've now disabled all paths for extraction to occur)? That would likely fix the issue of course, as the burn in is performed server-side, but would only work in scenarios where the server is capable of full real-time transcoding -- unfortunately this isn't practical in my case (I run the server on an older Synology DS415+ -- it can *almost* keep up with x264 1080p, but it's just a tad too slow for reliable on-the-fly transcoding).

Tangent: Although simply fixing the bug that is the subject of this issue thread would be the most desirable outcome, it makes me think that (automated) management of preemptive _offline_ transcoding to preferred codecs / formats might be a nice (future) feature for Jellyfin, as it would have practical applications for myself and many others that run servers incapable of reliable on-the-fly transcoding beyond just presenting yet another workaround for this bug.

**Comment by khellste** [comment]
> Doesn't this trigger transcoding (to burn-in the subtitles, since you've now disabled all paths for extraction to occur)? That would likely fix the issue of course, as the burn in is performed server-side, but would only work in scenarios where the server is capable of full real-time transcoding -- unfortunately this isn't practical in my case (I run the server on an older Synology DS415+ -- it can _almost_ keep up with x264 1080p, but it's just a tad too slow for reliable on-the-fly transcoding).

After each 10s startup delay, there are a bunch of new `.srt` files in the subtitle cache. My understanding is that SRT is widely supported and doesn't usually require being burned in, but I'm not sure how to actually tell whether any transcoding is happening.

**Comment by khellste** [comment]
> I have this problem as well, also on the Android TV Jellyfin app.
> 
> I was able to work around it (at least, that's how it seems for now) by doing the following:
> 
> 1. Disabling the builtin on-the-fly subtitle extraction in the Admin panel as described in [[Issue]: Broken subtitles: Multiple languages and timestamps mixing up on screen when using chromecast #12113 (comment)](https://github.com/jellyfin/jellyfin/issues/12113#issuecomment-2553583428)
> 2. _Disabling_ (not enabling) the Subtitle Extract plugin, which I already had installed.
> 3. Manually deleting the subtitle cache at `$JELLYFIN_DATA_DIR/subtitles`.
> 4. Restarting the server.
> 
> This seems to have fixed it for me, though at the cost of a small delay (~10s) on video startup.
> 
> I wonder if the only reason this works is because the subtitle cache miss triggers some better behaved code path, and I suspect that replaying the same video would repro the bug again, but I haven't been able to verify this.

Update: The issue competing subtitles started happening again for me, even after taking these steps.

**Comment by alltilla** [comment]
@khellste Can you check whether the subtitle files in `$JELLYFIN_DATA_DIR/subtitles` are correct, or they already contain mixed up content?

**Comment by khellste** [comment]
I glanced through a few of the SRT files in `$JELLYFIN_DATA_DIR/subtitles`, and they seem correct to me. At the very least, each file contained subtitles in only one language, which is consistent with the idea that multiple sets of subtitles are being played at the same time, rather than a single corrupted subtitles file.

**Comment by matthiasvegh** [comment]
I applied a similar workaround and had the same delay on startup. From what I recall, the issue came back on rewatching an episode after the delay. I also found the jellyfin logs were full of srt parse errors. I understand that 10.10 made it so that errors from parsing srts were actually logged, so it's not obvious whether the corrupted srts were new or old as the logging for them was new.

I don't have those logs anymore, but maybe @khellste can show an extract of them.

**Comment by patryk-matis** [comment]
So no fix so far?

**Comment by khellste** [comment]
> I applied a similar workaround and had the same delay on startup. From what I recall, the issue came back on rewatching an episode after the delay. I also found the jellyfin logs were full of srt parse errors. I understand that 10.10 made it so that errors from parsing srts were actually logged, so it's not obvious whether the corrupted srts were new or old as the logging for them was new.
> 
> I don't have those logs anymore, but maybe [@khellste](https://github.com/khellste) can show an extract of them.

Here's a relevant log file: [Log.txt](https://github.com/user-attachments/files/18279579/Log.txt)

And here's the first SRT file that gets extracted (renamed to txt for upload): [c3c35aa1-bb2f-839f-225b-6ee03ed72fa4.srt](https://github.com/user-attachments/files/18279609/c3c35aa1-bb2f-839f-225b-6ee03ed72fa4.txt)

Here's an excerpt from the log:
```
[2024-12-29 02:49:27.532 +00:00] [ERR] [103] MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser: 35 errors encountered while parsing '"srt"' subtitle using the "SubRip" format parser, errors: "Line 36 - expected subtitle number: Il y en aurait environ trois fois plus
Line 60 - error reading time code: que pendant la première Guerre Gamma.
Line 116 - error reading time code: 255
Line 175 - error reading time code: 11
Line 215 - error reading time code: 14
Line 287 - error reading time code: 20
Line 296: Empty line expected, but found number (120) followed by time code.
Line 304 - expected subtitle number: {\an8}<i>Jeg skal føre jer gennem
Line 305 - error reading time code: disse vidtstrakte nye virkeligheder.</i>
Line 422 - error reading time code: No niin, mahtava Kostaja!
Line 422: Empty line expected, but found number (139) followed by time code.
Line 440 - error reading time code: Banner teki käyttöliittymästä
Line 441 - expected subtitle number: helppokäyttöisen.
Line 445 - error reading time code: 276
Line 484 - error reading time code: 不是我,發生了別的狀況
Line 548 - error reading time code: 147
Line 550 - error reading time code: 35
Line 569 - error reading time code: Tuhotaan se.
Line 664: Empty line expected, but found number (289) followed by time code.
Line 820 - expected subtitle number: I've been trying everything lately.
Line 822 - error reading time code: 51
Line 844 - error reading time code: 164
Line 848 - error reading time code: 53
Line 852 - error reading time code: 他曾經是你的朋友,山姆
Line 1027 - expected subtitle number: Ei hätää, Sam.
Line 1035: Empty line expected, but found number (62) followed by time code.
Line 1070: Empty line expected, but found number (316) followed by time code.
Line 1082 - error reading time code: 317
Line 1087 - error reading time code: 67
Line 1311 - expected subtitle number: Så hvis nogen gerne vil tage billetten ...</i>
Line 1315 - error reading time code: 78
Line 1392 - error reading time code: 335
Line 1397 - expected subtitle number: 00:07:11,291 --> 00:07:13,375
Line 1398 - error reading time code: <i>Men hvor kommer de fra?</i>
Line 1404 - error reading time code: 84
Line 1427 - error reading time code: 86
Line 1430 - error reading time code: - [Sarah whimpers]
"
```

Now I'm no expert, but all the SRT files (such as the one I shared) seem fine and valid to me. The parser, on the other hand, seems to be somehow reading a garbled mix of multiple subtitle files at the same time, resulting in some wacky errors.

**Comment by matthiasvegh** [comment]
Yes I can confirm, this is what I saw, too. For episodes/movies with only one subtitle track, it didn't emerge even without any workarounds. SRTs looked reasonable when I looked at them, too. I just don't know if this garbling of SRTs is new with 10.10 or if it was there previously as the logs you have posted are new in 10.10 (https://github.com/jellyfin/jellyfin/pull/12479)

What confuses me is why my current setup of 10.10 with jellyfin-androidtv held back to 0.17.9 works well. Surely if 10.10 is extracting subtitles incorrectly it would send garbled subtitles to clients that request separate subtitles (like androidtv pre 0.18), and it should just work with clients that can render subtitles natively (androidtv 0.18 and up).

**Comment by alltilla** [comment]
Just an idea:

Maybe libse's SubtitleFormat::LoadSubtitle method is stateful (not thread safe), and the Parse  https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.MediaEncoding%2FSubtitles%2FSubtitleEditParser.cs#L36 method is using the same SubtitleFormat instances from multiple threads.

This would explain loading the srt file to Subtitle Edit (using libse) successfully, but failing to do so in Jellyfin.

On why it only happened now, I think changing the subtitle renderer in jellyfin-androidtv 0.18.0 might have resulted in calling some functions that have not been called before (or have not been called from multiple threads before), just a guess, though.

All of these are open source, so we can check, I will try to do so in a couple of days after the holidays.

**Comment by khellste** [comment]
> Maybe libse's SubtitleFormat::LoadSubtitle method is stateful (not thread safe), and the Parse https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.MediaEncoding%2FSubtitles%2FSubtitleEditParser.cs#L36 method is using the same SubtitleFormat instances from multiple threads.

One way to test this theory would be to invoke `GetSubtitleFormats()` inside the body of `Parse()` rather than once at startup, i.e. get rid of `_subtitleFormats`.

**Comment by RenV123** [comment]
@alltilla I changed the Parse function to add GetSubtitleFormats() inside the body and did some testing and from what I can tell it seems to fix the issue. All the media (which before had issues) I've tested so far displays the subtitles correctly.

**Comment by khellste** [comment]
> [@alltilla](https://github.com/alltilla) I changed the Parse function to add GetSubtitleFormats() inside the body and did some testing and from what I can tell it seems to fix the issue. All the media (which before had issues) I've tested so far displays the subtitles correctly.

Maybe not caching GetSubtitleFormats() doesn't actually have a big performance cost, and the suggested change could be a viable long-term fix? It's certainly easier than hunting down a race condition in a third-party dependency.

**Comment by alltilla** [comment]
Thanks @RenV123 for checking this out!

@khellste We could cache the class instead of the instances to a `_subtitleFormatTypes`  map, then lookup the class and create one new instance in `Parse()`. This would have minimal performance impact compared to the code on main, namely one constructor call. With @RenV123 's PoC we iterate though and instantiate all available `SubtitleFormat`s for each `Parse()` call, which can be significantly slower.

**Comment by alltilla** [comment]
Opened a PR with the fix. I could not reproduce the issue locally, so any testing of the PR is welcome. :)

**Comment by normanu** [comment]
Is it possible to test this with a docker branche?
Its not yet pushed in latest?

**Comment by alltilla** [comment]
This might help https://jellyfin.org/docs/general/installation/source/#container-image

**Comment by normanu** [comment]
I can also confirm it is fixed with this update. (latest push to 10.10.5)

**Comment by felix920506** [comment]
Closing as fixed by #13384
