### ISSUE TITLE
[Issue]: Audio Normalization Scheduled Task Errors

### ISSUE THREAD

**Issue by jamieboxtechs** [jellyfin/jellyfin#12145]
### Please describe your bug

I posted this in the forum first, and it was suggested that I create this post here, as the logging is showing a locked concat file, during the audio normalization scheduled task routine, that appears to be an under the hood problem, possibly a minor bug. Or it could be a plugin, maybe. The main log is sparse on the topic. 

From the Forum (edited for brevity):

I recently reset my Jellyfin to a clean install on a new box. 

The Audio Normalization scheduled task continues to fail. Log snip of the failure event and surrounding events is below.

    [2024-06-17 20:27:51.680 -04:00] [ERR] [57] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task System.IO.IOException: The process cannot access the file 'C:\ProgramData\Jellyfin\Server\cache\transcodes\6bab25e2-5614-4b60-a3d7-735ccb7f6501.concat' because it is being used by another process.

      at System.IO.FileSystem.DeleteFile(String fullPath)

      at Emby.Server.Implementations.ScheduledTasks.Tasks.AudioNormalizationTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)

      at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)

    [2024-06-17 20:27:51.974 -04:00] [INF] [57] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Audio Normalization" Failed after 0 minute(s) and 10 seconds

Jellyfin Server and PC Specs:

Jellyfin 10.9.6
Windows Server (Win 11 Pro) running Jellyfin service
AMD Ryzen 9 7950X
64GB DDR5-4800 RAM
NVIDIA RTX 3060 12GB
OS Drive: Samsung 990 Pro 2TB
Media Drive (all libraries): QNAP TS-932PX NAS with 5 x Seagate Ironwolf Pro 16TB in RAID5 connected with 10Gbps iSCSI link 

Logging output with debugging on, including the contents of the concat file, which is displayed with the same data in every concat file. It never changes. My audio library is thousands of songs, including audiobooks, and the scheduled task never runs for more than 10 seconds before bombing out. 

https://pastebin.com/a53KDFnG

### Reproduction Steps

Run Audio Normalization task. 

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS: Windows 11 Pro 64 23H2
- Linux Kernel: None
- Virtualization: None
- Clients: Browser and latest JMP 1.11.1
- Browser: Chrome, Edge, Firefox, Opera GX
- FFmpeg Version: Whatever the default is with 10.9.6
- Playback Method:
- Hardware Acceleration: NVIDIA NVENC
- GPU Model: RTX 3060 12GB
- Plugins: Artwork, AudioDB, Bookshelf, Covert Art Archive, Discogs, Fanart, IMVDb, Intro Skipper, MusicBrainz, OMDb, OPDS Feed, Open Subtitles, Session Cleaner, Studio Images, TMDb, TMDb Box Sets, TMDb Trailers, TVmaze, TheTVDB, VGMdb, Webhook
- Reverse Proxy: None
- Base URL: http://192.168.86.3
- Networking: local only. basic /24 subnet
- Storage: Noted in main description above.
```

### Jellyfin logs

```shell
On pastebin: https://pastebin.com/a53KDFnG
```

### FFmpeg logs

```shell
Please let me know where to find these if they're needed.
```

### Please attach any browser or client logs here

Let me know if these are needed and where to grab them from. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheParaTiger** [comment]
I can confirm that this happens on my Jellyfin instance as well.

Audio normalization will run fine at the first time but whenever you try to fire the task again (doesn't matter if manually or automatically) it will only fail repeatingly. My logs show the same as above with the files being locked.

OS: Windows 10 64-Bit 22H2
CPU: i7-4770K
GPU: GTX 960 4GB
RAM: 32GB DDR3
OS Drive: Samsung 840 Pro 256GB
HDD: Seagate Baraccuda 2TB (with the media stored on it)
Jellyfin Version was 10.9.6 at that time (I'm currently setting a new clean instance up, would update on this later)

**Comment by TheParaTiger** [comment]
Same as the Logs from OP

`System.IO.IOException: The process cannot access the file 'C:\Users\elias\Documents\Jellyfin Server\cache\transcodes\cc980e00-24a8-3c2f-70da-a9344583f583.concat' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at Emby.Server.Implementations.ScheduledTasks.Tasks.AudioNormalizationTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-07-15 18:13:44.582 +02:00] [INF] [18] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Audio Normalisierung" Failed after 0 minute(s) and 1 seconds
`

**Comment by halnine** [comment]
Same issue on server 10.9.8, Windows 11.

**Comment by 4g0tt3nSou1** [comment]
Not to flood the issue, but can confirm issue as well on 10.9.8, and now 10.9.11. Can provide/edit this to include logs as needed

**Comment by Cloweeee** [comment]
I can confirm that this issue is still present as of version 10.10.1
Are there any updates on this issue?

**Comment by DeeJaayMac** [comment]
Issue present for me as well. Running 10.9.11 on windows 11
nvid4090
96gb ddr5
i9-12900KF 3.20

**Comment by realtofuine** [comment]
Issue still on 10.10.3 Windows 11

**Comment by MuhClaren** [comment]
I have the same problem. Task runs and never gets beyond 0.0% after 12 hours, then fails.

System install, not containerized.
Linux Mint 22 Cinnamon
32 GB ECC Ram
Dual Intel X5680 @ 3.33 Ghz
TrueNAS on 10GbE Network

**Comment by iChristGit** [comment]
Are there any ETA for this issue? or workaround fix?

**Comment by 4g0tt3nSou1** [comment]
> Are there any ETA for this issue? or workaround fix?
> 
> I disabled the feature for the music library for now ![Image](https://github.com/user-attachments/assets/56f32b94-9ad4-45aa-b5e2-ff3985aa8af3)

This affects more than music. 

It is currently marked "in progress" by devs, so at this point anything other than reports for newer versions after the fix is applied is kinda spam. It is on their radar and there is a proposed fix if you read the history.

**Comment by eomanis** [comment]
```
jellyfin[1333051]: [21:32:43] [INF] Audio Normalization Cancelled after 1298 minute(s) and 59 seconds
```
It showed 0% progress on the dashboard when I noticed it, then I hit the "Cancel" button.
Looks like that feature needs to bake some more, yes.

**Comment by 4g0tt3nSou1** [comment]
> ```
> jellyfin[1333051]: [21:32:43] [INF] Audio Normalization Cancelled after 1298 minute(s) and 59 seconds
> ```
> 
> It showed 0% progress on the dashboard when I noticed it, then I hit the "Cancel" button. Looks like that feature needs to bake some more, yes.

Might not be the same issue. would suggest you check to see if you have the same logs as the OP, The issue of this thread usually immediately fails, not hangs like that.

would suggesy you review all the logs and post seperately in its own issue, if no others exist for the same problem

**Comment by Bond-009** [comment]
Should be fixed by #13593

**Comment by SightSpirit** [comment]
I'm still having this issue on 10.10.7. Same error message in logs as OP.

**Comment by HerrDoktor9001** [comment]
I'm on Jellyfin v10.10.6 and the exact same issue as OP happens. The normalisation task always immediately fails, with the message below registered in the logs

> [2025-05-10 01:25:04.285 -03:00] [ERR] [72] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.IO.IOException: The process cannot access the file 'C:\Users\PC\AppData\Local\Temp\jellyfin\c1054400-fb79-c080-dea0-942cb51db5f7.concat' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at Emby.Server.Implementations.ScheduledTasks.Tasks.AudioNormalizationTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2025-05-10 01:25:04.288 -03:00] [INF] [72] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Audio Normalization" Failed after 0 minute(s) and 4 seconds

**Comment by james-li** [comment]
still having this issue on 10.10.7 on macos m4.

**Comment by iChristGit** [comment]
Still an issue on Windows with  10.10.6
Bugs the heal out of me that the task is marked as Failed.. I just want to get rid of it.
