### ISSUE TITLE
[Issue]: Remote Control / Display Mirror not working

### ISSUE THREAD

**Issue by aaruni96** [jellyfin/jellyfin#12160]
### Please describe your bug

Ever since the update to 10.9 (currently 10.9.6) the remote control feature no longer works. Feels like its a repeat of #496 all over again. It used to work in 10.8.

My use case is, I like to play media on jellyfin-media-player on desktop, and control it via my mobile phone from the couch / bed.

Here's how the UI looks like on the mobile, while something is playing on the desktop. The pause/play button works, as does the volume slider and the mute button. Seek functionality does not work.

### Reproduction Steps

1. Play something on jellyfin
2. Try remote control from android app
3. Be sad that it doesn't work :(

### Jellyfin Version

10.9.0

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1.0
- Virtualization: none
- Clients: jellyfin-media-player 1.11.1 / jellyfin android 2.6.1
- Browser: nil
- FFmpeg Version: Server: 6.0.1 / Client: 7.0.1
- Playback Method: Direct play
- Hardware Acceleration: Server: none / Client: VAAPI
- GPU Model: RX7600
- Plugins: ??
- Reverse Proxy: nginx
- Base URL: none
- Storage: Local
```

### Jellyfin logs

Found this to be quite interesting: 192.168.0.103 is my mobile phone from which I try to remote control

```shell
[2024-06-23 15:48:19.505 +02:00] [INF] WS "192.168.0.103" request
[2024-06-23 15:48:28.276 +02:00] [WRN] Failed to process WebSocket message
MediaBrowser.Controller.Authentication.AuthenticationException: Only admin users can subscribe to session information.
   at Jellyfin.Api.WebSocketListeners.SessionInfoWebSocketListener.Start(WebSocketMessageInfo message)
   at MediaBrowser.Controller.Net.BasePeriodicWebSocketListener`2.ProcessMessageAsync(WebSocketMessageInfo message)
   at Emby.Server.Implementations.HttpServer.WebSocketManager.ProcessWebSocketMessageReceived(WebSocketMessageInfo result)
   at Emby.Server.Implementations.HttpServer.WebSocketConnection.ProcessInternal(PipeReader reader)
```

### Please attach any screenshots here

![image](https://github.com/jellyfin/jellyfin/assets/7453256/cf1d92c1-0cc6-4547-8228-ee98c87a0ceb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by XqeH57r** [comment]
I am having the same issue, with same error message. It's not an issue in the linux app, only the android app.

**Comment by not-root** [comment]
Still present in 10.10.3. Observed with all combinations of:
* Web on Linux Firefox
* Web on Windows Firefox
* Official desktop client on Windows
* MPV Shim
Notably, only the controlling device needs to be signed into an admin account. The device being controlled can be signed into *any* other account.

**Comment by gnattu** [comment]
“Allow this user to control other devices” is a separate permission that can be granted to a user in its user setting page, does that option work? The last time I checked a user with that permission can control other devices.

**Comment by aaruni96** [comment]
I do not find this option. I only find two options in the remote control section, see screenshot. The option "allow remote control of other users" seems dangerous

![Image](https://github.com/user-attachments/assets/f158f32b-385c-4f4d-aad1-be2144da80bf)

**Comment by Xameon42** [comment]
I guess that the problem is in the following [commit](https://github.com/jellyfin/jellyfin/commit/05d98fe24c594ae43de4cd9f54139f8b04324119), specifically in [line 73](https://github.com/jellyfin/jellyfin/commit/05d98fe24c594ae43de4cd9f54139f8b04324119#diff-cbe328c1e8576c96d0bd344bf0aee814cebc766b85c9869f86f891725ef1ed17R73) in [Jellyfin.Api/WebSocketListeners/SessionInfoWebSocketListener.cs](https://github.com/jellyfin/jellyfin/blob/05d98fe24c594ae43de4cd9f54139f8b04324119/Jellyfin.Api/WebSocketListeners/SessionInfoWebSocketListener.cs)
It would also fit in terms of time, as the commit has been present since v10.9.0.

For testing I removed the if statement and was able to successfully control the session again, without an admin account.
Also seeking seems working again.

Unfortunately I'm not familiar enough with the codebase to have a good solution to customize the check so that users can only control their own session and only admins can control all sessions.

**Comment by aaruni96** [comment]
This issue still affects me :(

**Comment by aaruni96** [comment]
On 10.10.6, this still doesn't work. I will need some time to run updates and try on 10.10.7, but the changelog doesn't mention it.

**Comment by felix920506** [comment]
Have you tried not going through your Nginx reverse proxy and directly connecting to Jellyfin?

**Comment by aaruni96** [comment]
Does not work even if I connect directly to jellyfin by bypassing nxinx

**Comment by Xameon42** [comment]
Maybe same issue than #13709 ?

**Comment by aaruni96** [comment]
Looks like the same symptoms, yes

**Comment by KGT1** [comment]
Please test again on latest rc.
should be fixed by #13767

**Comment by aaruni96** [comment]
I can't easily test on release candidates, so I haven't tried. But the new release just hit, and on version 10.11.0, this problem still persists for me.

------------------------

Edit: The problem seems to have slightly improved, but not quite fixed. I can now see some metadata on the mobile app, and controls are slightly better, but it doesn't "live update", i.e., when the playback has moved to 05:05, the mobile app still shows it "stuck" on 01:35.

I can provide more details later.

--------------------------

Edit edit
smal update:

The mobile screen seems to update every time admin refreshes the dashboard screen.

**Comment by KGT1** [comment]
Sorry but that seems like a new bug and not what you reported in this issue at all. please open a new bug with steps to reproduce. also make sure its a server issue and not an android issue.

**Comment by aaruni96** [comment]
> sure its a server issue and not an android issue

While I am starting to suspect this is an android client issue, how would I make sure ?

**Comment by KGT1** [comment]
generally you could try it out with different clients. its always a little hard to figure out in the jellyfin ecosystem, but if you give exact steps to reproduce, best with fresh and up to date instances of the server and clients, it would be way easier to figure out.

**Comment by aaruni96** [comment]
I didn't change anything (or at least I think I didn't change anything), but after a few restarts of both the server and the clients for other unrelated reasons, it appears to work now.
