### ISSUE TITLE
Collections's images doesn't show and identify function get not result

### ISSUE THREAD

**Issue by ReynierMatth** [jellyfin/jellyfin#12796]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Jellyfin 10.9.11
Docker environment, no vpn

When a collection is generated when movies are imported, I see that the title is rightly setted 
![image](https://github.com/user-attachments/assets/27117ef4-2f60-494b-bdc1-331d54add699)

But I don't see any images for the collections : 

![image](https://github.com/user-attachments/assets/0512f38a-2805-4ec6-b9be-b228e962a6fe)

And when I try to identify a collection manually i got no result : 

![image](https://github.com/user-attachments/assets/d314e42b-a1d8-4973-b296-82cd5dd8501b)

But I can confirm that if I tried to identify movies or tv it works : 

![image](https://github.com/user-attachments/assets/6834f426-8c66-4c8d-8eba-acd69313fe75)

I asked a friend with his instance of jellyfin, he reproduce the bug

### Reproduction steps

Try to identify a collection manually

### What is the current _bug_ behavior?

no result

### What is the expected _correct_ behavior?

Should have results, when identify manually and automatically too

### Jellyfin Server version

10.9.11+

### Specify the build version

10.9.11

### Environment

```markdown
- OS: Synology (for me ) - Ubuntu (for my friend)
- Linux Kernel:-
- Virtualization:Docker
- Clients: All
- Browser: - 
- FFmpeg Version: - 
- Playback Method: - 
- Hardware Acceleration: - 
- GPU Model:-
- Plugins: - 
- Reverse Proxy: Traefik for me, nginx for my friend
- Base URL: - 
- Networking: - 
- Storage: -
```

### Jellyfin logs

```shell
Nothing about api call to providers
```

### Relevant screenshots or videos

![image](https://github.com/user-attachments/assets/27117ef4-2f60-494b-bdc1-331d54add699)

![image](https://github.com/user-attachments/assets/0512f38a-2805-4ec6-b9be-b228e962a6fe)

![image](https://github.com/user-attachments/assets/d314e42b-a1d8-4973-b296-82cd5dd8501b)

![image](https://github.com/user-attachments/assets/6834f426-8c66-4c8d-8eba-acd69313fe75)

**Comment by felix920506** [comment]
Do the images appear after you refresh the page?

**Comment by ReynierMatth** [comment]
> Do the images appear after you refresh the page?

It's on all platforms Android App, Windows, Android TV etc but in the navigator I can try refresh the page when i'm in collections but it doesn't change anything

**Comment by Clement83** [comment]
Same problem here, Jellyfin doesn't get images for the collection.

**Comment by theguymadmax** [comment]
To manually identify collections without the TMDb Box Sets plugin, you must first unlock the collection. However, be aware that you might encounter a bug mentioned in issue #12724.

**Comment by thor9898** [comment]
Same problem here, can't get series identify nor images

**Comment by bobr-kun** [comment]
Hello everyone!
I suppose I'll be the one reopening this issue with collections identifications and empty search results. Although I can confirm that creating a new collection with a proper movies/series name leads to correct "identification under the hood"(during creation) and poster image appears. But for already created collections(especially for the automatically created ones during the very first scan) - the identification doesn't work at all - the search results page is simply always empty.

**Comment by rabbitambulance** [comment]
Same problem as of 10.10.7

**Comment by acosmichippo** [comment]
same problem here. sometimes identification works with manually created collections (not always), but no automatically created collections are identifiable.

@felix920506 can you re-open this issue? Thanks!

**Comment by theguymadmax** [comment]
This issue is fixed in master by https://github.com/jellyfin/jellyfin/pull/14259  

The fix will be included in the 10.11.0 release.

**Comment by EvansPM** [comment]
Still happen on 10.11.5 release.

**Comment by Ian6930087** [comment]
Still having this issue, installing IMDb movie collection plugin didn't solve the issue.
