### ISSUE TITLE
Trickplay stored next to media not properly imported and refreshed

### ISSUE THREAD

**Issue by Bryan792** [jellyfin/jellyfin#12887]
### This issue respects the following points:

- [X] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [X] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [X] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [X] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [X] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I upgraded two instances of jellyfin, both pointing to the same media source. Both instances seemingly have the same trickplay settings (stored as a 10x10 grid images). I had one instance generate trickplay files. My second instance was able to use the files, although it may have "imported" them through the trickplay generation process and not the library scan (not sure if this is intended). No new trickplay files were generated and I did not see any new generation from the debug logs. The issue is that the second instance displays the previews as 1x10 grid of images, instead of the 1x1 image. It is properly displayed on the first instance.

Another issue is that the trickplay files are not regenerated even when using the replace trickplay images when refreshing the media. Is this intentional?

May be related to #12818

https://forum.jellyfin.org/t-stacked-trickplay also seems related

### Reproduction steps

1. Import library with trickplay files/folders already next to the media.
2. Refreshing trickplay using the explicit option

### What is the current _bug_ behavior?

Trickplay files shown as 1x10 image. Trickplay files are not regenerated when using the refresh. Basically no change.

### What is the expected _correct_ behavior?

Trickplay files shown as 1x1 image. Trickplay files are regenerated when using the refresh.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.0

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization: Docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Nothing too relevant.
```

**Comment by Shadowghost** [comment]
Trickplay files are not scanned in by default since they require the media to be present in the database, so we deferred it to the trickplay task. This part is intentional.
The files being wrongly read or not regenerated seems like issues to me. Though I don't understand why on a 10x10 config the files should be shown as 1x10 in any case. Are you sure you synced these settings and the resolutions properly between your instances?

**Comment by Bryan792** [comment]
yes, because they are the default settings (resolution and grid size)

if you look at the forum post, we can see that other people have the same issue, so i doubt it's because of my configuration

**Comment by coreykovacs1** [comment]
Hi. I can also confirm on my setup that this is what happened. It appears that it recognises that the trickplay file exists in the directory and adds it to the trickplayinfos table in jellyfin.db but it adds the incorrect data associated with the trickplay files. I have added a picture to provide context.

You can see the height values of some of the entries are in the scope of 10x what the others are (this is the 10x1 behaviour). It looks as if during the generate trickplay task that it isn't properly factoring in the tile x tile dimension that is now provided in the folder schema, i.e. 320 - 10x10.

Also, a byproduct of this is incorrectly calculating the number of thumbnails but presumably this could be calculated doing an integer division on the runtime of a given media file.

I believe that once this is corrected the trickplay files will be genuinely portable between servers. 

Love your work mate, this has been a fantastic addition. Many likely don't appreciate the work that goes into implementing these changes and I truly appreciate the work that you and the others have done to improve Jellyfin.
![72e4d123-1f33-41be-921b-ca9ca62ce72c](https://github.com/user-attachments/assets/57cf3b1c-816d-4298-8670-0865ee43f6bd)

**Comment by solidsnake1298** [comment]
Is this what you're seeing?

![Image](https://github.com/user-attachments/assets/af48eeb6-383a-4bf4-9af8-dfa35dc5d980)

**Comment by coreykovacs1** [comment]
Yes. That is the output of the faulty height recognition in the db file.

**Comment by nyanmisaka** [comment]
Fixed in 10.10.2.

**Comment by Professorvennie** [comment]
@nyanmisaka Hey I just updated to 10.10.2 and I am still getting this bug.

**Comment by Bryan792** [comment]
hmm, i think its working for me, maybe if it was imported before then it doesn't fix it without replacement?

**Comment by nyanmisaka** [comment]
> @nyanmisaka Hey I just updated to 10.10.2 and I am still getting this bug. 

You need to manually refresh the metadata for the changes to take effect.

**Comment by Professorvennie** [comment]
> > [@nyanmisaka](https://github.com/nyanmisaka) Hey I just updated to 10.10.2 and I am still getting this bug.
> 
> You need to manually refresh the metadata for the changes to take effect.

Is there anyway to bulk do this? or do I have to do it individually on every movie?

**Comment by gottsman** [comment]
> > [@nyanmisaka](https://github.com/nyanmisaka) Hey I just updated to 10.10.2 and I am still getting this bug.
> 
> You need to manually refresh the metadata for the changes to take effect.

I am not sure if the forced metadata refresh needs to occur in the existing library or not. I created a new 10.10.2 instance on a new server with the same shared media mount and nfo/trickplay files... The trickplay files were not recognized in the new install.

If this is a separate issue, I can create a new issue.

**Comment by nyanmisaka** [comment]
> > > [@nyanmisaka](https://github.com/nyanmisaka) Hey I just updated to 10.10.2 and I am still getting this bug.
> > 
> > You need to manually refresh the metadata for the changes to take effect.
> 
> Is there anyway to bulk do this? or do I have to do it individually on every movie? 

Refresh metadata -> Replace all metadata -> Replace existing trickplay images

**Comment by nyanmisaka** [comment]
> > > [@nyanmisaka](https://github.com/nyanmisaka) Hey I just updated to 10.10.2 and I am still getting this bug.
> > 
> > You need to manually refresh the metadata for the changes to take effect.
> 
> I am not sure if the forced metadata refresh needs to occur in the existing library or not. I created a new 10.10.2 instance on a new server with the same shared media mount and nfo/trickplay files... The trickplay files were not recognized in the new install.
> 
> If this is a separate issue, I can create a new issue.

If the trickplay tile width is set to 320 (default) and the existing trickplay files are not, it will not be imported. Otherwise check the server log to see what happened. Anyway your problem is not related to this.

**Comment by coreykovacs1** [comment]
@Shadowghost Hi Tim, again thank you for your work on this. Looking above it seems like many people are still having issues with this (likely as the db got updated with the incorrect heights initially). Would it be possible to create a triggerable event that would refresh the metadata of the trickplay files without regenerating them? Basically, emptying the current trickplayinfo table and then parsing the folders to refill it. Not sure what would be involved in this, but it would also cover some other issues around cleaning the DB that some people have mentioned.
