### ISSUE TITLE
semicolon custom tag delimiter does not work for MP3 Artist tag

### ISSUE THREAD

**Issue by RobMielcarski** [jellyfin/jellyfin#12957]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Multiple artists delimited with a semicolon in an MP3 are not parsed correctly despite library option "Use custom tag delimiter" turned on with delimiter set to ;

### Reproduction steps

Scan an MP3 with multiple artists delimited by a semicolon and you will see that the artist is identified as a single artist with the semicolon removed.  For example, "Eric Gales;James Cotton" is identified as artist "Eric GalesJamesCotton".

It seems the "Use custom delimiter" feature is mostly working because as a test if you change the "Use custom tag delimiter" to a space then the artists above are identified as expected as:
Eric
GalesJames
Cotton

So the problem may be specific to the semicolon delimiter.

### What is the current _bug_ behavior?

Semicolon delimiter for multiple artists in MP3 are ignored.  

### What is the expected _correct_ behavior?

Multiple artists delimited by a semicolon should be parsed correctly.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.1

### Environment

Windows 11
Browser client

### Jellyfin logs

No log required to explain this problem.

**Comment by RobMielcarski** [comment]
Thanks for trying.  

The files are tagged using JRiver Media Center which is a popular long-time tested media manager. 

The multiple artists display properly in other players like VLC and MusicBee so I do think there is a problem in Jellyfin. 

Here is an example MP3 with multiple artists that I hope you can test.

https://drive.google.com/file/d/1-1XFAVhqHpiLAETQZcrWIlihvBxY_pHx/view?usp=sharing

**Comment by gnattu** [comment]
It is tagging in id3v2.3 format with id3v2.4 null character delimiters and not actually using semicolons...

I can't believe the "popular long-time tested media manager" is doing things wrong like this, which outright violates the ID3v2 specs....

**Comment by RobMielcarski** [comment]
Thanks. 

Every other media player I have tried including VLC and MusicBee on Windows, and many Android apps I have tried on my phone, all properly parse the multiple artists.

Could you please add the null character delimiter as a character that can be added to the "Use custom delimiter" options?

**Comment by RobMielcarski** [comment]
Thank you for making this change.

Sorry I incorrectly assumed semicolon was the delimiter.

**Comment by felix920506** [comment]
closing as fixed by linked pr

**Comment by RobMielcarski** [comment]
I tested 10.10.2 which has the change to recognize null as an artist delimiter.

Artists are still not being delimited.

Here is an MP3 with multiple artists you can use to see the problem.

https://drive.google.com/file/d/1-3enk0YWlh4_OxI8t89fC7kMo49EbTGU/view?usp=sharing

**Comment by gnattu** [comment]
It is delimited if you enable the use custom delimiter option

**Comment by RobMielcarski** [comment]
Thank you. All good now.

**Comment by AAMBIENTT** [comment]
Still having this issue. All music is tagged correctly, however Artist and Genres are seperated with '; " and still do not seperate them. The only way i can get them to update to get recognized is by clicking Edit Metadata and then save. Maybe someone knows whats going on?

![Image](https://github.com/user-attachments/assets/a03b6906-9ed6-4a71-afe4-d318dfbd0513)

**Comment by mindset-tk** [comment]
Hello, looks like this was broken by the changes made in https://github.com/jellyfin/jellyfin/pull/14100. I'm working on verifying that the file I am inserting is properly tagged before opening a new issue.

**Comment by mindset-tk** [comment]
Update: I had to update my tags to ID3v2.4 and it now works.
