### ISSUE TITLE
LiveTV Guide Backdrop images not updating.

### ISSUE THREAD

**Issue by IDisposable** [jellyfin/jellyfin#13496]
If the guide data changes an any other image, then the _Backdrop_ image will not be updated.

The changed line that causes the issue is: 
```csharp
// Backdrop
return updated || UpdateImage(ImageType.Backdrop, item, info);
```

This occurs because the `||` operator is a short-circuit so  if `updated` was already `true` then the call to `UpdateImage` would never execute, thus the _Backdrop_ image would not be updated.

This was unintentionally introduced in PR #13227 [here](https://github.com/jellyfin/jellyfin/pull/13227/files#diff-68cbfbf495bc9462524e5e837822194c426c5008491dfccdbc8773ef784aea50R682) and subsequently backported to main branch.

Note that if we made another guide data update, and none of the other images changed in this pass, then the _Backdrop_ would eventually be updated.

**Comment by Shadowghost** [comment]
Already fixed in #13469

**Comment by IDisposable** [comment]
No, that fixes an entirely different issue. The erroneous line is still present in #13469 [here](https://github.com/jellyfin/jellyfin/pull/13469/files#diff-68cbfbf495bc9462524e5e837822194c426c5008491dfccdbc8773ef784aea50R663)
