### ISSUE TITLE
Unwatched episode count incorrect

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin#13576]
### Description of the bug

The number of unwatched episodes for shows are incorrect.
In some cases, there may be more unwatched episodes displayed than the actual number of episodes.

The seasons seem to be counted as unwatched episodes from the mismatch in numbers

A rescan of scan for new and updated files type seems to fix the problem

Example 1: 13 episodes in 1 season, 1 season total, all unwatched
Total unwatched: 14
![Image](https://github.com/user-attachments/assets/2a609d7c-d225-4a59-a6eb-1d10db739a04)

Season 1 unwatched: 13
![Image](https://github.com/user-attachments/assets/646116f8-11d6-4850-ac99-5ccffc502c23)

Example 2: 4 seasons total, all watched, showing 4 episodes unwatched
![Image](https://github.com/user-attachments/assets/cd7e1ea4-936f-49e6-bd39-efdebe95fb27)

![Image](https://github.com/user-attachments/assets/923c02dc-24aa-4588-8c0b-830a303548fc)

### Reproduction steps

1. Add shows and scan the shows in on a 10.10 server
2. Upgrade to unstable
3. Open shows library
4. see error

### What is the current _bug_ behavior?

The number of unwatched episodes of a given show is wrong

### What is the expected _correct_ behavior?

the number of unwatched episodes should be correct

### Jellyfin Server version

Unstable

### Specify unstable release number

2025021706

### Specify the build version

10.11.0

### Environment

```markdown
- OS: Ubuntu 24.04
- Linux Kernel: 6.8.0-51-generic
- Virtualization: Docker
- Clients: Web
- Browser: Firefox
- FFmpeg Version: bundled
- Playback Method: N/A
- Hardware Acceleration: QSV
- GPU Model: N100
- Plugins: DLNA
- Reverse Proxy: None
- Base URL: /jellyfin
- Networking: docker port forward
- Storage: SMB
```

### Jellyfin logs

```shell
Nothing is generated
```

### FFmpeg logs

```shell

```

**Comment by theguymadmax** [comment]
The issue occurs only with imported media. Refreshing the metadata updates the item count accurately.

**Comment by felix920506** [comment]
@JPVenson is this one fixed by the linked PR completely?

**Comment by JPVenson** [comment]
@felix920506 not completly. As far as i can tell there is still an issue with specials within seasons that are not counting towards the unwatched indicator. Its a 99.999 percent situation. I would close this and recheck if specials are really supposed to be counted as well
