### ISSUE TITLE
[10.11.0] MoveExtractedFiles migration failing on first run after version upgrade

### ISSUE THREAD

**Issue by chrisforte** [jellyfin/jellyfin#15024]
### Description of the bug

Following the upgrade instructions from the blog post about the v10.11.0 release (yes I made 2 backups), I'm seeing an error during the `20250420210000_MoveExtractedFiles` migration. Seems to be a issue getting the file last write/access time for subtitle files. 

Error message is:
```
System.ArgumentOutOfRangeException: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
```

### Reproduction steps

1. Stop v10.10.7 of Jellyfin server (docker)
2. Pull latest image (v10.11.0)
3. Bring Jellyfin container back up
4. Observe migration `20250420210000_MoveExtractedFiles` fail while trying to process subtitle files

### What is the current _bug_ behavior?

Migrations fail during initial startup, server will not start.

### What is the expected _correct_ behavior?

Migration should process the subtitle files correctly and continue to the next migration step.

### Jellyfin Server version

10.10.0+

### Specify version number

10.11.0

### Specify the build version

n/a

### Environment

```markdown
- OS: Ubuntu Server 25.04
- Linux Kernel: 6.14.0-33-generic
- Virtualization: Docker
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: (built in to 10.11.0 image)
- Playback Method: n/a
- Hardware Acceleration: n/a
- GPU Model: Intel Integrated GPU
- Plugins:
- Reverse Proxy: traefik
- Base URL: none
- Networking: docker bridge
- Jellyfin Data Storage: local SSD
- Media Storage: NAS, cifs mount
- External Integrations: n/a
```

### Jellyfin logs

```shell
[23:28:20] [INF] [9] InternalCodeMigration: Perform migration 20250420210000_MoveExtractedFiles
[23:28:20] [INF] [9] Jellyfin.Server.Migrations.Routines.MoveExtractedFiles: Checking 20458 items for movable extracted files.
[23:28:20] [INF] [9] Jellyfin.Server.Migrations.Routines.MoveExtractedFiles: Checked: 0 - Moved: 0 - Time: 00:00:00.3890359
[23:28:26] [FTL] [9] InternalCodeMigration: Error: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
[23:28:26] [ERR] [9] InternalCodeMigration: Migration 20250420210000_MoveExtractedFiles failed
System.ArgumentOutOfRangeException: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
   at System.DateTimeOffset.FromUnixTimeSeconds(Int64 seconds)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.GetOldSubtitleCachePath(String path, Int32 streamIndex, String outputSubtitleExtension)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.MoveSubtitleAndAttachmentFiles(Guid id, String path, ICollection`1 mediaStreams, JellyfinDbContext context)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Stages.CodeMigration.Perform(IServiceProvider serviceProvider, IStartupLogger logger, CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.InternalCodeMigration.PerformAsync(IStartupLogger logger)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
[23:28:26] [INF] [9] InternalCodeMigration: Attempt to rollback librarydb.
```

### FFmpeg logs

```shell

```

**Comment by chrisforte** [comment]
Looking at the code my guess is it’s throwing at 

Jellyfin.Server/Migrations/Routines/MoveExtractedFiles.cs#219

Might be the same issue as #14719

**Comment by sirlancelot** [comment]
This is happening to me too. I wonder if it has something to do with some of my files having timestamps before the unix epoch.

<img width="430" height="186" alt="Image" src="https://github.com/user-attachments/assets/8ed3fd6c-b62a-4e90-b365-dfee0b2f096e" />

**Comment by Shadowghost** [comment]
Quite sure this is the issue. Not sure what to do about it though.

**Comment by chrisforte** [comment]
> Quite sure this is the issue. Not sure what to do about it though.

I tried running a recursive `touch` through my media libraries to update the file times, but that didn't help unfortunately.

**Comment by taiheng** [comment]
Also getting this error message. Log included if that helps.

```
[2025-10-20 17:46:50.424 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: "Saving 34342 People entries and 148544 maps" took '00:00:29.2076995'
[2025-10-20 17:46:50.424 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: "Moving People" took '00:00:30.5124911'
[2025-10-20 17:46:50.424 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: Start "Moving Chapters"
[2025-10-20 17:46:50.424 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: Start "Loading Chapters"
[2025-10-20 17:46:50.486 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: "Loading Chapters" took '00:00:00.0618994'
[2025-10-20 17:46:50.487 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: Start "Saving 0 Chapters entries"
[2025-10-20 17:46:50.487 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: "Saving 0 Chapters entries" took '00:00:00.0000895'
[2025-10-20 17:46:50.487 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: "Moving Chapters" took '00:00:00.0623404'
[2025-10-20 17:46:50.487 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: Start "Moving AncestorIds"
[2025-10-20 17:46:50.487 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: Start "Loading AncestorIds"
[2025-10-20 17:46:50.580 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: "Loading AncestorIds" took '00:00:00.0934358'
[2025-10-20 17:46:50.581 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: Start "Saving 0 AncestorId entries"
[2025-10-20 17:46:50.581 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: "Saving 0 AncestorId entries" took '00:00:00.0000376'
[2025-10-20 17:46:50.581 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: "Moving AncestorIds" took '00:00:00.0939142'
[2025-10-20 17:46:50.581 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: Migration of the Library.db done.
[2025-10-20 17:46:50.581 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: Migrating Library db took 00:01:38.9376694.
[2025-10-20 17:46:50.618 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: Move "/config/data/data/library.db" to "/config/data/data/library.db.old".
[2025-10-20 17:46:50.920 -04:00] [INF] [7] InternalCodeMigration: Migration "20250420200000_MigrateLibraryDb" was successfully applied
[2025-10-20 17:46:50.920 -04:00] [INF] [7] InternalCodeMigration: Perform migration "20250420210000_MoveExtractedFiles"
[2025-10-20 17:46:51.083 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MoveExtractedFiles: Checking 11432 items for movable extracted files.
[2025-10-20 17:46:51.087 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MoveExtractedFiles: Checked: 0 - Moved: 0 - Time: 00:00:00.1649962
[2025-10-20 17:46:51.255 -04:00] [WRN] [9] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:46:52.269 -04:00] [WRN] [9] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:46:53.282 -04:00] [WRN] [14] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0002ms with message '"Server is still starting up."'
[2025-10-20 17:46:54.295 -04:00] [WRN] [9] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:46:55.309 -04:00] [WRN] [9] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0002ms with message '"Server is still starting up."'
[2025-10-20 17:46:56.321 -04:00] [WRN] [9] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:46:57.335 -04:00] [WRN] [15] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0002ms with message '"Server is still starting up."'
[2025-10-20 17:46:58.348 -04:00] [WRN] [15] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:46:59.361 -04:00] [WRN] [15] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:00.374 -04:00] [WRN] [15] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:01.387 -04:00] [WRN] [15] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:02.401 -04:00] [WRN] [14] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:03.414 -04:00] [WRN] [14] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:04.427 -04:00] [WRN] [15] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:05.440 -04:00] [WRN] [15] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0002ms with message '"Server is still starting up."'
[2025-10-20 17:47:06.453 -04:00] [WRN] [12] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:07.012 -04:00] [INF] [7] Jellyfin.Server.Migrations.Routines.MoveExtractedFiles: Checked: 5000 - Moved: 139 - Time: 00:00:16.0903846
[2025-10-20 17:47:07.467 -04:00] [WRN] [18] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:08.479 -04:00] [WRN] [12] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:09.493 -04:00] [WRN] [12] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:10.506 -04:00] [WRN] [18] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:11.519 -04:00] [WRN] [14] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:12.533 -04:00] [WRN] [12] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:13.545 -04:00] [WRN] [18] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:14.558 -04:00] [WRN] [18] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:15.571 -04:00] [WRN] [12] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0001ms with message '"Server is still starting up."'
[2025-10-20 17:47:16.585 -04:00] [WRN] [18] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0002ms with message '"Server is still starting up."'
[2025-10-20 17:47:17.598 -04:00] [WRN] [12] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0002ms with message '"Server is still starting up."'
[2025-10-20 17:47:17.705 -04:00] [FTL] [7] InternalCodeMigration: Error: "Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')"
[2025-10-20 17:47:17.705 -04:00] [ERR] [7] InternalCodeMigration: Migration "20250420210000_MoveExtractedFiles" failed
System.ArgumentOutOfRangeException: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
   at System.DateTimeOffset.FromUnixTimeSeconds(Int64 seconds)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.GetOldSubtitleCachePath(String path, Int32 streamIndex, String outputSubtitleExtension)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.MoveSubtitleAndAttachmentFiles(Guid id, String path, ICollection`1 mediaStreams, JellyfinDbContext context)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Stages.CodeMigration.Perform(IServiceProvider serviceProvider, IStartupLogger logger, CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.InternalCodeMigration.PerformAsync(IStartupLogger logger)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
[2025-10-20 17:47:17.709 -04:00] [INF] [7] InternalCodeMigration: Attempt to rollback librarydb.
[2025-10-20 17:47:17.709 -04:00] [INF] [7] InternalCodeMigration: Attempt to rollback JellyfinDb.
[2025-10-20 17:47:17.818 -04:00] [FTL] [7] Main: Error while starting server
System.ArgumentOutOfRangeException: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
   at System.DateTimeOffset.FromUnixTimeSeconds(Int64 seconds)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.GetOldSubtitleCachePath(String path, Int32 streamIndex, String outputSubtitleExtension)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.MoveSubtitleAndAttachmentFiles(Guid id, String path, ICollection`1 mediaStreams, JellyfinDbContext context)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Stages.CodeMigration.Perform(IServiceProvider serviceProvider, IStartupLogger logger, CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.InternalCodeMigration.PerformAsync(IStartupLogger logger)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2025-10-20 17:47:18.611 -04:00] [ERR] [7] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Unhealthy completed after 0.0156ms with message '"Server is could not complete startup. Check logs."'
```

**Comment by Undeadllama** [comment]
Another 'me too' here. 
Running in docker.

```
[2025-10-21 09:38:03.412 +01:00] [INF] [9] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: Migration of the Library.db done.
[2025-10-21 09:38:03.412 +01:00] [INF] [9] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: Migrating Library db took 00:07:23.0302240.
[2025-10-21 09:38:03.537 +01:00] [INF] [9] Jellyfin.Server.Migrations.Routines.MigrateLibraryDb: Move "/config/data/library.db" to "/config/data/library.db.old".
[2025-10-21 09:38:03.544 +01:00] [INF] [9] InternalCodeMigration: Migration "20250420200000_MigrateLibraryDb" was successfully applied
[2025-10-21 09:38:03.545 +01:00] [INF] [9] InternalCodeMigration: Perform migration "20250420210000_MoveExtractedFiles"
[2025-10-21 09:38:03.720 +01:00] [INF] [9] Jellyfin.Server.Migrations.Routines.MoveExtractedFiles: Checking 40569 items for movable extracted files.
[2025-10-21 09:38:03.727 +01:00] [INF] [9] Jellyfin.Server.Migrations.Routines.MoveExtractedFiles: Checked: 0 - Moved: 0 - Time: 00:00:00.1764311
[2025-10-21 09:38:06.546 +01:00] [WRN] [13] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Degraded completed after 0.0071ms with message '"Server is still starting up."'
[2025-10-21 09:38:09.560 +01:00] [FTL] [9] InternalCodeMigration: Error: "Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')"
[2025-10-21 09:38:09.560 +01:00] [ERR] [9] InternalCodeMigration: Migration "20250420210000_MoveExtractedFiles" failed
System.ArgumentOutOfRangeException: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
   at System.DateTimeOffset.FromUnixTimeSeconds(Int64 seconds)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.GetOldSubtitleCachePath(String path, Int32 streamIndex, String outputSubtitleExtension)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.MoveSubtitleAndAttachmentFiles(Guid id, String path, ICollection`1 mediaStreams, JellyfinDbContext context)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Stages.CodeMigration.Perform(IServiceProvider serviceProvider, IStartupLogger logger, CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.InternalCodeMigration.PerformAsync(IStartupLogger logger)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
[2025-10-21 09:38:09.562 +01:00] [INF] [9] InternalCodeMigration: Attempt to rollback librarydb.
[2025-10-21 09:38:09.562 +01:00] [INF] [9] InternalCodeMigration: Attempt to rollback JellyfinDb.
[2025-10-21 09:38:09.910 +01:00] [FTL] [9] Main: Error while starting server
System.ArgumentOutOfRangeException: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
   at System.DateTimeOffset.FromUnixTimeSeconds(Int64 seconds)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.GetOldSubtitleCachePath(String path, Int32 streamIndex, String outputSubtitleExtension)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.MoveSubtitleAndAttachmentFiles(Guid id, String path, ICollection`1 mediaStreams, JellyfinDbContext context)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Stages.CodeMigration.Perform(IServiceProvider serviceProvider, IStartupLogger logger, CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.InternalCodeMigration.PerformAsync(IStartupLogger logger)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
[2025-10-21 09:38:36.647 +01:00] [ERR] [14] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Unhealthy completed after 0.0314ms with message '"Server is could not complete startup. Check logs."'
[2025-10-21 09:39:06.755 +01:00] [ERR] [23] Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService: Health check "StartupCheck" with status Unhealthy completed after 0.006ms with message '"Server is could not complete startup. Check logs."'
```

**Comment by ozmiimzo** [comment]
The log file in /var/log/jellyfin shows the following error.

`[ERR] Error determining LastAccessTimeUtc for "/path/to/mediafolder/file.mkv"
System.ArgumentOutOfRangeException: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
   at System.DateTimeOffset.FromUnixTimeSeconds(Int64 seconds)`

So i checked the last acces/modified/etc times of the file and it showed a five-digit year. I don't know why, though. With touch i set it to the current year.

I stopped the jellyfin service and to be sure i ran "find /path/to/mediafolder/ -type f -exec touch {} +".
Then i started the server again, but the following error occured

`[FTL] Error: "SQLite Error 1: 'no such table: ActivityLog'."
[ERR] Migration "20250420070000_MigrateActivityLogDb" failed
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: ActivityLog'.`

The Database was broken after the error occuredand i had to restore a backup.
I dont know if a library.db backup is enough, i restored the whole /var/lib/jellyfin folder and even the /etc/jellyfin folder.
Then i started the server and the migration was successful.

**Comment by theguymadmax** [comment]
Fixed by #15112

**Comment by JJBlue** [comment]
I had the same error.
After manually compiling from the source and replacing the files,
I recieved the same error in a different file: "Jellyfin.Server/Migrations/Routines/MigrateKeyframeData.cs"
```
System.ArgumentOutOfRangeException: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
   at System.DateTimeOffset.FromUnixTimeSeconds(Int64 seconds)
   at System.IO.FileSystem.GetLastWriteTime(String fullPath)
   at System.IO.File.GetLastWriteTimeUtc(String path)
   at Jellyfin.Server.Migrations.Routines.MigrateKeyframeData.GetCachePath(String keyframeCachePath, String filePath)
   at Jellyfin.Server.Migrations.Routines.MigrateKeyframeData.TryGetKeyframeData(Guid id, String path, KeyframeData& data)
   at Jellyfin.Server.Migrations.Routines.MigrateKeyframeData.Perform()
   at Jellyfin.Server.Migrations.Stages.CodeMigration.Perform(IServiceProvider serviceProvider, IStartupLogger logger, CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.InternalCodeMigration.PerformAsync(IStartupLogger logger)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
[2025-10-26 11:10:44.535 +01:00] [INF] Attempt to rollback librarydb.
[2025-10-26 11:10:44.535 +01:00] [INF] Attempt to rollback JellyfinDb.
[2025-10-26 11:10:44.566 +01:00] [FTL] Error while starting server
System.ArgumentOutOfRangeException: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
   at System.DateTimeOffset.FromUnixTimeSeconds(Int64 seconds)
   at System.IO.FileSystem.GetLastWriteTime(String fullPath)
   at System.IO.File.GetLastWriteTimeUtc(String path)
   at Jellyfin.Server.Migrations.Routines.MigrateKeyframeData.GetCachePath(String keyframeCachePath, String filePath)
   at Jellyfin.Server.Migrations.Routines.MigrateKeyframeData.TryGetKeyframeData(Guid id, String path, KeyframeData& data)
   at Jellyfin.Server.Migrations.Routines.MigrateKeyframeData.Perform()
   at Jellyfin.Server.Migrations.Stages.CodeMigration.Perform(IServiceProvider serviceProvider, IStartupLogger logger, CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.InternalCodeMigration.PerformAsync(IStartupLogger logger)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
```

After I patched this file as well, I was finally able to boot up my system again.

```
cd /etc/jellyfin
cp migrations.xml.backup migrations.xml
systemctl restart jellyfin
```

**Comment by HayateLaTech** [comment]
I'm still having problems with that migration because it tries to move files that are not available on my device. (even after upgrading to version 10.11.1)

In my case it tries to move a font that was available on another device and still embedded in a file, but it is not available on my device, meaning it errors out:

```[2025-10-27 20:38:26.119 +01:00] [INF] [11] InternalCodeMigration: Migration "20250420200000_MigrateLibraryDb" was successfully applied
[2025-10-27 20:38:26.119 +01:00] [INF] [11] InternalCodeMigration: Perform migration "20250420210000_MoveExtractedFiles"
[2025-10-27 20:38:26.169 +01:00] [INF] [11] Jellyfin.Server.Migrations.Routines.MoveExtractedFiles: Checking 11480 items for movable extracted files.
[2025-10-27 20:38:26.176 +01:00] [INF] [11] Jellyfin.Server.Migrations.Routines.MoveExtractedFiles: Checked: 0 - Moved: 0 - Time: 00:00:00.0539818
[2025-10-27 20:38:30.159 +01:00] [INF] [11] Jellyfin.Server.Migrations.Routines.MoveExtractedFiles: Checked: 5000 - Moved: 0 - Time: 00:00:04.0370031
[2025-10-27 20:38:30.931 +01:00] [FTL] [11] InternalCodeMigration: Error: "Could not find a part of the path 'path_to_font_file.dk'."
[2025-10-27 20:38:30.932 +01:00] [ERR] [11] InternalCodeMigration: Migration "20250420210000_MoveExtractedFiles" failed
System.IO.DirectoryNotFoundException: Could not find a part of the path 'path_to_font_file.dk'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.MoveSubtitleAndAttachmentFiles(Guid id, String path, ICollection`1 mediaStreams, JellyfinDbContext context)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Stages.CodeMigration.Perform(IServiceProvider serviceProvider, IStartupLogger logger, CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.InternalCodeMigration.PerformAsync(IStartupLogger logger)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
[2025-10-27 20:38:30.948 +01:00] [INF] [11] InternalCodeMigration: Attempt to rollback librarydb.
[2025-10-27 20:38:30.950 +01:00] [INF] [11] InternalCodeMigration: Attempt to rollback JellyfinDb.
[2025-10-27 20:38:30.977 +01:00] [FTL] [11] Main: Error while starting server
System.IO.DirectoryNotFoundException: Could not find a part of the path 'path_to_font_file.dk'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.MoveSubtitleAndAttachmentFiles(Guid id, String path, ICollection`1 mediaStreams, JellyfinDbContext context)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Routines.MoveExtractedFiles.PerformAsync(CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.Stages.CodeMigration.Perform(IServiceProvider serviceProvider, IStartupLogger logger, CancellationToken cancellationToken)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.InternalCodeMigration.PerformAsync(IStartupLogger logger)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
   at Jellyfin.Server.Migrations.JellyfinMigrationService.MigrateStepAsync(JellyfinMigrationStageTypes stage, IServiceProvider serviceProvider)
   at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)```

**Comment by AngelaDMerkel** [comment]
I consistently receive similar errors:

```
10/29/2025 2:59:35 AM +00:00 - Health check "StartupCheck" with status Unhealthy completed after 0.0328ms with message '"Server is could not complete startup. Check logs."'
10/29/2025 2:59:34 AM +00:00 - Error while starting server
```
