### ISSUE TITLE
[Bug] Music Playlist section is empty

### ISSUE THREAD

**Issue by npodbielski** [jellyfin/jellyfin#15028]
### Description of the bug

Today I could not see my music Playlists. It was working fine yesterday. Section appears to be empty. I opened it on multiple clients:
- Linux Flathub v1.12 - Empty Playlists
- Web Client v10.11 - Empty Playlists
- Android Client v2.6.3 - Can't login (but I was experimenting yesterday with headscale over the same domain so maybe it can't find correct IP though I doubt that since Web Client and Finamp works on the same device)

Server v10.11 on Docker on host network.

I double checked my Nginx proxy and restarted the server (just in case) - no luck. 
I checked my scripts for maintenance (update, backup etc.) - Jellyfin was not updated.
I checked browser developer tools for failed requests - everything was 200 OK or 204 or WS.
I checked docker logs - no problems there.

I tried to create new Playlists to check if any of them will be visible there - no luck.

This is how this looked yesterday:

<img width="554" height="301" alt="Image" src="https://github.com/user-attachments/assets/191a72ea-91a8-4ffc-ac4d-a1b094d26879" />

### Reproduction steps

1. Open Client
2. Navigate to music
3. Navigate to Playlists
4. Applications loads for like 1s
5. Shows empty screen

### What is the current _bug_ behavior?

Shows empty screen

### What is the expected _correct_ behavior?

Shows list of playlists

### Jellyfin Server version

10.10.0+

### Specify the build version

sha256:811e2573e6c377279615c491914e063fc333c21dea398e21011b6b2779d9d809

### Environment

```markdown
- OS: Docker sha256:811e2573e6c377279615c491914e063fc333c21dea398e21011b6b2779d9d809
- Linux Kernel: 6.16.9
- Virtualization: 
- Clients: Web Client
- Browser: Firefox 
- FFmpeg Version: 
- Playback Method: 
- Hardware Acceleration: 
- GPU Model: None
- Plugins: DLNA
- Reverse Proxy: Nginx
- Base URL: 
- Networking: Host
```

### Jellyfin logs

```shell
jellyfin  | [08:42:36] [INF] [18] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 172.18.0.20 request                                                                                                  
jellyfin  | [08:42:44] [INF] [30] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 172.18.0.20 request                                                                                                  
jellyfin  | [08:43:00] [INF] [28] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 172.18.0.20 closed                                                                                                   
jellyfin  | [08:43:01] [INF] [28] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 172.18.0.20 request
```

### FFmpeg logs

```shell

```

**Comment by npodbielski** [comment]
Funny thing I was able to fix it by adding new Playlist to the system. Opened random album clicked [...] button, add to playlist, I entered some name and then all the playlists became visible again.

**Comment by h4p** [comment]
Happened to me too recently! 
There is a startup task called "Clean up collections and playlists" which cleans all items it cannot find after booting up the service. 

Did you forget to connect your hard drive at one point? Or is the mount point different?

I hope you backed up your playlist.xml files! The are located at `config/data/playlists/**/playlist.xml`

After restoring the XML files you have to call the "Scan All Libraries" job to see your items again.

Hope that helps

**Comment by h4p** [comment]
Although in my case the playlists still showed up in the section (but were empty however).
Yours seem to be missing entirely. Maybe you can check the path mentioned above to see if the XML files (and folders) are still there

**Comment by npodbielski** [comment]
No, everything was fine till morning, as far as I can tell. I do not have any external drives that I have to mount after power failure, that are used for anything important (I had setup like that and it was very unstable).

I have just some scripts that do maintenance of my server every day about 00:00 - 01:00, it stops all services, does snapshots and starts all services again. Beside that nothing out of the ordinary happened. 

And I was able to get all of my playlists back when I did create new one, so maybe it was just some weird cache issue.

**Comment by npodbielski** [comment]
I checked and `config/data/playlists/` seems to have correct set of files.

**Comment by csaavedra** [comment]
> Funny thing I was able to fix it by adding new Playlist to the system. Opened random album clicked [...] button, add to playlist, I entered some name and then all the playlists became visible again.

I can confirm that I could recover all my playlists by creating a new one. Then they all apperead again.

**Comment by csaavedra** [comment]
Update: I removed the test playlist I created

> > Funny thing I was able to fix it by adding new Playlist to the system. Opened random album clicked [...] button, add to playlist, I entered some name and then all the playlists became visible again.
> 
> I can confirm that I could recover all my playlists by creating a new one. Then they all apperead again.

I deleted the playlist I created and then all playlists dissapeared again. Creating a new one again restored them once again.

**Comment by JPVenson** [comment]
As our blog post https://jellyfin.org/posts/jellyfin-release-10.11.0/#tl-dr point no. 6 recommends, doing a full scan with replace metadata on all music libraries fixes this issue.

**Comment by npodbielski** [comment]
Thanks @JPVenson, if those users would read release notes, right? :)

What I did:
1. Scanned libraries - Playlists are there
2. Removed new playlist - Playlists are gone.
3. Scanned libraries - Playslists are gone
4. Added another playlist - Playlists are there
5. Removed new playlist - Playlists are gone
6. Added another new playlists - Playlists are gone again

**Comment by theguymadmax** [comment]
Thanks, for testing. I've confirm the behavior, users must add a new playlist for the playlist folder to appear, and is removed once again if the playlist is deleted. We’ll look into it.

**Comment by theguymadmax** [comment]
For some reason playlist are working again after scanning a library, ~~.but the behavior is different depending on the type of playlist~~:

Playlist with movies
Must perform a scan all libraries to get playlist to get the playlist folder back on the UI

Old behavior - earlier today:
Must add a new dummy playlist to get the playlist folder back on the UI
Removing dummy playlist will also remove playlist folder back on the UI
Scanning library - doesn't help

 
Playlist with music
Must perform a scan all libraries to get playlist to get the playlist folder back on the UI

Old behavior like one hour ago:
Must add a new dummy playlist to get the playlist folder back on the UI
Removing dummy playlist will also remove playlist folder back on the UI
Scanning library - doesn't help
Logs were spammed with these error messages when the scan all libraries didn't restore the playlist
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MetaBrainz.MusicBrainz.Query'.
   at MetaBrainz.MusicBrainz.Query.get_Client()
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(Uri uri, HttpMethod method, HttpContent body, CancellationToken cancellationToken, String format)
   at MetaBrainz.MusicBrainz.Query.ApplyDelayAsync[T](Func`2 request, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Objects.PagedQueryResults`3.PerformRequestAsync(CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Objects.PagedQueryResults`3.NextAsync(CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.MusicBrainz.MusicBrainzAlbumProvider.GetMetadata(AlbumInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

```

**Comment by storfors** [comment]
> Thanks, for testing. I've confirm the behavior, users must add a new playlist for the playlist folder to appear, and is removed once again if the playlist is deleted. We’ll look into it.

I too can confirm this is how it behaves for me.


> Although in my case the playlists still showed up in the section (but were empty however). Yours seem to be missing entirely. Maybe you can check the path mentioned above to see if the XML files (and folders) are still there

For me the time it takes for tracks to show up once I click in on a playlist is proportional to how large the playlist is. So if I click on a playlist that only has a handful of songs its "quick", but a list with about 3000 songs it takes about 20 seconds to be populated.

**Comment by kandykarter** [comment]
I have this issue as well, however I don't have a music collection in Jellyfin. A few of my users make playlists for their watchlists, and they're all missing. I've refreshed all metadata for my existing libraries and this has not changed.

**Comment by alexkahler** [comment]
I also had this issue. Playlist with movies and episodes for Media Bar. Adding a new playlist made the old one appear. I ended up deleting the old playlist a created a new one.

**Comment by mihawk90** [comment]
> As our blog post https://jellyfin.org/posts/jellyfin-release-10.11.0/#tl-dr point no. 6 recommends, doing a full scan with replace metadata on all music libraries fixes this issue.

I only have one music library and for me the replace metadata scan did *not* fix this.

Also the blog post says
> Additionally, users should also perform a _scan for **missing** metadata_ on their Music libraries

Not replace, but either way it doesn't work (I did both).

Today's log (upgrade starts at 09:23-ish):

[log_20251022.log](https://github.com/user-attachments/files/23049440/log_20251022.log)

**Comment by theguymadmax** [comment]
This issue was fixed in 10.11.3 ( #15446). There was a bug in 10.11.0 → 10.11.2 for users migrating their old DB (10.10.x) to 10.11.x. The ancestor IDs were not migrated. This caused several issues, such as not being able to play or shuffle an album, playlists disappearing, plus other issues.

The bug fix only applies to users doing a database migration from 10.10.x to 10.11.3. It does not fix the issue for those already on 10.11.x.

For those on 10.11.x, you have to scan each library with the “scan for missing metadata” option to repopulate the ancestor IDs.
Also, due to other issues, many people have errors such as DB locks, so these scans will sometimes fail, and you may need to scan multiple times for the database to repopulate with the ancestor ID. 

If the scan doesn’t work for you and you have a backup of 10.10.x, then you can restore your backup copy, then re-migrate. Note, there is no rolling back; you must still have a backup copy to try again.  Another workaround is to create a new playlist.

**Comment by npodbielski** [comment]
I confirm that playlists view works again. 
What is still not working is playing album via album thumbnail. You have to open it and play song from the album. 
Should this be fixed too, by scanning the library?

https://github.com/user-attachments/assets/3c0c8dc4-75f0-491c-98aa-71f99924c615
