### ISSUE TITLE
Searching for Portuguese subtitles doesn't specify region

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin#15106]
### Description of the bug

It is currently impossible to search for different Portugese subtitles (and other languages) 

### Reproduction steps

1. Install OpenSubtitle plugin
2. Search for "Portugese (Brazil)" subtitles
  - See "por" being requested
3. Search for "Portugese (Portugal)" subtitles
  - See "por" being requested

### What is the current _bug_ behavior?

"por" is requested for every variation of subtitle

### What is the expected _correct_ behavior?

We should be able to tell which culture is being requested

### Jellyfin Server version

10.10.0+

### Specify the build version

10.11.0

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Jellyfin Data Storage:
- Media Storage:
- External Integrations:
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell

```

**Comment by crobibero** [comment]
For some reason we also send "pt-br" and "pt-pt" as the culture name.

Maybe we should make the request with the full culture object? or at least both the two-letter and three-letter iso codes

**Comment by MBR-0001** [comment]
It would probably be best to switch to the two letter name, both internally and on the web (manual search). I think this would be too big of a change for a 10.11 backport (library config would have to be migrated, all the internals changed).

I guess the "easiest" solution would be to revert the PR that caused this (https://github.com/jellyfin/jellyfin/pull/14030)

Aditionally, how it currently looks in options.xml:
```xml
  <SubtitleDownloadLanguages>
    <string>por</string>
    <string>por</string>
    <string>por</string>
  </SubtitleDownloadLanguages>
```

**Comment by mndti** [comment]
Here I had to revert to version 10.10.7, because both 10.11.0 and 10.11.1 have this same behavior.

In version 10.10.7, it is correct:
por - Portugal
pob - Brazil

**Comment by lulajardim** [comment]
I couldn't find any workaround for this, except manually navigating to open subtitles to download pt-br subtitles. In the end, I also had to revert to 10.10.7. 

Although I can live without PT-BR subtitles, my family cannot. So, until a workaround is found or a fix is implemented, i'll have to stick with an outdated version.

**Comment by bighi** [comment]
Is there no way to fix this temporarily until you can change to 2 letter plus culture?

For people that speak Brazilian Portuguese, the European Portuguese is very hard to understand. So this mix up makes the subtitles completely useless. 🙁

**Comment by alexjcgdf** [comment]
> I couldn't find any workaround for this, except manually navigating to open subtitles to download pt-br subtitles. In the end, I also had to revert to 10.10.7.
> 
> Although I can live without PT-BR subtitles, my family cannot. So, until a workaround is found or a fix is implemented, i'll have to stick with an outdated version.

happens the same to me at home - I can rely on English subtitles but my entire family dont. And as also posted above, the Portuguese (Portugal) is very different from the wording used by Brazillian Portuguese which makes for us in Brazil useless as a plugin and therefore having to manually downloading them from the opensubtitle website.

**Comment by alexjcgdf** [comment]
thanks a lot @MBR-0001 !!!!!!

**Comment by MBR-0001** [comment]
should be solved in 10.11.4

**Comment by arielsantarosa** [comment]
Running 10.11.4 but not fixed yet.

When I set Brazilian Portuguese, in Subtitles > Preferred subtitle language
now it sticks when saved, but when I choose any title, ENG still is the default.

**Comment by MBR-0001** [comment]
@arielsantarosa this issue is for searching subtitles, what you are describing is something else

**Comment by lulajardim** [comment]
Tested it today by installing 10.11.5 on my windows pc and it seems to be solved. Don't feel like upgrading my main server right now since i'm still learning how to safely rollback apps on Dockge.

**Comment by MBR-0001** [comment]
@crobibero can this be closed?
