### ISSUE TITLE
Wrong aspect ratio after transcoding of cropped HDR MKV-files

### ISSUE THREAD

**Issue by olanwe** [jellyfin/jellyfin#15134]
### Description of the bug

After upgrading to Jellyfin 10.11.0 I noticed that the transcoding of HDR MKV files with cropping information is broken. The cropped image will be vertically stretched.

### Reproduction steps

1. Convert a HDR video (e.g. https://repo.jellyfin.org/test-videos/HDR/Dolby%20Vision/Test%20Jellyfin%201080p%20DV%20P8.1.mp4 ) to a MKV file, applying the MKV-"cropping" parameter to crop away the top- and bottom-part of the video (e.g. by setting it to "0,139,0,139").
2. The result is the same video with cropping information added by the MKV-muxer. A capable player will display the video without the cropped areas, although they are still part of the video.
3. Upload this video to the Jellyfin server.
4. Activate transcoding and play the video.

### What is the current _bug_ behavior?

The transcoded video is vertically stretched.

This effect is even visible in the preview pictures:

<img width="1251" height="456" alt="Image" src="https://github.com/user-attachments/assets/add7ffac-9712-4864-8345-54b34687edad" />

### What is the expected _correct_ behavior?

The aspect ratio should stay the same (no matter if the cropped bars are removed during transcoding or not).

### Jellyfin Server version

10.10.0+

### Specify the build version

10.11.0

### Environment

```markdown
- OS: Ubuntu 24.04.3 LTS
- Linux Kernel: 6.8.0-84-generic
- Virtualization: Docker
- Clients:
- Browser:
- FFmpeg Version: 7.1.2-Jellyfin
- Playback Method: Transcoding 
- Hardware Acceleration: QSV
- GPU Model: Intel UHD Graphics Gen11 16EU
- Installed Plugins:
- Reverse Proxy: none
- Base URL:
- Networking:
- Jellyfin Data Storage:
- Media Storage:
- External Integrations:
```

### Jellyfin logs

```shell
[2025-10-22 23:49:36.624 +00:00] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "user". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2025-10-22 23:49:36.624 +00:00] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 42000000, RemoteIP: "192.168.170.70", IsInLocalNetwork: True
[2025-10-22 23:49:36.640 +00:00] [INF] [61] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : SmVsbHlmaW5NZWRpYVBsYXllciAxLjExLjEgKHdpbmRvd3MteDg2XzY0IDEwKXwxNzE5MzYzMjUyNTM0-454548ca26584cff8203bf8ecd205407-d655a390d76caad7d99e5c72eae68183
[2025-10-22 23:49:36.640 +00:00] [INF] [61] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 10/22/2025 23:49:36
[2025-10-22 23:49:36.640 +00:00] [INF] [61] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[2025-10-22 23:49:36.640 +00:00] [INF] [31] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[2025-10-22 23:49:36.753 +00:00] [INF] [59] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -f matroska -init_hw_device vaapi=va:,vendor_id=0x8086,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:\"/media_2/videos/Test_Jellyfin_cropped_1080p_DV_P8.1.mkv\" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map -0:a -map -0:s -codec:v:0 hevc_qsv -tag:v:0 hvc1 -low_power 1 -preset veryfast -mbbrc 1 -b:v 12866990 -maxrate 12866991 -rc_init_occupancy 25733980 -bufsize 51467960 -profile:v:0 main -level 41 -g:v:0 180 -keyint_min:v:0 180 -vf \"setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,scale_vaapi=w=0:h=0:extra_hw_frames=24,hwmap=derive_device=opencl:mode=read,tonemap_opencl=format=nv12:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0,hwmap=derive_device=qsv:mode=write:reverse=1:extra_hw_frames=16,format=qsv\"  -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/transcodes/51c9647de90f633134dbe957b7c62341%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/transcodes/51c9647de90f633134dbe957b7c62341.m3u8\""
[2025-10-22 23:49:37.637 +00:00] [INF] [31] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "SmVsbHlmaW5NZWRpYVBsYXllciAxLjExLjEgKHdpbmRvd3MteDg2XzY0IDEwKXwxNzE5MzYzMjUyNTM0-454548ca26584cff8203bf8ecd205407-d655a390d76caad7d99e5c72eae68183"
[2025-10-22 23:49:44.434 +00:00] [INF] [45] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.170.70" closed
[2025-10-22 23:49:44.577 +00:00] [INF] [62] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2025-10-22 23:49:44.855 +00:00] [INF] [62] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.170.70" request
[2025-10-22 23:49:56.640 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: session.RemoteEndPoint : "192.168.170.70"
[2025-10-22 23:49:56.640 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_playing_id     = "d655a390d76caad7d99e5c72eae68183"
[2025-10-22 23:49:56.640 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id        = "454548ca26584cff8203bf8ecd205407"
[2025-10-22 23:49:56.641 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : event_user_id_int    = 4
[2025-10-22 23:49:56.641 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_playing_id   = "d655a390d76caad7d99e5c72eae68183"
[2025-10-22 23:49:56.641 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : session_user_id      = "454548ca26584cff8203bf8ecd205407"
[2025-10-22 23:49:56.641 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : play_method          = "Transcode (v:hevc a:)"
[2025-10-22 23:49:56.641 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.ClientName         = "Jellyfin Media Player"
[2025-10-22 23:49:56.641 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : e.DeviceName         = "PC"
[2025-10-22 23:49:56.641 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemName             = "Test_Jellyfin_cropped"
[2025-10-22 23:49:56.641 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemId               = "d655a390d76caad7d99e5c72eae68183"
[2025-10-22 23:49:56.641 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : ItemType             = "Movie"
[2025-10-22 23:49:56.641 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : All matches, playback registered
[2025-10-22 23:49:56.641 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback tracker found, adding playback info : "SmVsbHlmaW5NZWRpYVBsYXllciAxLjExLjEgKHdpbmRvd3MteDg2XzY0IDEwKXwxNzE5MzYzMjUyNTM0-454548ca26584cff8203bf8ecd205407-d655a390d76caad7d99e5c72eae68183"
[2025-10-22 23:49:56.641 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[2025-10-22 23:49:56.647 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Exited
[2025-10-22 23:49:58.323 +00:00] [INF] [62] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "SmVsbHlmaW5NZWRpYVBsYXllciAxLjExLjEgKHdpbmRvd3MteDg2XzY0IDEwKXwxNzE5MzYzMjUyNTM0-454548ca26584cff8203bf8ecd205407-d655a390d76caad7d99e5c72eae68183"
[2025-10-22 23:50:09.357 +00:00] [INF] [67] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "/transcodes/51c9647de90f633134dbe957b7c62341.m3u8"
[2025-10-22 23:50:10.868 +00:00] [INF] [67] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.170.70" closed
[2025-10-22 23:50:10.875 +00:00] [INF] [68] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Media Player" "1.12.0" playing "Test_Jellyfin_cropped". Stopped at "29950" ms
[2025-10-22 23:50:10.878 +00:00] [INF] [67] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : "SmVsbHlmaW5NZWRpYVBsYXllciAxLjExLjEgKHdpbmRvd3MteDg2XzY0IDEwKXwxNzE5MzYzMjUyNTM0-454548ca26584cff8203bf8ecd205407-d655a390d76caad7d99e5c72eae68183"
[2025-10-22 23:50:10.878 +00:00] [INF] [67] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 10/22/2025 23:50:10
[2025-10-22 23:50:10.879 +00:00] [INF] [67] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Saving playback tracking activity in DB
[2025-10-22 23:50:11.256 +00:00] [INF] [45] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.170.70" request
```

### FFmpeg logs

```shell
{"Protocol":0,"Id":"d655a390d76caad7d99e5c72eae68183","Path":"/media_2/videos/Test_Jellyfin_cropped_1080p_DV_P8.1.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv","Size":48196530,"Name":"Test_Jellyfin_cropped_1080p_DV_P8.1","IsRemote":false,"ETag":"09c720453f100ec10e183189b8741246","RunTimeTicks":299660000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"UseMostCompatibleTranscodingProfile":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"hevc","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":"bt2020nc","ColorTransfer":"smpte2084","ColorPrimaries":"bt2020","DvVersionMajor":1,"DvVersionMinor":0,"DvProfile":8,"DvLevel":5,"RpuPresentFlag":1,"ElPresentFlag":0,"BlPresentFlag":1,"DvBlSignalCompatibilityId":1,"Rotation":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"Hdr10PlusPresentFlag":null,"VideoRange":2,"VideoRangeType":5,"VideoDoViTitle":"Dolby Vision Profile 8.1 (HDR10)","AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":"1080p HEVC Dolby Vision Profile 8.1 (HDR10)","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":12866990,"BitDepth":10,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1080,"Width":1920,"AverageFrameRate":60,"RealFrameRate":60,"ReferenceFrameRate":60,"Profile":"Main 10","Type":1,"AspectRatio":"4:3","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":123,"IsAnamorphic":true}],"MediaAttachments":[],"Formats":[],"Bitrate":12866990,"FallbackMaxStreamingBitrate":null,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":0,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null,"HasSegments":false}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -f matroska -init_hw_device vaapi=va:,vendor_id=0x8086,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media_2/videos/Test_Jellyfin_cropped_1080p_DV_P8.1.mkv" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map -0:a -map -0:s -codec:v:0 hevc_qsv -tag:v:0 hvc1 -low_power 1 -preset veryfast -mbbrc 1 -b:v 12866990 -maxrate 12866991 -rc_init_occupancy 25733980 -bufsize 51467960 -profile:v:0 main -level 41 -g:v:0 180 -keyint_min:v:0 180 -vf "setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,scale_vaapi=w=0:h=0:extra_hw_frames=24,hwmap=derive_device=opencl:mode=read,tonemap_opencl=format=nv12:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0,hwmap=derive_device=qsv:mode=write:reverse=1:extra_hw_frames=16,format=qsv"  -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/transcodes/51c9647de90f633134dbe957b7c62341%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/transcodes/51c9647de90f633134dbe957b7c62341.m3u8"


ffmpeg version 7.1.2-Jellyfin Copyright (c) 2000-2025 the FFmpeg developers
  built with gcc 14 (Debian 14.2.0-19)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.101 / 61. 19.101
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
Input #0, matroska,webm, from 'file:/media_2/videos/Test_Jellyfin_cropped_1080p_DV_P8.1.mkv':
  Metadata:
    encoder         : libebml v1.4.5 + libmatroska v1.7.1
    creation_time   : 2025-10-22T22:51:22.000000Z
    MOVIE/ENCODER   : Lavf61.1.100
  Duration: 00:00:29.97, start: 0.000000, bitrate: 12866 kb/s
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 1920x1080 [SAR 1:1 DAR 16:9], SAR 401:540 DAR 1604:1215, 60 fps, 60 tbr, 1k tbn (default)
      Metadata:
        BPS             : 12861403
        DURATION        : 00:00:29.966000000
        NUMBER_OF_FRAMES: 1797
        NUMBER_OF_BYTES : 48175601
        _STATISTICS_WRITING_APP: mkvmerge v95.0 ('Goodbye Stranger') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2025-10-22 22:51:22
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      Side data:
        Frame cropping: 0/0/139/139
        DOVI configuration record: version: 1.0, profile: 8, level: 5, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 1, compression: 0
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> hevc (hevc_qsv))
Press [q] to stop, [?] for help
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
Output #0, hls, to '/transcodes/51c9647de90f633134dbe957b7c62341.m3u8':
  Metadata:
    encoder         : Lavf61.7.100
  Stream #0:0: Video: hevc (hvc1 / 0x31637668), qsv(tv, bt709, progressive), 1920x1080 [SAR 401:540 DAR 1604:1215], q=2-31, 12866 kb/s, 60 fps, 90k tbn (default)
      Metadata:
        encoder         : Lavc61.19.101 hevc_qsv
      Side data:
        cpb: bitrate max/min/avg: 12866991/0/12866990 buffer size: 51467960 vbv_delay: N/A
frame=   89 fps=0.0 q=-0.0 size=N/A time=00:00:00.00 bitrate=N/A dup=1 drop=0 speed=   0x    
[hls @ 0x7b4bbc6d0a00] Opening '/transcodes/51c9647de90f633134dbe957b7c623410.ts' for writing
frame=  210 fps=210 q=-0.0 size=N/A time=00:00:02.01 bitrate=N/A dup=1 drop=0 speed=2.02x    
frame=  327 fps=218 q=-0.0 size=N/A time=00:00:03.96 bitrate=N/A dup=1 drop=0 speed=2.64x    
[hls @ 0x7b4bbc6d0a00] Opening '/transcodes/51c9647de90f633134dbe957b7c623411.ts' for writing
frame=  447 fps=223 q=-0.0 size=N/A time=00:00:05.96 bitrate=N/A dup=1 drop=0 speed=2.98x    
[hls @ 0x7b4bbc6d0a00] Opening '/transcodes/51c9647de90f633134dbe957b7c623412.ts' for writing
frame=  567 fps=227 q=-0.0 size=N/A time=00:00:07.96 bitrate=N/A dup=1 drop=0 speed=3.19x    
frame=  689 fps=230 q=-0.0 size=N/A time=00:00:10.00 bitrate=N/A dup=1 drop=0 speed=3.33x    
[hls @ 0x7b4bbc6d0a00] Opening '/transcodes/51c9647de90f633134dbe957b7c623413.ts' for writing
frame=  802 fps=229 q=-0.0 size=N/A time=00:00:11.88 bitrate=N/A dup=1 drop=0 speed=3.39x    
[hls @ 0x7b4bbc6d0a00] Opening '/transcodes/51c9647de90f633134dbe957b7c623414.ts' for writing
frame=  917 fps=229 q=-0.0 size=N/A time=00:00:13.80 bitrate=N/A dup=1 drop=0 speed=3.45x    
frame= 1032 fps=229 q=-0.0 size=N/A time=00:00:15.71 bitrate=N/A dup=1 drop=0 speed=3.49x    
[hls @ 0x7b4bbc6d0a00] Opening '/transcodes/51c9647de90f633134dbe957b7c623415.ts' for writing
frame= 1151 fps=230 q=-0.0 size=N/A time=00:00:17.70 bitrate=N/A dup=1 drop=0 speed=3.54x    
[hls @ 0x7b4bbc6d0a00] Opening '/transcodes/51c9647de90f633134dbe957b7c623416.ts' for writing
frame= 1272 fps=231 q=-0.0 size=N/A time=00:00:19.71 bitrate=N/A dup=1 drop=0 speed=3.58x    
frame= 1393 fps=232 q=-0.0 size=N/A time=00:00:21.73 bitrate=N/A dup=1 drop=0 speed=3.62x    
[hls @ 0x7b4bbc6d0a00] Opening '/transcodes/51c9647de90f633134dbe957b7c623417.ts' for writing
frame= 1511 fps=232 q=-0.0 size=N/A time=00:00:23.70 bitrate=N/A dup=1 drop=0 speed=3.65x    
[hls @ 0x7b4bbc6d0a00] Opening '/transcodes/51c9647de90f633134dbe957b7c623418.ts' for writing
frame= 1629 fps=233 q=-0.0 size=N/A time=00:00:25.66 bitrate=N/A dup=1 drop=0 speed=3.67x    
frame= 1750 fps=233 q=-0.0 size=N/A time=00:00:27.68 bitrate=N/A dup=1 drop=0 speed=3.69x    
[hls @ 0x7b4bbc6d0a00] Opening '/transcodes/51c9647de90f633134dbe957b7c623419.ts' for writing
[out#0/hls @ 0x7b4bbc6f6b00] video:46354KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
frame= 1798 fps=234 q=-0.0 Lsize=N/A time=00:00:28.48 bitrate=N/A dup=1 drop=0 speed= 3.7x
```

**Comment by nyanmisaka** [comment]
It looks like JMP requested an invalid resolution `scale_vaapi=w=0:h=0`.

Please test in the web client to see if the same problem occurs.

**Comment by olanwe** [comment]
Yes. I have tested it on the Jellyfin PC client as well as the web player. The aspect ratio is correct when no transcoding takes place. It also seems to work for transcoded SDR content.
Also bear in mind that the generated preview image is stretched as well.

**Comment by nyanmisaka** [comment]
Well, it turns out that Jellyfin Server doesn't currently support applying crop metadata set by MKVToolNix to the hardware transcoding pipeline.

This metadata changed the aspect ratios in ffprobe, and 10.11 added further anamorphic video detection, which caused this issue.

You can try #15144 and refresh the metadata of the affected videos to see if it fixes the issue.

**Comment by theguymadmax** [comment]
Fixed by #15144

**Comment by olanwe** [comment]
Sorry, but I just upgraded to 10.11.1 and the problem is still there (preview picture and transcode still stretched)!
I tried to reset the metadata, replace all information and pictures and clear the browser cache but this did not help. Please let me know in case I am missing something.

Jellyfin-Log:
```
[2025-10-27 20:13:16.597 +00:00] [INF] [17] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "user". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2025-10-27 20:13:16.597 +00:00] [INF] [17] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 42000000, RemoteIP: "192.168.170.70", IsInLocalNetwork: True
[2025-10-27 20:13:16.916 +00:00] [INF] [39] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2025-10-27 20:13:16.916 +00:00] [INF] [39] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -f matroska -init_hw_device vaapi=va:,vendor_id=0x8086,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:\"/media_2/videos/Test_Jellyfin_cropped_1080p_DV_P8.1.mkv\" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map -0:a -map -0:s -codec:v:0 hevc_qsv -tag:v:0 hvc1 -low_power 1 -preset veryfast -mbbrc 1 -b:v 12866990 -maxrate 12866991 -rc_init_occupancy 25733980 -bufsize 51467960 -profile:v:0 main -level 41 -g:v:0 180 -keyint_min:v:0 180 -vf \"setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,hwmap=derive_device=opencl:mode=read,tonemap_opencl=format=nv12:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0,hwmap=derive_device=qsv:mode=write:reverse=1:extra_hw_frames=16,format=qsv\"  -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename \"06b85147629b89ac1b62802352e9a032-1.mp4\" -start_number 0 -hls_segment_filename \"/transcodes/06b85147629b89ac1b62802352e9a032%d.mp4\" -hls_playlist_type vod -hls_list_size 0 -hls_segment_options movflags=+frag_discont -y \"/transcodes/06b85147629b89ac1b62802352e9a032.m3u8\""
[2025-10-27 20:13:19.366 +00:00] [INF] [39] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTQ0LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTQ0LjB8MTc2MTE2NDUyMDA5Mg11-454548ca26584cff8203bf8ecd205407-d655a390d76caad7d99e5c72eae68183
[2025-10-27 20:13:19.368 +00:00] [INF] [39] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 10/27/2025 20:13:19
[2025-10-27 20:13:19.369 +00:00] [INF] [39] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[2025-10-27 20:13:19.370 +00:00] [INF] [41] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[2025-10-27 20:13:20.331 +00:00] [INF] [7] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTQ0LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTQ0LjB8MTc2MTE2NDUyMDA5Mg11-454548ca26584cff8203bf8ecd205407-d655a390d76caad7d99e5c72eae68183"
[2025-10-27 20:13:24.629 +00:00] [INF] [17] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2025-10-27 20:13:26.184 +00:00] [INF] [17] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.170.70" closed
[2025-10-27 20:13:26.609 +00:00] [INF] [17] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.170.70" request
[2025-10-27 20:13:34.143 +00:00] [INF] [7] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "/transcodes/06b85147629b89ac1b62802352e9a032.m3u8"
[2025-10-27 20:13:35.660 +00:00] [INF] [17] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.11.1" playing "Test_Jellyfin_cropped". Stopped at "15000" ms
[2025-10-27 20:13:35.673 +00:00] [INF] [7] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop tracker found, processing stop : "TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6MTQ0LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvMTQ0LjB8MTc2MTE2NDUyMDA5Mg11-454548ca26584cff8203bf8ecd205407-d655a390d76caad7d99e5c72eae68183"
[2025-10-27 20:13:35.674 +00:00] [INF] [7] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Stop Event : 10/27/2025 20:13:35
[2025-10-27 20:13:35.674 +00:00] [INF] [7] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Playback stop but TrackedPlaybackInfo not found! not storing activity in DB
[2025-10-27 20:13:36.353 +00:00] [INF] [38] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.170.70" closed
[2025-10-27 20:13:36.782 +00:00] [INF] [38] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.170.70" request
```

FFmpeg Transcode-Log:
```
{"Protocol":0,"Id":"d655a390d76caad7d99e5c72eae68183","Path":"/media_2/videos/Test_Jellyfin_cropped_1080p_DV_P8.1.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv","Size":48196530,"Name":"Test_Jellyfin_cropped_1080p_DV_P8.1","IsRemote":false,"ETag":"09c720453f100ec10e183189b8741246","RunTimeTicks":299660000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"UseMostCompatibleTranscodingProfile":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"hevc","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":"bt2020nc","ColorTransfer":"smpte2084","ColorPrimaries":"bt2020","DvVersionMajor":1,"DvVersionMinor":0,"DvProfile":8,"DvLevel":5,"RpuPresentFlag":1,"ElPresentFlag":0,"BlPresentFlag":1,"DvBlSignalCompatibilityId":1,"Rotation":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"Hdr10PlusPresentFlag":null,"VideoRange":2,"VideoRangeType":5,"VideoDoViTitle":"Dolby Vision Profile 8.1 (HDR10)","AudioSpatialFormat":0,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"LocalizedHearingImpaired":null,"DisplayTitle":"1080p HEVC Dolby Vision Profile 8.1 (HDR10)","NalLengthSize":null,"IsInterlaced":false,"IsAVC":false,"ChannelLayout":null,"BitRate":12866990,"BitDepth":10,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1080,"Width":1920,"AverageFrameRate":60,"RealFrameRate":60,"ReferenceFrameRate":60,"Profile":"Main 10","Type":1,"AspectRatio":"4:3","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":123,"IsAnamorphic":false}],"MediaAttachments":[],"Formats":[],"Bitrate":12866990,"FallbackMaxStreamingBitrate":null,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":0,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null,"HasSegments":false}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -probesize 1G -f matroska -init_hw_device vaapi=va:,vendor_id=0x8086,driver=iHD -init_hw_device qsv=qs@va -init_hw_device opencl=ocl@va -filter_hw_device qs -hwaccel vaapi -hwaccel_output_format vaapi -noautorotate -i file:"/media_2/videos/Test_Jellyfin_cropped_1080p_DV_P8.1.mkv" -noautoscale -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map -0:a -map -0:s -codec:v:0 hevc_qsv -tag:v:0 hvc1 -low_power 1 -preset veryfast -mbbrc 1 -b:v 12866990 -maxrate 12866991 -rc_init_occupancy 25733980 -bufsize 51467960 -profile:v:0 main -level 41 -g:v:0 180 -keyint_min:v:0 180 -vf "setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,hwmap=derive_device=opencl:mode=read,tonemap_opencl=format=nv12:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0,hwmap=derive_device=qsv:mode=write:reverse=1:extra_hw_frames=16,format=qsv"  -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename "06b85147629b89ac1b62802352e9a032-1.mp4" -start_number 0 -hls_segment_filename "/transcodes/06b85147629b89ac1b62802352e9a032%d.mp4" -hls_playlist_type vod -hls_list_size 0 -hls_segment_options movflags=+frag_discont -y "/transcodes/06b85147629b89ac1b62802352e9a032.m3u8"


ffmpeg version 7.1.2-Jellyfin Copyright (c) 2000-2025 the FFmpeg developers
  built with gcc 14 (Debian 14.2.0-19)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.101 / 61. 19.101
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
Input #0, matroska,webm, from 'file:/media_2/videos/Test_Jellyfin_cropped_1080p_DV_P8.1.mkv':
  Metadata:
    encoder         : libebml v1.4.5 + libmatroska v1.7.1
    creation_time   : 2025-10-22T22:51:22.000000Z
    MOVIE/ENCODER   : Lavf61.1.100
  Duration: 00:00:29.97, start: 0.000000, bitrate: 12866 kb/s
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 1920x1080 [SAR 1:1 DAR 16:9], SAR 401:540 DAR 1604:1215, 60 fps, 60 tbr, 1k tbn (default)
      Metadata:
        BPS             : 12861403
        DURATION        : 00:00:29.966000000
        NUMBER_OF_FRAMES: 1797
        NUMBER_OF_BYTES : 48175601
        _STATISTICS_WRITING_APP: mkvmerge v95.0 ('Goodbye Stranger') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2025-10-22 22:51:22
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      Side data:
        Frame cropping: 0/0/139/139
        DOVI configuration record: version: 1.0, profile: 8, level: 5, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 1, compression: 0
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> hevc (hevc_qsv))
Press [q] to stop, [?] for help
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
[hls @ 0x729edb2d0a00] Opening '/transcodes/06b85147629b89ac1b62802352e9a032-1.mp4' for writing
Output #0, hls, to '/transcodes/06b85147629b89ac1b62802352e9a032.m3u8':
  Metadata:
    encoder         : Lavf61.7.100
  Stream #0:0: Video: hevc (hvc1 / 0x31637668), qsv(tv, bt709, progressive), 1920x1080 [SAR 401:540 DAR 1604:1215], q=2-31, 12866 kb/s, 60 fps, 15360 tbn (default)
      Metadata:
        encoder         : Lavc61.19.101 hevc_qsv
      Side data:
        cpb: bitrate max/min/avg: 12866991/0/12866990 buffer size: 51467960 vbv_delay: N/A
frame=   93 fps=0.0 q=-0.0 size=N/A time=00:00:00.00 bitrate=N/A dup=1 drop=0 speed=   0x    
[hls @ 0x729edb2d0a00] Opening '/transcodes/06b85147629b89ac1b62802352e9a0320.mp4' for writing
frame=  216 fps=216 q=-0.0 size=N/A time=00:00:02.05 bitrate=N/A dup=1 drop=0 speed=2.05x    
frame=  334 fps=223 q=-0.0 size=N/A time=00:00:04.01 bitrate=N/A dup=1 drop=0 speed=2.68x    
[hls @ 0x729edb2d0a00] Opening '/transcodes/06b85147629b89ac1b62802352e9a0321.mp4' for writing
frame=  456 fps=228 q=-0.0 size=N/A time=00:00:06.05 bitrate=N/A dup=1 drop=0 speed=3.02x    
[hls @ 0x729edb2d0a00] Opening '/transcodes/06b85147629b89ac1b62802352e9a0322.mp4' for writing
frame=  573 fps=229 q=-0.0 size=N/A time=00:00:08.00 bitrate=N/A dup=1 drop=0 speed= 3.2x    
frame=  695 fps=232 q=-0.0 size=N/A time=00:00:10.03 bitrate=N/A dup=1 drop=0 speed=3.34x    
[hls @ 0x729edb2d0a00] Opening '/transcodes/06b85147629b89ac1b62802352e9a0323.mp4' for writing
frame=  814 fps=233 q=-0.0 size=N/A time=00:00:12.01 bitrate=N/A dup=1 drop=0 speed=3.43x    
[hls @ 0x729edb2d0a00] Opening '/transcodes/06b85147629b89ac1b62802352e9a0324.mp4' for writing
frame=  932 fps=233 q=-0.0 size=N/A time=00:00:13.98 bitrate=N/A dup=1 drop=0 speed=3.49x    
frame= 1051 fps=233 q=-0.0 size=N/A time=00:00:15.96 bitrate=N/A dup=1 drop=0 speed=3.55x    
[hls @ 0x729edb2d0a00] Opening '/transcodes/06b85147629b89ac1b62802352e9a0325.mp4' for writing
frame= 1174 fps=235 q=-0.0 size=N/A time=00:00:18.01 bitrate=N/A dup=1 drop=0 speed= 3.6x    
[hls @ 0x729edb2d0a00] Opening '/transcodes/06b85147629b89ac1b62802352e9a0326.mp4' for writing
frame= 1295 fps=235 q=-0.0 size=N/A time=00:00:20.03 bitrate=N/A dup=1 drop=0 speed=3.64x    
frame= 1416 fps=236 q=-0.0 size=N/A time=00:00:22.05 bitrate=N/A dup=1 drop=0 speed=3.67x    
[hls @ 0x729edb2d0a00] Opening '/transcodes/06b85147629b89ac1b62802352e9a0327.mp4' for writing
frame= 1532 fps=236 q=-0.0 size=N/A time=00:00:23.98 bitrate=N/A dup=1 drop=0 speed=3.69x    
[hls @ 0x729edb2d0a00] Opening '/transcodes/06b85147629b89ac1b62802352e9a0328.mp4' for writing
frame= 1651 fps=236 q=-0.0 size=N/A time=00:00:25.96 bitrate=N/A dup=1 drop=0 speed=3.71x    
frame= 1773 fps=236 q=-0.0 size=N/A time=00:00:28.00 bitrate=N/A dup=1 drop=0 speed=3.73x    
[hls @ 0x729edb2d0a00] Opening '/transcodes/06b85147629b89ac1b62802352e9a0329.mp4' for writing
[out#0/hls @ 0x729edb2f6b00] video:46354KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
frame= 1798 fps=237 q=-0.0 Lsize=N/A time=00:00:28.41 bitrate=N/A dup=1 drop=0 speed=3.74x
```
@theguymadmax @nyanmisaka

**Comment by nyanmisaka** [comment]
It is now a combination of two problems:

- First, the Jellyfin server does not support this metadata, so transcoding it should be avoided. Disabling anamorphic attribute eliminates this in most cases.

- Second, the native HLS player included in Chrome 141+ always requests the SDR playlist on SDR displays, which leads to transcoding. https://github.com/jellyfin/jellyfin-web/pull/7274

**Comment by olanwe** [comment]
This issue is still open - both preview images as well as transcoded video have a wrong aspect ratio when using cropped videos.

**Comment by xanshark** [comment]
Figured I'd mention this also happens with non-HDR video, at least for me. Here's an example of a DVD rip with MKVToolNix's cropping metadata:

Jellyfin Transcoding:

<img width="2560" height="1394" alt="Image" src="https://github.com/user-attachments/assets/f201dc10-8fc0-413f-bfc4-8df22c2a0613" />

MPV (Expected Output):

<img width="2560" height="1394" alt="Image" src="https://github.com/user-attachments/assets/b57e4d54-f211-4467-a866-f1cfec3ea53d" />

**Comment by nyanmisaka** [comment]
DirecPlay in MPV or other local video players is much more flexible because it allows for using shaders in at least OpenGL, while our hardware transcoding pipeline here needs to consider more than five different hardware acceleration methods, some of which cannot run shaders. jellyfin-ffmpeg8 should provide sufficient HWA cropping support, but some additional code needs to be written on the server to enable it.

**Comment by PC-Heini** [comment]
This issue still exists, at least with my AMD-APU hardware-accelerated transcodes. The trickplay generation just ignores the crop and renders the black bars, which is better than the content being distorted.
