### ISSUE TITLE
10.11 collection display order not working

### ISSUE THREAD

**Issue by lostb1t** [jellyfin/jellyfin#15179]
### Description of the bug

Collection items ordering does not seem to work
anymore

### Reproduction steps

Items should be sorted by order of insertion into collection for "date modified" option (the default) (ref https://github.com/jellyfin/jellyfin/pull/12457)

So when you add new items to a collection should show up as last but it does not

same goes for sorting by sort name. Also doesnt seem to work

### What is the current _bug_ behavior?

.

### What is the expected _correct_ behavior?

.

### Jellyfin Server version

Master

### Specify the build version

10.11.0

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Jellyfin Data Storage:
- Media Storage:
- External Integrations:
```

### Jellyfin logs

```shell
.
```

### FFmpeg logs

```shell

```

**Comment by cigdangle** [comment]
It seems as though none of the collection sort options except for "Release Date" are working on collections.  They all display in order of Release Date.

**Comment by lostb1t** [comment]
good catch. Did not realize that. Will change the issue accordingly

**Comment by theguymadmax** [comment]
@lostb1t Boxset ordering regressed with #14795. My quick fix was #14919

**Comment by lostb1t** [comment]
Well that sucks. Its pretty broken but i guess this might need to be rolled into the rework of pulling in  collections and playlists into the db

**Comment by lostb1t** [comment]
k well that explains it.

Kinda bummed such a regression would be knowingly released tho.

Looking at it, the fix probaply should be rolled into the rework of pulling in collections and playlists in to the db

**Comment by misku** [comment]
I'd like to confirm the problem. After some update, sorting got botched. In my case sorting by "date added" simply sorts by "name" (ascending and descending). The same problem exists in the web UI, Android app, and Google TV app.
- Libraries->Display->Date added behavior for new content is set to: "Use file creation date". Changing it to "Use date scanned..." doesn't help.
- Checking/unchecking "Group movies/shows into collections" does not help.
- Rescanning all Libraries and replacing all metadata on every one of them doesn't help.
- Sorting files on Linux by "created date", shows the correct order of files (`find . -type f -print0 | xargs -0 stat --format='%W %n' | sort -k1,1nr | head -n 50 | cut -d' ' -f2-`)

Looks like a regression to me. One day Watchtower auto updated Jellyfin image and the sorting just stopped working (no config touched).

Server 10.11.3

**Comment by barrelltitor** [comment]
@misku not to take away from the issue but you should never use watchtower. Always use versioning and backup before updates

**Comment by misku** [comment]
@barrelltitor I only use watchtower for non-crucial containers. If something breaks I can always recover from backup manually and anchor the container if needed. Fortunately the sorting bug is not the end of the world, so I added more info for devs.

**Comment by n3fariox** [comment]
Hello, I'm still having this issue on the latest 10.11.4 release.

I updated, toggled the collection order to "Release Date" then back to "Name", and it's still sorting by release date.

This is a custom collection and the sorting is wrong on all my clients (android/web/etc).
Is there any trick to getting it to getting it to work?

**Comment by kurtosterhage** [comment]
I am also still having this issue on 10.11.4. The release order is always the sort order, no matter which one I choose.

**Comment by misku** [comment]
Also confirming the problem still exists on 10.11.4: in my case "date added" sorts by "name".

**Comment by theguymadmax** [comment]
Collections sorting should be fixed by #15767. The default query was producing a Null Exception; that query should now be ignored, see #15768

**Comment by misku** [comment]
Not sure about @n3fariox and @kurtosterhage, but I'm still having the issue on `10.11.5`. I'm using a custom library. I don't remember what I chose when creating it, but it says "Other". I also created a new library using the same folder "Home Videos and Photos". Same sorting issue ("sort by date added" is exactly the same as "sort by name", but it's not correct - new files were added in directories that are in the middle of the sorted pack).

**Comment by kurtosterhage** [comment]
@misku 10.11.5 seems to have fixed it for me. I'm only using Movie and Shows libraries and my collections are all created using the TMDb Box Sets and Auto Collections plugins.

**Comment by misku** [comment]
@kurtosterhage Thanks for testing and the update.

**Comment by jyourstone** [comment]
Working for me as well, both manually created collections and the ones created by the SmartLists plugin.

**Comment by n3fariox** [comment]
10.11.5 fixed it for me.
My home alone movies in my Christmas collection are all grouped by name as expected 😎
