### ISSUE TITLE
Recently Added links broken

### ISSUE THREAD

**Issue by markster1700** [jellyfin/jellyfin#15204]
### Description of the bug

After upgrade all links on Main Page for Recently Added Photo and Music are broken.

### Reproduction steps

1. sign into jellyfin
2. Select any links to Recently Added Photo or Music
3. Jellyfin display error that link is missing.

### What is the current _bug_ behavior?

After update to latest 10.11.0 Recently Added Phot and Music links on the Main Page are broken.

### What is the expected _correct_ behavior?

The links should display selected elements

### Jellyfin Server version

10.10.0+

### Specify version number

10.11.0

### Specify the build version

I donmt have it 

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Jellyfin Data Storage:
- Media Storage:
- External Integrations:
```

### Jellyfin logs

```shell
NA
```

### FFmpeg logs

```shell
NA
```

**Comment by theguymadmax** [comment]
Which links are you referring to? Can you post a screenshot? If you are referring to the album artist link on the bottom of the music card: https://github.com/jellyfin/jellyfin-web/issues/7247, then that issue has been fixed and will be included in the upcoming bugfix release.

**Comment by DarkCTO** [comment]
@theguymadmax  From the home page, hovering on the artist names in the recently added music or audiobooks.
I will get  ?id=undefined&serverID=undefined
So clicking on just give me empty page loading forever. Same issue after full rescan multiple times.
Had to revert to previous version because this update is trash, unstable as hell.

**Comment by DarkCTO** [comment]
To reproduce, I have mp3 that I tag it myself (not using online metadata), 
TIT2 -> Title
TPE2 -> Artist Name
TALB -> Category (Audiobooks)

Previous versions, recently added artists link will have proper URL, with defined IDs.
After updating, full scan, they still come up as undefined.

**Comment by theguymadmax** [comment]
Artist links have already been reported here:
https://github.com/jellyfin/jellyfin-web/issues/7247
https://github.com/jellyfin/jellyfin/issues/15111
https://github.com/jellyfin/jellyfin/issues/15124
And fixed by:
https://github.com/jellyfin/jellyfin-web/pull/7248 

This will be included in the upcoming bugfix release, which should be released soon.

**Comment by DarkCTO** [comment]
OK Thanks.

**Comment by markster1700** [comment]
I just tested in 10.11.2. Its not there. The issue is still present in 10.11.2

**Comment by theguymadmax** [comment]
> I just tested. IT IS NOT FIXED. I REPEAT. NOT FIXED.

Could you please reply with the requested information from my initial post? Also, can you post a screenshot of your dashboard that shows the server and web version number?  Additionally, do you get an error message when you click a link, or errors in the logs?

**Comment by markster1700** [comment]
I do not run a lab and have only one instance of the server. This is such a simple issue. But I cannot keep a broken jellyfin running. I reverted back to 10:10:7.

Good luck

**Comment by sevenrats** [comment]
luck is no substitute for actually answering the questions we ask.

**Comment by markster1700** [comment]
Yes, your r correct. Experience and good testing and regration testing strategy with automated scripts will definitely eliminated many mistakes.
