### ISSUE TITLE
Music Artists Not Correct on Tracks with Multiple 'artist' Entries

### ISSUE THREAD

**Issue by lexitronic** [jellyfin/jellyfin#15283]
### Description of the bug

On Jellyfin 10.11+, and when adding a song with multiple 'artist' metadata entries, Jellyfin seems to randomise the artists is adds to its database, often excluding the artist that is also in the 'albumartist' field if they exist. This happens regardless of if I use the "Replace existing metadata", or "Search for missing metadata" options, or remove and re-add the library.

### Reproduction steps

0. Fresh Jellyfin configuration, with no changes to default settings.
1. Add Music library.
2. Add song with multiple 'artist' metadata entries.
3. Scan for new songs.
4. Go to the album that was added.
5. Look at the metadata that Jellyfin stored for the song using "Edit Metadata".
6. its wrong

### What is the current _bug_ behavior?

The "artists" field in the "Edit Metadata" menu has different data to the file itself.

<img width="1154" height="755" alt="Image" src="https://github.com/user-attachments/assets/f0b4a16d-ca33-4a30-bb7d-d74932f1aae7" />

### What is the expected _correct_ behavior?

The "artists" field in the "Edit Metadata" menu matches the metadata in the file.

<img width="1145" height="764" alt="Image" src="https://github.com/user-attachments/assets/76e5cb05-23a3-49bb-b43d-b8010034c714" />

### Jellyfin Server version

10.10.0+

### Specify version number

10.11.1

### Specify the build version

10.11.1

### Environment

```markdown
- OS: Debian 13
- Linux Kernel: 6.12.48+deb13-amd64
- Virtualization: Docker in KVM
- Clients: Browser
- Browser: Firefox 143.0.1
- FFmpeg Version: 7.1.2-Jellyfin
- Playback Method: None
- Hardware Acceleration: None
- GPU Model: None
- Plugins: None
- Reverse Proxy: None
- Base URL: None
- Networking: Bridge
- Jellyfin Data Storage: Local SATA SSD
- Media Storage: Local SATA SSD
- External Integrations: None
```

### Jellyfin logs

```shell
See attachments
```

### FFmpeg logs

```shell

```

### Relevant screenshots or videos

Library setup settings on creation, 10.10.7:
<img width="1201" height="3417" alt="Image" src="https://github.com/user-attachments/assets/a457e131-cc48-4757-95d9-daaec8aa2f71" />

Library setup settings on creation, 10.11.1:
<img width="1175" height="3385" alt="Image" src="https://github.com/user-attachments/assets/b73a3939-4f92-4944-a5e9-26cca17bd4ea" />

### Additional information

I tested with a fresh installation of Debian with no internet access.

I verified correct behaviour on Jellyfin 10.10.7 and incorrect behaviour on Jellyfin 10.11.1.

Log file for Jellyfin 10.10.7:
[jellyfin-10-10-7-log.log](https://github.com/user-attachments/files/23193467/jellyfin-10-10-7-log.log)

Log file for Jellyfin 10.11.1:
[jellyfin-10-11-1-log.log](https://github.com/user-attachments/files/23193473/jellyfin-10-11-1-log.log)

Docker Compose for Jellyfin 10.10.7:
```
services:
  jellyfin:
    container_name: "jellyfin"
    hostname: jellyfin
    image: jellyfin/jellyfin:10.10.7
    user: 1000:1000
    ports:
      - 8096:8096
    restart: "unless-stopped"
    volumes:
      - "/srv/docker/music:/Music:ro"
      - "/srv/docker/jellyfin-10-10-7:/config"
      - "/srv/docker/.cache:/cache"
```

 Docker Compose for Jellyfin 10.11.1:
```
services:
  jellyfin:
    container_name: "jellyfin"
    hostname: jellyfin
    image: jellyfin/jellyfin:latest
    user: 1000:1000
    ports:
      - 8096:8096
    restart: "unless-stopped"
    volumes:
      - "/srv/docker/music:/Music:ro"
      - "/srv/docker/jellyfin-10-11:/config"
      - "/srv/docker/.cache:/cache"
```

Directory tree that was used in environment:
```
root@Jellyfin-Test:~# tree /srv/docker/music/
/srv/docker/music/
└── Kira
    └── The Introduction (Deluxe Edition)
        └── 05 - Games.flac

3 directories, 1 file
```

Song metadata entries, reported by FFmpeg and mutagen, respectively:
```
Input #0, flac, from '/srv/docker/music/Kira/The Introduction (Deluxe Edition)/05 - Games.flac':
  Metadata:
    album           : The Introduction (Deluxe Edition)
    title           : Games
    track           : 05
    tracktotal      : 15
    comment         : Visit https://kiraproductions.bandcamp.com
    album_artist    : KIRA
    disc            : 01
    date            : 2018
    artist          : KIRA;Ruby;GUMI
  Duration: 00:03:19.38, start: 0.000000, bitrate: 1800 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s32 (24 bit)

...

Python 3.13.5 (main, Jun 25 2025, 18:55:22) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mutagen.flac import FLAC
>>> file = FLAC('/srv/docker/music/Kira/The Introduction (Deluxe Edition)/05 - Games.flac')
>>> print(file.pprint())
FLAC, 199.38 seconds, 44100 Hz (audio/flac)
album=The Introduction (Deluxe Edition)
title=Games
tracknumber=05
tracktotal=15
description=Visit https://kiraproductions.bandcamp.com
albumartist=KIRA
discnumber=01
date=2018
artist=KIRA
artist=Ruby
artist=GUMI
>>>
```

**Comment by sapphic-wallflower** [comment]
related https://github.com/jellyfin/jellyfin/issues/15265

**Comment by sapphic-wallflower** [comment]
Still broken in 10.11.3, extremely easy to replicate as well.

**Comment by gnattu** [comment]
May I ask how are you tagging (or could you provide a copyright-free file just with dummy tags) so that I can reproduce this " extremely easy to replicate" issue? It might be a regression of the upstream ATL library (which is updated in 10.11) but I cannot reproduce with my own files.

**Comment by mumeicopperhead** [comment]
I can confirm the issue is still replicable on the Jellyfin 10.11.3 official docker image.

Here's the file I used to test (in the zip because Github doesn't support flacs):
[test.zip](https://github.com/user-attachments/files/23833371/test.zip)
(I replaced the audio stream with the Markiplier bite of 87 meme)

I used the below script to generate the file:
```
from mutagen.flac import FLAC

# test file
file = '/home/mumei/Downloads/2.flac'
audiofile_1 = FLAC(file)

# real file
file_2 = '/srv/files/Music/Kira/The Introduction (Deluxe Edition)/05 - Games.flac'
audiofile_2 = FLAC(file_2)

# erase all keys in test file
for key in audiofile_1:
    audiofile_1[key] = []

# copy keys from real file to test file
for key in audiofile_2:
    audiofile_1[key] = audiofile_2[key]

# add cover art
audiofile_1.add_picture(audiofile_2.pictures[0])

# save
audiofile_1.save()
```

**Comment by gnattu** [comment]
Unfortunately I still failed to reproduce this very issue on my instance. I failed to reproduce this on minimal environment either.

What I did:

- Download the test.zip posted above
- On Linux host I did the following:
```shell
sudo docker pull jellyfin/jellyfin
mkdir config
mkdir cache
mkdir media
sudo docker run -d \
 --name jellyfin \
 --user uid:gid \
 -p 8096:8096/tcp \
 -p 7359:7359/udp \
 --volume ./config:/config \
 --volume ./cache:/cache \
 --mount type=bind,source=./media,target=/media \
 jellyfin/jellyfin
cd media
mkdir test-bug
mv ~/test.flac ./test-bug/
```

Then connect to the started instance, setup a new server with `/media` as the only music library, and I got correct artists assigned:

<img width="1689" height="262" alt="Image" src="https://github.com/user-attachments/assets/0e707c58-e406-42e9-aae1-451a7dab3297" />

**Comment by sapphic-wallflower** [comment]
all files are tagged with the latest and stock version of picard https://files.catbox.moe/uqr4w6.webm

jellyfin has always been horrible with multiple artists. this is why editing is required. however, editing is broken.

artist tags: https://files.catbox.moe/uavyoa.png

**Comment by gnattu** [comment]
I *think* I know the problem but that might be a bigger problem.

Actually all three tagged artists are detected AND being entered to the database. It is the People creation logic failed in which, confused the frontend which make it to *think* the file only has two artists:

<img width="400" height="200" alt="Image" src="https://github.com/user-attachments/assets/a49c28cf-fe5d-4c7f-b613-93e840e64264" />

So this is not a tagging problem, nor editing problem. It is a people relation regression introduced in the DB refactor (and no it was not the refactor's fault, our people relation works terribly even before the refactoring). 

Current problem seems like the people named Kira cannot be an aritist and an album artsit at the same time, so the people item for Kira did not create, and then our frontend will only list artists with a people entry and ignores the "Artists" property totally and shows this inconsistent results.

**Comment by sapphic-wallflower** [comment]
Still broken on 10.11.4 in the same way, unfortunately.

**Comment by gnattu** [comment]
I believe I found the root cause and I could explain why this is so hard to reproduce:

Basically, you have to have multiple artists that have same spelling but differ in something like cases. In this case, KIRA and Kira.

Now our refactored DB queries would:
- Block KIRA be created because it think this artist already exists, although with name Kira
- But the Artist lookup query would not find Kira, because the artist lookup is case-sensitive

I plan to make the behavior consistent so that the Artist name will not be normalized on both creation and look up (so always use the raw name)

It is the user's responsibility to make sure the same person will always have the same spelling(and case).

**Comment by theguymadmax** [comment]
Fixed by #15689

**Comment by sapphic-wallflower** [comment]
This didn't fix the issue, metadata is still broken. @theguymadmax please re-open the issue if you have that ability. 

https://github.com/user-attachments/assets/5d1882e5-bbcb-463b-a96d-dba2f845e90e

**Comment by theguymadmax** [comment]
@sapphic-wallflower Thanks for the demonstration of the issue. I've submitted a fix.  

Workaround around in the meantime. When adding multiple artists, don't include extra whitespace after the separator:
"Artist 1;Artist 2" as opposed to "Artist 1; Artist 2"

**Comment by gnattu** [comment]
Or just retag the music. Artist editor is very fragile indeed but this should not happen on properly tagged music files

**Comment by sapphic-wallflower** [comment]
@theguymadmax My apologies, I should have demonstrated that as well. I have been trying that, but forgot to in the previous video. The two outcomes happen without the whitespace as well.

https://github.com/user-attachments/assets/136dd5ea-8fee-42ea-b373-26b36ffe07b9

@gnattu Jellyfin has never respected adding semicolons to the music files itself. I tried this all the way back in 8.0.

Before: 

<img width="2065" height="632" alt="Image" src="https://github.com/user-attachments/assets/bdc9e544-5357-4206-aa52-f1a4922a333b" />

After: 

<img width="2048" height="606" alt="Image" src="https://github.com/user-attachments/assets/fc8083e3-d410-401c-8376-4b05ce26d05a" />

The after may look correct, but it's not when you press play. There should be a comma, denoting that there are two artists, but it just has the semicolon, doing the same thing that "ft." was doing. Combining the two artists. 

<img width="308" height="85" alt="Image" src="https://github.com/user-attachments/assets/f7d67767-7a20-4f83-b286-86c748d68a26" />

<img width="1152" height="105" alt="Image" src="https://github.com/user-attachments/assets/8f4035ec-ec8b-4e72-aee8-d1a0fefcf0d1" />

"Properly tagged" is a bit nebulous, if the automatic tagging system by Picard isn't enough (no realistic person is going to tag their metadata files manually), I don't know what properly tagged is supposed to look like.

**Comment by gnattu** [comment]
> "Properly tagged" is a bit nebulous, if the automatic tagging system by Picard isn't enough (no realistic person is going to tag their metadata files manually), I don't know what properly tagged is supposed to look like.

We had a long discussion on this topic and unfortunately no, the default format that Picard enforce on you is NOT the most correct way to tag multi value fields like artists. That default is merely a compatibility trade off as id3v2.3 offers no way to tag multi values. But for vorbis tag (which flac files are using) and id3v2.4, there are official ways in spec that does not need a special character as a separator. You could refer to https://github.com/jellyfin/jellyfin/issues/11871#issuecomment-2225146012 for more info, if you are interested you can also scroll up for the discussions in that issue.

> @gnattu Jellyfin has never respected adding semicolons to the music files itself. I tried this all the way back in 8.0

Because this non standard convention of tagging is extremely popular we introduced an opt-in library option you can set the delimiter yourself in 10.9
https://github.com/jellyfin/jellyfin/pull/12385

**Comment by mumeicopperhead** [comment]
Adding onto this:

I have recreated the issue in video form:

Adding a new artist using the correct syntax in the "Edit Metadata" UI results in the new artist not appearing in the field after a refresh:
https://github.com/user-attachments/assets/5f6850b8-20dc-4983-b221-7913c09e3df5

Adding existing artists works fine, though:
https://github.com/user-attachments/assets/8b083a42-336d-48fc-be28-91f97180441d

This worked in 10.10.7.

Also, here's a video of my attempt to add spaces after the semicolons in the field (for sake of reproducibility):
https://github.com/user-attachments/assets/f3859def-ab52-46f6-ba30-9fd2f172fc99

@sapphic-wallflower What @gnattu is referring to is the fact that VorbisComment (FLAC, Opus, Ogg) and ID3v2.4 and above (mp3) both expect multiple *entrys* to appear in the field `artist` when the user wants to attribute multiple artists to the file. This is also true of `genre` and `albumartist` (and any other tag.)

It's like adding each artist individually in their own lines vs. adding them all to the same line in a spreadsheet:
<img width="263" height="127" alt="Image" src="https://github.com/user-attachments/assets/63b76538-1e80-4036-8154-627831deb925" />
You want your program to support adding multiple entries in this way *and actually saves them in this way*.

It looks like you're on linux (KDE Plasma cursor), so correct formatting in an already built program is incredibly hard to find, even in enthusiast solutions. Most programs I can find are Windows only.
You can use [mutagen](https://mutagen.readthedocs.io) like I do. (python library, so you'll have to learn python if you don't know already, and it's manual, unless you want to integrate it with MusicBrainz or Spotify).

> @gnattu Because this non standard convention of tagging is extremely popular we introduced an opt-in library option you can set the delimiter yourself in 10.9

IMO this compatibility should probably happen in the background automatically, with overrides in the library settings, so people don't scratch their heads wondering why their music shows up properly in Picard, but not in Jellyfin.

**Comment by sapphic-wallflower** [comment]
I mean no disrespect when I say the following. I respect the efforts of everyone on the Jellyfin team.

This worked as expected all the way from 10.6 until the end of 10.10.7. I understand that massive changes went on, but it's difficult to believe I'm now suddenly doing the wrong thing. I spent a lot of time editing my metadata because I could never get Jellyfin to respect multiple artists. There's never been any documentation on this. Editing artists manually has always worked fine. Now it doesn't. I'm not changing the way I add metadata. Setting the delimiter to something other than a semicolon doesn't work in the same ways I've shown in the video above, so it's not useful. 

If the final answer is "change your workflow", I'm unfortunately going to have to give up on this specific issue and using Jellyfin for music all together. I've known since the start that Jellyfin isn't built for people who use music, it's been in an immature state from the start of me using Jellyfin back in 2020. Navidrome can detect my files without any modifications, so switching to that full-time seems like the path forward.

Again, I love Jellyfin, and I love the developers for putting their time and effort into the software, but I haven't seen much love ever given to the music functionality in the last five years. Since I'm no longer adding metadata in a way that Jellyfin supports, this probably turns into a feature request. I don't think enough people use Jellyfin for music for that to change, either, sadly.

**Comment by mumeicopperhead** [comment]
@sapphic-wallflower If you're using docker, you can switch the jellyfin image to `jellyfin/jellyfin:10.10.7`. You'll have to set up a temporary config directory though, because 10.11 config isn't compatible.

@gnattu Honestly, "Do it the to the standard" doesn't feel like an answer to "the database only adds artists when it feels like it" to me.

I'm also gonna [echo Torvalds](https://lkml.org/lkml/2012/12/23/75) ("If a change [in the kernel] results in user programs breaking, it's a bug in the kernel") and say that Jellyfin needs to have default support for *all* metadata configurations, whether they are 'standard' or not.

When said "standard" is only implemented by **one** python library and a handful of Windows-only programs, you cannot expect anyone to use it.

I don't even think `ffmpeg` supports it.

**Comment by gnattu** [comment]
Since the merging of https://github.com/jellyfin/jellyfin/pull/12385 you *CAN* set your own custom delimiter per library so that what ever delimiters like semicolons, can be parsed. So it is already a *supported* use case. So there is no need to "change your workflow", only change your library configuration and do a metadata replacement scan.

> Since I'm no longer adding metadata in a way that Jellyfin supports, this probably turns into a feature request.

So this is already an implemented feature.

> @gnattu Honestly, "Do it the to the standard" doesn't feel like an answer to "the database only adds artists when it feels like it" to me.

I'm not denying that "the database only adds artists when it feels like it" is a bug, it is a bug **indeed**, but "Do it the to the standard" is one workaround to this bug.

> Editing artists manually has always worked fine. Now it doesn't.

So yes this is indeed a bug, and it is related to our recent database refactor, and we are sorry for any inconvenience that changed cause.

> When said "standard" is only implemented by one python library and a handful of Windows-only programs, you cannot expect anyone to use it.

Actually it is more popular than you think it is. Picard also supports that (you have to manually change the config to prefer id3v2.4 formatting to make it write in the id3v2.4/vorbis tag way). ffmpeg also supports vorbis tag fully, it just supports id3v2.4 badly because it will cut off the string at null char and id3v2.4 uses the null char as multi-value separator. And not one python library, even for [taglib](https://taglib.org), we have two python implementations and all projects uses taglib supports this standard, for example, vlc. So at least several hundreds of software supports this standard. The problem here is that 

- The most popular Picard defaults to not use the standard way. 
- And there is already tons of music files tagged in the non standard way, it is impossible to ask everyone to retag everything.

This is the exact reason why we introduced the custom delimiter configuration feature. It is not enabled by default because we tend to not make assumptions for users. Unlike emby, which tends to make a lot of assumptions and often causes issues when it predicts use cases badly. 

> Jellyfin needs to have default support for all metadata configurations, whether they are 'standard' or not.

This is impossible to do in practice because it usually means make assumptions because nonstandard behavior is not predictable, and the "convention" usually conflicts with real artist names. In Jellyfin, as of its current state, we put this behind an opt-in library configuration to let the user set
- The preferred delimiter character
- The whitelisted names (like `AC/DC`) so that the delimiter will not be applied to it
- And a few alternative tags like `ARTISTS` that is non standard but used by Picard and Kodi

<img width="911" height="657" alt="Image" src="https://github.com/user-attachments/assets/1070b936-3ce3-481e-8914-ab832c3cbc5f" />

Because we never know the actual music collections better than the user themselves, asking users to properly config the library to fit their collection is not "asking too much"  to me at least. 

I have more than 100k music files in my own Jellyfin instances and I know that Jellyfin has shortcomings in managing music. The way it scans music is actually flawed, because music files are usualy properly tagged unlike video files, so current file-structure based scan just falls apart for music and requires a lot of post-processing to override the early (wrong) decisions made by the scanner. The KIRA and Kira case is actually one of it. The file structure based scanner first assumed an Artist name Kira from the folder name, and then it realized the artist should be KIRA from the actual tag, and then funny things happened.  I am fully aware of such limitation but changing how our file scanner work is an ever larger task and also hard to do right. What I can do is to add more patches so that current library "appears to work".

Hope the above explanation is clear enough.

**Comment by sapphic-wallflower** [comment]
These are the default Picard settings, and it's not doing what you're proposing. I didn't change these, I made sure to install on a fresh install, just to see what they were.

<img width="1507" height="468" alt="Image" src="https://github.com/user-attachments/assets/0b3edf64-e15c-40e5-9fec-544dc8e0c027" />

<img width="1500" height="391" alt="Image" src="https://github.com/user-attachments/assets/d6b2e311-e582-44ed-8f71-32f5e4c1ecd4" />

I went to go check my own Picard on my install, and it was set to prefer ID3v2.4. 

It doesn't add multiple artists to a new line. In theory, it should remove the feat. and add a semicolon, showing they're on two different lines, but it doesn't change the artist field at all. But I'm not going to make you troubleshoot my MusicBrainz or Picard, so this is just for demonstration. 

<img width="2400" height="1780" alt="Image" src="https://github.com/user-attachments/assets/96968cc9-fb88-45c4-8257-ef8fe0676de3" />

I know there's a scroll bar, but trust me, there's nothing down there relating to any of the many artists adjacent metadata fields.

I've also tried to use "Prefer ARTISTS" because that's what I can see it says in Picard, and it still doesn't use the "ARTISTS" metadata field properly when enabled. I've tried all the library options, way before 28th October when this issue was opened. It still reverses the order, or rather, randomizes the order. I need the main artists to be first, but it always defaults to last. 

<img width="962" height="548" alt="Image" src="https://github.com/user-attachments/assets/d884531a-da23-40b7-aa16-b771ca91530f" />

<img width="2482" height="1749" alt="Image" src="https://github.com/user-attachments/assets/3730b288-f545-4478-ab75-e1ff4851bb54" />

**Comment by sapphic-wallflower** [comment]
I also want to say in a fresh comment, I don't really care that the metadata doesn't import into Jellyfin properly. It never has, and I came to terms with that. I'm fine editing it.

I'd just like editing to be fixed. Anything else isn't the most pressing issue to me. I'm realizing how in the weeds this has gotten with the metadata being directly imported.

**Comment by gnattu** [comment]
> It still reverses the order, or rather, randomizes the order. I need the main artists to be first, but it always defaults to last.

This is what would help make Jellyfin better, just say what part is not working loud and clear so that we know what was wrong.

> I also want to say in a fresh comment, I don't really care that the metadata doesn't import into Jellyfin properly. It never has, and I came to terms with that. I'm fine editing it.
> 
> I'd just like editing to be fixed. Anything else isn't the most pressing issue to me. I'm realizing how in the weeds this has gotten with the metadata being directly imported

And this isn’t *that* helpful. Yes, I agree that import tags never meet everyone’s needs. However, as I mentioned earlier, we can’t predict everyone’s use cases, which is why we need a clearer message about what’s going wrong. With a clearer message, instead of merely saying “it just isn’t working from the beginning” the chances of your problem being addressed increase. It might sound stupid but there are a lot of things that sounds "obvious" from your side is unclear from our side. Like the strict sorting of the tag order is something we totally overlooked because most of us do not really care about sorting order.

**Comment by mumeicopperhead** [comment]
There seems to be four issues in this thread:

Resolved:
- Metadata not imported properly (bug) (appears solved by #15689)
    - Not showing artists in UI, but appearing in database.
- Display order for tracks with a list of entries is incorrect (bug, should be fixed by #15816)
- Not clearly stating (ex. in docs) that Jellyfin expects metadata to adhere to standard conventions.
    - Could be solved by adding metadata standard conventions to the [music naming guide](https://jellyfin.org/docs/general/server/media/music/) (Probably a feature request) (Moved to https://github.com/jellyfin/jellyfin.org/issues/1758)

Unresolved:
- Metadata editor is not working (bug) (#15974)
    - Does not add artists to metadata when they aren't already in database (at least in UI)

**Comment by Almamu** [comment]
@sapphic-wallflower Regarding editing metadata (artist and album artist) from Jellyfin, there's a bug where it will only be properly added if you do so under Album artist and then reload the page you're in. After that you should be able to use that artist under both "Album artist" and "Artist" in any item as long as the spelling is exactly the same. I made a PR to fix this regression (#15974) but I have the feeling it might need more work as it's a simple patch and doesn't actually address the underlying issue.

**Comment by mumeicopperhead** [comment]
(Reply to https://github.com/jellyfin/jellyfin/issues/15283#issuecomment-3664254999)

The display order bug appears to be fixed, but the "Edit Metadata" bug is still present. The behaviour is the same as previously described.

In addition, I created a separate issue focusing on the documentation issue. https://github.com/jellyfin/jellyfin.org/issues/1758

**Comment by theguymadmax** [comment]
> (Reply to [#15283 (comment)](https://github.com/jellyfin/jellyfin/issues/15283#issuecomment-3664254999))
> 
> The display order bug appears to be fixed, but the "Edit Metadata" bug is still present. The behaviour is the same as previously described.
> 
> In addition, I created a separate issue focusing on the documentation issue. [jellyfin/jellyfin.org#1758](https://github.com/jellyfin/jellyfin.org/issues/1758)

Can you be specific on which one you are referring to? Re-add the reproducible steps and/or a video describing the issue. Thanks.

**Comment by Almamu** [comment]
> > (Reply to [#15283 (comment)](https://github.com/jellyfin/jellyfin/issues/15283#issuecomment-3664254999))
> > 
> > The display order bug appears to be fixed, but the "Edit Metadata" bug is still present. The behaviour is the same as previously described.
> > 
> > In addition, I created a separate issue focusing on the documentation issue. [jellyfin/jellyfin.org#1758](https://github.com/jellyfin/jellyfin.org/issues/1758)
> 
> Can you be specific on which one you are referring to? Re-add the reproducible steps and/or a video describing the issue. Thanks.  
> 

They're referring to this behavior: https://github.com/jellyfin/jellyfin/issues/15283#issuecomment-3722587320 which should be fixed by this PR #15974

**Comment by Delivator** [comment]
Comment to remove stale
