### ISSUE TITLE
'Season Unknown' metadata created for new TV Series with jellyfin server 10.11.1

### ISSUE THREAD

**Issue by cohortcw179** [jellyfin/jellyfin#15327]
### Description of the bug

A "Seasons Unknown" metadata was created when I added a new TV Series into my library. When I tried editing the metadata, the Content type is listed as "Inherit" and most of the fields are empty. 

### Reproduction steps

This can be recreated with another new TV Series folder and scan for new and updated files.

### What is the current _bug_ behavior?

An additional "Seasons Unknown" is created when refresh metadata is triggered. Triggering refresh all metadata does not help to remove this additional metadata.

### What is the expected _correct_ behavior?

No additional folder "Season Unknown" should be created.

### Jellyfin Server version

10.10.0+

### Specify the build version

10.11.1

### Environment

```markdown
- OS: Ubuntu 22.04.5 LTS
- Linux Kernel: Linux 6.14.11-4-pve x86_64)
- Virtualization: Proxmox 9.0.11
- Clients:[Brave Jellyfin Web 10.11.1]
- Browser:Brave
- FFmpeg Version: ffmpeg 7:4.4.2-0ubuntu0.22.04.1
- Playback Method: Brave + AndroidTV
- Hardware Acceleration: QSV
- GPU Model: iGPU (Intel Gen9)
- Plugins: default plugins, Meilisearch, Reports, TheTVDB, Kodi Sync Queue, TVMaze, TMDb Box Sets, Trakt
- Reverse Proxy: None
- Base URL:
- Networking: Bridge/NAT
- Jellyfin Data Storage: local SSD
- Media Storage: OneDrive via rclone
- External Integrations: none
```

### Jellyfin logs

```shell
[2025-10-30 21:59:58.020 +08:00] [INF] Started library sync
[2025-10-30 22:00:00.062 +08:00] [INF] Library Sync: Updated 3 items
[2025-10-30 22:00:00.062 +08:00] [INF] Finished library sync, taking "00:00:02.0417074"
[2025-10-30 22:00:09.257 +08:00] [INF] [GetImages] Images found for "Star Wars: Visions": [RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/595/1487926.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/355/889467.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/355/889468.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/565/1414264.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/586/1466306.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/288/720871.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Backdrop, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/358/897007.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Backdrop, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/459/1149573.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Backdrop, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/288/720885.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Logo, RatingType: Score }]
[2025-10-30 22:00:10.483 +08:00] [INF] [GetImages] Images found for "Star Wars: Visions": [RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/595/1487926.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/355/889467.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/355/889468.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/565/1414264.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/586/1466306.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/288/720871.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Backdrop, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/358/897007.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Backdrop, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/459/1149573.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Backdrop, RatingType: Score }, RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/288/720885.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Logo, RatingType: Score }]
[2025-10-30 22:00:12.232 +08:00] [INF] [GetImages] Images found for "Volume 1": [RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/565/1414263.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }]
[2025-10-30 22:00:13.549 +08:00] [INF] [GetImages] Images found for "Volume 2": [RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/565/1414261.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }]
[2025-10-30 22:00:14.799 +08:00] [INF] [GetImages] Images found for "Volume 3": [RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/586/1466305.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }]
[2025-10-30 22:00:19.882 +08:00] [INF] Started library sync
[2025-10-30 22:00:22.627 +08:00] [INF] Library Sync: Updated 8 items
[2025-10-30 22:00:22.627 +08:00] [INF] Finished library sync, taking "00:00:02.7443143"
[2025-10-30 22:00:27.775 +08:00] [INF] Started library sync
[2025-10-30 22:00:29.695 +08:00] [INF] Library Sync: Updated 2 items
[2025-10-30 22:00:29.695 +08:00] [INF] Finished library sync, taking "00:00:01.9200157"
[2025-10-30 22:00:34.836 +08:00] [INF] Started library sync
[2025-10-30 22:00:36.758 +08:00] [INF] Library Sync: Updated 2 items
[2025-10-30 22:00:36.758 +08:00] [INF] Finished library sync, taking "00:00:01.9220572"
[2025-10-30 22:00:41.893 +08:00] [INF] Started library sync
[2025-10-30 22:00:43.789 +08:00] [INF] Library Sync: Updated 2 items
[2025-10-30 22:00:43.789 +08:00] [INF] Finished library sync, taking "00:00:01.8960005"
[2025-10-30 22:00:49.740 +08:00] [INF] Started library sync
[2025-10-30 22:00:51.672 +08:00] [INF] Library Sync: Updated 2 items
[2025-10-30 22:00:51.672 +08:00] [INF] Finished library sync, taking "00:00:01.9322618"
[2025-10-30 22:00:56.826 +08:00] [INF] Started library sync
[2025-10-30 22:00:58.729 +08:00] [INF] Library Sync: Updated 2 items
[2025-10-30 22:00:58.729 +08:00] [INF] Finished library sync, taking "00:00:01.9025695"
[2025-10-30 22:01:03.859 +08:00] [INF] Started library sync
[2025-10-30 22:01:05.774 +08:00] [INF] Library Sync: Updated 2 items
[2025-10-30 22:01:05.774 +08:00] [INF] Finished library sync, taking "00:00:01.9145224"
[2025-10-30 22:01:16.023 +08:00] [INF] Started library sync
[2025-10-30 22:01:18.060 +08:00] [INF] Library Sync: Updated 3 items
[2025-10-30 22:01:18.061 +08:00] [INF] Finished library sync, taking "00:00:02.0375933"
[2025-10-30 22:01:28.120 +08:00] [INF] Started library sync
[2025-10-30 22:01:30.200 +08:00] [INF] Library Sync: Updated 3 items
[2025-10-30 22:01:30.201 +08:00] [INF] Finished library sync, taking "00:00:02.0801453"
[2025-10-30 22:01:35.339 +08:00] [INF] Started library sync
[2025-10-30 22:01:37.228 +08:00] [INF] Library Sync: Updated 2 items
[2025-10-30 22:01:37.228 +08:00] [INF] Finished library sync, taking "00:00:01.8887816"
[2025-10-30 22:01:48.438 +08:00] [INF] Started library sync
[2025-10-30 22:01:50.481 +08:00] [INF] Library Sync: Updated 3 items
[2025-10-30 22:01:50.482 +08:00] [INF] Finished library sync, taking "00:00:02.0430473"
[2025-10-30 22:01:55.623 +08:00] [INF] Started library sync
[2025-10-30 22:01:57.500 +08:00] [INF] Library Sync: Updated 2 items
[2025-10-30 22:01:57.500 +08:00] [INF] Finished library sync, taking "00:00:01.8776946"
[2025-10-30 22:02:03.445 +08:00] [INF] Started library sync
[2025-10-30 22:02:05.324 +08:00] [INF] Library Sync: Updated 2 items
[2025-10-30 22:02:05.324 +08:00] [INF] Finished library sync, taking "00:00:01.8781550"
[2025-10-30 22:02:10.462 +08:00] [INF] Started library sync
[2025-10-30 22:02:12.365 +08:00] [INF] Library Sync: Updated 2 items
[2025-10-30 22:02:12.365 +08:00] [INF] Finished library sync, taking "00:00:01.9021102"
[2025-10-30 22:02:17.499 +08:00] [INF] Started library sync
[2025-10-30 22:02:19.378 +08:00] [INF] Library Sync: Updated 2 items
[2025-10-30 22:02:19.378 +08:00] [INF] Finished library sync, taking "00:00:01.8791978"
[2025-10-30 22:02:22.554 +08:00] [INF] Timer elapsed - processing queued items
```

### FFmpeg logs

```shell

```

### Relevant screenshots or videos

![Image](https://github.com/user-attachments/assets/6d411f96-5f93-4848-847a-464c3cf3c5a1)

**Comment by ivanjx** [comment]
which metadata plugin are you using? have you updated them?

**Comment by cohortcw179** [comment]
Hi, I am mostly using TVDB plugin for my TVshows. And yes it is updated. I even tried uninstalling the plugin and reinstall it but my DB was messed up after that. 

Also not too sure if it is due to the naming of my folders to 'Star Wars Visions (2019) [tvdbid-393190]. It detected fine with Jellyfin 10.10.7.

**Comment by cohortcw179** [comment]
I just retried introducing a new tvshow and noticed jellyfin is throwing out a bunch of errors.

[2025-11-07 17:47:03.795 +08:00] [INF] Removing item, Type: "Season", Name: "Season 1", Path: "", Id: 2ccffe71-0de5-a3fd-d33c-9f230bd1e48a
[2025-11-07 17:47:04.234 +08:00] [ERR] Failed executing DbCommand ("1"ms) [Parameters=["@p0='?' (DbType = Guid), @p1='?', @p2='?', @p3='?', @p4='?' (DbType = Int32), @p5='?' (DbType = Guid), @p6='?' (Size = 11), @p7='?' (DbType = Single), @p8='?' (DbType = Single), @p9='?', @p10='?' (Size = 315), @p11='?' (DbType = DateTime), @p12='?' (DbType = DateTime), @p13='?' (DbType = DateTime), @p14='?' (DbType = DateTime), @p15='?' (DbType = DateTime), @p16='?' (DbType = DateTime), @p17='?', @p18='?', @p19='?', @p20='?', @p21='?', @p22='?' (DbType = Int32), @p23='?', @p24='?', @p25='?' (DbType = Int32), @p26='?' (DbType = Int32), @p27='?' (DbType = Int32), @p28='?' (DbType = Int32), @p29='?' (DbType = Boolean), @p30='?' (DbType = Boolean), @p31='?' (DbType = Boolean), @p32='?' (DbType = Boolean), @p33='?' (DbType = Boolean), @p34='?' (DbType = Boolean), @p35='?' (DbType = Boolean), @p36='?' (DbType = Single), @p37='?' (Size = 5), @p38='?' (Size = 11), @p39='?' (DbType = Single), @p40='?', @p41='?', @p42='?' (Size = 138), @p43='?' (Size = 36), @p44='?' (DbType = Guid), @p45='?' (DbType = Int32), @p46='?', @p47='?', @p48='?', @p49='?' (DbType = DateTime), @p50='?' (Size = 32), @p51='?', @p52='?', @p53='?' (DbType = Int32), @p54='?' (DbType = Int64), @p55='?' (DbType = Guid), @p56='?' (Size = 8), @p57='?' (DbType = Guid), @p58='?' (Size = 18), @p59='?', @p60='?', @p61='?' (DbType = Int64), @p62='?' (Size = 24), @p63='?' (DbType = DateTime), @p64='?', @p65='?', @p66='?', @p67='?' (DbType = Guid), @p68='?' (DbType = Int32), @p69='?' (Size = 43), @p70='?' (Size = 6), @p71='?' (DbType = Int32)"], CommandType='Text', CommandTimeout='30']"
""INSERT INTO \"BaseItems\" (\"Id\", \"Album\", \"AlbumArtists\", \"Artists\", \"Audio\", \"ChannelId\", \"CleanName\", \"CommunityRating\", \"CriticRating\", \"CustomRating\", \"Data\", \"DateCreated\", \"DateLastMediaAdded\", \"DateLastRefreshed\", \"DateLastSaved\", \"DateModified\", \"EndDate\", \"EpisodeTitle\", \"ExternalId\", \"ExternalSeriesId\", \"ExternalServiceId\", \"ExtraIds\", \"ExtraType\", \"ForcedSortName\", \"Genres\", \"Height\", \"IndexNumber\", \"InheritedParentalRatingSubValue\", \"InheritedParentalRatingValue\", \"IsFolder\", \"IsInMixedFolder\", \"IsLocked\", \"IsMovie\", \"IsRepeat\", \"IsSeries\", \"IsVirtualItem\", \"LUFS\", \"MediaType\", \"Name\", \"NormalizationGain\", \"OfficialRating\", \"OriginalTitle\", \"Overview\", \"OwnerId\", \"ParentId\", \"ParentIndexNumber\", \"Path\", \"PreferredMetadataCountryCode\", \"PreferredMetadataLanguage\", \"PremiereDate\", \"PresentationUniqueKey\", \"PrimaryVersionId\", \"ProductionLocations\", \"ProductionYear\", \"RunTimeTicks\", \"SeasonId\", \"SeasonName\", \"SeriesId\", \"SeriesName\", \"SeriesPresentationUniqueKey\", \"ShowId\", \"Size\", \"SortName\", \"StartDate\", \"Studios\", \"Tagline\", \"Tags\", \"TopParentId\", \"TotalBitrate\", \"Type\", \"UnratedType\", \"Width\")
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20, @p21, @p22, @p23, @p24, @p25, @p26, @p27, @p28, @p29, @p30, @p31, @p32, @p33, @p34, @p35, @p36, @p37, @p38, @p39, @p40, @p41, @p42, @p43, @p44, @p45, @p46, @p47, @p48, @p49, @p50, @p51, @p52, @p53, @p54, @p55, @p56, @p57, @p58, @p59, @p60, @p61, @p62, @p63, @p64, @p65, @p66, @p67, @p68, @p69, @p70, @p71);
SELECT changes();"
[2025-11-07 17:47:04.243 +08:00] [ERR] An exception occurred in the database while saving changes for context type '"Jellyfin.Database.Implementations.JellyfinDbContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)"
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
[2025-11-07 17:47:04.243 +08:00] [ERR] Error trying to save changes.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Implementations.Item.BaseItemRepository.UpdateOrInsertItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
[2025-11-07 17:47:04.244 +08:00] [ERR] Error while performing a library operation
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Implementations.Item.BaseItemRepository.UpdateOrInsertItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.UpdateToRepositoryAsync(ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Video.UpdateToRepositoryAsync(ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.<RefreshMetadata>g__SaveInternal|36_0(BaseItem item, MetadataRefreshOptions refreshOptions, ItemUpdateType updateType, Boolean isFirstRefresh, Boolean requiresRefresh, MetadataResult`1 metadataResult, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.TV.Series.RefreshAllMetadata(MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshAllMetadataForContainer(IMetadataContainer container, MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.LibraryTaskScheduler.LimitedConcurrencyLibraryScheduler.ProcessItem(TaskQueueItem item)
[2025-11-07 17:47:04.257 +08:00] [ERR] Failed executing DbCommand ("0"ms) [Parameters=["@p0='?' (DbType = Guid), @p1='?', @p2='?', @p3='?', @p4='?' (DbType = Int32), @p5='?' (DbType = Guid), @p6='?' (Size = 11), @p7='?' (DbType = Single), @p8='?' (DbType = Single), @p9='?', @p10='?' (Size = 315), @p11='?' (DbType = DateTime), @p12='?' (DbType = DateTime), @p13='?' (DbType = DateTime), @p14='?' (DbType = DateTime), @p15='?' (DbType = DateTime), @p16='?' (DbType = DateTime), @p17='?', @p18='?', @p19='?', @p20='?', @p21='?', @p22='?' (DbType = Int32), @p23='?', @p24='?', @p25='?' (DbType = Int32), @p26='?' (DbType = Int32), @p27='?' (DbType = Int32), @p28='?' (DbType = Int32), @p29='?' (DbType = Boolean), @p30='?' (DbType = Boolean), @p31='?' (DbType = Boolean), @p32='?' (DbType = Boolean), @p33='?' (DbType = Boolean), @p34='?' (DbType = Boolean), @p35='?' (DbType = Boolean), @p36='?' (DbType = Single), @p37='?' (Size = 5), @p38='?' (Size = 11), @p39='?' (DbType = Single), @p40='?', @p41='?', @p42='?' (Size = 138), @p43='?' (Size = 36), @p44='?' (DbType = Guid), @p45='?' (DbType = Int32), @p46='?', @p47='?', @p48='?', @p49='?' (DbType = DateTime), @p50='?' (Size = 32), @p51='?', @p52='?', @p53='?' (DbType = Int32), @p54='?' (DbType = Int64), @p55='?' (DbType = Guid), @p56='?' (Size = 8), @p57='?' (DbType = Guid), @p58='?' (Size = 18), @p59='?', @p60='?', @p61='?' (DbType = Int64), @p62='?' (Size = 24), @p63='?' (DbType = DateTime), @p64='?', @p65='?', @p66='?', @p67='?' (DbType = Guid), @p68='?' (DbType = Int32), @p69='?' (Size = 43), @p70='?' (Size = 6), @p71='?' (DbType = Int32)"], CommandType='Text', CommandTimeout='30']"
""INSERT INTO \"BaseItems\" (\"Id\", \"Album\", \"AlbumArtists\", \"Artists\", \"Audio\", \"ChannelId\", \"CleanName\", \"CommunityRating\", \"CriticRating\", \"CustomRating\", \"Data\", \"DateCreated\", \"DateLastMediaAdded\", \"DateLastRefreshed\", \"DateLastSaved\", \"DateModified\", \"EndDate\", \"EpisodeTitle\", \"ExternalId\", \"ExternalSeriesId\", \"ExternalServiceId\", \"ExtraIds\", \"ExtraType\", \"ForcedSortName\", \"Genres\", \"Height\", \"IndexNumber\", \"InheritedParentalRatingSubValue\", \"InheritedParentalRatingValue\", \"IsFolder\", \"IsInMixedFolder\", \"IsLocked\", \"IsMovie\", \"IsRepeat\", \"IsSeries\", \"IsVirtualItem\", \"LUFS\", \"MediaType\", \"Name\", \"NormalizationGain\", \"OfficialRating\", \"OriginalTitle\", \"Overview\", \"OwnerId\", \"ParentId\", \"ParentIndexNumber\", \"Path\", \"PreferredMetadataCountryCode\", \"PreferredMetadataLanguage\", \"PremiereDate\", \"PresentationUniqueKey\", \"PrimaryVersionId\", \"ProductionLocations\", \"ProductionYear\", \"RunTimeTicks\", \"SeasonId\", \"SeasonName\", \"SeriesId\", \"SeriesName\", \"SeriesPresentationUniqueKey\", \"ShowId\", \"Size\", \"SortName\", \"StartDate\", \"Studios\", \"Tagline\", \"Tags\", \"TopParentId\", \"TotalBitrate\", \"Type\", \"UnratedType\", \"Width\")
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20, @p21, @p22, @p23, @p24, @p25, @p26, @p27, @p28, @p29, @p30, @p31, @p32, @p33, @p34, @p35, @p36, @p37, @p38, @p39, @p40, @p41, @p42, @p43, @p44, @p45, @p46, @p47, @p48, @p49, @p50, @p51, @p52, @p53, @p54, @p55, @p56, @p57, @p58, @p59, @p60, @p61, @p62, @p63, @p64, @p65, @p66, @p67, @p68, @p69, @p70, @p71);
SELECT changes();"
[2025-11-07 17:47:04.257 +08:00] [ERR] An exception occurred in the database while saving changes for context type '"Jellyfin.Database.Implementations.JellyfinDbContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)"
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Implementations.Item.BaseItemRepository.UpdateOrInsertItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
[2025-11-07 17:47:04.257 +08:00] [ERR] Error trying to save changes.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Implementations.Item.BaseItemRepository.UpdateOrInsertItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.UpdateToRepositoryAsync(ItemUpdateType updateReason, CancellationToken cancellationToken)
[2025-11-07 17:47:04.257 +08:00] [ERR] Error refreshing item
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Implementations.Item.BaseItemRepository.UpdateOrInsertItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.UpdateToRepositoryAsync(ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Video.UpdateToRepositoryAsync(ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.<RefreshMetadata>g__SaveInternal|36_0(BaseItem item, MetadataRefreshOptions refreshOptions, ItemUpdateType updateType, Boolean isFirstRefresh, Boolean requiresRefresh, MetadataResult`1 metadataResult, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
[2025-11-07 17:47:04.271 +08:00] [ERR] Failed executing DbCommand ("0"ms) [Parameters=["@p0='?' (DbType = Guid), @p1='?', @p2='?', @p3='?', @p4='?' (DbType = Int32), @p5='?' (DbType = Guid), @p6='?' (Size = 11), @p7='?' (DbType = Single), @p8='?' (DbType = Single), @p9='?', @p10='?' (Size = 315), @p11='?' (DbType = DateTime), @p12='?' (DbType = DateTime), @p13='?' (DbType = DateTime), @p14='?' (DbType = DateTime), @p15='?' (DbType = DateTime), @p16='?' (DbType = DateTime), @p17='?', @p18='?', @p19='?', @p20='?', @p21='?', @p22='?' (DbType = Int32), @p23='?', @p24='?', @p25='?' (DbType = Int32), @p26='?' (DbType = Int32), @p27='?' (DbType = Int32), @p28='?' (DbType = Int32), @p29='?' (DbType = Boolean), @p30='?' (DbType = Boolean), @p31='?' (DbType = Boolean), @p32='?' (DbType = Boolean), @p33='?' (DbType = Boolean), @p34='?' (DbType = Boolean), @p35='?' (DbType = Boolean), @p36='?' (DbType = Single), @p37='?' (Size = 5), @p38='?' (Size = 11), @p39='?' (DbType = Single), @p40='?', @p41='?', @p42='?' (Size = 138), @p43='?' (Size = 36), @p44='?' (DbType = Guid), @p45='?' (DbType = Int32), @p46='?', @p47='?', @p48='?', @p49='?' (DbType = DateTime), @p50='?' (Size = 32), @p51='?', @p52='?', @p53='?' (DbType = Int32), @p54='?' (DbType = Int64), @p55='?' (DbType = Guid), @p56='?' (Size = 8), @p57='?' (DbType = Guid), @p58='?' (Size = 18), @p59='?', @p60='?', @p61='?' (DbType = Int64), @p62='?' (Size = 24), @p63='?' (DbType = DateTime), @p64='?', @p65='?', @p66='?', @p67='?' (DbType = Guid), @p68='?' (DbType = Int32), @p69='?' (Size = 43), @p70='?' (Size = 6), @p71='?' (DbType = Int32)"], CommandType='Text', CommandTimeout='30']"
""INSERT INTO \"BaseItems\" (\"Id\", \"Album\", \"AlbumArtists\", \"Artists\", \"Audio\", \"ChannelId\", \"CleanName\", \"CommunityRating\", \"CriticRating\", \"CustomRating\", \"Data\", \"DateCreated\", \"DateLastMediaAdded\", \"DateLastRefreshed\", \"DateLastSaved\", \"DateModified\", \"EndDate\", \"EpisodeTitle\", \"ExternalId\", \"ExternalSeriesId\", \"ExternalServiceId\", \"ExtraIds\", \"ExtraType\", \"ForcedSortName\", \"Genres\", \"Height\", \"IndexNumber\", \"InheritedParentalRatingSubValue\", \"InheritedParentalRatingValue\", \"IsFolder\", \"IsInMixedFolder\", \"IsLocked\", \"IsMovie\", \"IsRepeat\", \"IsSeries\", \"IsVirtualItem\", \"LUFS\", \"MediaType\", \"Name\", \"NormalizationGain\", \"OfficialRating\", \"OriginalTitle\", \"Overview\", \"OwnerId\", \"ParentId\", \"ParentIndexNumber\", \"Path\", \"PreferredMetadataCountryCode\", \"PreferredMetadataLanguage\", \"PremiereDate\", \"PresentationUniqueKey\", \"PrimaryVersionId\", \"ProductionLocations\", \"ProductionYear\", \"RunTimeTicks\", \"SeasonId\", \"SeasonName\", \"SeriesId\", \"SeriesName\", \"SeriesPresentationUniqueKey\", \"ShowId\", \"Size\", \"SortName\", \"StartDate\", \"Studios\", \"Tagline\", \"Tags\", \"TopParentId\", \"TotalBitrate\", \"Type\", \"UnratedType\", \"Width\")
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20, @p21, @p22, @p23, @p24, @p25, @p26, @p27, @p28, @p29, @p30, @p31, @p32, @p33, @p34, @p35, @p36, @p37, @p38, @p39, @p40, @p41, @p42, @p43, @p44, @p45, @p46, @p47, @p48, @p49, @p50, @p51, @p52, @p53, @p54, @p55, @p56, @p57, @p58, @p59, @p60, @p61, @p62, @p63, @p64, @p65, @p66, @p67, @p68, @p69, @p70, @p71);
SELECT changes();"
[2025-11-07 17:47:04.271 +08:00] [ERR] An exception occurred in the database while saving changes for context type '"Jellyfin.Database.Implementations.JellyfinDbContext"'."
""Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)"
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
[2025-11-07 17:47:04.272 +08:00] [ERR] Error trying to save changes.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Implementations.Item.BaseItemRepository.UpdateOrInsertItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.UpdateToRepositoryAsync(ItemUpdateType updateReason, CancellationToken cancellationToken)
[2025-11-07 17:47:04.272 +08:00] [ERR] Error refreshing item
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Server.Implementations.Item.BaseItemRepository.UpdateOrInsertItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.UpdateToRepositoryAsync(ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Video.UpdateToRepositoryAsync(ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.<RefreshMetadata>g__SaveInternal|36_0(BaseItem item, MetadataRefreshOptions refreshOptions, ItemUpdateType updateType, Boolean isFirstRefresh, Boolean requiresRefresh, MetadataResult`1 metadataResult, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
[2025-11-07 17:47:09.628 +08:00] [INF] Started library sync
[2025-11-07 17:47:10.494 +08:00] [INF] Library Sync: Added 5 items
[2025-11-07 17:47:10.494 +08:00] [INF] Finished library sync, taking "00:00:00.8663874"
[2025-11-07 17:47:12.159 +08:00] [INF] Timer elapsed - processing queued items
[2025-11-07 17:47:12.159 +08:00] [INF] No events... stopping queue timer

**Comment by evoandroidevo** [comment]
Been noticing this as well on newly added shows doing a replace metadata scan on the episode will update it to the right season and name of the episode and a library scan will remove the unknown season. This is what i have been doing on my setup to solve the issue temporarily. I didnt do an upgrade from 10.10, did a full rebuild of my vm for jellyfin fresh for 10.11.

**Comment by bilbospocketses** [comment]
Happening for me as well. 

Docker Desktop on WSL2 (Win11 25H2). 

I did a complete reset to try out 10.11.2 (deleted all metadata from media folders, and started from scratch with cache and config folders, making this a brand new jellyfin install). 

The system is performing very well. The longest wait is for the rebuild of trickplays and keyframes. But that's a backend thing that will take a week or so. 

I noticed that certain series get an unknown season, even though the show has no specials or extras. I can't find a rhyme or reason. The same shows did not have this behavior under 10.10.7. I am using all standard, 10.11 verified, plugins (tvdb, primarily)

**Comment by Pentaphon** [comment]
@ivanjx on 10.11.3 I am also getting "season unknown" in the episode details page on a popular new show that is well organized on TMDB but has not yet finished the 1st season even though the file is clearly labeled "S1E5" and everywhere else on the WEBUI correctly shows the show and episode as being labeled "Season 1"

<img width="298" height="119" alt="Image" src="https://github.com/user-attachments/assets/314742bf-9975-4005-9017-f42fa529d7c8" />

<img width="289" height="410" alt="Image" src="https://github.com/user-attachments/assets/8ad34e60-7af6-4e8f-80b5-e291ecc9bb46" />

**Comment by ivanjx** [comment]
@Pentaphon does this happen on newly added episodes or on already existing ones that is being watched? in my case with anilist plugin it marks the season number properly on all parts of the gui you mentioned.

**Comment by Pentaphon** [comment]
> does this happen on newly added episodes

Yes. It happens on newly added episodes. It doesn't seem to interfere with playback on the WEBUI or official Android TV client but I first noticed the issue when it that it affected a 3rd party client, whose dev asked me if "season unknown" shows up on the WEBUI and indeed, it shows up on the episodes details page of the episode I just added to the server but nowhere else on the WEBUI. Very odd. 

I am using 10.11.3

Edit: per @evoandroidevo I did a library rescan and the info was corrected. However, the first scan when the episode was added should have gotten it correct in the first place. Keep in mind this show is on Season 1, which has not finished airing. 

<img width="317" height="136" alt="Image" src="https://github.com/user-attachments/assets/a62d33ef-dee3-43b2-908a-ad8c072f4a65" />

**Comment by ivanjx** [comment]
so i have tried to reproduce the issue by adding 4 episodes of the series and scanned it. none of the episodes are having season unknown in the episode details page. i also marked all of them as watched. and then i tried adding the 5th episode and run a library scan, and it shows up in the "next up" section. going into the episode details still shows "season 1" as shown in the screenshots below.

<img width="429" height="350" alt="Image" src="https://github.com/user-attachments/assets/69e5fb45-93c5-484d-a4d4-67eea579c4f6" />

<img width="477" height="347" alt="Image" src="https://github.com/user-attachments/assets/72eeadf6-ad68-4216-bcbc-66b94ef744ed" />

**Comment by Pentaphon** [comment]
> so i have tried to reproduce the issue by adding 4 episodes of the series and scanned it. none of the episodes are having season unknown in the episode details page. i also marked all of them as watched. and then i tried adding the 5th episode and run a library scan, and it shows up in the "next up" section. going into the episode details still shows "season 1" as shown in the screenshots below.

Try adding just the latest episode by itself in the show folder and let the initial scan be the only scan you do. I don't know why it happens because the filename is commonly used is formatted "Pluribus.S01E05.restofinfo.mkv" It happened the same way last week as well with episode 4 but that was when I had all 4 episodes.

**Comment by evoandroidevo** [comment]
11.3 fixed the episode titles and unknown season for me. I havent noticed it happening since updating

**Comment by Pentaphon** [comment]
> so i have tried to reproduce the issue by adding 4 episodes of the series and scanned it. none of the episodes are having season unknown in the episode details page. i also marked all of them as watched. and then i tried adding the 5th episode and run a library scan, and it shows up in the "next up" section. going into the episode details still shows "season 1" as shown in the screenshots below.

@ivanjx as you can see from my screenshot: I just had the issue happen again on 10.11.3. Here's how I came across it. 

<img width="291" height="179" alt="Image" src="https://github.com/user-attachments/assets/11234d0c-5d29-4f06-a3da-c10958f241ac" />

I had S2E2 of the aforementioned show but NOT S2E1. Episode 3 came out today and I added S2E3, giving me a total of 2 out of 3 of the episodes of Season 2, which leads me to believe the issue occurs in shows that are:

1. Not yet finished airing their current season. In my case: being halfway through season 2. 
2. Not complete on the user server, such as only adding 1 episode of a season without having any other episodes of that season that aired previously. 

The developer of Wholphin was [able to reproduce this issue and commented: ](https://github.com/damontecres/Wholphin/issues/280#issuecomment-3582336849)

>I was able to contrive an example and reproduce this. However, after ~30 minutes and a library scan, it fixed itself.

>Ultimately this is caused by a missing seasonId. This is different from the "Season Number" which is why some of the UI shows the right season number and other show "Season Unknown". Wholphin doesn't show individual episodes (like the official client), it shows Series by Season. So a missing seasonId means Wholphin doesn't know which season to display and it displays the (misdirecting) "Unsupported item type: Episode" error.

>Seems that the server is not fully populating the metadata for the episodes in the initial scan.

I hope this gives you enough information to resolve this issue.

**Comment by bilbospocketses** [comment]
> Happening for me as well.
> 
> Docker Desktop on WSL2 (Win11 25H2).
> 
> I did a complete reset to try out 10.11.2 (deleted all metadata from media folders, and started from scratch with cache and config folders, making this a brand new jellyfin install).
> 
> The system is performing very well. The longest wait is for the rebuild of trickplays and keyframes. But that's a backend thing that will take a week or so.
> 
> I noticed that certain series get an unknown season, even though the show has no specials or extras. I can't find a rhyme or reason. The same shows did not have this behavior under 10.10.7. I am using all standard, 10.11 verified, plugins (tvdb, primarily)

After updating to 10.11.3, the issue of unknown seasons remained. However, by pulling the media out, running a full scan, then putting the media back in and re-scanning (I deleted all metadata in the media folders, trickplays, backdrops, nfo files, etc) the unknown seasons have not come back, even after many subsequent library scans and restarts of the container.

**Comment by jhanmann** [comment]
My solution was to set the metadata manually for "Season number" element under each episode in the "Season Unknown" to 0 (zero). This eliminated all the content from the Season Unknown folder on the UI. I then did a rescan for changed and updated files on the "Shows" and the "Season Unknown" folder in the UI was removed.

I saw this originally on 10.11.3 but have updated to 10.11.5 prior to doing this. Updating alone and refreshing the entire library _did not_ fix the issue.

**Comment by theguymadmax** [comment]
This issue was fixed in a prior release, but seasons unknown will continue to happen if Jellyfin can not recognize the season path. Refer to the documentation for the recommended folder structures and naming conventions: https://jellyfin.org/docs/general/server/media/shows

**Comment by Pentaphon** [comment]
Still an issue in 10.11.11

<img width="385" height="293" alt="Image" src="https://github.com/user-attachments/assets/39b7036c-c1cf-4003-b3de-dc7000509d8d" />

**Comment by ivanjx** [comment]
@Pentaphon does it fix itself after manual library scan (or scheduled scan) ?

**Comment by Pentaphon** [comment]
> does it fix itself after manual library scan (or scheduled scan) ?

Yes, but it shouldn't be happening in the first place. The folder and files are all correctly named.

**Comment by ivanjx** [comment]
@Pentaphon do you use docker? can you test my jf build from here https://github.com/ivanjx/jellyfin-packaging/pkgs/container/jellyfin-packaging (it is based on 10.11.11).

make sure to disable the scheduled scan and do not run manual library scan. it should be picked up in a minute or so after you add a new episode file.

**Comment by Pentaphon** [comment]
> do you use docker?

Sorry, no I don't.

**Comment by ivanjx** [comment]
@Pentaphon your specific issue should be tracked in https://github.com/jellyfin/jellyfin/issues/16215
