### ISSUE TITLE
Cannot edit media metadata

### ISSUE THREAD

**Issue by wolf7689** [jellyfin/jellyfin#15361]
### Description of the bug

After attempting to edit the metadata for an unknown season, I can no longer edit the metadata for any items. you can see the logs.

### Reproduction steps

1. edit the metadata for an unknown season
2. Change inheritance to episodes
3. save it

### What is the current _bug_ behavior?

When opening the metadata editing interface, no content loads and it keeps spinning indefinitely.

### What is the expected _correct_ behavior?

metadata can be edit

### Jellyfin Server version

10.10.0+

### Specify the build version

10.11.0

### Environment

```markdown
- OS:docker jellyfin/jellyfin
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Jellyfin Data Storage:
- Media Storage:
- External Integrations:
```

### Jellyfin logs

```shell
[2025-11-03 14:17:49.594 +08:00] [ERR] [16] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Items/0e0d9129afd1cab57ea9fba085dbbcf2/MetadataEditor".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.IO.ManagedFileSystem.AreEqual(String path1, String path2)
   at Emby.Server.Implementations.Library.LibraryManager.<>c__DisplayClass168_0.<GetContentTypeOverride>b__0(NameValuePair i)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Jellyfin.Api.Controllers.ItemUpdateController.GetMetadataEditorInfo(Guid itemId)
   at lambda_method101473(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

[2025-11-03 14:17:20.653 +08:00] [ERR] [38] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.IO.ManagedFileSystem.AreEqual(String path1, String path2)
   at Emby.Server.Implementations.Library.LibraryManager.<>c__DisplayClass168_0.<GetContentTypeOverride>b__0(NameValuePair i)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Emby.Server.Implementations.Library.LibraryManager.GetContentType(BaseItem item)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.AggregateFolder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
```

### FFmpeg logs

```shell

```

**Comment by wolf7689** [comment]
It's resolved at 10.11.2

**Comment by wolf7689** [comment]
I'm sorry, but the issue persists.

**Comment by lorenzolamas** [comment]
> I'm sorry, but the issue persists.

Same for me.

**Comment by wolf7689** [comment]
I know everyone is working hard, dedicating their personal time to create. But unless this issue is resolved, the system remains unusable. We'll never be able to add new media to it. Or could someone help provide a temporary workaround to help me bypass this problem? Thank you.

**Comment by theguymadmax** [comment]
Can you post the contents of your system.xml, which is located in your config folder.

**Comment by wolf7689** [comment]
> Can you post the contents of your system.xml, which is located in your config folder.

[system.xml](https://github.com/user-attachments/files/23575854/system.xml)

**Comment by theguymadmax** [comment]
Delete this section:
```
  <ContentTypes>
    <NameValuePair>
      <Value>tvshows</Value>
    </NameValuePair>
  </ContentTypes>
```

and replace with:
`<ContentTypes />`

Stop Jellyfin before making the change, then restart once done. That should solve the issue.

**Comment by wolf7689** [comment]
I upgraded to 10.11.3 today, but the issue persists. Modifying the system.xml resolved it—thanks. I still hope the next version will fix this without requiring configuration file changes. Wishing Jellyfin continued improvement.

**Comment by theguymadmax** [comment]
Fixed by: #15548
