### ISSUE TITLE
Ghost entries when deleting things from albums

### ISSUE THREAD

**Issue by felix920506** [jellyfin/jellyfin#15384]
### Description of the bug

When deleting things from albums, things may show as both deleted and not deleted at the same time in the Jellyfin UI

### Reproduction steps

1. Find a music album and delete a track from it directly from the filesystem (not going through Jellyfin)
2. Rescan the album using "Scan for new and updated files"
3. See album track count change but the deleted track is still there in the UI (image 1)
4. Rescan the album with replace all metadata
5. See things back to normal
6. Add the track you just deleted back
7. Rescan with "Scan for new and updated files"
8. See album track count change but the new track is not there (image 2)
9. Delete the track from the filesystem (without going through Jellyfin)
10. Rescan with "Scan for new and updated files"
11. See the track appear but broken for some unknown reason (image 3)
12. Rescan again with "Scan for new and updated files"
13. Everything back to normal

### What is the current _bug_ behavior?

The info shown about the same album is inconsistent with itself

### What is the expected _correct_ behavior?

it should be consistent with itself

### Jellyfin Server version

10.10.0+

### Specify version number

10.11.2

### Specify the build version

10.11.2

### Environment

```markdown
- OS: Linux
- Linux Kernel: Irrelevant
- Virtualization: Docker
- Clients: Web
- Browser: Firefox
- FFmpeg Version: irrelevant
- Playback Method: N/A
- Hardware Acceleration: N/A
- GPU Model: N/A
- Plugins: AniDB, DLNA
- Reverse Proxy: Caddy
- Base URL: /jellyfin
- Networking: RP
- Jellyfin Data Storage: ZFS, Nvme
- Media Storage: ZFS, HDD
- External Integrations: N/A
```

### Jellyfin logs

```shell
The only log line generated during the above event other than WS request and WS closed is:

[2025-11-04 07:22:38.305 +00:00] [INF] Removing item, Type: "Audio", Name: "ClariS 10th year StartinG 仮面の塔 -#1 エンカウンター (出会い)-", Path: "/mnt/media/acg-music/magia record/[200304] ｢アリシア／シグナル｣／ClariS [24bit_96kHz] (flac)/01 ClariS - ClariS 10th year StartinG 仮面の塔 -#1 エンカウンター (出会い)-.flac", Id: 4505ece7-88af-98ad-7d7e-732cc87e8625
```

### FFmpeg logs

```shell
None generated
```

### Relevant screenshots or videos

1.
<img width="1512" height="862" alt="Image" src="https://github.com/user-attachments/assets/ff9aa9c5-037c-401c-943d-e8a20ba07db9" />

2.
<img width="1512" height="842" alt="Image" src="https://github.com/user-attachments/assets/4a268a1c-eb5a-477e-865b-f3bac349ea84" />

3.
<img width="1512" height="848" alt="Image" src="https://github.com/user-attachments/assets/3b884f3f-92a7-4597-9c67-1c55d0cf2800" />

### Additional information

Finamp correctly shows that a track has been deleted but doesn't show the correct album runtime

**Comment by felix920506** [comment]
In Finamp after adding the track back it shows the new track but the title is the file name and the runtime is 0 seconds 

 ![image](https://github.com/user-attachments/assets/4a3988f2-aac3-42b0-8040-9cf549c32585)

**Comment by sapphic-wallflower** [comment]
related https://github.com/jellyfin/jellyfin/issues/15283 https://github.com/jellyfin/jellyfin/issues/15265

currently, music is extremely broken. there's a display bug with all music metadata fields, where it changes (sometimes) in the database, but won't show in the UI

**Comment by GentleHoneyLover** [comment]
I can confirm this behavior with Movies and Shows — files deleted from the filesystem but stay in Jelly libraries... I beleive this was introduced with 10.11 — I do not recall that behavior in prior versions...

**Comment by felix920506** [comment]
Fixed by #15423

**Comment by teledyn** [comment]
> Fixed by [#15423](https://github.com/jellyfin/jellyfin/pull/15423)

Problem persists in 10.11.11

**Comment by dx7even** [comment]
This issue still persists in the latest released build. I have several ghost entries after deletion.
