### ISSUE TITLE
10.11.4 is slow to load

### ISSUE THREAD

**Issue by Ondjultomte** [jellyfin/jellyfin#15742]
### Description of the bug

Upgraded 10.11.4 now the dashboard /controlpanel and general webb gui is really slow.

### Reproduction steps

Upgraded 10.11.4 now the dashboard /controlpanel and general webb gui is really slow.

### What is the current _bug_ behavior?

Upgraded 10.11.4 now the dashboard /congtrolpannel and general webb gui is really slow, some dasgboard nanes just get stuck. see below screenshots.

what do you need to help track down these issues?

<img width="1258" height="1217" alt="Image" src="https://github.com/user-attachments/assets/f973c22c-6e23-461b-bf10-2c6d81550671" />

### What is the expected _correct_ behavior?

fast , responsive web gui

### Jellyfin Server version

10.11.4

### Specify the build version

10.11.4

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- CPU Model:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Jellyfin Data Storage & Filesystem:
- Media Storage & Filesystem:
- External Integrations:
```

### Jellyfin logs

```shell
at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2025-12-06 20:19:15.427 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:16.427 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:17.132 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:17.132 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:17.132 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:17.132 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:17.132 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2025-12-06 20:19:17.132 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2025-12-06 20:19:17.427 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:18.426 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:19.373 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:19.373 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:19.373 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2025-12-06 20:19:19.427 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:20.427 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:21.152 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:21.152 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:21.152 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2025-12-06 20:19:21.154 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:21.154 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:21.154 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2025-12-06 20:19:21.427 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:22.427 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:23.427 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:24.426 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:24.662 +00:00] [ERR] Error processing request. URL "POST" "/Sessions/Playing/Progress".
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at Jellyfin.Api.Controllers.PlaystateController.ReportPlaybackProgress(PlaybackProgressInfo playbackProgressInfo)
   at lambda_method14545(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2025-12-06 20:19:25.427 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:26.385 +00:00] [INF] Deleting partial stream file(s) "/var/cache/jellyfin/transcodes/72dc7dfcc03e095403c83112f4a04407.m3u8"
[2025-12-06 20:19:26.416 +00:00] [INF] WS "10.1.20.5" closed
[2025-12-06 20:19:26.427 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:27.427 +00:00] [ERR] Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
[2025-12-06 20:19:27.939 +00:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.11.4" playing "Planet.Earth.III.S01E01.Coasts". Stopped at "107032" ms
[2025-12-06 20:19:27.942 +00:00] [ERR] Error in event handler
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Jellyfin.Data.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint.SessionManager_PlaybackStop(Object sender, PlaybackStopEventArgs e)
   at MediaBrowser.Common.Events.EventHelper.<>c__DisplayClass1_0`1.<QueueEventIfNotNull>b__0()
[2025-12-06 20:19:33.924 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:33.924 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:33.924 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:33.924 +00:00] [INF] "CustomAuthentication" was not authenticated. Failure message: "Invalid token."
[2025-12-06 20:19:33.924 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
[2025-12-06 20:19:33.924 +00:00] [INF] AuthenticationScheme: "CustomAuthentication" was challenged.
```

### FFmpeg logs

```shell

```

**Comment by Ondjultomte** [comment]
<img width="1786" height="952" alt="Image" src="https://github.com/user-attachments/assets/2649658e-79d7-4fc5-882d-efe27b57eb63" />

**Comment by Ondjultomte** [comment]
<img width="1786" height="952" alt="Image" src="https://github.com/user-attachments/assets/afa909a2-10c0-4015-8e0b-52034e40be46" />

**Comment by Ondjultomte** [comment]
This network request is a GET request to https://jellyfin.jelly.com/Users/2100e33cea184d54930c5cbf562a502c/Items/Resume. Its purpose is to retrieve a list of up to 12 video items that the user "2100e33cea184d54930c5cbf562a502c" has partially watched (Resume). The request specifies various fields to include (like PrimaryImageAspectRatio), image types to enable (Primary, Backdrop, Thumb), and filters for Video media types, while also explicitly disabling the total record count (EnableTotalRecordCount=false) to potentially optimize the server response. The Recursive=true parameter suggests it's searching within a hierarchical structure, possibly across libraries or folders. The 200 OK status indicates that the request was successfully processed by the server, and a response containing an array of Items (video content) was returned.

The primary reason this network request is taking so long is evident in the timing breakdown:

Waiting for server response (duration): 39.9 s: This is the most significant bottleneck. It indicates that the client sent the request to the server, and the server took approximately 39.9 seconds to process it and start sending back the first byte of the response. This duration accounts for almost the entire request time.
Potential Causes:
Server-side processing: The Jellyfin server is likely performing a complex database query, fetching metadata, or processing image-related tasks (like generating blur hashes) for the requested Resume items, which is taking a long time.
Resource contention: The server might be under heavy load, or its resources (CPU, memory, disk I/O) are constrained, causing delays in processing this request.
Database performance: If the underlying database queries are not optimized, retrieving the user's resume items and their associated details (including image tags and blur hashes) could be slow.
External dependencies: The server might be waiting on other internal or external services (e.g., transcoding services, external metadata providers) to complete before compiling the full response.
Other timings:
Queueing (duration): 0.8 ms, Connection start (stalled) (duration): 0.4 ms, Request sent (duration): 0.6 ms, and Content download (duration): 14 ms are all negligible compared to the server response time. This confirms that network latency and client-side processing are not the primary issues.
Conclusion for a Software Engineer:

The critical area for optimization is on the server side (jellyfin.jelly.com). You should investigate the Jellyfin server's logs, database performance, and resource utilization during the execution of this specific /Users/{userId}/Items/Resume endpoint. Profiling the server-side code handling this request would be beneficial to pinpoint the exact operations causing the 39.9-second delay.

**Comment by Ondjultomte** [comment]
<img width="464" height="126" alt="Image" src="https://github.com/user-attachments/assets/fb7c61cf-66bc-4481-bc8a-81a43de9a004" />

**Comment by Taegost** [comment]
What version were you on previously? I ask because I saw something similar when I upgraded from 10.10.7 to 10.11.1-3 (I tried all 3 previous updates).
I eventually had to downgrade back to 10.10.7 because only 3 out of my 7 libraries would even load because the server queries were taking so long.

**Comment by luigi311** [comment]
Are you using the Playback Reporting plugin? If so can you try removing it and see if it improves the situation for you?

**Comment by ojm2015** [comment]
I'm experiencing the exact same issue with the slowdown, my server since upgrading to 10.11.3 and above has been considerably slower than on 10.11.2, I've had to downgrade to 10.11.2 to have my server working fast again, while requiring Android version 2.6.2 to have the admin panel working for the android application. Notably, the slowdowns happened for the main page and shows which had lots of folders with files in them.

**Comment by Taegost** [comment]
> Are you using the Playback Reporting plugin? If so can you try removing it and see if it improves the situation for you?

I can confirm that I am not using that plugin, nor was I using it when I had the same issue as the OP

**Comment by Taegost** [comment]
> I'm experiencing the exact same issue with the slowdown, my server since upgrading to 10.11.3 and above has been considerably slower than on 10.11.2, I've had to downgrade to 10.11.2 to have my server working fast again, while requiring Android version 2.6.2 to have the admin panel working for the android application. Notably, the slowdowns happened for the main page and shows which had lots of folders with files in them.

That is what I experienced as well, except it was happening even in 10.11.1 and 10.11.2.

**Comment by vortex91** [comment]
I had to delete entire db and restart from scratch after upgrading from 10.10.x to 10.11.x   AFter which it performed better then on 10.10.x   Also I did notice errors in my log and  I changed SQL handling in database.xml to optomistic

<?xml version="1.0" encoding="utf-8"?>
<DatabaseConfigurationOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <DatabaseType>Jellyfin-SQLite</DatabaseType>
  <LockingBehavior>Optimistic</LockingBehavior>
</DatabaseConfigurationOptions>

now my pages load faster then when I was on 10.7

**Comment by Ondjultomte** [comment]
> What version were you on previously? I ask because I saw something similar when I upgraded from 10.10.7 to 10.11.1-3 (I tried all 3 previous updates). I eventually had to downgrade back to 10.10.7 because only 3 out of my 7 libraries would even load because the server queries were taking so long.

Came from 10.10.7

**Comment by Ondjultomte** [comment]
> Are you using the Playback Reporting plugin? If so can you try removing it and see if it improves the situation for you?

preior to upgrade I tried to delete all plugins that I could, I hade the reporting plugin installed before I removed it.

**Comment by Ondjultomte** [comment]
Seems that a reinstall and start from scratch is the way to go.

**Comment by DwayneGodden** [comment]
Is there a way to export the user's and password from the DB then do a reinstall and import them back?

I have a lot of users and don't want to have stuff around with that mess.
I'm running on 10.11.4

I know there was some scripts for the older version but don't know if they work for the 10.11.x

**Comment by braminsign** [comment]
> Is there a way to export the user's and password from the DB then do a reinstall and import them back?
> 
> I have a lot of users and don't want to have stuff around with that mess. I'm running on 10.11.4
> 
> I know there was some scripts for the older version but don't know if they work for the 10.11.x

Backup jellyfin.db and replace this file again?

**Comment by DwayneGodden** [comment]
> > Is there a way to export the user's and password from the DB then do a reinstall and import them back?
> > I have a lot of users and don't want to have stuff around with that mess. I'm running on 10.11.4
> > I know there was some scripts for the older version but don't know if they work for the 10.11.x
> 
> Backup jellyfin.db and replace this file again?

That will not work as the idea of a fresh install is to have a clean DB. 

Then just push the user logins devices and passwords back.

**Comment by Ondjultomte** [comment]
How do we debug this issue on the serverside?

**Comment by thulle** [comment]
Works fine for a while after restart here, then hours later I get the 1min+ loading times:

<img width="987" height="144" alt="Image" src="https://github.com/user-attachments/assets/77ada100-4aea-4a54-924f-ae3aaa1ce7e2" />

But in my case the log starts getting spammed by database is locked messages:

```
[2025-12-14 20:59:33.224 +01:00] [ERR] Error refreshing owned items for "123.mkv"
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked: BaseItemImageInfos'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.<>c.<NonQueryResult>b__31_0(DbContext _, ValueTuple`3 state)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.NonQueryResult(RelationalQueryContext relationalQueryContext, RelationalCommandResolver relationalCommandResolver, Type contextTy
pe, CommandSource commandSource, Boolean threadSafetyChecksEnabled)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteCore[TResult](Expression query, Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Jellyfin.Server.Implementations.Item.BaseItemRepository.SaveImages(BaseItem item)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
```

```
[2025-12-14 20:59:33.939 +01:00] [ERR] Failed executing DbCommand ("30,026"ms) [Parameters=["@__item_Id_0='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""DELETE FROM \"BaseItemImageInfos\" AS \"b\"
WHERE \"b\".\"ItemId\" = @__item_Id_0"
[2025-12-14 20:59:33.939 +01:00] [ERR] Failed executing DbCommand ("30,023"ms) [Parameters=["@__item_Id_0='?' (DbType = Guid)"], CommandType='Text', CommandTimeout='30']"
""DELETE FROM \"BaseItemImageInfos\" AS \"b\"
WHERE \"b\".\"ItemId\" = @__item_Id_0"
[2025-12-14 20:59:33.939 +01:00] [ERR] An exception occurred while executing an 'ExecuteDelete' operation for context type '"Jellyfin.Database.Implementations.JellyfinDbContext"'."
""Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.<>c.<NonQueryResult>b__31_0(DbContext _, ValueTuple`3 state)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.NonQueryResult(RelationalQueryContext relationalQueryContext, RelationalCommandResolver relationalCommandResolver, Type contextType, CommandSource commandSource, Boolean threadSafetyChecksEnabled)"
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database table is locked'.
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.<>c.<NonQueryResult>b__31_0(DbContext _, ValueTuple`3 state)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.NonQueryResult(RelationalQueryContext relationalQueryContext, RelationalCommandResolver relationalCommandResolver, Type contextType, CommandSource commandSource, Boolean threadSafetyChecksEnabled)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteCore[TResult](Expression query, Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Jellyfin.Server.Implementations.Item.BaseItemRepository.SaveImages(BaseItem item)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
```

I'll try to check what seems to be up with the sqlite database when there's less risk of the users running amok.

**Comment by luigi311** [comment]
Can you check to see after if you see anything related to db optimizing? In the logs it should show up as something like

[2025-12-08 18:15:22.473 -05:00] [INF] [25] Jellyfin.Database.Providers.Sqlite.SqliteDatabaseProvider: jellyfin.db optimized successfully!
[2025-12-08 18:15:22.473 -05:00] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Optimize database" Completed after 1 minute(s) and 55 seconds

**Comment by Smeagolworms4** [comment]
I had the same problem. Before, I could load all 300 movies at once without pagination.

But now I have to paginate every 100 items. And the response takes 30 seconds. Before, it took less than 5 seconds for all 300.

Fresh installation, same problem after re-importing my media

**Comment by Ondjultomte** [comment]
> I had the same problem. Before, I could load all 300 movies at once without pagination.
> 
> But now I have to paginate every 100 items. And the response takes 30 seconds. Before, it took less than 5 seconds for all 300.
> 
> Fresh installation, same problem after re-importing my media

Hm, even with fresh install? thats is bad.

**Comment by mdedonno1337** [comment]
Same issue here with 10.11.5, but it's better than 10.11.4. I suspect a join sql query that may be unnecessary (in the changelog for 10.11.5, apparently, some sql have been redone, I dont know).

**Comment by r0d0dendr0n** [comment]
I'm also experiencing low performance on 10.11.5. Installing this plugin may help, according to it's author: https://github.com/pelluch/jellyfin-plugin-disable-user-data . Also there's a reddit thread that suggests disabling "recently added" sections from the main screen will help.

**Comment by thulle** [comment]
@luigi311 db optimizing completes in 5-11 seconds and didn't coincide with the log errors. Checking other issues I saw that some were having trouble with ZFS, and while my setup is on ext4 the layer below it is a ZFS zvol. So I thought that it still might be some fsync-related issue and attempted some workarounds suggested there, namely lowering parallel library scan tasks limit and changing database LockingBehaviour to Optimistic. 

With Optimistic locking I could see 1,2 and occasionally 3 retries on database updates, but no errors in the logs. UI responsiveness remained bad though.
With scan tasks at 2, and optimistic locking, the amount of retries dropped and UI became pretty responsive, but at certain points during the scan it could still be multiple seconds worse than usual on some requests.
Here I assumed that since the VM has 64 cores the amount of spawned scan tasks manages to slam the database way harder after the code updates to the database handling, and combined with the file data probably cached in RAM it might stress the databse harder than most setups. I don't remember seeing the 1000%+ CPU usage of jellyfin during scans earlier, but haven't looked it up.
Reverting database locking behaviour to the default NoLock and leaving scan tasks at 2 left me with no errors in log, performant UI and faster scan times than with Optimistic locking.
I haven't had the time to test it out that much, but so far this seems to've solved the issue for me.

**Comment by braminsign** [comment]
> I'm also experiencing low performance on 10.11.5. Installing this plugin may help, according to it's author: https://github.com/pelluch/jellyfin-plugin-disable-user-data . Also there's a reddit thread that suggests disabling "recently added" sections from the main screen will help.

Thanks, but to be honest, those are core functionalities I use on a daily basis. Disabling them feels like a workaround that misses the point.

I’ve managed to tackle the performance issues by implementing caching within my Nginx reverse proxy instead. This dropped my loading times from a painful 16 seconds down to just 3 seconds. It’s a much better compromise for me, as it keeps the features intact while making the UI actually usable again.

**Comment by damomato** [comment]
Can anyone confirm if a fresh install to the latest version doesn't cause this issue? With all the database problems I'll likely just do that instead of updating as I only have a few users I can recreate.

**Comment by Smeagolworms4** [comment]
No. A fresh installation only works at the beginning.

**Comment by damomato** [comment]
Ok thanks. I'll stick to v 10.10 for now then

**Comment by Ondjultomte** [comment]
I doubt its a zfs issue(or that user could have that also) Im using 128GB
arc and optane för slog on a 99% idle homeserver., nvme drives on the zpool
for the JF container. so both sync writes and async are fast!

**Comment by a413107719** [comment]
> I'm also experiencing low performance on 10.11.5. Installing this plugin may help, according to it's author: https://github.com/pelluch/jellyfin-plugin-disable-user-data . Also there's a reddit thread that suggests disabling "recently added" sections from the main screen will help.

Thanks.The slow loading problem has been resolved since installing this plugin.

**Comment by Ondjultomte** [comment]
> > I'm also experiencing low performance on 10.11.5. Installing this plugin may help, according to it's author: https://github.com/pelluch/jellyfin-plugin-disable-user-data . Also there's a reddit thread that suggests disabling "recently added" sections from the main screen will help.
> 
> Thanks.The slow loading problem has been resolved since installing this plugin.

Could there be a fix for the issue derived from this plugin?I tried this plugin didnt solve the issue. It could have reduced the delay though.

<img width="1148" height="108" alt="Image" src="https://github.com/user-attachments/assets/d35d2b8f-c50d-4f48-8d32-a99fd2509469" />

still lots of penging 30s plus items


<img width="1136" height="463" alt="Image" src="https://github.com/user-attachments/assets/68347f1b-7f1e-4c6f-b691-ffa763a80480" />

**Comment by rpm5099** [comment]
I am also having the same problem.  I deleted the entire db and started over, which took a lot of time, and if anything it's much slower.  It's not really usable at this point, I can't identify the shows or navigate the gui because the gui just hangs.  It's pretty much been like this for several years on every browser/app/platform I have used it on.  I have analyzed CPU usage, disk I/O and GPU extensively and I'm not seeing any bottlenecks anywhere.  I'm not sure what the problem is but I can't use it the way it is now.  I've eliminated all possible variables I can think of.  I am more than happy to provide any debug information or chrome dev panel performance logs, but I dont think they are going to look much different that what is already here.  I dont know if it's related but after deleting everything and starting over it's been over 3 weeks and the scheduled jobs for generating trickplay images and extracting chapter images are nowhere near completing.  I have hardware acceleration enabled and a massively overpowered server with multiple gpu's, 60 cpu cores and 128GB of memory dedicated to it.

@braminsign I agree that disabling features like this seems tantamount to admitting failure.  

I'm willing to help and provide troubleshooting data.

**Comment by rpm5099** [comment]
> I am also having the same problem. I deleted the entire db and started over, which took a lot of time, and if anything it's much slower. It's not really usable at this point, I can't identify the shows or navigate the gui because the gui just hangs. It's pretty much been like this for several years on every browser/app/platform I have used it on. I have analyzed CPU usage, disk I/O and GPU extensively and I'm not seeing any bottlenecks anywhere. I'm not sure what the problem is but I can't use it the way it is now. I've eliminated all possible variables I can think of. I am more than happy to provide any debug information or chrome dev panel performance logs, but I dont think they are going to look much different that what is already here. I dont know if it's related but after deleting everything and starting over it's been over 3 weeks and the scheduled jobs for generating trickplay images and extracting chapter images are nowhere near completing. I have hardware acceleration enabled and a massively overpowered server with multiple gpu's, 60 cpu cores and 128GB of memory dedicated to it.
> 
> [@braminsign](https://github.com/braminsign) I agree that disabling features like this seems tantamount to admitting failure.
> 
> I'm willing to help and provide troubleshooting data.

I did try disabling all updates, and installing the plugin that disables user data.  Certain navigation functions in the gui take less time, but it's still hanging on something.  Not sure what.

**Comment by DwayneGodden** [comment]
> > I am also having the same problem. I deleted the entire db and started over, which took a lot of time, and if anything it's much slower. It's not really usable at this point, I can't identify the shows or navigate the gui because the gui just hangs. It's pretty much been like this for several years on every browser/app/platform I have used it on. I have analyzed CPU usage, disk I/O and GPU extensively and I'm not seeing any bottlenecks anywhere. I'm not sure what the problem is but I can't use it the way it is now. I've eliminated all possible variables I can think of. I am more than happy to provide any debug information or chrome dev panel performance logs, but I dont think they are going to look much different that what is already here. I dont know if it's related but after deleting everything and starting over it's been over 3 weeks and the scheduled jobs for generating trickplay images and extracting chapter images are nowhere near completing. I have hardware acceleration enabled and a massively overpowered server with multiple gpu's, 60 cpu cores and 128GB of memory dedicated to it.
> > [@braminsign](https://github.com/braminsign) I agree that disabling features like this seems tantamount to admitting failure.
> > I'm willing to help and provide troubleshooting data.
> 
> I did try disabling all updates, and installing the plugin that disables user data. Certain navigation functions in the gui take less time, but it's still hanging on something. Not sure what.

I upgraded to the 10.12.0 (the unstable weekly) and it's much better.

I do have TVDB and reporting plugins removed.

Disable collections and trick play

**Comment by rpm5099** [comment]
@DwayneGoddem - obviously since I just saw that I'm going to have to try it right now.  Do you have any logs or information that links collections and trick play to the issues, or did you try disabling them and that made a difference?

edit: unfortunately made no difference, still hanging forever pulling up shows.

**Comment by sjorge** [comment]
I finally upgraded to 10.11.5 from 10.10.7 after holding off for a while for the fear of performance troubles as I had them in the past.

But I'm not seeing much impact, although my DB is pretty small, 3k songs, 20k epsiodes, 800 movies. I did configure sqlite cacheSize back on 10.10.7 which based on PR's is still supported on 10.11.x:

```
# /etc/systemd/system/jellyfin.service.d/40-cache.conf
[Service]
# 1024 * 1024 * 1024 / 4096 -- 1G
Environment="JELLYFIN_sqlite__cacheSize=262144"
```

Not sure it will help much but it's worth a shot I guess, my db is around 800M at the moment so it's entirely allowed to be cached.

**Comment by r0d0dendr0n** [comment]
> I finally upgraded to 10.11.5 from 10.10.7 after holding off for a while for the fear of performance troubles as I had them in the past.
> 
> But I'm not seeing much impact, although my DB is pretty small, 3k songs, 20k epsiodes, 800 movies. I did configure sqlite cacheSize back on 10.10.7 which based on PR's is still supported on 10.11.x:
> 
> ```
> # /etc/systemd/system/jellyfin.service.d/40-cache.conf
> [Service]
> # 1024 * 1024 * 1024 / 4096 -- 1G
> Environment="JELLYFIN_sqlite__cacheSize=262144"
> ```
> 
> Not sure it will help much but it's worth a shot I guess, my db is around 800M at the moment so it's entirely allowed to be cached.

In case casual Sunday home admins wonder how to do it in docker:
Edit docker-compose.yml:
```
environment:
- JELLYFIN_sqlite__cacheSize=262144
```
(remember yaml syntax - indentation matters)

and then recreate the container:
`docker-compose down; docker-compose up -d`

**Comment by a413107719** [comment]
> > I finally upgraded to 10.11.5 from 10.10.7 after holding off for a while for the fear of performance troubles as I had them in the past.
> > But I'm not seeing much impact, although my DB is pretty small, 3k songs, 20k epsiodes, 800 movies. I did configure sqlite cacheSize back on 10.10.7 which based on PR's is still supported on 10.11.x:
> > ```
> > # /etc/systemd/system/jellyfin.service.d/40-cache.conf
> > [Service]
> > # 1024 * 1024 * 1024 / 4096 -- 1G
> > Environment="JELLYFIN_sqlite__cacheSize=262144"
> > ```
> > 
> > 
> >     
> >   
> > Not sure it will help much but it's worth a shot I guess, my db is around 800M at the moment so it's entirely allowed to be cached.
> 
> In case casual Sunday home admins wonder how to do it in docker: Edit docker-compose.yml:
> 
> ```
> environment:
> - JELLYFIN_sqlite__cacheSize=262144
> ```
> 
> (remember yaml syntax - indentation matters)
> 
> and then recreate the container: `docker-compose down; docker-compose up -d`

How to configure 'JELLYFIN_sqlite__cacheSize' on windows ?

**Comment by rpm5099** [comment]
I am not seeing this documented or referenced anywhere: `JELLYFIN_sqlite__cacheSize` - this looks like AI made up nonsense.  Anyone have a source for it?

**Comment by sjorge** [comment]
> I am not seeing this documented or referenced anywhere: `JELLYFIN_sqlite__cacheSize` - this looks like AI made up nonsense. Anyone have a source for it?

https://github.com/jellyfin/jellyfin/pull/9666

**Comment by DwayneGodden** [comment]
> > > I finally upgraded to 10.11.5 from 10.10.7 after holding off for a while for the fear of performance troubles as I had them in the past.
> > > But I'm not seeing much impact, although my DB is pretty small, 3k songs, 20k epsiodes, 800 movies. I did configure sqlite cacheSize back on 10.10.7 which based on PR's is still supported on 10.11.x:
> > > ```
> > > # /etc/systemd/system/jellyfin.service.d/40-cache.conf
> > > [Service]
> > > # 1024 * 1024 * 1024 / 4096 -- 1G
> > > Environment="JELLYFIN_sqlite__cacheSize=262144"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Not sure it will help much but it's worth a shot I guess, my db is around 800M at the moment so it's entirely allowed to be cached.
> > 
> > 
> > In case casual Sunday home admins wonder how to do it in docker: Edit docker-compose.yml:
> > ```
> > environment:
> > - JELLYFIN_sqlite__cacheSize=262144
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (remember yaml syntax - indentation matters)
> > and then recreate the container: `docker-compose down; docker-compose up -d`
> 
> How to configure 'JELLYFIN_sqlite__cacheSize' on windows ?

Windows "Advanced System Settings" 
Then environment variables 

I have just set this pening a a restart to see if it will do anything.

This would have been better if it was in the system.xml or something but this is the way.

**Comment by sjorge** [comment]
> This would have been better if it was in the system.xml or something but this is the way.

I can’t promise it will, but after holding off so long to wait out the massive regression everyone kept reporting I found the impact in my setup to be negligible. The any thing that came to mind as possibly why was this tweak I had.

And I’m in the worst situation with media on NFS and db/metadata in zfs.

**Comment by DwayneGodden** [comment]
> > This would have been better if it was in the system.xml or something but this is the way.
> 
> I can’t promise it will, but after holding off so long to wait out the massive regression everyone kept reporting I found the impact in my setup to be negligible. The any thing that came to mind as possibly why was this tweak I had.
> 
> And I’m in the worst situation with media on NFS and db/metadata in zfs.

I'm all on windows but have over 12TB of data and that is also a issue. over 40,000 TV EP's is not loving life in 10.11.x+ 
I'm running the unstable version but lots of addons don't work like Jellyseerr Bridge etc. so might go back.

**Comment by rpm5099** [comment]
> > > This would have been better if it was in the system.xml or something but this is the way.
> > 
> > 
> > I can’t promise it will, but after holding off so long to wait out the massive regression everyone kept reporting I found the impact in my setup to be negligible. The any thing that came to mind as possibly why was this tweak I had.
> > And I’m in the worst situation with media on NFS and db/metadata in zfs.
> 
> I'm all on windows but have over 12TB of data and that is also a issue. over 40,000 TV EP's is not loving life in 10.11.x+ I'm running the unstable version but lots of addons don't work like Jellyseerr Bridge etc. so might go back.

I'm on Ubuntu in docker, with media on NFS and db/meta on local nvme.  I think my library is around the same size yours is.  I switched back from the nightly because I saw no performance benefit, and like you said most of the addons don't work and Kodi won't connect to it (authentication fails).  I'm pretty sure that 10.12 is still using sqlite if I'm not mistaken - I don't think most of these issues are going to be resolved until the switch to more performant PGSql happens.  Hopefully that is not too far off.  

I tried setting the environment variable `JELLYFIN_sqlite__cacheSize=262144`, but I don't know if that works on *nix or how to verify it's working.

**Comment by DwayneGodden** [comment]
> > > > This would have been better if it was in the system.xml or something but this is the way.
> > > 
> > > 
> > > I can’t promise it will, but after holding off so long to wait out the massive regression everyone kept reporting I found the impact in my setup to be negligible. The any thing that came to mind as possibly why was this tweak I had.
> > > And I’m in the worst situation with media on NFS and db/metadata in zfs.
> > 
> > 
> > I'm all on windows but have over 12TB of data and that is also a issue. over 40,000 TV EP's is not loving life in 10.11.x+ I'm running the unstable version but lots of addons don't work like Jellyseerr Bridge etc. so might go back.
> 
> I'm on Ubuntu in docker, with media on NFS and db/meta on local nvme. I think my library is around the same size yours is. I switched back from the nightly because I saw no performance benefit, and like you said most of the addons don't work and Kodi won't connect to it (authentication fails). I'm pretty sure that 10.12 is still using sqlite if I'm not mistaken - I don't think most of these issues are going to be resolved until the switch to more performant PGSql happens. Hopefully that is not too far off.
> 
> I tried setting the environment variable `JELLYFIN_sqlite__cacheSize=262144`, but I don't know if that works on *nix or how to verify it's working.

Oh the auth issue can be fixed by enabling classic auth in the system.xml i had to do they to get jellyseerr to work.
The unstable is the current release with all newest untested code updates.

**Comment by rpm5099** [comment]
> Oh the auth issue can be fixed by enabling classic auth in the system.xml i had to do they to get jellyseerr to work. The unstable is the current release with all newest untested code updates.


If you had not happened to mention this I don't know how much time I would have wasted.  FYI to others, you must make this change to system.xml after using 10.12 *even if you revert back to 10.11* if you use anything that uses the legacy auth headers:
`<EnableLegacyAuthorization>true</EnableLegacyAuthorization>`

Otherwise jellyseerr and kodi - and probably others - cannot login.  There hasn't been time for the other projects to change over to the more standardized authorization headers yet.

**Comment by DwayneGodden** [comment]
> > Oh the auth issue can be fixed by enabling classic auth in the system.xml i had to do they to get jellyseerr to work. The unstable is the current release with all newest untested code updates.
> 
> If you had not happened to mention this I don't know how much time I would have wasted. FYI to others, you must make this change to system.xml after using 10.12 _even if you revert back to 10.11_ if you use anything that uses the legacy auth headers: `<EnableLegacyAuthorization>true</EnableLegacyAuthorization>`
> 
> Otherwise jellyseerr and kodi - and probably others - cannot login. There hasn't been time for the other projects to change over to the more standardized authorization headers yet.

Yes that is the one sorry I was on my phone and could not think of the exact wording for the option. Glad you found it and it fixed the issue. It took me a while to find it so glad it helped you.

**Comment by Smeagolworms4** [comment]
/Users/3b9a1fe90f274f47b6276dac3a1fb169/Items?StartIndex=0&Fields=PrimaryImageAspectRatio%2CSortName%2CPath%2CChildCount%2CMediaSourceCount%2CPrimaryImageAspectRatio&ImageTypeLimit=1&ParentId=db4c1708cbb5dd1676284a40f2950aba&SortBy=SortName&SortOrder=Ascending

40s even with JELLYFIN_sqlite__cacheSize=262144

**Comment by rpm5099** [comment]
Ok, I can report the following:

- the primary problem was outdated jellysearch, which is no longer maintained. My assumption is that it was hammering the api, but there's nothing at all in the log output. It might be a good idea to ensure whatever it was doing to cause the problem is somehow captured in the logs. I'll look more into it when I have time.

- changed sqlite database to WAL, which is the only non connection specific setting that does not get overridden. Allowing a pass through setting from database.xml to change connection specific settings was considered but not implemented (don't have the pr now, on my phone). As a stopgap before pgsql transition this would allow more detailed sqlite db optimization and troubleshooting for those that would like to. I do not know the reasons for the limitations on sqlite db connection pass through parameters, maybe someone can fill in. 

Edit: quick addendum to this.  [Jellystat](https://github.com/CyferShepard/Jellystat), which runs in a separate container and was updated only 2 weeks ago causes the *jellyfin* GUI to hang at least with the latest nightly version of jellyfin.  Again, there is nothing in the log output to indicate an issue that I can see at debug level.  That project does not claim to be compatible with 10.12, but again log output indicating an issue would be helpful.  It's understandable if the API is not backwards compatible, but it shouldnt become unresponsive.

Edit2: Figured I should add the only thing that does show in the logs when the gui is hanging/unresponsive:

```
jellyfin    | 2026-01-02T22:27:08.958039098Z [17:27:08] [DBG] [10] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://jellyfin.[redacted]/Users/8d9ab5b22c324179ad7d3dda4876f901/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video to 10.0.0.1 in 0:00:00.8217373 with Status Code 200
jellyfin    | 2026-01-02T22:27:08.962344084Z [17:27:08] [DBG] [62] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://jellyfin.[redacted]/Users/8d9ab5b22c324179ad7d3dda4876f901/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=afd60c36d723db143b840c599ce53b5b to 10.0.0.1 in 0:00:00.8240012 with Status Code 200
jellyfin    | 2026-01-02T22:27:08.974720692Z [17:27:08] [DBG] [52] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://jellyfin.[redacted]/Users/8d9ab5b22c324179ad7d3dda4876f901/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=a6356ffb611a5a783ef43cae9f9ffd0a to 10.0.0.1 in 0:00:00.8370904 with Status Code 200
jellyfin    | 2026-01-02T22:27:08.975808743Z [17:27:08] [DBG] [67] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://jellyfin.[redacted]/Users/8d9ab5b22c324179ad7d3dda4876f901/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=8925c9ac4b541827e50b8dbc7f623a94 to 10.0.0.1 in 0:00:00.8370097 with Status Code 200
jellyfin    | 2026-01-02T22:27:08.976191698Z [17:27:08] [DBG] [47] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://jellyfin.[redacted]/Users/8d9ab5b22c324179ad7d3dda4876f901/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=20330483dddb1db0de57051d2da927cc to 10.0.0.1 in 0:00:00.8375767 with Status Code 200
jellyfin    | 2026-01-02T22:27:08.983897758Z [17:27:08] [DBG] [25] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://jellyfin.[redacted]/Users/8d9ab5b22c324179ad7d3dda4876f901/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=0ad7b208bdfa9823f6a770b5a19de17f to 10.0.0.1 in 0:00:00.8456233 with Status Code 200
jellyfin    | 2026-01-02T22:27:08.986193550Z [17:27:08] [DBG] [74] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://jellyfin.[redacted]/Users/8d9ab5b22c324179ad7d3dda4876f901/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=34f331a89ce405e2b877d68d5ee4d4a2 to 10.0.0.1 in 0:00:00.8466225 with Status Code 200
jellyfin    | 2026-01-02T22:27:08.996858207Z [17:27:08] [DBG] [23] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://jellyfin.[redacted]/Users/8d9ab5b22c324179ad7d3dda4876f901/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=b628989bf75884aec305905c2bb6b618 to 10.0.0.1 in 0:00:00.858463 with Status Code 200
jellyfin    | 2026-01-02T22:27:09.014282999Z [17:27:09] [DBG] [45] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://jellyfin.[redacted]/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CDateCreated%2CPath%2CMediaSourceCount&UserId=8d9ab5b22c324179ad7d3dda4876f901&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false&DisableFirstEpisode=false&NextUpDateCutoff=2025-01-02T22%3A27%3A09.898Z&EnableResumable=false&EnableRewatching=false to 10.0.0.1 in 0:00:00.8778914 with Status Code 200
jellyfin    | 2026-01-02T22:27:09.014455494Z [17:27:09] [DBG] [78] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://jellyfin.[redacted]/Users/8d9ab5b22c324179ad7d3dda4876f901/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805 to 10.0.0.1 in 0:00:00.876052 with Status Code 200
jellyfin    | 2026-01-02T22:27:09.231313770Z [17:27:09] [DBG] [75] Jellyfin.Api.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://jellyfin.[redacted]/Users/8d9ab5b22c324179ad7d3dda4876f901/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=a656b907eb3a73532e40e44b968d0225 to 10.0.0.1 in 0:00:01.0918035 with Status Code 200
```

**Comment by r0d0dendr0n** [comment]
Are the above changes included in 10.11.6? Tbh I didn't notice a significant speedup after upgrade.

**Comment by ojm2015** [comment]
+Bump, is this still occuring in the newest release, I'm still on 10.11.2, waiting until this is completely fixed until I upgrade.

**Comment by a413107719** [comment]
> +Bump, is this still occuring in the newest release, I'm still on 10.11.2, waiting until this is completely fixed until I upgrade.



> Are the above changes included in 10.11.6? Tbh I didn't notice a significant speedup after upgrade.

unresolved
