### ISSUE TITLE
Restore from backup - incomplete image restoration

### ISSUE THREAD

**Issue by BotBlake** [jellyfin/jellyfin#15829]
### Description of the bug

Restoring a Jellyfin instance using “Restore from Backup” (on a brand new install) results in an incomplete restore:

User accounts are restored successfully, but user profile pictures are not. (They are included in the backup `zip` though!)

Additionally, metadata restoration appears to work just fine, however artwork restoration seems to be inconsistent. Some pictures are restored, while others are missing. I encountered this most notably with my audiobooks library, where all artwork (posters/covers) was manually added via the Jellyfin UI - There, NO images have been restored, only blurry previews. On my movies library SOME movies had artwork but most did not.

After restoring from a backup:
- MOST restored images appeared blurry, as if only low-resolution previews were available and the full images were never loaded (SOME did though).
- The logs were filled with errors indicating that poster/image files could not be found.
- Running a “Scan for new and updated metadata” caused the blurry image previews to disappear entirely, leaving no artwork.

This suggests that some image data may have been present initially (since correct image previews were shown).

I have Verified that Jellyfin has proper read/write permissions to all relevant directories and confirmed that Docker internal paths were kept identical between the original instance and the restored one.

### Reproduction steps

Jellyfin Instance A:
1. Create a backup via the "Create Backup" function - With all options checked
2. Copy `backup.zip` to Jellyfin Instance B

Jellyfin Instance B:
1. Install brand new instance. Give it access to the same media, brand new config/cache/transcoding folders.
2. Complete Setup wizzard
3. Copy `backup.zip` from Instance A into `/config/data/backups` (of instance B)
4. Go into the backup-ui of instance B and restore the backup
5. Observer missing images everywhere

### What is the current _bug_ behavior?

When restoring from backup (on a new instance) a lot of images are missing. Even when they are clearly included in the `backup.zip` file.
This involves User Profile Pictures, but also a lot of Metadata across the libraries.

### What is the expected _correct_ behavior?

Images that are included in the backup file should be restored properly.

### Jellyfin Server version

10.11.5

### Specify the build version

10.11.5

### Environment

```markdown
- OS: Debian 13 (Trixie)/ TrueNAS Scale
- Virtualization: Docker
- Hardware Acceleration: yes
- CPU Model: AMD Ryzen 7 5700G
- GPU Model: Intel ARC A380
- Plugins: on old instance some (i dont remember) on restored instance none
- Reverse Proxy: irrelevant
- Base URL: no
- Networking: Bridge
- Jellyfin Data Storage & Filesystem: ZFS/ ext4
- Media Storage & Filesystem: ZFS
- External Integrations:
```

### Jellyfin logs

```shell
Not relevant, simply "FileNotFound" exceptions for some of the missing artwork.
The restore process went smoothly as well without and thrown errors in the logs.
```

### FFmpeg logs

```shell

```

**Comment by AndreHatt-git** [comment]
Isn't this mostly out of scope of current backup implementation?
As it states here: https://jellyfin.org/posts/jellyfin-release-10.11.0/

> The backup and restore system can only restore systems on which the backup was originally made, so this is not a tool to migrate from other OS's or 3rd party containers.

**Comment by nielsvanvelzen** [comment]
I would argue docker to docker with the same image (Jellyfin/Jellyfin) and internal paths is the same system

**Comment by dbolger** [comment]
Regardless of whether or not this is in scope, is there a task we can use to regenerate these?

**Comment by BotBlake** [comment]
regenerate what?
You mean profile pictures? Those SHOULD be included in the restore from backup-feature.
They ARE included in the backup files at least.

**Comment by dbolger** [comment]
> regenerate what? You mean profile pictures? Those SHOULD be included in the restore from backup-feature. They ARE included in the backup files at least.

Regenerate metadata. And I've found it, you just have to go through and click refresh metadata data for each library. Though for some reason that seems to only work sometimes.

I'm not suggesting this as a end-all solution, obviously. This is a workaround until someone decides to address the root cause.

**Comment by dbolger** [comment]
Okay, the solution I posed isn't working for entire libraries. Scanning the entire library and requesting new metadata unfortunately isn't getting anything new. I have to go to individual series or episodes to get thumbnails.

Is there any traction or mitigation to this? Each time I load a page, it's filling my logs with these:
```
jellyfin  | [00:47:11] [ERR] [127] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/metadata/library/68/682aaa66b5ecde47cbf19aebf2653e4a/poster.jpg'. URL GET /Items/682aaa66b5ecde47cbf19aebf2653e4a/Images/Primary.

```

Not only that, but most of my experience of getting automatic metadata is now gone. Is there a database I can purge these hanging metadata references that no longer exist?

**Comment by KarkaLT** [comment]
I'm experiencing exactly the same issue. All of the media posters and logos seem to be not restored. Also, chapter images and actor images. I'm creating a backup with all options checked (Database, Metadata, Subtitles, Trickplay) and restoring it on the same machine, so there should be no path problems.

**Comment by dbolger** [comment]
@nielsvanvelzen Any updates on when this might be fixed?

**Comment by JPVenson** [comment]
@BotBlake please check if the previous backuped files are at the same location the restored system throws the file not found errors

**Comment by dbolger** [comment]
also, not sure why my previous comment is “Hidden as abuse”

**Comment by Meru** [comment]
I have similar issues. Backup feature fails to restore metadata even if I tick the relevant checkbox. Files are not present in target place for metadata. And even if it would include them, the process fails to update paths to point to the new location. It still attempts to load metadata from whatever place it was before. Kinda makes the whole feature unusable. This is the main reason for so-called blurry images people are reporting.

**Comment by lightmon233** [comment]
This bug is still here, and after I pressed restore, my Jellyfin server is stuck with high CPU usage that just won't drop.

**Comment by lightmon233** [comment]
For example, under TrueNAS, when I click the restore button in Jellyfin, the process appears to extract the backup zip into /config/data/metadata. However, Jellyfin continues trying to read metadata from /config/metadata, leading to errors in the logs.

**Comment by JPVenson** [comment]
For everyone that has similar issues:

It does not help to say "Me too" we need detailed infos about your system, logs and actually errors from those logs otherwise we cannot do anything.

**Comment by dbolger** [comment]
> For everyone that has similar issues:
> 
> It does not help to say "Me too" we need detailed infos about your system, logs and actually errors from those logs otherwise we cannot do anything.

You could also just try to recreate it. The original reporter gave reproduction steps. If you aren’t able to recreate it, maybe then ask for additional context or logs. It sounds like you just need to attempt recreating it. The reporter gave you more than enough to go and chase after this issue.

**Comment by Salvoxia** [comment]
Me too 😉 
Similar finding to what @lightmon233 decsribes [here](https://github.com/jellyfin/jellyfin/issues/15829#issuecomment-4020895345).

So here's background info:
Using `jellyfin/jellyfin:10.11.16` in a Docker compose file:

```yaml
---
services:
  jellyfin:
    image: jellyfin/jellyfin:${IMAGE_VERSION} # #lscr.io/linuxserver/jellyfin:${IMAGE_VERSION}
    container_name: jellyfin_restoretest
    hostname: Jellyfin[TEST]
    healthcheck:
      test: curl -s --fail http://localhost/health | grep "Healthy" > /dev/null || exit 1
      interval: 60s
      timeout: 5s
      start_period: 90s
    volumes:
      - ${PROJECT_HOME}/jellyfin_restoretest/jellyfin:/config
      - ${PROJECT_HOME}/jellyfin_restoretest/cache:/cache
      - ${VIDEO_FOLDER}:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
```

I added a movie library and let it fetch metadata with all posters/thumbnails etc etc.
My `${PROJECT_HOME}/jellyfin_restoretest/jellyfin` folder looked like this
```
.
└── jellyfin
    ├── config
    ├── data
    │   ├── backups
    │   ├── playlists
    │   ├── ScheduledTasks
    │   ├── SQLiteBackups
    │   └── transcodes
    ├── log
    ├── metadata
    ├── plugins
    └── root
```

Then I created a backup using the Admin Web Interface, the `zip` file was placed in `${PROJECT_HOME}/jellyfin_restoretest/jellyfin/data/backups`.

I stopped the container, deleted everything except for the backups folder, restarted the container, performed inital setup and restored the backup from the Admin web inteface.
All users/libraries etc were restored, but no posters/thumbnails showed up. Logs full of errors like this:
```
[23:33:22] [ERR] [25] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/metadata/library/2d/2d253488e506e6a97635e51776c768e9/poster.jpg'. URL GET /Items/2d253488e506e6a97635e51776c768e9/Images/Primary.
[23:33:22] [ERR] [12] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/metadata/library/0d/0d74d52ae862c081993e877f83557be0/poster.jpg'. URL GET /Items/0d74d52ae862c081993e877f83557be0/Images/Primary.
[23:33:22] [ERR] [26] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/metadata/library/1e/1e4223a4f8cfbf23677b06040421cdc8/poster.jpg'. URL GET /Items/1e4223a4f8cfbf23677b06040421cdc8/Images/Primary.
[23:33:22] [ERR] [17] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/metadata/library/34/34ce3824049139632e027d649813ac55/poster.jpg'. URL GET /Items/34ce3824049139632e027d649813ac55/Images/Primary.
```

Upon closer inspection, it turns out that the complete `metadata` folder was restored to `${PROJECT_HOME}/jellyfin_restoretest/jellyfin/data/metadata` instead of  `${PROJECT_HOME}/jellyfin_restoretest/jellyfin/metadata`.
After moving that folder one level up all images are back.

So it seems the restore process simply misplaces the `metadata` folder.

Please let me know if you need any further clarifications.

**Comment by Salvoxia** [comment]
One more thing I noticed just now: 
Even after moving the `metadata` folder from (the container's perspective) `/config/data/metadata` to `/config/metata`, MOST of the images came back, but not all of them.

Logs now show the following errors:
```
[11:26:41] [WRN] [50] Emby.Server.Implementations.Library.LibraryManager: Image not found at /config/data/metadata/library/b1/b1ce4284a88c3b8b7bfa0655d5c5c073/poster.jpg |  
[11:26:41] [WRN] [50] Emby.Server.Implementations.Library.LibraryManager: Image not found at /config/data/metadata/library/21/21f89326aff5c2a5e1b3d9d0631b619a/poster.jpg |  
[11:26:41] [WRN] [50] Emby.Server.Implementations.Library.LibraryManager: Image not found at /config/data/metadata/library/b2/b2366d1e2153157b2230b56d8763ed14/poster.jpg |  
[11:26:41] [WRN] [50] Emby.Server.Implementations.Library.LibraryManager: Image not found at /config/data/metadata/library/65/650d31483800bf63437860aceb8f96a9/poster.jpg |  
[11:26:41] [WRN] [50] Emby.Server.Implementations.Library.LibraryManager: Image not found at /config/data/metadata/library/ff/ff33c25c83344298c9e9a0b0072f45c4/poster.jpg |  
[11:26:41] [WRN] [50] Emby.Server.Implementations.Library.LibraryManager: Image not found at /config/data/metadata/library/5a/5a43486692d547a0f79d68a550d6e140/poster.jpg
```

as opposed to 
```
[23:33:22] [ERR] [25] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/metadata/library/2d/2d253488e506e6a97635e51776c768e9/poster.jpg'. URL GET /Items/2d253488e506e6a97635e51776c768e9/Images/Primary.
[23:33:22] [ERR] [12] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/metadata/library/0d/0d74d52ae862c081993e877f83557be0/poster.jpg'. URL GET /Items/0d74d52ae862c081993e877f83557be0/Images/Primary.
[23:33:22] [ERR] [26] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/metadata/library/1e/1e4223a4f8cfbf23677b06040421cdc8/poster.jpg'. URL GET /Items/1e4223a4f8cfbf23677b06040421cdc8/Images/Primary.
[23:33:22] [ERR] [17] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request: Could not find file '/config/metadata/library/34/34ce3824049139632e027d649813ac55/poster.jpg'. URL GET /Items/34ce3824049139632e027d649813ac55/Images/Primary.
```
from before.

So it seems that Jellyfin is looking for some images in `/config/metdata`, for in `/config/data/metadata` for others.
Not sure of the metdata folder location was moved in a previous version and all images for assets that were added in a new version were stored in a different location so that the database now has differing paths depending on asset age or something..

**Comment by Meru** [comment]
> So it seems that Jellyfin is looking for some images in `/config/metdata`, for in `/config/data/metadata` for others.

Jellyfin has a setting that tells him where to look for metadata. So it can be wrong, but why would it look some metadata in one place and some in the other is unclear.

So far my experience with the feature:

- if I use commandline switches to apply backup to a brand new jellyfin install - it produces a totally broken result. Nothing works.
- if I initiate database in the new place first and then apply backup via web interface - it works but has the same metadata issues people are mentioning above.

What I think jellyfin should do during applying a backup that it currently doesn't do or attempts to do but has a bug:

- If applied to an uninitiated database - assume all paths should be in the same default spots they would be as if we just started jellyfin for the first time. Then update all metadata paths to point to new directories. (but this is too hard and unnecessary , read below!)
- if applied to initiated database - read the setting of the existing setup, take metadata path from it and put metadata where it says it should be.

As A side note. Using latest jellyfin I can successfully move database anywhere I want by simply replacing path strings in the database to the new ones. This was not always possible but right now it is. Given this, I see no reason to hardcode metadata paths at all! Just make them relative from now on so that jellyfin takes system path of the metadata folder and attaches is to the relative metadata path. And if it encounters full path - just use that (will keep backwards compatible with old databases). This would likely solve any possible backup issues or will help with it.

**Comment by theguymadmax** [comment]
Fixed by: #16425

**Comment by canepan** [comment]
This issue is still present in 10.11.11 (using offical Docker image), and the problem is in the DB.

Restoring a backup created by Jellyfin's built-in backup feature (10.11.11, backup engine 0.2.0) loses the UserId foreign key on ImageInfos rows. The archive itself contains the correct value; the restored database has NULL. Users'
profile images silently disappear after a restore (the API returns 404 for /Users/{id}/Images/Primary; the image file itself is still on disk and still referenced by Path).
I am running in Docker, and this proves the issue after a successfull restore:
```
sqlite3 data/jellyfin.db "SELECT Id, UserId, Path FROM ImageInfos;" → 1||/config/config/users/Nicola/profile.png — UserId is NULL
```

### Additional context
- Reproduced identically restoring to a MySQL database via a third-party provider plugin, so this is backend-independent restore logic, not a provider issue.
- In Users.json, ProfileImage is null on all users (expected, ReferenceHandler.IgnoreCycles), so the FK's only surviving copy is the one in ImageInfos.json — which the restore then apparently drops, possibly during EF relationship fixup
across the single tracked graph in BackupService.RestoreBackupAsync.
- Workaround: manually re-link after restore (UPDATE ImageInfos SET UserId = <user guid> WHERE Path LIKE '%/users/<name>/%').

i.e., in the DB (tested with the MySQL plugin):
```
SELECT Id, Username FROM jellyfin.Users;
```
take the `Id` column for the associated user, then:
```
UPDATE jellyfin.ImageInfos SET UserId = 'XXX' WHERE Id = 1;
```
XXX and 1 must match the user
