### ISSUE TITLE
Password Reset Fails

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#1797]
_Originally posted by @grafixeyehero in https://github.com/jellyfin/jellyfin/issues/1076#issuecomment-480103412_

>and another thing when entering the pin code dosent seem to rest the password

```
[02:32:50] [ERR] Error processing request
MediaBrowser.Common.Extensions.ResourceNotFoundException: No Users found with a password reset request matching pin E4-9B-D0-33
   at Emby.Server.Implementations.Library.DefaultPasswordResetProvider.RedeemPasswordResetPin(String pin) in C:\Users\admin\Documents\GitHub\Jellyfin\Emby.Server.Implementations\Library\DefaultPasswordResetProvider.cs:line 75
   at Emby.Server.Implementations.Library.UserManager.RedeemPasswordResetPin(String pin) in C:\Users\admin\Documents\GitHub\Jellyfin\Emby.Server.Implementations\Library\UserManager.cs:line 926
   at MediaBrowser.Api.UserService.Post(ForgotPasswordPin request) in C:\Users\admin\Documents\GitHub\Jellyfin\MediaBrowser.Api\UserService.cs:line 531
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in C:\Users\admin\Documents\GitHub\Jellyfin\Emby.Server.Implementations\Services\ServiceExec.cs:line 110
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in C:\Users\admin\Documents\GitHub\Jellyfin\Emby.Server.Implementations\Services\ServiceHandler.cs:line 95
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in C:\Users\admin\Documents\GitHub\Jellyfin\Emby.Server.Implementations\HttpServer\HttpListenerHost.cs:line 575
```

**Comment by anthonylavado** [comment]
The issue appears to be a missing Password Reset Provider in a user's `policy.xml` file.

If you add the following line to the bottom of a user's policy file, then restart Jellyfin, it will work:
```xml
<PasswordResetProviderId>Emby.Server.Implementations.Library.DefaultPasswordResetProvider</PasswordResetProviderId>
```

**Comment by anthonylavado** [comment]
Okay, so digging further. After the first successful login from a password reset, this line is getting removed again. To get it to stay, you need to fo this:
- Go to the user settings
- Change the Authentication Provider from "Default" to "InvalidOrMissingAuthenticationProvider"
- Click Save
- Change it back to "Default"
- Save again

After this, the line stays in the user's policy.

**Comment by anthonylavado** [comment]
Interesting notes from testing:
- The first user account created (the default Admin) doesn't have this item in their policy, but password resets work without issue
- Creating a second user account, and setting it to Admin technically adds this line (as you are clicking save on the edit screen). Removing the line, restarting Jellyfin, and performing a password reset still works

It would seem Admins are assumed to go through the default password reset provider, even if it isn't specified in the user policy.

**Comment by anthonylavado** [comment]
So this is then fixed by https://github.com/jellyfin/jellyfin-web/pull/501

With that fix in place, when you create a new user, you're brought to the user edit page. This page does update the policy to have a default user authentication provider. Having this set means that the user gets the default reset provider, so it all works down the chain.

**Comment by bengalih** [comment]
So apologies if I'm not reading these issues correctly, but I'm running 10.4.3 and still having an issue when resetting the Admin user's password.
The json reset procedure works, but I still am unable to login without first modifying the IsDisabled is policy.xml and restarting the server.

Shouldn't the reset procedure also include unlocking/enabling the account?
