### ISSUE TITLE
Docker: libva-drm2 unavailable in debian stretch

### ISSUE THREAD

**Issue by justinfenn** [jellyfin/jellyfin#1948]
**Describe the bug**

The docker build breaks with recent changes using the debian stretch base image.  It looks like `libva-drm1` is the version available in stretch.  I'm not sure if the solution is to change the base image or use this version of the library.

**To Reproduce**

1. Check out current master branch
2. Build docker image: `docker build -t my-image .`
3. See error

**Expected behavior**

The docker build should complete successfully.

**Logs**

```
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libva-drm2
The command '/bin/sh -c apt-get update  && apt-get install --no-install-recommends --no-install-suggests -y    libfontconfig1 libgomp1 libva-drm2 mesa-va-drivers  && apt-get clean autoclean  && apt-get autoremove  && rm -rf /var/lib/apt/lists/*  && mkdir -p /cache /config /media  && chmod 777 /cache /config /media  && ln -s /opt/ffmpeg/bin/ffmpeg /usr/local/bin  && ln -s /opt/ffmpeg/bin/ffprobe /usr/local/bin' returned a non-zero code: 100
```

**System (please complete the following information):**

 - OS: Docker
 - Browser: N/A
 - Jellyfin Version: master/10.5.0
 - Reverse proxy: N/A

**Comment by stevehayles** [comment]
just edit the Dockerfile and change to a more recent Debian

Change line 20

FROM debian:stretch-slim

to 

FROM debian:buster-slim

I'm in the process of issuing a pull request but it's in with a load of other changes I made.  I think you will also find that the version of the .NET Core SDK in Microsoft container is wrong (perview 6) and you may find issues when you run it.  If so change line 13

FROM mcr.microsoft.com/dotnet/core/sdk:${DOTNET_VERSION} as builder

to 

FROM mcr.microsoft.com/dotnet/core/sdk:${DOTNET_VERSION}-buster as builder

Probably easier for you to edit these locally as my pull request will take a while

**Comment by gerrit507** [comment]
I've made the suggested changes. I'm still getting 
`No usable version of libssl was found`
when starting the container. See https://github.com/jellyfin/jellyfin/issues/1911#issuecomment-546728257

**Comment by stevehayles** [comment]
I've issued a pull request to fix all of these issues.  For the libssl problem amend the apt-get lines which look like this around line 32

libfontconfig1 libgomp1 libva-drm2 mesa-va-drivers \

to include the openssl library

libfontconfig1 libgomp1 libva-drm2 mesa-va-drivers openssl \

**Comment by gerrit507** [comment]
After adding the openssl package, jellyfin starts but vaapi isn't working:
`[AVHWDeviceContext @ 0x556dd33c7980] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Input/output error
Error parsing global options: Input/output error`

I got an Intel G4600. 

Why are mesa (AMD) drivers included into the image but Intel drivers are not?

I always thought that the drivers are used from the host.

**Comment by dkanada** [comment]
> Why are mesa (AMD) drivers included into the image but Intel drivers are not?

Maybe we shouldn't include any hardware acceleration drivers in the provided image to avoid preferential treatment. I believe the current reason is just that someone decided to add the mesa drivers, which we merged.

**Comment by stevehayles** [comment]
This is a hard one to cover in a generic sense as you will need to match the driver to suit your hardware. Probably shouldn't be in the provided Dockerfile full stop in my view but that is a question for the core maintainers.

If it's intel hardware then I would try adding either the 'intel-media-va-driver' or 'i965-va-driver' packages to your docker file. Remember the spaces and keep the trailing \

**Comment by gerrit507** [comment]
> If it's intel hardware then I would try adding either the 'intel-media-va-driver' or 'i965-va-driver' packages to your docker file. Remember the spaces and keep the trailing \

I tried both packages already, sadly still the same error message.

> This is a hard one to cover in a generic sense as you will need to match the driver to suit your hardware. Probably shouldn't be in the provided Dockerfile full stop in my view but that is a question for the core maintainers.

I agree. And you'll get into non-free territory pretty fast when including drivers.

This leaves the question to me why this container can't access the hardware. I have an emby and another jellyfin container (10.3.7) running with same vaapi variables and they got no issues.

**Comment by stevehayles** [comment]
@gerrit507  Are you are sure you are mounting the video device from within the container properly ?

You need --device /dev/dri:/dev/dri in your docker create command

**Comment by gerrit507** [comment]
@stevehayles I'm mounting it with `--device /dev/dri/renderD128`

**Comment by stevehayles** [comment]
@gerrit507  Maybe a permissions issue, not sure what user Jellyfin runs as (used to be 'emby') but it will need appropriate permissions on the video device

**Comment by gerrit507** [comment]
I also have `--env GIDLIST=44`, which is my video group. As I have two other containers running with those settings, I don't see why they wouldn't work on this build.

**Comment by gerrit507** [comment]
I have to add: When using the intel-media-va-driver package transcoding fails with 
`[AVHWDeviceContext @ 0x556dd33c7980] Failed to initialise VAAPI connection: -1 (unknown libva error). Device creation failed: -5. Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Input/output error Error parsing global options: Input/output error`

When using the i965-va-driver package it fails with:
`ffmpeg: i965_encoder.c:1692: intel_enc_hw_context_init: Assertion `encoder_context->mfc_context' failed.`

Probably because the non-free i965-va-driver-shaders  is needed for AVC and HEVC. But I can't get it out of the configured sources...

**Comment by gerrit507** [comment]
It finally works with following list and packages:
`RUN echo "deb [arch=amd64] http://deb.debian.org/debian buster non-free" | tee /etc/apt/sources.list.d/nonfree.list`
`libfontconfig1 libgomp1 libva-drm2 mesa-va-drivers openssl i965-va-driver-shaders`

This is the full dockerfile: https://pastebin.com/i59L3vhW

Honestly adding a bunchload of drivers to the container isn't a good solution imho... There are still nvidia drivers missing for example.

**Comment by JustAMan** [comment]
> I agree. And you'll get into non-free territory pretty fast when including drivers.

AFAIK both Intel and AMD drivers are completely FOSS now (Intel's were so for quite a while, and AMD is proprietary only for their professional cards now).

**Comment by JustAMan** [comment]
also do you mind trying my ffmpeg build and seeing if it works for you? https://github.com/JustAMan/ffmpeg-standalone-build (shameless advertising LOL)
