### ISSUE TITLE
After 10.4.1(with baseurl) LiveTV using an m3u / iptv service fails to stream

### ISSUE THREAD

**Issue by cesalo** [jellyfin/jellyfin#2035]
**Describe the bug**
I have 10.4.1 and using baseurl = /jellyfin and also nginx to redirect to www.domain.com/jellyfin from the internet, since upgrading to 10.4.1 I started noticing few recordings failing and then found that all channels were failing to play. This was working in 10.4.0.

**To Reproduce**
Open any live tv channel.

**Expected behavior**
Live tv channels to work normally .

**Logs**

```
[2019-11-20 22:15:07.223 -05:00] [INF] User policy for "xxxx". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-11-20 22:15:07.224 -05:00] [INF] Profile: "Android-Exo", Path: "http://xxxxxx:xxxxxx/xxxxxxx/11664", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-11-20 22:15:07.224 -05:00] [INF] Profile: "Android-Exo", No direct play profiles found for Path: "http://xxxxxx:xxxxxx/xxxxx/11664"
[2019-11-20 22:15:07.224 -05:00] [INF] Profile: "Android-Exo", Path: "http://xxxxxx:xxxxxx/xxxxx/11664", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-11-20 22:15:07.224 -05:00] [INF] Profile: "Android-Exo", No direct play profiles found for Path: "http://xxxxxx:xxxxxx/xxxxxxx/11664"
[2019-11-20 22:15:07.279 -05:00] [INF] Opening channel stream from "Emby", external channel Id: "m3u_9e5155fe037a017beb99503a6b697caa7aac83f28a94684fee33432963bccbab"
[2019-11-20 22:15:07.279 -05:00] [INF] Streaming Channel m3u_9e5155fe037a017beb99503a6b697caa7aac83f28a94684fee33432963bccbab
[2019-11-20 22:15:07.280 -05:00] [INF] Opening SharedHttpStream Live stream from "http://xxxxxx:xxxxxx/xxxxxxxx/11664"
[2019-11-20 22:15:07.461 -05:00] [WRN] HTTP Response 200 to "192.168.194.244". Time (slow): 0:00:02.3253521. "http://192.168.194.104:8096/jellyfin/Items/ce14a3a0697bb96d62bab3fac76d4e55/Images/Thumb?EnableImageEnhancers=true&MaxHeight=300&Tag=7a8c2e1e98d20e40f5dc82364f6f0a82"
[2019-11-20 22:15:08.494 -05:00] [INF] Beginning "SharedHttpStream" stream to "/config/transcoding-temp/transcodes/74daae499dae45c5a1649e1891a9cf3b.ts"
[2019-11-20 22:15:08.495 -05:00] [INF] Live stream opened after 1214.4587ms
[2019-11-20 22:15:08.495 -05:00] [INF] Returning mediasource streamId "2d6ff814cf2533a6ad2472bc57819a14", mediaSource.Id "2d6ff814cf2533a6ad2472bc57819a14", mediaSource.LiveStreamId null
[2019-11-20 22:15:08.495 -05:00] [INF] Waiting 3000ms before probing the live stream
[2019-11-20 22:15:11.484 -05:00] [ERR] Failed to bind to port 1900: "Address already in use". DLNA will be unavailable
[2019-11-20 22:15:11.497 -05:00] [INF] "/usr/local/bin/ffprobe" "-analyzeduration 3000000 -i \"http://127.0.0.1:8096/LiveTv/LiveStreamFiles/74daae499dae45c5a1649e1891a9cf3b/stream.ts\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2019-11-20 22:15:11.632 -05:00] [ERR] Error probing live tv stream
System.Exception: ffprobe failed - streams and format are both null.
```
**System (please complete the following information):**
- OS: Docker
- Jellyfin Version: 10.4.1
- Reverse proxy: nginx

**Additional context**
If I remove the baseurl live tv works again.
After the upg to 10.4.1 I also had this issue: https://github.com/jellyfin/jellyfin/issues/2009 also related with the baseurl change.

**Comment by JustAMan** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin/pull/2019 and https://github.com/jellyfin/jellyfin/pull/2008, hopefully released in 10.4.2

**Comment by cesalo** [comment]
@JustAMan unfortunately it didn't. I just tested 10.4.2 with /baseurl and the issue is still present same errors as reported initially.

**Comment by JustAMan** [comment]
@Bond-009 could you please have a look?

**Comment by jrbski** [comment]
#1979 is still an issue with jellyfin 10.4.3. @cesalo are you still seeing the iptv issue on 10.4.3?

**Comment by cesalo** [comment]
@jrbski Yes (I'm in 10.4.3 - Docker) - The way the issue presents is  that the first 4 or 5 channels play ok but if I keep trying: ch#6 , ch#7 they start failing (the rest of the channels). The first channels always play ok,

**Comment by mooninite** [comment]
The problem is that these base url changes were not tested. Jellyfin talks to itself via the web API for Live TV and any changes to port, SSL, or path (Base URL in this case) cause Live TV to break.

Live TV / m3u streams are attempted to be read via:
```
http://127.0.0.1:8096/LiveTv/LiveStreamFiles/<channel id>/stream.ts
```
As of 10.4.1, Jellyfin is no longer responding to these requests because the base url is not part of the URL. The "fix" is either:

1. Always treat localhost requests as local and disregard base url.
2. Add the base url as part of the URL. Ex: http://127.0.0.1:8096/$BASE_URL/LiveTv/LiveStreamFiles/<channel id>/stream.ts

**Comment by PrplHaz4** [comment]
@mooninite a third option would be to reset baseurl back to blank.

Unfortunately, the Network Settings and their impact on different features is not very well understood yet.  I think this is a great area for automated tests (your example above being one of them).

**Comment by jlanzobr** [comment]
This issue should not be marked closed. It's ongoing as of 10.7.1 using a baseurl in Docker with an nginx reverse proxy (or without for that matter).

**Comment by crobibero** [comment]
> This issue should not be marked closed. It's ongoing as of 10.7.1 using a baseurl in Docker with an nginx reverse proxy (or without for that matter).

As this issue as been closed for over a year, please open a new issue.
