### ISSUE TITLE
UTF-8 subtitles without BOM are not displayed

### ISSUE THREAD

**Issue by JustAMan** [jellyfin/jellyfin#2525]
I'm not yet sure if it is a server or a web problem, so I'll make it in server for now.

> So I've been messing around with the subs and read somewhere that the encoding matters. I forced change the EP8 subs to **UTF-8 with BOM** and it worked. But still, there was a significant delay about about 40 secs before the subs appeared. I checked EP9 subs and found that it was already UTF-8 with BOM, hence maybe that's why it worked.
>
> I tried UTF-8 but it did not work. It had to be UTF-8 with BOM. But seriously, how is the average user supposed to sort this out? The subs were in English and was downloaded by Bazarr. The "Encode Subtitles to UTF8" option in Bazarr was enabled.

_Originally posted by @eltiel in https://github.com/jellyfin/jellyfin/issues/2507#issuecomment-595581475_

**Comment by Artiume** [comment]
https://www.reddit.com/r/jellyfin/comments/fgg39l/subtitle_not_working_1050/fk6vxtx

In your root media directory,

`find . -iname '*.srt' -print -exec sed -i '1s/^/\xef\xbb\xbf/' {} \;`

**Comment by JustAMan** [comment]
For reference: fixed by https://github.com/jellyfin/jellyfin/pull/2582

**Comment by rscm** [comment]
Still happening on Jellyfin 10.5.5

Version: Linuxserver.io version:- v10.5.5-ls54 Build-date:- 2020-05-24T08:25:39+02:00
Docker Version: Docker version 19.03.12, build 48a6621
OS: Debian Buster (Armbian)

I've used the command to bypass the bug

The video file was the tv show "The 100" and the episode was "The flock" (latest episode)

I checked the logs and there's nothing useful to post, unless you tell me what kind of flag I must define on the service

**Comment by TKFRvisionOfficial** [comment]
For reference https://github.com/CharsetDetector/UTF-unkown/pull/118
