### ISSUE TITLE
Anime shows fail to play properly with 10.5.1

### ISSUE THREAD

**Issue by mirolm** [jellyfin/jellyfin#2615]
After upgrading jellyfin from 10.5.0 to 10.5.1 all files encoded by HorribleSubs group stoped playing. Before the upgrade they was playing using direct play without any issues.

If i disable subtitles all files play fine.

**Media Info of the file**
[mediainfo_log.txt](https://github.com/jellyfin/jellyfin/files/4339572/mediainfo_log.txt)

**Logs**
[jellyfin_log.txt](https://github.com/jellyfin/jellyfin/files/4339530/jellyfin_log.txt)

Attaching a log from 10.5.0 too if this can help.
[jellyfin_10.5.0.txt](https://github.com/jellyfin/jellyfin/files/4339972/jellyfin_10.5.0.txt)

**FFmpeg Logs**
[ffmpeg_log.txt](https://github.com/jellyfin/jellyfin/files/4339531/ffmpeg_log.txt)

**Stats for Nerds Screenshots**
![image](https://user-images.githubusercontent.com/9135358/76785054-65a4cb00-67bd-11ea-8cf2-3f86c53e20a6.png)

**Server System (please complete the following information):**
 - OS: Debian Buster 10.3
 - Jellyfin Version: 10.5.1
 - Hardware settings & device: VAAPI on Intel i5 i5-4570S
 - Reverse proxy: nginx
 - Other hardware notes: none
 
**Client System (please complete the following information):**
 - Device: Playing through web browser
 - OS: Arch Linux
 - Client: Web/Browser
 - Browser: Chromium (Version 80.0.3987.132 (Official Build) Arch Linux (64-bit))
 - Client and Browser Version: 10.5.1 and 80.0.3987.132

**Comment by nyanmisaka** [comment]
Try the following commands to see if subtitle burning and transcoding work.
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 -i file:"/media/lv2/download/anime/Laid-Back Camp/Season 1/Laid-Back.Camp.S01E10.010.HDTV-720p-HorribleSubs.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -codec:v:0 h264_vaapi  -b:v 4766055 -maxrate 4766055 -bufsize 9532110 -profile:v high -level 41  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -copyts -vf "format=nv12|vaapi,hwupload,scale_vaapi=format=nv12,hwmap=mode=read+write,format=nv12,subtitles='/media/lv2/download/anime/Laid-Back Camp/Season 1/Laid-Back.Camp.S01E10.010.HDTV-720p-HorribleSubs.mkv:si=0',hwmap" -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 192000 /tmp/out.mp4
```

**Comment by mirolm** [comment]
Tested with the command. Subtitles show on the output file.

Below you can find log and screenshot:

![image](https://user-images.githubusercontent.com/9135358/76878264-42d9eb80-687d-11ea-9909-3eb3f3b86605.png)

[out.txt](https://github.com/jellyfin/jellyfin/files/4344527/out.txt)

**Comment by nyanmisaka** [comment]
This issue will be fixed in https://github.com/jellyfin/jellyfin/pull/2503

**Comment by mirolm** [comment]
I hope this gets fixed soon, because right now jellyfin is unusable for me. Will wait and watch with smplayer in the meantime. :)

**Comment by isdamir** [comment]
I had this problem too, I rolled back to the 10.4.3 version and disabled hardware decoding.

**Comment by Artiume** [comment]
Anyone who wants to try using 2503 with the jellyfin/jellyfin docker image can try my personal image: `Artiume/jellyfin` (this is not compatible with the linuxserver/jellyfin image). It would also give us some feedback with PR 2503

**Comment by SLCH** [comment]
Tried out @Artiume 's docker image based on #2503 
First thing noticed - doesn't work with subtitles inside `.mkv` - but this could be a client issue?
Also only works with `.srt` subs. `.ass` are still not burned in.
But i'm new with jellyfin, could be i did not enable smth.

**Comment by nyanmisaka** [comment]
> Tried out @Artiume 's docker image based on #2503
> Doesn't work with subtitles inside `.mkv`.
> Also only works with `.srt` subs. `.ass` are still not burned in (on android that is, web is fine).
> But i'm new with jellyfin, could be i did not enable smth.

Are you using VAAPI or QSV or NVENC? The image needs an update since I have updated PR to address some QSV/NVENC issues. In addition, you may also need to turn on "Burn All Format Subtitles". I tested and found that if set to "Auto" in the web client, the subtitles may not be burned. If it is not the above two cases, can I get your ffmpeg log?

**Comment by Artiume** [comment]
> Doesn't work with subtitles inside .mkv.
Also only works with .srt subs. .ass are still not burned in (on android that is, web is fine). 

Yeah, my image is out dated for several reasons. It is based on 10.5.2 which has broken embedded subtitles. I need to rebase it off 10.5.3.

> I tested and found that if set to "Auto" in the web client, the subtitles may not be burned.

Did you make  ticket for this? Seems worthy of tracking.

**Comment by SLCH** [comment]
> Are you using VAAPI or QSV or NVENC? The image needs an update since I have updated PR to address some QSV/NVENC issues. 

Not using any hardware acceleration. At least there is none chosen in settings.

> In addition, you may also need to turn on "Burn All Format Subtitles". I tested and found that if set to "Auto" in the web client, the subtitles may not be burned.

Seems fine with or without option on web. On android such option is absent :) Are these option per client and can not be set globally?

btw after playing around found out that it indeed does not transcode with "Burn All Format Subtitles"-"Auto". But still displays subtitles correctly.

> If it is not the above two cases, can I get your ffmpeg log?

Here it is [for pc](https://pastebin.com/PWVLux1G) with subs working and [for android](https://pastebin.com/53jkeYe6) with them not.

> Yeah, my image is out dated for several reasons. It is based on 10.5.2 which has broken embedded subtitles. I need to rebase it off 10.5.3.

Oh, it's fixed, great! Will wait for official release then since .3 was pulled.

**Comment by Artiume** [comment]
10.5.3 is out. Let's see how it behaves so we can hopefully close out this ticket :)

**Comment by SLCH** [comment]
Works fine :+1: 

Except for android app client, but that is it's fault, not server's. Android web is fine.

**Comment by Artiume** [comment]
Yeah, we're working on updating android. Once we can fix https://github.com/jellyfin/jellyfin-web/issues/899 we should be able to update Android :)
