### ISSUE TITLE
Improvement for special editions, directors cut etc (displaying in UI)

### ISSUE THREAD

**Issue by jeff7269** [jellyfin/jellyfin#262]
To my knowledge (at least I have never been able to get it to work) emby (and thus Jellyfin) should be able to handle multiple releases of the same movie, for example:

Alien (1979)
 - Alien (1979).mp4
 - Alien (1979) - Directors Cut.mp4

Personally, if I have the director's cut, I wouldn't have the theatrical cut but I still want to know it's the directors cut in the UI. Even when following the naming schema, this isn't displayed. If this could be added to the UI regardless of if there's only one file in the folder, it would be very handy.

**Comment by jeff7269** [comment]
I don’t have the theatrical cut... as mentioned above, if I have the DC, I probably won’t have the TC. The issue is around displaying what cut it is, when there is only one and the handling of things it doesn’t recognise (eg. Disney often uses Diamond Edition).

**Comment by dkanada** [comment]
@jeff7269 so you have exactly one movie file and want the version displayed in the web client? Please explain your existing situation a bit more clearly.

**Comment by dkanada** [comment]
This should have been resolved in recent versions, please comment again if there are still issues.

**Comment by Seyloria** [comment]
Sorry to necro this out. Is this actually solved in one way or another?

I feature requested exactly this some time ago.

as @jeff7269 stated it would make sense to show if its the directors cut for example, even if there is only 1 version of the movie.

**Comment by drewbaker** [comment]
As far as I can tell, this is still an issue. If you only have one version of a film, it doesn’t display what version you have anywhere in the web UI. 

So it’s impossible to tell what version I’m actually watching.

**Comment by Seyloria** [comment]
Here is my feature request on that topic:

https://features.jellyfin.org/posts/2537/display-movie-version-like-extended-directors-cut-etc

**Comment by felix920506** [comment]
Please open a new issue if you believe the issue still exists.
