### ISSUE TITLE
v 10.5.3 Embedded subs don't play in some files

### ISSUE THREAD

**Issue by johnvick** [jellyfin/jellyfin#2802]
Two Intel Debian based systems, two Docker installs, one Linuxserver and the other Jellyfin. The former has BaseURL, the latter does not. Same behaviour with both.

Subs embedded in some MKV files (typically Netflix rips) do not play in Windows on Chrome or Edge or Firefox on a Linux device. One file plays OK with subs on Ipad app but not on the same Ipad on Safari. Doesn't display subs on Android phone.

With all but the English subs stripped out the file plays OK with subs in VLC but not in Jellyfin web interface.

Forum thread:
https://www.reddit.com/r/jellyfin/comments/fwaw5y/embedded_subtitles_v1053/fmqipft/

Media info on one offending file:
https://pastebin.com/7Am65JH1

**Comment by akhoa12** [comment]
This happen to me too.

OS: Mint 19.3
Docker image: linuxserver 10.5.3
Client: Jellyfin for Android

I find that this happens whenever I have ASS/SSA subs embedded in the video, and this only happens on my Android phone as watching on Chrome and my AndroidTV is fine. I have "subtitle extraction on the fly" ON, and "burn in" option set to image only. 

I read somewhere that for these embedded subs you have to wait 30s or so before the sub appears, but this did not happen even after the 2min mark. Also, just more info, but pgssub plays fine on my phone.

**Comment by Artiume** [comment]
Is this fixed?

**Comment by johnvick** [comment]
Still the same here on v 10.5.5

**Comment by loligans** [comment]
I am also experiencing this issue. The video I have has multiple embedded ASS subtitles. I confirmed the Japanese ASS subtitles work, but the English ones do not. I am using the iOS app and the Web app. All subtitles work in VLC player.

**Comment by dkanada** [comment]
Most of these issues should have been solved in the latest updates, I think 10.5.3 is two versions behind at this point.

**Comment by loligans** [comment]
I still experience this issue running Jellyfin for Windows `v10.5.5` 64-bit

**Comment by loligans** [comment]
I would be happy to provide logs and troubleshoot.

**Comment by loligans** [comment]
Here is a screenshot of the file's media information. The first square shows the Japanese subtitles which work in the Jellyfin Web and iOS client. The second square shows the English subtitles that do not work in the Jellyfin Web and iOS client.
![image](https://user-images.githubusercontent.com/3218210/85218159-62852200-b34c-11ea-9df4-92657866ae80.png)

**Comment by loligans** [comment]
**This is the transcoding log:**
[ffmpeg-transcode-388ef48c-cac4-4df1-ada0-c7900e037193.txt&api_key=50e05578667a47bfb72c49658cdbff11.txt](https://github.com/jellyfin/jellyfin/files/4809021/ffmpeg-transcode-388ef48c-cac4-4df1-ada0-c7900e037193.txt.api_key.50e05578667a47bfb72c49658cdbff11.txt)
