### ISSUE TITLE
Failure to Create User Folders in a Fresh Setup

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#3191]
On macOS, the user configuration is stored at this path by default:
`/Users/username/.local/share/jellyfin`

Because of the name `.local` (which is shared by **many** applications), this filter causes a failure:
https://github.com/jellyfin/jellyfin/blob/7c72f69189500ef491a0e81d8ce6788987f47fa3/Emby.Server.Implementations/Library/IgnorePatterns.cs#L46-L47

This prevents the server from correctly recording the key of the root folder, even though it has already successfully created the folder! This causes everything to come down crashing and burning with this message:
```
Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Error creating recording folders
System.Reflection.TargetException: Non-static method requires a target.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Reflection.PropertyInfo.GetValue(Object obj)
   at MediaBrowser.Controller.Entities.BaseItemExtensions.DeepCopy[T,TU](T source, TU dest) in /Users/anthonylavado/repos/jellyfin/MediaBrowser.Controller/Entities/BaseItemExtensions.cs:line 80
   at MediaBrowser.Controller.Entities.BaseItemExtensions.DeepCopy[T,TU](T source) in /Users/anthonylavado/repos/jellyfin/MediaBrowser.Controller/Entities/BaseItemExtensions.cs:line 103
   at Emby.Server.Implementations.Library.LibraryManager.GetUserRootFolder() in /Users/anthonylavado/repos/jellyfin/Emby.Server.Implementations/Library/LibraryManager.cs:line 779
   at Emby.Server.Implementations.Library.LibraryManager.GetVirtualFolders(Boolean includeRefreshState) in /Users/anthonylavado/repos/jellyfin/Emby.Server.Implementations/Library/LibraryManager.cs:line 1139
   at Emby.Server.Implementations.Library.LibraryManager.GetVirtualFolders() in /Users/anthonylavado/repos/jellyfin/Emby.Server.Implementations/Library/LibraryManager.cs:line 1133
   at Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV.CreateRecordingFolders() in /Users/anthonylavado/repos/jellyfin/Emby.Server.Implementations/LiveTv/EmbyTV/EmbyTV.cs:line 168
```

**Comment by anthonylavado** [comment]
This was added in https://github.com/jellyfin/jellyfin/pull/3099 to fix https://github.com/jellyfin/jellyfin/issues/3032.

The original fix proposed in https://github.com/jellyfin/jellyfin/pull/3069 by @rigtorp would have been better.

**Comment by anthonylavado** [comment]
The folders in use on macOS would be:
```
~/.config/jellyfin
~/.cache/jellyfin
~/.local/share/jellyfin
```

This issue is also occurring on some other operating systems.

**Comment by Artiume** [comment]
https://github.com/jellyfin/jellyfin/pull/3195

see if this fixes it

**Comment by Bond-009** [comment]
I took a quick look at the code and I I'm pretty sure the exception occurs because the function that should resolve the `UserRootFolder` returns `null` because of this line: https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Library/LibraryManager.cs#L534
I don't think this code should follow the same ignore rules as the media scanner

**Comment by Artiume** [comment]
This is also impacting Linux

**Comment by Artiume** [comment]
#3195 did not fix my linux error. Would you mind testing MacOS? I think there might be an issue elsewhere

**Comment by anthonylavado** [comment]
So #3195 worked for me on macOS, but if it's not a fix for Linux, we should pursue @Bond-009's comment

https://github.com/jellyfin/jellyfin/issues/3191#issuecomment-634822149


> I took a quick look at the code and I I'm pretty sure the exception occurs because the function that should resolve the `UserRootFolder` returns `null` because of this line: https://github.com/jellyfin/jellyfin/blob/master/Emby.Server.Implementations/Library/LibraryManager.cs#L534
> I don't think this code should follow the same ignore rules as the media scanner

**Comment by anthonylavado** [comment]
Fixed in #3268.
