### ISSUE TITLE
Hide multple versions of same movie

### ISSUE THREAD

**Issue by Thalhammer** [jellyfin/jellyfin#3361]
**Describe the bug**
If a movie is added in multiple versions it shows up multiple times in the search/list ui.
All versions with the number of version in the top corner.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: LXC (Proxmox VE 6.2)
 - Clients: Browser; Android
 - Browser: Chrome 83
 - Jellyfin Version: 10.5.5
 - Playback: None
 - Installed Plugins:AudioDB;Fanart;IPTV;MusicBrainz;Playback Reporting;Reports
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Direct via Linux Bridge
 - Storage: NFS to VM on the same VM Host (FreeNAS)

**To Reproduce**
1. Put movies with the same name + version postfix in mediafolder.
2. Let it scan them
3. Go through media collection and group duplicates
4. View Media List/Search for title

**Expected behavior**
The Title shows up once, with both versions available when opening the details.

**Seen behavior**
The title shows up twice, both with the indicator for multiple versions and clicking on any of them
shows the version selection (So it definitly understood that they both belong together).

**Logs**
**Screenshots**
See below

**Additional context**
I do not have both movies in a folder named after the movie as I would need to move a lot of files and would break other software accessing the library. However I have all movies in a single folder and group them manually through the ui.
I am not sure if this is a bug or the intended behavior, but it is intended, I believe there should be an option to hide those duplicates on the UI (which I could not find anywhere).

**Comment by 1024mb** [comment]
Yes, this has been happening for quite some time, would be nice to have a fix for this.

**Comment by Thalhammer** [comment]
I do have experience with C# / Javascript development.
Any hints on where to start if I where to try fixing this myself ?

**Comment by anthonylavado** [comment]
This is mostly inherited behaviour, which we haven't changed. I think there's already a proposal to auto identify qualities and group them that way, using the codec/quality as the identifying marker.

I don't know where you'd work on this though - it would need implementation in the server and in the web interface, then the clients, etc...

**Comment by Thalhammer** [comment]
I don't think you'd actually need to change the clients, I think it would be enough to remove the duplicate item from the list returned when listing movies.

**Comment by anthonylavado** [comment]
You're right - I was confusing this with the logic to select a version to playback as well. Anyway...

**Comment by holow29** [comment]
I think same issue as: https://github.com/jellyfin/jellyfin/issues/3242

**Comment by Thalhammer** [comment]
@holow29 I dont think so. The issue you linked is about individual files not getting group automatically. My issue is about the files still showing up as two titles after being grouped manually (both with the group marking), where IMHO the gui should only show one entry for the group.

**Comment by holow29** [comment]
Seems to be the same as what the author said in his reply here, right? https://github.com/jellyfin/jellyfin/issues/3242#issuecomment-641009760

**Comment by holow29** [comment]
@Thalhammer you're right. I think the issues are similar but not the same.

**Comment by danieladov** [comment]
This only occurs when grouping movies into collections is enabled

**Comment by Thalhammer** [comment]
It still exists....

**Comment by iFloris** [comment]
@Thalhammer this can be mitigated somewhat by using the mergeversions plugin; we use that and it works well, even for separated HD/4K libraries.

https://github.com/danieladov/jellyfin-plugin-mergeversions

**Comment by Thalhammer** [comment]
It feels like #5324 should have fixed this, but for me the issue still persists. I am using version 10.7.0 from docker (jellyfin/jellyfin, not the linuxservers one).
I also tried ungrouping and regrouping some movies, which did nothing.
@iFloris I dont care if I have to manually group them (I dont add new media that often and when I do, converting takes way more time than grouping them afterwards), the issue is that even grouped they show twice pretty much everywhere.

**Comment by cvium** [comment]
#5324 is slated for a 10.7.1 release fyi

**Comment by Thalhammer** [comment]
Fixed by 10.7.1

**Comment by 1024mb** [comment]
@Thalhammer 

It is not entirely fixed. If two individual non-collection movies are grouped there is no problem now, but if those movies are inside a Collection they are shown twice like before the fix. See pic.

![alien collection](https://user-images.githubusercontent.com/9301204/115487357-0dee5400-a248-11eb-8232-4079870d639b.png)

Please, re-open the issue.

**Comment by Thalhammer** [comment]
Sorry, did not know that.

**Comment by 1024mb** [comment]
To update: Even with movies that aren't in a collection the issue is still present.

![firefox_2021-05-05_17-48-08](https://user-images.githubusercontent.com/9301204/117219054-fe4c3f00-adf3-11eb-94bf-2d115ae45b1c.png)

**Comment by BugFixesAndPerformanceImprovements** [comment]
As a suggestion: make this a toggle in the dashboard as having movies display for each duplicate file is a handy way to spot them in (very)  large libraries.

**Comment by Lakeland97** [comment]
![Screenshot_20211113-010131](https://user-images.githubusercontent.com/78028724/141479203-343f0f4e-fdb4-4cb6-950a-b0d1552b40f4.png)
Same issue here

**Comment by eqnot** [comment]
Same here. Even the correct naming on the folders/files doesn't seem to work correctly. They just don't group as one. Though... if I have two versions of a Movie and I click on the group option they actually have the drop down menu to choose from both versions. This works. But they still show up as a single movie in Library and colletions.

**Comment by 1337haXXor** [comment]
I didn't want to create a new issue, because I believe it's the same. Here's my setup:
Movies
└── Donnie Darko (2001) [4K] {Arrow}
    ├── extras
    │        └── Special Feature 1.mkv
    │        └── Special Feature 2.mkv
    ├── Donnie Darko - [Theatrical].mkv
    └── Donnie Darko - [Director's Cut].mkv

I performed a rescan, but I have twice the problems. The movie is displaying twice in the library with no dropdown option. Additionally, all of those special features are showing in my movie library, which indicates to me there's a problem with the naming. When I FIRST migrated my library to accommodate jellyfin formatting, I had a few movie folders with the year first (1940 - Fantasia), and I noticed that all the special features, even when in an "extras" folder, showed up in the library. But when I fixed the root movie folder name, the extras worked properly.

So I guess there's something with the naming? I tried changing the folder to remove the [4K] and {Arrow} tags and did a rescan after each, but still nothing.

**Comment by GodTamIt** [comment]
I have another use-case that seems to break as well.

**Example for TV:**

```
TV/
  Breaking Bad (2008)/
    Season 01 - 1080p /
      Breaking Bad (2008) - s01e01.mkv
    Season 01 - 2160p AV1/
      Breaking Bad (2008) - s01e01.mkv
```

Currently, this results in two entries for each episode in Season 1. Instead, we should just group them together.

**Comment by Shadowghost** [comment]
Multiple versions are not supported for episodes so this is expected.

**Comment by xenago** [comment]
This would be a great feature. It's baffling that the scanner can identify two files as being the same film but does not combine them

**Comment by nickspacemonkey** [comment]
There is a workaround for this on reddit: https://www.reddit.com/r/jellyfin/comments/11o3nwa/how_to_handle_multiple_movie_versions_and/?utm_source=share&utm_medium=web2x&context=3

Although there seems to be some contention as to whether or not this is a bug, or if people are not following the naming conventions correcty.

**Comment by xenago** [comment]
It's definitely still a problem in the main release in the main library sections. It will still match multiple copies of the same item and not combine them:

![image](https://user-images.githubusercontent.com/11216007/225423541-d5728e49-5145-4bdd-bbe4-c672028fc3e3.png)

It ought to be a pretty simple fix since the scanner is correctly matching the films, just not combining them (even though the files are all being matched to the same exact film in TMDB).

**Comment by xenago** [comment]
File structure is irrelevant to this issue, each of the films is matching to the same TMDB ID and therefore should be combined since JF is completely aware they are the same. I used the plugin for now until this is fixed properly.

**Comment by Thalhammer** [comment]
> It's definitely still a problem in the main release in the main library sections. It will still match multiple copies of the same item and not combine them:

Thats a separate issue though. This issue was about **grouped** items showing multiple times, not about same movies not being automatically grouped, which while still a bad thing is less of an issue IMHO because you can just manually group them.

**Comment by Bond-009** [comment]
@Thalhammer Is right, and I haven't really seen examples of the original issue since the fix so I think this issue can be closed?

**Comment by rodhfr** [comment]
for me the issue was there  (i'm using linuxserver docker container) but as commented above this plugin solved:
https://github.com/danieladov/jellyfin-plugin-mergeversions
![image](https://github.com/jellyfin/jellyfin/assets/83579016/8a29c22a-7f71-412b-abdd-bcb6c2de7783)
![image](https://github.com/jellyfin/jellyfin/assets/83579016/3eca403d-e2e2-4093-8a18-cd3299b66c68)

**Comment by saberblaze** [comment]
One thing I don't think I've seen mentioned is that when there is a movie with 2 versions in one folder that also has an extras folder, the extras folder is not picked up by Jellyfin. The movies shows up twice in the library but no extras are shown. If I follow Jellyfin naming guide with identical names and dash at the end, the extras do show up. The mergeversions plugin avoids having to rename hundreds of files however the Jellyfin bug that prevents the extras from being picked up is present regardless of wheter the plugin is used or not. I'm not sure if opening a new issue is warranted or if it all falls under the same umbrella.

Ideally, it would be nice if Jellyfin can incorporate the mergeversions plugin functionality to avoid duplicate entries in the library and in collections while also making sure that the extras folder is properly picked up when there are multiple movie versions present.

**Comment by tromphakvoort** [comment]
I had the same issue with episodes where I have a low quality version and a high quality version, the plugin mentioned before did the trick. https://github.com/danieladov/jellyfin-plugin-mergeversions

**Comment by Panda260** [comment]
bump

**Comment by CaCTuCaTu4ECKuu** [comment]
I see it like that. I merged movies manually.

![Image](https://github.com/user-attachments/assets/0264997b-8195-44a0-9690-262b1f34a39c)

**Comment by RomingGnome** [comment]
I'm getting 2 different behaviors, as shown in the screenshots. I'm running Jellyfin 10.10.7 in a Docker container on a Synology NAS.

Here's where it worked as expected:
![Image](https://github.com/user-attachments/assets/f3ba07b5-863c-47fc-90ba-fe6851b706cb)

![Image](https://github.com/user-attachments/assets/60432962-4b23-458a-81c8-0299986e0368)

![Image](https://github.com/user-attachments/assets/6a186a20-4599-4d41-ac4e-f9170ae522d6)


Here's where it fails, using the same naming format:
![Image](https://github.com/user-attachments/assets/50060418-a0d0-42b0-a4e1-478e6e0f25f3)

![Image](https://github.com/user-attachments/assets/bd280860-806f-4d2c-ba3b-43c51d5b5b6a)

![Image](https://github.com/user-attachments/assets/86441d7f-491f-4181-9477-fcc5cadd0557)

![Image](https://github.com/user-attachments/assets/9deabcc4-f9b0-43b5-91ff-38db80a80312)

**Comment by theguymadmax** [comment]
Can the folder name to:
`Transformers Dark of the Moon (2011)`
Files to:
`Transformers Dark of the Moon (2011) [2D].mkv`
`Transformers Dark of the Moon (2011) [3D] - MVC.mkv`

**Comment by lawleagle** [comment]
I came here because even with merge plugin, I get the same movie rendered twice, even though it is grouped properly and I can select the version to play when I click on either of the two entries. it's just duplicate entries in the list

<img width="507" height="404" alt="Image" src="https://github.com/user-attachments/assets/02fbde24-346e-4093-9933-f355c8eccb72" />

**Comment by CaCTuCaTu4ECKuu** [comment]
@lawleagle Check files naming, having `-` symbols in name may be the cause

**Comment by MaddyGuthridge** [comment]
@CaCTuCaTu4ECKuu the `-` symbol is listed in the docs as a valid way to list two versions.

**Comment by MaddyGuthridge** [comment]
I just had this issue result in ***DATA LOSS*** on my server.

1. I re-encoded "Spirited Away" in a higher resolution
2. It failed to group them automatically
3. Both versions in the list showed both resolutions
4. When I deleted the unwanted new copy, believing that it would keep the files since they were associated with the new version too, it permanently removed the files for both encodings from the file system, and left the old listed version as-is, causing an error whenever I tried to play it back.

Issues that can result in data loss like this should be urgent to fix.

**Comment by MewStr** [comment]
Is there any update regarding this issue? I’m experiencing it as well. I’m running the latest version of Jellyfin, and everything was working perfectly until I enabled collections. I tried installing the MergeVersions plugin, but it didn’t make any difference on my end. I tested both a Jellyfin instance running on Windows and another running in Docker, and the issue occurs in both cases.

**Comment by sergio221095** [comment]
Same problem, mergeversion works fine but duplicates the cards. I hope it gets fixed soon, please.

**Comment by K-Zawis** [comment]
I have the same problem. For example here is my Alien collection:

<img width="1198" height="985" alt="Image" src="https://github.com/user-attachments/assets/91f38213-2cb7-4e05-90ef-f5af893297ec" />

As you can see the first Alien movie is merged fine, but they live in the same folder:

<img width="593" height="57" alt="Image" src="https://github.com/user-attachments/assets/d2071348-f244-4b77-9cae-04c36f29ab62" />

<img width="398" height="20" alt="Image" src="https://github.com/user-attachments/assets/3d577cf6-5475-4f9b-9901-f164fefef107" />

However Aliens, which is split between two libraries (English and Polish), and thus live in seperate folders, fails to merge and shows both "merged" versions:

<img width="581" height="41" alt="Image" src="https://github.com/user-attachments/assets/48b125ea-ea08-43eb-b548-840875c3c037" />

<img width="418" height="18" alt="Image" src="https://github.com/user-attachments/assets/1305ad29-5698-4a8d-95f4-2ae3b8bc19b6" />

I also run the mergeversions plugin but it doesn't remove the duplicates, just makes them both show both versions. Has there been any attempt at finding what the issue has been? Jellyfin has a big backlog so just want to set my expectations accordingly!

**Comment by sergio221095** [comment]
I haven't found a solution.
I have symlinks and I've even tried renaming them manually, but I can't get it to work.

**Comment by yankees5963** [comment]
Current workaround is to go to Dashboard -> Libraries -> Display -> Uncheck "Group Movies into collections"

**Comment by theguymadmax** [comment]
Multiple versions work as [documented](https://jellyfin.org/docs/general/server/media/movies#multiple-versions). Media must be in the same folder; we do not support multiple versions spread across different libraries or folders.

The base filename for each version must match the **_complete folder name_** exactly, followed by a separator (-) and then labels:

Movie (2021) [imdbid-tt12801262]
├── Movie (2021) [imdbid-tt12801262] - 2160p.mp4
├── Movie (2021) [imdbid-tt12801262] - 1080p.mp4

Support for handling multiple versions across different directories has been requested, but it is not currently supported. You can follow or vote on the feature request here:
https://features.jellyfin.org/posts/174/better-handling-of-movie-versions-in-multiple-directories

If you are having issues, you can seek help on the forum or the Matrix chat rooms: https://jellyfin.org/contact

**Comment by MaddyGuthridge** [comment]
According to [the documentation](https://jellyfin.org/docs/general/server/media/movies/), the following format is also permitted:

```
Movies
└── Best_Movie_Ever (2019)
    ├── Best_Movie_Ever (2019) - [1080P].mp4
    ├── Best_Movie_Ever (2019) - [720P].mp4
    └── Best_Movie_Ever (2019) - [Directors Cut].mp4
```

This is the format that my library has. I have confirmed that the two media items are in the same directory. However, they are not merged in the UI, and attempts to merge them all have no effect. Both entries in the library are identical, and both reference the same two encodings of the movie. Deleting one entry also deletes the other, meaning that there is no way to fix this duplication.

![Screenshot_20260613_011316_Jellyfin.jpg](https://github.com/user-attachments/assets/9f83b83e-844c-406d-a31d-8b27b4e3d3e4)

![Screenshot_20260613_011337_Jellyfin.jpg](https://github.com/user-attachments/assets/230afee5-1302-4585-8184-f18e6dcb9249)

(Note that the app trims off the file extension, both are .mkv files).

I have experienced similar issues with encodings of at least 4 other movies, although it does not happen consistently.

I am confident that this but is still present in the latest release of Jellyfin, as I have reproduced this issue within the past 5 days. Please reopen the issue, @theguymadmax . If there is more I can do to help investigate please let me know.

**Comment by MaddyGuthridge** [comment]
Note: if you have this kind of corruption in your database, updating to v12 will cause Jellyfin to get stuck in an infinite loop during the migration. I had to completely delete and recreate my instance to fix it.
