### ISSUE TITLE
User password reset undefined

### ISSUE THREAD

**Issue by KeyboardDabbler** [jellyfin/jellyfin#4129]
**Describe the bug**
User password reset "undefined"

**System (please complete the following information):**
 - OS: Ubuntu
 - Clients: Browser
 - Browser: Chrome
 - Jellyfin Version: 10.6.4
 - Reverse Proxy: HAproxy
 - Networking: Host
 - Storage: local, NFS, cloud

**To Reproduce**
1. Go to 'login page'
2. Click on 'reset password'
3. Enter 'username'

**Expected behavior**
Outputs a folder path, also generating a file named passwordreset*.json

**Logs**
no entries of the event recorded

**Screenshots**
![pwreset](https://user-images.githubusercontent.com/53971316/93005563-450bd100-f5a6-11ea-97f9-3aaa47744599.PNG)

**Comment by cvium** [comment]
Fixed in https://github.com/jellyfin/jellyfin-web/pull/1946

**Comment by zephyr0223** [comment]
I still have this issue (just now updated to 10.7.0 stable, which includes jellyfin/jellyfin-web#1946.) 
Can verify that this is a web-only issue, as I see that the passwordreset<id>.json file is properly created in jellyfin data folder (Windows C:\ProgramData\Jellyfin\Server).


    OS: Windows 10
    Clients: Browser
    Browser: Firefox
    Jellyfin Version: 10.7.0
    Storage: local

**Comment by Jakobud** [comment]
I still have this issue in Jellyfin 10.7.7-4 on my Synology NAS.
