### ISSUE TITLE
10.7.0 RC3: Displaying missing episodes by seasons has stopped working. 

### ISSUE THREAD

**Issue by WWWesten** [jellyfin/jellyfin#5125]
**Describe the bug**

Displaying missing episodes by seasons has stopped working. The checkbox "Display missing episodes within seasons" in user settings is checked. Although it says "This must also be enabled for TV libraries in the server configuration.", this item disappeared from the parameters of the TV library.

**System:**
 - OS: [Windows 10 64bit]
 - Virtualization: [none]
 - Clients: [Web-client, Android TV ]
 - Browser: [e.g. Edge Chromium 88.0.705.53, Chrome 88.0.4324.104]
 - Jellyfin Version: [10.7.0, RC3]
 - Playback: [Direct Play, Remux, Direct Stream, Transcode] 
 - Installed Plugins: [Fanart, AudioDB, Bookshelf, MusicBrainz, OMDb, TMDb Box Sets, TV Maze, TheTVDB.]
 - Reverse Proxy: [none]
 - Base URL: [none]
 - Networking: [NAT]
 - Storage: [local]

**To Reproduce**

1. Go to 'User Settings'
2. Click on 'Display'
3. Scroll down to 'Display missing episodes within seasons'
4. Click on checkbox
5. Refresh TV Library
6. Go to any tv series with missing or/and unaired episodes eg 'Snowpiercer'
7. Open Season 2
8. Displaying missing and unaired episodes in the Season 2 doesn't work

**Expected behavior**

Displaying missing and unaired episodes in seasons must work

**Logs**

**Screenshots**

**Additional context**

**Comment by crobibero** [comment]
https://github.com/jellyfin/jellyfin-plugin-missingepisodeprovider

**Comment by cvium** [comment]
Try installing that plugin and let us know if it still doesn't work.

**Comment by sPOiDar** [comment]
That plugin doesn't appear to be available in the Stable repository.

**Comment by douglasparker** [comment]
@cvium 

> https://github.com/jellyfin/jellyfin-plugin-missingepisodeprovider

> Try installing that plugin and let us know if it still doesn't work.

That plugin is currently archived and is seems to be no longer maintained.
> ARCHIVED: Functionality moved to jellyfin-plugin-tvdb.

Right now a lot of people are confused on where this functionality has gone.

Currently, you can go into **Settings -> Display -> Display missing episodes within seasons** to enable the functionality on the client side.

However, the following text below that setting is very confusing and should be updated.
> This must also be enabled for TV libraries in the server configuration.

Otherwise you end up with a lot of people scratching their heads with no answers.

To further make things worse, there are plenty of people describing how to enable this functionality the old way.

Ultimately, the settings to enable this functionality on the client side should probably explain how to enable it on the server side.

It might make more sense to describe how to do all of this in the documentation, and to just link to the docs under the client side setting.

* https://www.reddit.com/r/jellyfin/comments/mdcui4/show_missing_episodes_within_seasons_feature/
* https://www.reddit.com/r/jellyfin/comments/k3ccow/looking_for_plugin_to_list_missing_episodes/
* https://www.reddit.com/r/jellyfin/comments/ghj6b7/how_does_display_missing_episodes_within_seasons/

**Comment by jfml** [comment]
For those who came here completely confused on how this works past 10.7. (like me):

- Enable TVDB-addon
- Client: Settings -> Display -> Display missing episodes within seasons
- Server: Settings -> Libraries -> Manage Library -> Series metadata downloaders: check: Missing Episode Fetcher

**Comment by Waldkoenig** [comment]
Why is this issue closed? The workaround by @jmfl adds another problem as actor/people pictures are primarely downloaded by the TVDB plugin now and they have all individual pictures for each series.

**Comment by MrReSc** [comment]
I have found exactly the same thing as @Waldkoenig  In addition, there is now a duplicate entry for each epsisode.

**Comment by jfml** [comment]
@MrReSc Do you have duplicate entries for every series you have? I noticed duplicate entries as well (one where the episode is „missing“, one where Jellyfin can see it) but only for certain series. Did not have the time to try investigate which ones/what's causing this, though.

**Comment by Serveurperso** [comment]
When I add a missing episode, the "missing" entry is not removed !

**Comment by WWWesten** [comment]
Guys, don't try hijacking the closed discussion! 

The issue closed because the described problem has been solved and there is no reason to continue writing in vain, because no one is going to do anything about the closed issue.

If you want to continue, open a new Issue(s) and describe clearly what you want.

ISSUE IS CLOSED, SORRY. PERIOD.

**Comment by joepie91** [comment]
This isn't actually resolved, though? The original bug is that the instructions are faulty; this continues to be the case, as far as I can tell. At the very least, the instructions in Jellyfin's UI should be updated to indicate that this functionality has moved to the TVDB plugin, rather than pointing people to an option that no longer exists.

**Comment by erujp** [comment]
> Why is this issue closed? The workaround by [@JMFL](https://github.com/JMFL) adds another problem as actor/people pictures are primarely downloaded by the TVDB plugin now and they have all individual pictures for each series. The order of the metadata plugins and/or disabling TVDB as a source for any metadata does not change that unfortunately.

For people, like me, reading this comment in 2026 and worried about this behavior, you don't need to activate the TVDB plugin. Just install it and then, in Settings -> Libraries -> Manage Library -> Series metadata downloaders: check: "Missing Episode Fetcher" WITHOUT CHECKING the TVDB itself. Then rescan the whole library.
