### ISSUE TITLE
Jellyfin 10.7.0 windows x64 don't load http://localhost:8096, ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by morralletti** [jellyfin/jellyfin#5497]
Hi.

After upgrading to Jellyfin 10.7.0 server on Windows 10 x64 I can't start the web interface from http://localhost:8096 because the browser returns the error ERR_CONNECTION_REFUSED.

However, I can access the web interface from http://(local-ip):8096.

I can't access from http://127.0.0.1:8096 either.

Where is the problem?

**Comment by manjotsc** [comment]
@morralletti I have the same problem after updating,

Ubuntu 20.04 LTS

**Comment by Resurrection2981** [comment]
> @morralletti更新后，我有同样的问题，即使在新机器上安装 jellyfin 也会出现相同的行为。
> 
> Ubuntu 20.04 LTS
> 
> **登录更新的 VM Ubuntu 20.04**
> 
> ```
> [2021-03-12 01:28:22.142 +00:00] [INF] [4] Main: Jellyfin version: "10.7.0"
> [2021-03-12 01:28:22.169 +00:00] [INF] [4] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /var/log/jellyfin/logs]"]
> [2021-03-12 01:28:22.173 +00:00] [INF] [4] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--logdir", "/var/log/jelly>
> [2021-03-12 01:28:22.174 +00:00] [INF] [4] Main: Operating system: "Linux"
> [2021-03-12 01:28:22.174 +00:00] [INF] [4] Main: Architecture: X64
> [2021-03-12 01:28:22.175 +00:00] [INF] [4] Main: 64-Bit Process: True
> [2021-03-12 01:28:22.175 +00:00] [INF] [4] Main: User Interactive: True
> [2021-03-12 01:28:22.175 +00:00] [INF] [4] Main: Processor count: 4
> [2021-03-12 01:28:22.175 +00:00] [INF] [4] Main: Program data path: "/root/.local/share/jellyfin"
> [2021-03-12 01:28:22.176 +00:00] [INF] [4] Main: Web resources path: "/usr/lib/jellyfin/bin/jellyfin-web"
> [2021-03-12 01:28:22.176 +00:00] [INF] [4] Main: Application directory: "/usr/lib/jellyfin/bin/"
> [2021-03-12 01:28:22.340 +00:00] [INF] [4] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: ">
> [2021-03-12 01:28:22.393 +00:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[127.0.0.1/8,1>
> [2021-03-12 01:28:22.394 +00:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
> [2021-03-12 01:28:22.394 +00:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[127.0.0.1/8,10.0>
> [2021-03-12 01:28:22.403 +00:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
> [2021-03-12 01:28:22.403 +00:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
> [2021-03-12 01:28:22.412 +00:00] [FTL] [4] Main: Error while starting server.
> System.InvalidOperationException: The server is expected to host the web client, but the provided content directory is either >
>    at Jellyfin.Server.Program.StartApp(StartupOptions options)
> [2021-03-12 01:28:22.417 +00:00] [INF] [4] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
> [2021-03-12 01:28:22.418 +00:00] [INF] [2] Main: Received a SIGTERM signal, shutting down](url)
> ```
> 
> **登录新虚拟机**
> 
> ```
> [2021-03-11 23:23:30.625 -05:00] [INF] [1] Main: Jellyfin version: "10.7.0"
> [2021-03-11 23:23:30.686 -05:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /var/log/jellyfin/jellyfin/log]"]
> [2021-03-11 23:23:30.708 -05:00] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll"]
> [2021-03-11 23:23:30.712 -05:00] [INF] [1] Main: Operating system: "Linux"
> [2021-03-11 23:23:30.717 -05:00] [INF] [1] Main: Architecture: X64
> [2021-03-11 23:23:30.720 -05:00] [INF] [1] Main: 64-Bit Process: True
> [2021-03-11 23:23:30.722 -05:00] [INF] [1] Main: User Interactive: True
> [2021-03-11 23:23:30.724 -05:00] [INF] [1] Main: Processor count: 4
> [2021-03-11 23:23:30.728 -05:00] [INF] [1] Main: Program data path: "/var/log/jellyfin/jellyfin"
> [2021-03-11 23:23:30.736 -05:00] [INF] [1] Main: Web resources path: "/usr/lib/jellyfin/bin/jellyfin-web"
> [2021-03-11 23:23:30.744 -05:00] [INF] [1] Main: Application directory: "/usr/lib/jellyfin/bin/"
> [2021-03-11 23:23:31.589 -05:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/root/.cache/jellyfin"
> [2021-03-11 23:23:31.701 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
> [2021-03-11 23:23:31.704 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
> [2021-03-11 23:23:31.706 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
> [2021-03-11 23:23:31.717 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
> [2021-03-11 23:23:31.719 -05:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
> [2021-03-11 23:23:31.811 -05:00] [FTL] [1] Main: Error while starting server.
> System.InvalidOperationException: The server is expected to host the web client, but the provided content directory is either invalid or empty: /usr/lib/jellyfin/bin/jellyfin-web. If you do not want to host the>   at Jellyfin.Server.Program.StartApp(StartupOptions options)
> [2021-03-11 23:23:31.835 -05:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing "CoreAppHost"
> [2021-03-11 23:23:31.838 -05:00] [INF] [2] Main: Received a SIGTERM signal, shutting down
> ```

I have the same issue on Ubuntu 20.04

**Comment by BaronGreenback** [comment]
It looks like it cannot find the web content at /usr/lib/jellyfin/bin/jellyfin-web

Does that folder exists, and does the account JF runs under have access to it?

**Comment by manjotsc** [comment]
@BaronGreenback jellyfin-web is missing under bin.

**Comment by BaronGreenback** [comment]
That usually happens when the web files are not correct for the version of JF.

Did you install JF 10.7, or one of the 10.7.RC versions - as i beleve they didn't have the web components bundled with them?

**Comment by manjotsc** [comment]
How can I check if its rc or regular? I just ran apt update.

**Comment by manjotsc** [comment]
Solved here https://www.reddit.com/r/jellyfin/comments/m38sqo/cannot_start_jellyfin_server/

**Comment by BaronGreenback** [comment]
Is this still in an issue with the latest version?

**Comment by TimB0** [comment]
> Solved here https://www.reddit.com/r/jellyfin/comments/m38sqo/cannot_start_jellyfin_server/

This is still happening to me....the guy deleted his comments and you didnt say how you fixed the web part
