### ISSUE TITLE
Hardware accelerated transcoding doesn't work properly

### ISSUE THREAD

**Issue by ErinnerMO** [jellyfin/jellyfin#5527]
**Describe the bug**
When I play a hevc video, hardware accelerated transcoding doesn't work properly.And then i monitored the load of CPU and GPU. It seems that GPU decoding is not working properly?

**System**
 - OS:Ubuntu 20.04.1 LTS
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Chrome 89.0.4389.82
 - Jellyfin Version:10.7.0
 - Playback:Transcode
 - Installed Plugins: none
 - Reverse Proxy:none
 - Base URL: none
 - Networking: LAN
 - Storage:local
 - CPU:AMD Ryzen 3 PRO 3200GE w/ Radeon Vega Graphics
 - GPU:AMD Radeon RX470

**To Reproduce**
Playing hevc video.

**Expected behavior**
Smooth transcoding and playing.

**Logs**
```
/videos/a13343dc-4ad3-7296-2c87-2a96f0ca5ef3/hls1/main/0.ts

{"Protocol":0,"Id":"a13343dc4ad372962c872a96f0ca5ef3","Path":"/media/SnapRaidPool/MediaLibrary/Video/Film/\u94A2\u94C1\u4FA0 Iron.Man.2008.FRA.UHD.Blu-ray.2160p.HEVC.TrueHD.Atmos.7.1-Pete@HDSky/Iron Man - 4K Ultra HD.iso","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mpegts","Size":69400608768,"Name":"Iron Man - 4K Ultra HD/ISO","IsRemote":false,"ETag":"0d409edcb75ad7c312346dd4aa9e80be","RunTimeTicks":75600519168,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":false,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":1,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"hevc","CodecTag":"HDMV","Language":null,"ColorRange":null,"ColorSpace":"bt2020nc","ColorTransfer":"smpte2084","ColorPrimaries":"bt2020","Comment":null,"TimeBase":"1/90000","CodecTimeBase":"1001/24000","Title":null,"VideoRange":"HDR","localizedUndefined":null,"localizedDefault":null,"localizedForced":null,"DisplayTitle":"4K HEVC HDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":73439290,"BitDepth":null,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":2160,"Width":3840,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"Main 10","Type":1,"AspectRatio":"16:9","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":153,"IsAnamorphic":null},{"Codec":"hevc","CodecTag":"HDMV","Language":null,"ColorRange":null,"ColorSpace":"bt2020nc","ColorTransfer":"smpte2084","ColorPrimaries":"bt2020","Comment":null,"TimeBase":"1/90000","CodecTimeBase":"1001/24000","Title":null,"VideoRange":"HDR","localizedUndefined":null,"localizedDefault":null,"localizedForced":null,"DisplayTitle":"1080p HEVC HDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":73439290,"BitDepth":null,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":1080,"Width":1920,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"Main 10","Type":1,"AspectRatio":"16:9","Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":153,"IsAnamorphic":null},{"Codec":"truehd","CodecTag":"AC-3","Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":"1/48000","Title":null,"VideoRange":null,"localizedUndefined":null,"localizedDefault":null,"localizedForced":null,"DisplayTitle":"TRUEHD - 7.1","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"7.1","BitRate":null,"BitDepth":24,"RefFrames":null,"PacketLength":null,"Channels":8,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"ac3","CodecTag":"AC-3","Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":"1/48000","Title":null,"VideoRange":null,"localizedUndefined":null,"localizedDefault":null,"localizedForced":null,"DisplayTitle":"Dolby Digital - 5.1","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"5.1","BitRate":384000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":6,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":3,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"dts","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":"1/48000","Title":null,"VideoRange":null,"localizedUndefined":null,"localizedDefault":null,"localizedForced":null,"DisplayTitle":"DTS - 7.1","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"7.1","BitRate":null,"BitDepth":24,"RefFrames":null,"PacketLength":null,"Channels":8,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"DTS-HD MA","Type":0,"AspectRatio":null,"Index":4,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"dts","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":"1/48000","Title":null,"VideoRange":null,"localizedUndefined":null,"localizedDefault":null,"localizedForced":null,"DisplayTitle":"DTS - 7.1","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"7.1","BitRate":null,"BitDepth":24,"RefFrames":null,"PacketLength":null,"Channels":8,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"DTS-HD MA","Type":0,"AspectRatio":null,"Index":5,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"PGSSUB","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":"0/1","Title":null,"VideoRange":null,"localizedUndefined":"\u672A\u5B9A\u4E49","localizedDefault":"\u9ED8\u8BA4","localizedForced":"\u5F3A\u5236\u7684","DisplayTitle":"\u672A\u5B9A\u4E49","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":6,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"PGSSUB","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":"0/1","Title":null,"VideoRange":null,"localizedUndefined":"\u672A\u5B9A\u4E49","localizedDefault":"\u9ED8\u8BA4","localizedForced":"\u5F3A\u5236\u7684","DisplayTitle":"\u672A\u5B9A\u4E49","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":7,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"PGSSUB","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":"0/1","Title":null,"VideoRange":null,"localizedUndefined":"\u672A\u5B9A\u4E49","localizedDefault":"\u9ED8\u8BA4","localizedForced":"\u5F3A\u5236\u7684","DisplayTitle":"\u672A\u5B9A\u4E49","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":8,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"PGSSUB","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":"0/1","Title":null,"VideoRange":null,"localizedUndefined":"\u672A\u5B9A\u4E49","localizedDefault":"\u9ED8\u8BA4","localizedForced":"\u5F3A\u5236\u7684","DisplayTitle":"\u672A\u5B9A\u4E49","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":9,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"PGSSUB","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":"0/1","Title":null,"VideoRange":null,"localizedUndefined":"\u672A\u5B9A\u4E49","localizedDefault":"\u9ED8\u8BA4","localizedForced":"\u5F3A\u5236\u7684","DisplayTitle":"\u672A\u5B9A\u4E49","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":10,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"PGSSUB","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":"0/1","Title":null,"VideoRange":null,"localizedUndefined":"\u672A\u5B9A\u4E49","localizedDefault":"\u9ED8\u8BA4","localizedForced":"\u5F3A\u5236\u7684","DisplayTitle":"\u672A\u5B9A\u4E49","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":11,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"PGSSUB","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":"0/1","Title":null,"VideoRange":null,"localizedUndefined":"\u672A\u5B9A\u4E49","localizedDefault":"\u9ED8\u8BA4","localizedForced":"\u5F3A\u5236\u7684","DisplayTitle":"\u672A\u5B9A\u4E49","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":12,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"PGSSUB","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":"0/1","Title":null,"VideoRange":null,"localizedUndefined":"\u672A\u5B9A\u4E49","localizedDefault":"\u9ED8\u8BA4","localizedForced":"\u5F3A\u5236\u7684","DisplayTitle":"\u672A\u5B9A\u4E49","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":13,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":73439290,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -vaapi_device /dev/dri/renderD128 -i bluray:"/media/SnapRaidPool/MediaLibrary/Video/Film/閽㈤搧渚� Iron.Man.2008.FRA.UHD.Blu-ray.2160p.HEVC.TrueHD.Atmos.7.1-Pete@HDSky/Iron Man - 4K Ultra HD.iso" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:2 -codec:v:0 h264_vaapi -b:v 9360000 -maxrate 9360000 -bufsize 18720000 -profile:v:0 high -level 41  -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -filter_complex "[0:12]scale=1920x1080[sub];[0:0]format=nv12|vaapi,hwupload,scale_vaapi=w=1920:h=1080:format=nv12,hwdownload[base];[base][sub]overlay,format=nv12,hwupload" -start_at_zero -vsync -1 -codec:a:0 aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/2ac3bfa98f468331ef8d2a39d2da76a9%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/2ac3bfa98f468331ef8d2a39d2da76a9.m3u8"


ffmpeg version 4.3.1-Jellyfin Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-gpl --enable-version3 --enable-static --enable-libfontconfig --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-ffnvcodec
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
index_parse.c:224: index.bdmv: unknown data in extension 3.1: 0x00 0x00 0x01 0x00 0x00000000
bluray.c:1068: WARNING: BluRay profile 6 BD-J menu support is experimental
[bluray @ 0x559a40070c80] 1 usable playlists:
[bluray @ 0x559a40070c80] playlist 00006.mpls (2:06:00)
[bluray @ 0x559a40070c80] selected 00006.mpls
[hevc @ 0x559a40082e00] Skipping NAL unit 62
[mpegts @ 0x559a400700c0] start time for stream 6 is not set in estimate_timings_from_pts
[mpegts @ 0x559a400700c0] start time for stream 7 is not set in estimate_timings_from_pts
[mpegts @ 0x559a400700c0] start time for stream 9 is not set in estimate_timings_from_pts
[mpegts @ 0x559a400700c0] start time for stream 10 is not set in estimate_timings_from_pts
[mpegts @ 0x559a400700c0] start time for stream 11 is not set in estimate_timings_from_pts
[mpegts @ 0x559a400700c0] start time for stream 12 is not set in estimate_timings_from_pts
[mpegts @ 0x559a400700c0] start time for stream 13 is not set in estimate_timings_from_pts
bluray.c:255: 00008.m2ts: no timestamp for SPN 0 (got 0). clip 188955000-529179874.
[mpegts @ 0x559a400700c0] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x559a400700c0] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x559a400700c0] Could not find codec parameters for stream 9 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x559a400700c0] Could not find codec parameters for stream 10 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x559a400700c0] Could not find codec parameters for stream 11 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x559a400700c0] Could not find codec parameters for stream 12 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 0x559a400700c0] Could not find codec parameters for stream 13 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from 'bluray:/media/SnapRaidPool/MediaLibrary/Video/Film/閽㈤搧渚� Iron.Man.2008.FRA.UHD.Blu-ray.2160p.HEVC.TrueHD.Atmos.7.1-Pete@HDSky/Iron Man - 4K Ultra HD.iso':
  Duration: 02:06:00.05, start: 4199.000000, bitrate: 73439 kb/s
  Program 1 
    Stream #0:0[0x1011]: Video: hevc (Main 10) (HDMV / 0x564D4448), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 23.98 tbc
    Stream #0:1[0x1015]: Video: hevc (Main 10) (HDMV / 0x564D4448), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 90k tbn, 23.98 tbc
    Stream #0:2[0x1100]: Audio: truehd (AC-3 / 0x332D4341), 48000 Hz, 7.1, s32 (24 bit)
    Stream #0:3[0x1100]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, 5.1(side), fltp, 384 kb/s
    Stream #0:4[0x1101]: Audio: dts (DTS-HD MA) ([134][0][0][0] / 0x0086), 48000 Hz, 7.1, s32p (24 bit)
    Stream #0:5[0x1102]: Audio: dts (DTS-HD MA) ([134][0][0][0] / 0x0086), 48000 Hz, 7.1, s32p (24 bit)
    Stream #0:6[0x12a0]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090)
    Stream #0:7[0x12a1]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090)
    Stream #0:8[0x12a2]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090), 1920x1080
    Stream #0:9[0x12a3]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090)
    Stream #0:10[0x12a4]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090)
    Stream #0:11[0x12a5]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090)
    Stream #0:12[0x12a6]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090)
    Stream #0:13[0x12a7]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090)
Stream mapping:
  Stream #0:0 (hevc) -> format (graph 0)
  Stream #0:12 (pgssub) -> scale (graph 0)
  hwupload (graph 0) -> Stream #0:0 (h264_vaapi)
  Stream #0:2 -> #0:1 (truehd (native) -> aac (native))
Press [q] to stop, [?] for help
[mpegts @ 0x559a400700c0] sub2video: using 3840x2160 canvas
[h264_vaapi @ 0x559a40c78300] Driver does not support some wanted packed headers (wanted 0xd, found 0).
[h264_vaapi @ 0x559a40c78300] Driver does not support packed sequence headers, but a global header is requested.
[h264_vaapi @ 0x559a40c78300] No global header will be written: this may result in a stream which is not usable for some purposes (e.g. not muxable to some containers).
Output #0, hls, to '/config/transcodes/2ac3bfa98f468331ef8d2a39d2da76a9.m3u8':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (h264_vaapi) (High), vaapi_vld, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 9360 kb/s, 23.98 fps, 90k tbn, 23.98 tbc (default)
    Metadata:
      encoder         : Lavc58.91.100 h264_vaapi
    Stream #0:1: Audio: aac (LC), 48000 Hz, 5.1, fltp (24 bit), 640 kb/s
    Metadata:
      encoder         : Lavc58.91.100 aac
frame=    5 fps=0.0 q=-0.0 size=N/A time=00:00:00.29 bitrate=N/A speed=0.521x    
frame=   11 fps= 10 q=-0.0 size=N/A time=00:00:00.55 bitrate=N/A speed=0.51x    
frame=   16 fps=9.6 q=-0.0 size=N/A time=00:00:00.78 bitrate=N/A speed=0.474x    
frame=   21 fps=9.5 q=-0.0 size=N/A time=00:00:00.98 bitrate=N/A speed=0.446x    
frame=   26 fps=9.5 q=-0.0 size=N/A time=00:00:01.19 bitrate=N/A speed=0.438x    
frame=   32 fps=9.6 q=-0.0 size=N/A time=00:00:01.42 bitrate=N/A speed=0.427x    
frame=   38 fps=9.7 q=-0.0 size=N/A time=00:00:01.68 bitrate=N/A speed=0.432x    
frame=   44 fps=9.7 q=-0.0 size=N/A time=00:00:01.94 bitrate=N/A speed=0.43x    
frame=   49 fps=9.8 q=-0.0 size=N/A time=00:00:02.19 bitrate=N/A speed=0.438x    
frame=   54 fps=9.7 q=-0.0 size=N/A time=00:00:02.34 bitrate=N/A speed=0.421x    
frame=   60 fps=9.8 q=-0.0 size=N/A time=00:00:02.60 bitrate=N/A speed=0.425x    
frame=   65 fps=9.8 q=-0.0 size=N/A time=00:00:02.85 bitrate=N/A speed=0.432x    
frame=   70 fps=9.8 q=-0.0 size=N/A time=00:00:03.02 bitrate=N/A speed=0.422x    
[hls @ 0x559a40c87f00] Opening '/config/transcodes/2ac3bfa98f468331ef8d2a39d2da76a90.ts' for writing
frame=   76 fps=9.9 q=-0.0 size=N/A time=00:00:03.28 bitrate=N/A speed=0.427x    
frame=   81 fps=9.8 q=-0.0 size=N/A time=00:00:03.47 bitrate=N/A speed=0.42x    
frame=   86 fps=9.8 q=-0.0 size=N/A time=00:00:03.69 bitrate=N/A speed=0.42x    
frame=   91 fps=9.8 q=-0.0 size=N/A time=00:00:03.88 bitrate=N/A speed=0.417x    
frame=   97 fps=9.8 q=-0.0 size=N/A time=00:00:04.13 bitrate=N/A speed=0.417x    
frame=  103 fps=9.8 q=-0.0 size=N/A time=00:00:04.39 bitrate=N/A speed=0.417x    
frame=  110 fps=9.9 q=-0.0 size=N/A time=00:00:04.69 bitrate=N/A speed=0.421x    
frame=  117 fps= 10 q=-0.0 size=N/A time=00:00:04.97 bitrate=N/A speed=0.424x    
frame=  123 fps= 10 q=-0.0 size=N/A time=00:00:05.22 bitrate=N/A speed=0.426x    
frame=  129 fps= 10 q=-0.0 size=N/A time=00:00:05.48 bitrate=N/A speed=0.426x    
frame=  134 fps= 10 q=-0.0 size=N/A time=00:00:05.67 bitrate=N/A speed=0.424x    
frame=  140 fps= 10 q=-0.0 size=N/A time=00:00:05.93 bitrate=N/A speed=0.424x    
[hls @ 0x559a40c87f00] Opening '/config/transcodes/2ac3bfa98f468331ef8d2a39d2da76a91.ts' for writing
frame=  146 fps= 10 q=-0.0 size=N/A time=00:00:06.18 bitrate=N/A speed=0.424x    
frame=  152 fps= 10 q=-0.0 size=N/A time=00:00:06.44 bitrate=N/A speed=0.425x    
frame=  157 fps= 10 q=-0.0 size=N/A time=00:00:06.63 bitrate=N/A speed=0.422x    
frame=  164 fps= 10 q=-0.0 size=N/A time=00:00:06.93 bitrate=N/A speed=0.425x    
frame=  169 fps= 10 q=-0.0 size=N/A time=00:00:07.14 bitrate=N/A speed=0.422x    
frame=  175 fps= 10 q=-0.0 size=N/A time=00:00:07.44 bitrate=N/A speed=0.427x    
frame=  180 fps= 10 q=-0.0 size=N/A time=00:00:07.65 bitrate=N/A speed=0.426x    
frame=  185 fps= 10 q=-0.0 size=N/A time=00:00:07.85 bitrate=N/A speed=0.424x    
frame=  191 fps= 10 q=-0.0 size=N/A time=00:00:08.10 bitrate=N/A speed=0.424x    
frame=  197 fps= 10 q=-0.0 size=N/A time=00:00:08.29 bitrate=N/A speed=0.422x    
frame=  202 fps= 10 q=-0.0 size=N/A time=00:00:08.55 bitrate=N/A speed=0.423x    
frame=  208 fps= 10 q=-0.0 size=N/A time=00:00:08.78 bitrate=N/A speed=0.423x    
frame=  212 fps= 10 q=-0.0 size=N/A time=00:00:08.98 bitrate=N/A speed=0.422x    
[hls @ 0x559a40c87f00] Opening '/config/transcodes/2ac3bfa98f468331ef8d2a39d2da76a92.ts' for writing
frame=  218 fps= 10 q=-0.0 size=N/A time=00:00:09.19 bitrate=N/A speed=0.42x    
frame=  222 fps=9.9 q=-0.0 size=N/A time=00:00:09.45 bitrate=N/A speed=0.422x    
frame=  227 fps=9.9 q=-0.0 size=N/A time=00:00:09.62 bitrate=N/A speed=0.419x    
frame=  232 fps=9.9 q=-0.0 size=N/A time=00:00:09.81 bitrate=N/A speed=0.418x    
frame=  237 fps=9.9 q=-0.0 size=N/A time=00:00:10.02 bitrate=N/A speed=0.417x    
frame=  242 fps=9.8 q=-0.0 size=N/A time=00:00:10.21 bitrate=N/A speed=0.416x    
frame=  248 fps=9.9 q=-0.0 size=N/A time=00:00:10.45 bitrate=N/A speed=0.415x    
frame=  253 fps=9.8 q=-0.0 size=N/A time=00:00:10.64 bitrate=N/A speed=0.413x    
frame=  260 fps=9.9 q=-0.0 size=N/A time=00:00:10.98 bitrate=N/A speed=0.416x    
frame=  266 fps=9.9 q=-0.0 size=N/A time=00:00:11.17 bitrate=N/A speed=0.414x    
frame=  271 fps=9.9 q=-0.0 size=N/A time=00:00:11.45 bitrate=N/A speed=0.417x    
frame=  276 fps=9.9 q=-0.0 size=N/A time=00:00:11.66 bitrate=N/A speed=0.417x    
frame=  282 fps=9.9 q=-0.0 size=N/A time=00:00:11.86 bitrate=N/A speed=0.415x    
frame=  288 fps=9.9 q=-0.0 size=N/A time=00:00:12.13 bitrate=N/A speed=0.417x    
[hls @ 0x559a40c87f00] Opening '/config/transcodes/2ac3bfa98f468331ef8d2a39d2da76a93.ts' for writing
frame=  293 fps=9.9 q=-0.0 size=N/A time=00:00:12.37 bitrate=N/A speed=0.417x    
frame=  298 fps=9.8 q=-0.0 size=N/A time=00:00:12.52 bitrate=N/A speed=0.414x    
frame=  303 fps=9.8 q=-0.0 size=N/A time=00:00:12.80 bitrate=N/A speed=0.416x    
frame=  308 fps=9.8 q=-0.0 size=N/A time=00:00:12.97 bitrate=N/A speed=0.413x    
frame=  312 fps=9.8 q=-0.0 size=N/A time=00:00:13.16 bitrate=N/A speed=0.412x    
frame=  317 fps=9.7 q=-0.0 size=N/A time=00:00:13.35 bitrate=N/A speed=0.41x    
frame=  323 fps=9.7 q=-0.0 size=N/A time=00:00:13.61 bitrate=N/A speed=0.41x    
frame=  329 fps=9.7 q=-0.0 size=N/A time=00:00:13.84 bitrate=N/A speed=0.41x    
frame=  334 fps=9.7 q=-0.0 size=N/A time=00:00:14.10 bitrate=N/A speed=0.411x    
frame=  339 fps=9.7 q=-0.0 size=N/A time=00:00:14.29 bitrate=N/A speed=0.411x    
frame=  344 fps=9.7 q=-0.0 size=N/A time=00:00:14.48 bitrate=N/A speed=0.41x    
frame=  350 fps=9.8 q=-0.0 size=N/A time=00:00:14.69 bitrate=N/A speed=0.41x    
frame=  355 fps=9.7 q=-0.0 size=N/A time=00:00:14.95 bitrate=N/A speed=0.411x    
[hls @ 0x559a40c87f00] Opening '/config/transcodes/2ac3bfa98f468331ef8d2a39d2da76a94.ts' for writing
frame=  361 fps=9.8 q=-0.0 size=N/A time=00:00:15.14 bitrate=N/A speed=0.41x    
frame=  366 fps=9.8 q=-0.0 size=N/A time=00:00:15.38 bitrate=N/A speed=0.411x    
frame=  370 fps=9.7 q=-0.0 size=N/A time=00:00:15.53 bitrate=N/A speed=0.408x    
frame=  375 fps=9.7 q=-0.0 size=N/A time=00:00:15.72 bitrate=N/A speed=0.407x    
frame=  381 fps=9.7 q=-0.0 size=N/A time=00:00:15.97 bitrate=N/A speed=0.407x    
frame=  385 fps=9.7 q=-0.0 size=N/A time=00:00:16.17 bitrate=N/A speed=0.407x    
frame=  389 fps=9.7 q=-0.0 size=N/A time=00:00:16.34 bitrate=N/A speed=0.406x    
frame=  394 fps=9.7 q=-0.0 size=N/A time=00:00:16.59 bitrate=N/A speed=0.407x    
frame=  400 fps=9.7 q=-0.0 size=N/A time=00:00:16.78 bitrate=N/A speed=0.405x    
frame=  406 fps=9.7 q=-0.0 size=N/A time=00:00:17.04 bitrate=N/A speed=0.406x    
frame=  412 fps=9.7 q=-0.0 size=N/A time=00:00:17.30 bitrate=N/A speed=0.406x    
frame=  417 fps=9.7 q=-0.0 size=N/A time=00:00:17.55 bitrate=N/A speed=0.408x    
frame=  422 fps=9.7 q=-0.0 size=N/A time=00:00:17.70 bitrate=N/A speed=0.406x    
frame=  427 fps=9.7 q=-0.0 size=N/A time=00:00:17.96 bitrate=N/A speed=0.407x    
frame=  432 fps=9.7 q=-0.0 size=N/A time=00:00:18.15 bitrate=N/A speed=0.407x    
[hls @ 0x559a40c87f00] Opening '/config/transcodes/2ac3bfa98f468331ef8d2a39d2da76a95.ts' for writing
frame=  438 fps=9.7 q=-0.0 size=N/A time=00:00:18.38 bitrate=N/A speed=0.407x    
frame=  444 fps=9.7 q=-0.0 size=N/A time=00:00:18.60 bitrate=N/A speed=0.406x    
frame=  449 fps=9.7 q=-0.0 size=N/A time=00:00:18.83 bitrate=N/A speed=0.407x    
frame=  454 fps=9.7 q=-0.0 size=N/A time=00:00:19.02 bitrate=N/A speed=0.406x    
frame=  458 fps=9.7 q=-0.0 size=N/A time=00:00:19.24 bitrate=N/A speed=0.406x    
frame=  463 fps=9.7 q=-0.0 size=N/A time=00:00:19.41 bitrate=N/A speed=0.405x    
frame=  469 fps=9.7 q=-0.0 size=N/A time=00:00:19.66 bitrate=N/A speed=0.406x    
frame=  473 fps=9.7 q=-0.0 size=N/A time=00:00:19.81 bitrate=N/A speed=0.405x    
frame=  478 fps=9.6 q=-0.0 size=N/A time=00:00:20.05 bitrate=N/A speed=0.404x    
[hls @ 0x559a40c87f00] Opening '/config/transcodes/2ac3bfa98f468331ef8d2a39d2da76a96.ts' for writing
frame=  479 fps=9.6 q=-0.0 Lsize=N/A time=00:00:20.16 bitrate=N/A speed=0.405x    
video:22913kB audio:268kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[aac @ 0x559a40c57440] Qavg: 65536.000
```

**Additional context**
The playback is not smooth, and the CPU load is high, reaching about 70%. Using sudo radeontop to monitor GPU, the load is 0%.But if hardware accelerated transcoding is not enabled, the CPU load should be above 100%, which makes me confused. Because I have two graphics cards, I don't know which one of them is render128.

Is this a driver problem and how can I solve it?

I follow the [Hardware Acceleration](https://jellyfin.org/docs/general/administration/hardware-acceleration.html) guidelines to use vaapi.

Here is some information:

`sudo vainfo`
```
error: XDG_RUNTIME_DIR not set in the environment.
No protocol specified
error: can't connect to X server!
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.6.0)
vainfo: Driver version: Mesa Gallium driver 21.0.0 - kisak-mesa PPA for AMD Radeon (TM) RX 470 Graphics (POLARIS10, DRM 3.38.0, 5.8.0-45-generic, LLVM 11.0.1)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```

`glxinfo | grep Mesa`
```
client glx vendor string: Mesa Project and SGI
    Vendor: Mesa/X.org (0xffffffff)
OpenGL vendor string: Mesa/X.org
OpenGL core profile version string: 4.5 (Core Profile) Mesa 21.0.0 - kisak-mesa PPA
OpenGL version string: 3.1 Mesa 21.0.0 - kisak-mesa PPA
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.0.0 - kisak-mesa PPA
```

`lshw -C display`
```
WARNING: you should run this program as super-user.
  *-display                 
       description: VGA compatible controller
       product: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:10:00.0
       version: cf
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:87 memory:d0000000-dfffffff memory:e0000000-e01fffff ioport:f000(size=256) memory:fcf00000-fcf3ffff memory:fcf40000-fcf5ffff
  *-display
       description: VGA compatible controller
       product: Picasso
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:28:00.0
       version: db
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list
       configuration: driver=amdgpu latency=0
       resources: irq:77 memory:b0000000-bfffffff memory:c0000000-c01fffff ioport:d000(size=256) memory:fca00000-fca7ffff
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.

```

**Comment by nyanmisaka** [comment]
You have to check the HEVC codec in dashboard manually.

**Comment by ErinnerMO** [comment]
> You have to check the HEVC codec in dashboard manually.

How can I check hevc codec in dashboard?I used linux system with separate graphics card for the first time and used headless Linux server before.

**Comment by jacobrham** [comment]
> > You have to check the HEVC codec in dashboard manually.
> 
> How can I check hevc codec in dashboard?I used linux system with separate graphics card for the first time and used headless Linux server before.

Navigate to your dashboard by logging into jellyfin from a browser as an admin. Open the hamburger menu on the top left of the screen and click "dashboard". Then, click Playback on the left hand menu and ensure hardware acceleration is enabled and all the following are checked: Allow decoding for HEVC, Enable 10-bit hardware decoding for HEVC, Enable Hardware encoding, allow encoding in HEVC format. Here's a picture of what mine looks like (using an Nvidia GPU, you'll have to select the encoding method proper to your graphics card).

![image](https://user-images.githubusercontent.com/35405092/111181828-bd1e7800-8584-11eb-98aa-f16b3b1869d0.png)

**Comment by ErinnerMO** [comment]
> > > You have to check the HEVC codec in dashboard manually.
> > 
> > 
> > How can I check hevc codec in dashboard?I used linux system with separate graphics card for the first time and used headless Linux server before.
> 
> Navigate to your dashboard by logging into jellyfin from a browser as an admin. Open the hamburger menu on the top left of the screen and click "dashboard". Then, click Playback on the left hand menu and ensure hardware acceleration is enabled and all the following are checked: Allow decoding for HEVC, Enable 10-bit hardware decoding for HEVC, Enable Hardware encoding, allow encoding in HEVC format. Here's a picture of what mine looks like (using an Nvidia GPU, you'll have to select the encoding method proper to your graphics card).
> 
> ![image](https://user-images.githubusercontent.com/35405092/111181828-bd1e7800-8584-11eb-98aa-f16b3b1869d0.png)

I have confirmed my current configuration page as shown.I didn't change the configuration after checking the log.Device `/dev/dri/renderD128` is the render I pass into docker.As mentioned above, I followed the amdgpu configuration in VAAPI of [Hardware Acceleration](https://jellyfin.org/docs/general/administration/hardware-acceleration.html) and upgraded mesa to 21.0.0

I checked the transcoding of h264 and it seems to be working properly. But it's not working properly in hevc transcoding, which makes me confused

![image](https://user-images.githubusercontent.com/57552242/111687084-d82f0780-8864-11eb-8668-def296090b19.png)

**Comment by jacobrham** [comment]
Can you pass `/dev/dri/renderD129` to docker and configuring Jellyfin to transcode with it?

**Comment by yaspoon** [comment]
I've got the same problem. Running the ffmpeg command manually produces the following errors when trying to transcode HEVC.

`/usr/bin/ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i file:"/path/to/hevc_file.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:2 -map -0:s -codec:v:0 h264_nvenc -preset medium -b:v 5176475 -maxrate 5176475 -bufsize 10352950 -profile:v:0 high -g:v:0 72 -keyint_min:v:0 72 -sc_threshold:v:0 0 -start_at_zero -vsync -1 -codec:a:0 copy -strict -2 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/tmp/6429ceaa31729107c325da97c81baa8d%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/tmp/6429ceaa31729107c325da97c81baa8d.m3u8"`

[ffmpeg.log](https://github.com/jellyfin/jellyfin/files/6603704/ffmpeg.log)

Changing the command to use nvdec instead works fine.

`/usr/bin/ffmpeg -hwaccel nvdec -hwaccel_output_format nvdec -i file:"/path/to/hevc_file.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:2 -map -0:s -codec:v:0 h264_nvenc -preset medium -b:v 5176475 -maxrate 5176475 -bufsize 10352950 -profile:v:0 high -g:v:0 72 -keyint_min:v:0 72 -sc_threshold:v:0 0 -start_at_zero -vsync -1 -codec:a:0 copy -strict -2 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/tmp/6429ceaa31729107c325da97c81baa8d%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/tmp/6429ceaa31729107c325da97c81baa8d.m3u8"`

This server was running:
ArchLinux 5.12.6
Jellyfin-server 10.7.5
Jellyfin-web 10.7.5

nvidia 465.31 on a 1050ti

Jellyfin hardware acceleration was configured to use Nvidia NVENC

**Comment by nyanmisaka** [comment]
> I've got the same problem. Running the ffmpeg command manually produces the following errors when trying to transcode HEVC.
> 
> `/usr/bin/ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i file:"/path/to/hevc_file.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:2 -map -0:s -codec:v:0 h264_nvenc -preset medium -b:v 5176475 -maxrate 5176475 -bufsize 10352950 -profile:v:0 high -g:v:0 72 -keyint_min:v:0 72 -sc_threshold:v:0 0 -start_at_zero -vsync -1 -codec:a:0 copy -strict -2 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/tmp/6429ceaa31729107c325da97c81baa8d%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/tmp/6429ceaa31729107c325da97c81baa8d.m3u8"`
> 
> [ffmpeg.log](https://github.com/jellyfin/jellyfin/files/6603704/ffmpeg.log)
> 
> Changing the command to use nvdec instead works fine.
> 
> `/usr/bin/ffmpeg -hwaccel nvdec -hwaccel_output_format nvdec -i file:"/path/to/hevc_file.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:2 -map -0:s -codec:v:0 h264_nvenc -preset medium -b:v 5176475 -maxrate 5176475 -bufsize 10352950 -profile:v:0 high -g:v:0 72 -keyint_min:v:0 72 -sc_threshold:v:0 0 -start_at_zero -vsync -1 -codec:a:0 copy -strict -2 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/tmp/6429ceaa31729107c325da97c81baa8d%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/tmp/6429ceaa31729107c325da97c81baa8d.m3u8"`
> 
> This server was running:
> ArchLinux 5.12.6
> Jellyfin-server 10.7.5
> Jellyfin-web 10.7.5
> 
> nvidia 465.31 on a 1050ti
> 
> Jellyfin hardware acceleration was configured to use Nvidia NVENC

This should be fixed by https://github.com/jellyfin/jellyfin/pull/6053

**Comment by yaspoon** [comment]
Thanks for the quick reply. I changed the manual ffmpeg command to have the fixes in that pull request. It still throws the errors. But changing -extra_hw_frames 3 to -extra_hw_frames 5 solves the problem. This could be because I have the preset set to medium so the cpu is able to fly through frames. I will check that now.

**Comment by yaspoon** [comment]
Changing the preset from medium to slow still produces the errors. -extra_hw_frames 5 seems to be the only way get rid of the errors from ffmpeg.

**Comment by nyanmisaka** [comment]
The Polaris card issue have been fixed in upstream Mesa 22.0.
