### ISSUE TITLE
Jellyfin fetching metadata from TheAudioDb and MusicBrainz when providers are unchecked in library settings

### ISSUE THREAD

**Issue by SightSpirit** [jellyfin/jellyfin#5778]
**Describe the bug**
[Copied from a March 31 Matrix post.](https://matrix.to/#/!YjAUNWwLVbCthyFrkz:bonifacelabs.ca/$ZQbdX_GSpMmY0WZV4Nhps9Z85L_8uWFDRPfW6fhZc74?via=matrix.org&via=t2bot.io&via=privacytools.io) 

> A few days ago, I brought up a weird issue I was having where, despite all "Music Artist metadata" services' being unchecked in my Music library settings, I'm still getting data being pulled for artists automatically from both MusicBrainz and The AudioDB. I don't want that happening, as I prefer to create my own metadata—I'm a librarian by trade!—except sometimes with regard to images. Is this a bug? Is it happening to anyone else? This only started after updating to 10.7.0. (I don't know if it was fixed in the hotfix or not; I haven't had time to update yet.) It also has only affected the artists behind music I've newly added since the update, thankfully.
> 
> I finally got around to fiddling with settings and database files. No luck fixing the issue. I tried adding MusicBrainz and TheAudioDb to various `<DisabledMetadataFetchers>` elements, e.g. in system.xml, and nothing stopped JF from pulling artist images and metadata from these providers. I also investigated disabling or uninstalling the plugins, but they're baked into the binaries. I even poked through the source code for the server and Web client on GitHub for a couple hours the other day to see if I could determine if a bug were present in the code, but I couldn't identify one, based on my limited knowledge of the code base.

New info: Even if no metadata exists on those services for a given artist, if there is a record on one or both of them, Jellyfin will still add the ID(s) to the artist, which adds a link(s) to the artist page.

**System (please complete the following information):**
 - OS: Windows
 - Clients: jellyfin-web
 - Browser: Chrome 90 Beta / Chrome OS 90 Beta / Chrome 89
 - Jellyfin Version: 10.7.1 
 - Installed Plugins: AudioDB (built-in), LDAP-Auth, MusicBrainz (built-in), OMDb (built-in), Open Subtitles, Playback Reporting, Reports, Webhook (currently disabled)
 - Reverse Proxy: apache
 - Base URL: none(?)
 - Networking: NAT
 - Storage: local external HDD via USB 3

**To Reproduce**
1. Have an existing music library on Jellyfin.
2. In the library's settings, uncheck the metadata downloaders, especially the "Music Artist" ones.
3. Add a new song to the library, especially by a well-known artist. (Note that this _can_ be by an artist who is already in your library, but make sure you erase any metadata associated with that artist in advance if you want to reproduce this problem.)
4. Wait for the new music to be scanned in.
5. Go to the page of the artist associated with the new music, and observe how the page now includes one or more images, a biography of the artist, and/or links to the artist's AudioDb and/or MusicBrainz record.

**Expected behavior**
Artists should not have associated descriptions/overviews, images, external provider IDs, or links, except for those I added myself.

**Additional context**
I realize that I am probably in a tiny minority of JF users who don't like auto-populating their metadata, so this may or may not be a priority. Still, I find it a little absurd that metadata provider plugins are hardcoded into the server binaries and thus can't be uninstalled or even disabled. Plugins should not be mandatory; otherwise, they shouldn't be considered plugins but rather components of the software itself. (That's just my unprofessional, outside opinion, though; perhaps there's a well-considered decision that led to these plugins' being baked in.)

**Comment by giorgi-kiknavelidze** [comment]
Having the same problem as well. Not only that for some reason jellyfin shows artist pictures as covers on some albums.

**Comment by SightSpirit** [comment]
At some point since 10.7.2 (now on 10.7.5), "Fetcher Settings" buttons were added to the library settings' provider categories. I entered these and found that images were, indeed, checked for retrieval. I assume this is related.

These settings ignored the fact that the actual "AudioDB" provider was unchecked, which feels like an oversight.

Not yet sure if any of this affects the automatic fetching of artist descriptions into the "Overview" field; my guess is not.

**Comment by SightSpirit** [comment]
Still happens as of 10.7.7.

**Comment by 1337joe** [comment]
The `<DisabledMetadataFetchers>` tags in the server settings (system.xml) should work as of #6849, but the library settings still aren't affecting metadata queries for artists.

In case anyone else looks into this before I get back to it: The artists appear to be outside the library (or at least they don't have a parent or owner that trees back up to the library), so they use the default settings of "use everything that matches the type" instead of actually using the library settings.

**Comment by ppittle** [comment]
Did this get fixed in `v10.8` (guessing here 58be1d7)?

**Unable to reproduce in `#v10.8.4`** - UI settings appear to be appropriately respected:

![image](https://user-images.githubusercontent.com/1190907/186052327-5ab52c8b-ed09-4d76-8e93-2c47318a5b93.png)

**Comment by SightSpirit** [comment]
I believe that the issue was fixed in 10.8.0, yes. I haven't experienced any unwanted metadata fetches in recent memory.

**Comment by animaldaydream** [comment]
I am using latest official Docker image, running 10.8.9

The issue is absolutely still present. No settings for TheAudioDB have any effect whatsoever. I will get images retrieved no matter what.

I have wiped the metadata, cache and database files. I don't know whether that helps this, but the images are still retrieved.

I have also tried both disabling the main toggle and the ones on the submenu, and manually removing the images and then scanning again, no dice.

There is no way to disable this feature.

**Comment by micheal65536** [comment]
Same issue here on version 10.8.10.

I can't speak for whether or not "metadata" (setting the album etc. for files that don't have it tagged locally) sync is disabled as I haven't paid attention and all of my files so far include appropriate artist/album/etc. tags anyway, but artist and (in some cases) album photos are being downloaded even though I have disabled all of the "Image fetchers" settings (I have disabled the "TheAudioDB" entry that appears in each section and also opened the "Fetcher Settings" page and disabled all of the listed image types).

This is a blocking issue for me as I absolutely detest the automatic display of any metadata or artwork that I have not explicitly added myself or asked for. I am reluctant to do hackish firewall/host file workarounds as above (partly because it's ugly, partly because I don't want a failed refresh job constantly being retried in the background or some similar situation) and at this point I am considering abandoning the idea of setting up a centralised local media server and going back to manually copying my media library onto each device as I did up until yesterday.

**Comment by micheal65536** [comment]
It appears that a possible "official workaround" (without resorting to manually editing/deleting files or filtering network traffic) is to go to the "Albums" or "Artists" tab in the UI and manually remove the images and extra metadata for each artist where it has been automatically added.

I'm not sure if/when it will reappear by itself again though.

**Comment by JosBritton** [comment]
> It appears that a possible "official workaround" (without resorting to manually editing/deleting files or filtering network traffic) is to go to the "Albums" or "Artists" tab in the UI and manually remove the images and extra metadata for each artist where it has been automatically added.
> 
> I'm not sure if/when it will reappear by itself again though.

You can also block theaudiodb domains from the hosts file on your server as @animaldaydream said, but this only works for artists that have never had theaudiodb metadata applied before, because jellyfin seems to cache it somewhere (when I tried clearing my cache using the scheduled task it didn't get rid of it). I haven't looked into clearing it manually but it should be possible.

I ended up wiping my entire jellyfin install and started again with a hosts file setup before doing anything, and although the initial scan took a bit longer than normal due to jellyfin waiting for timeouts querying to the non-routable address, but it never grabbed any metadata from theaudiodb.

You definitely need to make sure to block theaudiodb's R2 bucket endpoint `r2.theaudiodb.com`, but I'm unsure about their other subdomains, I blocked everything i could find for good measure, example:

```
0.0.0.0	media.theaudiodb.com	www.theaudiodb.com	theaudiodb.com	r2.theaudiodb.com
```

**Comment by AlbertMarkovski** [comment]
> the initial scan took a bit longer than normal due to jellyfin waiting for timeouts querying to the non-routable address, it never grabbed any metadata from theaudiodb.

I used to hit this problem all the time where scans took forever due to running my Jellyfin server VM on a subnet without internet access. 

An effective workaround for preventing these excessive scan times is to make the musicbrainz requests fail immediately without timeout: 

- In the musicbrainz plugin settings, configure the server address to https://127.0.0.1 and rate limit to something low like .05

Another plus is you don't have to worry about missing an endpoint in your hosts file this way.

**Comment by Behem07h** [comment]
still happening on version 10.10.7. My album artists are showing up duplicated, once with the associated media folder path (ie music/artistname) as expected by the directory structure and unaltered from what I had set it to, but there is a second with path config/metadata/artists/slightly_reworded_artistname/artist.nfo

As best I can tell it seems to be from the metadata plugins, when I remove the entries in config/metadata/artists they get regenerated. My file metadata albumartist tag matches my directory structure. The metadata manager is of no help here as it only shows metadata associated to my media directories - entries in config/metadata are not visible there. I tried asking around the jellyfin discord server but many simply informed me they did not use jellyfin for music and so couldnt help

**Comment by Behem07h** [comment]
> * In the musicbrainz plugin settings, configure the server address to https://127.0.0.1 and rate limit to something low like .05

In the plugin settings, the rate limit description states "span of time between requests in seconds", and only seems to accept whole numbers. how did you set it to 0.05?

**Comment by AlbertMarkovski** [comment]
I just highlighted the contents and typed over it, clicked save, and it persisted. Using Firefox ESR if that matters.

**Comment by oshurkov** [comment]
Same issue here on version 10.10.7 

> despite all "Music Artist metadata" services' being unchecked in my Music library settings, I'm still getting data being pulled for artists automatically from both MusicBrainz and The AudioDB.

log 
```
[2025-10-16 05:30:52.375 +05:00] [ERR] [16] MediaBrowser.Providers.Music.ArtistMetadataService: Error in "MusicBrainz"
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
```

**Comment by oshurkov** [comment]
Same issue here on version 10.11.1

<img width="779" height="485" alt="Image" src="https://github.com/user-attachments/assets/1766c050-3a50-4575-8cbe-377ae16f9de9" />

**and setting plugins for speed up scaning** 
<img width="821" height="485" alt="Image" src="https://github.com/user-attachments/assets/797b5556-8bbc-4dc0-885f-18f4d47e6253" />

**logs:**
`[2025-11-04 14:48:18.837 +05:00] [ERR] [67] MediaBrowser.Providers.Music.ArtistMetadataService: Error in "MusicBrainz"
System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:80)`
<details><summary>details</summary>
<p>

[2025-11-04 14:48:18.837 +05:00] [ERR] [67] MediaBrowser.Providers.Music.ArtistMetadataService: Error in "MusicBrainz"
System.Net.Http.HttpRequestException: Connection refused (127.0.0.1:80)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.InjectNewHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at MetaBrainz.MusicBrainz.Query.PerformRequestAsync(Uri uri, HttpMethod method, HttpContent body, CancellationToken cancellationToken, String format)
   at MetaBrainz.MusicBrainz.Query.ApplyDelayAsync[T](Func`2 request, CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Objects.PagedQueryResults`3.PerformRequestAsync(CancellationToken cancellationToken)
   at MetaBrainz.MusicBrainz.Objects.PagedQueryResults`3.NextAsync(CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.MusicBrainz.MusicBrainzArtistProvider.GetSearchResults(ArtistInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Plugins.MusicBrainz.MusicBrainzArtistProvider.GetMetadata(ArtistInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

</p>
</details>

**Comment by grillonbleu** [comment]
This issue driving me nuts right now.

Some artists seem stuck with a musicbrainartistid and automatically download images on refresh. No matter if I delete the files and all fetching is disabled, they'll come back. There's some sticky data that's hard to pin down and quite bothersome. New users can plausibly go through the steps of enabling a library with defaults (meaning online image fetching is on), be annoyed with the images, disable the fetching and finally get stuck in this state.

To be more precise:

**Steps to reproduce**

* All Metadata and Image fetchers for music artists are disabled.

1. See that artist Glasser has automatically downloaded art, and an NFO file with a `musicbrainzartistid`.
2. Either delete the `/var/lib/jellyfin/metadata/artists/Glasser/` folder are delete images in the UI.
3. On the artist, in the UI, trigger a *Refresh Metadata/Replace all metadata/Replace existing images*.
4. Folder `/var/lib/jellyfin/metadata/artists/Glasser/` is back with all its files.

**Expected behaviour**

After disabling fetching AND manual deletion, MusicBrainz images are gone forever and do not come back.

**Other**

* Some known artists are unaffected (for example Air) possibly because I stopped the initial fetching before they were processed.
* Creating a new library doesn't resolve the issue.

**Comment by grillonbleu** [comment]
I tried uninstalling everything, reinstalling & carefully creating the music library without any fetching. Now I have **even** more artist images.

**Comment by emoxam** [comment]
can confirm it unckecked but still working somehow at 10.11.10
