### ISSUE TITLE
DLNA: Seek is not possible using LGTV

### ISSUE THREAD

**Issue by qkhanhpro** [jellyfin/jellyfin#6360]
**Describe the bug**
DLNA: Seek is not possible using LGTV

**System (please complete the following information):**
 - OS: Windows
 - Virtualization: No
 - Clients: LG 55UM7600 DLNA
 - Jellyfin Version: Master branch - https://github.com/jellyfin/jellyfin/commit/0e2a6f8216e0a675b43cf2919fb1d57b46f14972
 - Playback: DirectPlay
 - Hardware Acceleration: No
 - Installed Plugins: No
 - Reverse Proxy: No
 - Base URL: Default
 - Networking: UPnP / DLNA / LAN
 - Storage: Local

**To Reproduce**
Start Jellyfin, Play any video from LG TV, Using DLNA, use the seek function

**Expected behavior**
The TV should be able to seek when using DLNA. I tried with Windows Media Player Network Sharing Service and is able to seek ( Also direct streaming )

The DLNA Profile I used
```
<?xml version="1.0"?>
<Profile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Name>LG Custom TV</Name>
  <Identification>
    <FriendlyName>LG.*</FriendlyName>
    <Headers>
      <HttpHeaderInfo name="User-Agent" value="LG" match="Substring" />
    </Headers>
  </Identification>
  <Manufacturer>Jellyfin</Manufacturer>
  <ManufacturerUrl>https://github.com/jellyfin/jellyfin</ManufacturerUrl>
  <ModelName>Jellyfin Server</ModelName>
  <ModelDescription>UPnP/AV 1.0 Compliant Media Server</ModelDescription>
  <ModelNumber>01</ModelNumber>
  <ModelUrl>https://github.com/jellyfin/jellyfin</ModelUrl>
  <EnableAlbumArtInDidl>false</EnableAlbumArtInDidl>
  <EnableSingleAlbumArtLimit>false</EnableSingleAlbumArtLimit>
  <EnableSingleSubtitleLimit>false</EnableSingleSubtitleLimit>
  <SupportedMediaTypes>Audio,Photo,Video</SupportedMediaTypes>
  <AlbumArtPn>JPEG_SM</AlbumArtPn>
  <MaxAlbumArtWidth>480</MaxAlbumArtWidth>
  <MaxAlbumArtHeight>480</MaxAlbumArtHeight>
  <MaxIconWidth>48</MaxIconWidth>
  <MaxIconHeight>48</MaxIconHeight>
  <MaxStreamingBitrate>140000000</MaxStreamingBitrate>
  <MaxStaticBitrate>140000000</MaxStaticBitrate>
  <MusicStreamingTranscodingBitrate>192000</MusicStreamingTranscodingBitrate>
  <MaxStaticMusicBitrate xsi:nil="true" />
  <ProtocolInfo>http-get:*:video/mpeg:*,http-get:*:video/mp4:*,http-get:*:video/vnd.dlna.mpeg-tts:*,http-get:*:video/avi:*,http-get:*:video/x-matroska:*,http-get:*:video/x-ms-wmv:*,http-get:*:video/wtv:*,http-get:*:audio/mpeg:*,http-get:*:audio/mp3:*,http-get:*:audio/mp4:*,http-get:*:audio/x-ms-wma:*,http-get:*:audio/wav:*,http-get:*:audio/L16:*,http-get:*:image/jpeg:*,http-get:*:image/png:*,http-get:*:image/gif:*,http-get:*:image/tiff:*</ProtocolInfo>
  <TimelineOffsetSeconds>0</TimelineOffsetSeconds>
  <RequiresPlainVideoItems>false</RequiresPlainVideoItems>
  <RequiresPlainFolders>false</RequiresPlainFolders>
  <EnableMSMediaReceiverRegistrar>false</EnableMSMediaReceiverRegistrar>
  <IgnoreTranscodeByteRangeRequests>false</IgnoreTranscodeByteRangeRequests>
  <XmlRootAttributes />
  <DirectPlayProfiles>
    <DirectPlayProfile container="" type="Video" />
    <DirectPlayProfile container="" type="Audio" />
  </DirectPlayProfiles>
  <TranscodingProfiles>
    <TranscodingProfile container="mp3" type="Audio" audioCodec="mp3" estimateContentLength="false" enableMpegtsM2TsMode="false" transcodeSeekInfo="Auto" copyTimestamps="false" context="Streaming" enableSubtitlesInManifest="false" minSegments="0" segmentLength="0" breakOnNonKeyFrames="false" />
    <TranscodingProfile container="ts" type="Video" videoCodec="h264" audioCodec="aac" estimateContentLength="false" enableMpegtsM2TsMode="false" transcodeSeekInfo="Auto" copyTimestamps="false" context="Streaming" enableSubtitlesInManifest="false" minSegments="0" segmentLength="0" breakOnNonKeyFrames="false" />
    <TranscodingProfile container="jpeg" type="Photo" estimateContentLength="false" enableMpegtsM2TsMode="false" transcodeSeekInfo="Auto" copyTimestamps="false" context="Streaming" enableSubtitlesInManifest="false" minSegments="0" segmentLength="0" breakOnNonKeyFrames="false" />
  </TranscodingProfiles>
  <ContainerProfiles />
  <CodecProfiles />
  <ResponseProfiles>
    <ResponseProfile container="m4v" type="Video" mimeType="video/mp4">
      <Conditions />
    </ResponseProfile>
  </ResponseProfiles>
  <SubtitleProfiles>
    <SubtitleProfile format="srt" method="External" />
    <SubtitleProfile format="sub" method="External" />
    <SubtitleProfile format="srt" method="Embed" />
    <SubtitleProfile format="ass" method="Embed" />
    <SubtitleProfile format="ssa" method="Embed" />
    <SubtitleProfile format="smi" method="Embed" />
    <SubtitleProfile format="dvdsub" method="Embed" />
    <SubtitleProfile format="pgs" method="Embed" />
    <SubtitleProfile format="pgssub" method="Embed" />
    <SubtitleProfile format="sub" method="Embed" />
    <SubtitleProfile format="subrip" method="Embed" />
    <SubtitleProfile format="vtt" method="Embed" />
  </SubtitleProfiles>
</Profile>

```

Seeking is possible with **Windows Media Sharing**. The video is Direct Playing, HEVC codec is kept.  there is a thumbnail indicating content at the seek bar
![_DSF2694](https://user-images.githubusercontent.com/10443536/127335560-806516c6-94c5-4589-b8e4-8374f0da42bf.JPG)

With Jellyfin, seeking is disabled (So does fastforward/fastbackward/resume play)
![_DSF2695](https://user-images.githubusercontent.com/10443536/127336301-5b178997-e0e5-429d-85ed-ee055d8bccb9.JPG)

**Comment by amzamzamzamz** [comment]
+1
transcoding failed on Athlon 200GE and LGTV after upgrading software

**Comment by qkhanhpro** [comment]
Will just keep update my findings here 
Some wireshark capture with Jellyfin
<details>
    <summary>WireShark</summary>

```
GET /AVTransport/6f4104fc-978f-e6fd-09c3-e0586550b501/scpd.xml HTTP/1.1
Cache-Control: no-cache
Connection: Close
Pragma: no-cache
Accept: text/xml, application/xml
User-Agent: Microsoft-Windows/10.0 UPnP/1.0
Host: 192.168.1.101:1926

HTTP/1.1 200 OK
DLNADeviceName.lge.com: %5bLG%5d%20DQK
Date: Sun, 08 Aug 2021 09:30:06 GMT
Server: Linux/i686 UPnP/1,0 DLNADOC/1.50 LGE WebOS TV/Version 0.9
Content-Length: 21421
Content-Type: text/xml; charset="utf-8"
Connection: close

<?xml version="1.0" encoding="UTF-8"?>
<scpd xmlns="urn:schemas-upnp-org:service-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <actionList>
    <action>
      <name>SetAVTransportURI</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
        <argument>
          <name>CurrentURI</name>
          <direction>in</direction>
          <relatedStateVariable>AVTransportURI</relatedStateVariable>
        </argument>
        <argument>
          <name>CurrentURIMetaData</name>
          <direction>in</direction>
          <relatedStateVariable>AVTransportURIMetaData</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>GetMediaInfo</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
        <argument>
          <name>NrTracks</name>
          <direction>out</direction>
          <relatedStateVariable>NumberOfTracks</relatedStateVariable>
        </argument>
        <argument>
          <name>MediaDuration</name>
          <direction>out</direction>
          <relatedStateVariable>CurrentMediaDuration</relatedStateVariable>
        </argument>
        <argument>
          <name>CurrentURI</name>
          <direction>out</direction>
          <relatedStateVariable>AVTransportURI</relatedStateVariable>
        </argument>
        <argument>
          <name>CurrentURIMetaData</name>
          <direction>out</direction>
          <relatedStateVariable>AVTransportURIMetaData</relatedStateVariable>
        </argument>
        <argument>
          <name>NextURI</name>
          <direction>out</direction>
          <relatedStateVariable>NextAVTransportURI</relatedStateVariable>
        </argument>
        <argument>
          <name>NextURIMetaData</name>
          <direction>out</direction>
          <relatedStateVariable>NextAVTransportURIMetaData</relatedStateVariable>
        </argument>
        <argument>
          <name>PlayMedium</name>
          <direction>out</direction>
          <relatedStateVariable>PlaybackStorageMedium</relatedStateVariable>
        </argument>
        <argument>
          <name>RecordMedium</name>
          <direction>out</direction>
          <relatedStateVariable>RecordStorageMedium</relatedStateVariable>
        </argument>
        <argument>
          <name>WriteStatus</name>
          <direction>out</direction>
          <relatedStateVariable>RecordMediumWriteStatus</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>GetTransportInfo</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
        <argument>
          <name>CurrentTransportState</name>
          <direction>out</direction>
          <relatedStateVariable>TransportState</relatedStateVariable>
        </argument>
        <argument>
          <name>CurrentTransportStatus</name>
          <direction>out</direction>
          <relatedStateVariable>TransportStatus</relatedStateVariable>
        </argument>
        <argument>
          <name>CurrentSpeed</name>
          <direction>out</direction>
          <relatedStateVariable>TransportPlaySpeed</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>GetPositionInfo</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
        <argument>
          <name>Track</name>
          <direction>out</direction>
          <relatedStateVariable>CurrentTrack</relatedStateVariable>
        </argument>
        <argument>
          <name>TrackDuration</name>
          <direction>out</direction>
          <relatedStateVariable>CurrentTrackDuration</relatedStateVariable>
        </argument>
        <argument>
          <name>TrackMetaData</name>
          <direction>out</direction>
          <relatedStateVariable>CurrentTrackMetaData</relatedStateVariable>
        </argument>
        <argument>
          <name>TrackURI</name>
          <direction>out</direction>
          <relatedStateVariable>CurrentTrackURI</relatedStateVariable>
        </argument>
        <argument>
          <name>RelTime</name>
          <direction>out</direction>
          <relatedStateVariable>RelativeTimePosition</relatedStateVariable>
        </argument>
        <argument>
          <name>AbsTime</name>
          <direction>out</direction>
          <relatedStateVariable>AbsoluteTimePosition</relatedStateVariable>
        </argument>
        <argument>
          <name>RelCount</name>
          <direction>out</direction>
          <relatedStateVariable>RelativeCounterPosition</relatedStateVariable>
        </argument>
        <argument>
          <name>AbsCount</name>
          <direction>out</direction>
          <relatedStateVariable>AbsoluteCounterPosition</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>GetDeviceCapabilities</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
        <argument>
          <name>PlayMedia</name>
          <direction>out</direction>
          <relatedStateVariable>PossiblePlaybackStorageMedia</relatedStateVariable>
        </argument>
        <argument>
          <name>RecMedia</name>
          <direction>out</direction>
          <relatedStateVariable>PossibleRecordStorageMedia</relatedStateVariable>
        </argument>
        <argument>
          <name>RecQualityModes</name>
          <direction>out</direction>
          <relatedStateVariable>PossibleRecordQualityModes</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>GetTransportSettings</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
        <argument>
          <name>PlayMode</name>
          <direction>out</direction>
          <relatedStateVariable>CurrentPlayMode</relatedStateVariable>
        </argument>
        <argument>
          <name>RecQualityMode</name>
          <direction>out</direction>
          <relatedStateVariable>CurrentRecordQualityMode</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>Stop</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>Play</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
        <argument>
          <name>Speed</name>
          <direction>in</direction>
          <relatedStateVariable>TransportPlaySpeed</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>Pause</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>Seek</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
        <argument>
          <name>Unit</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_SeekMode</relatedStateVariable>
        </argument>
        <argument>
          <name>Target</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_SeekTarget</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>Next</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>Previous</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>GetCurrentTransportActions</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
        <argument>
          <name>Actions</name>
          <direction>out</direction>
          <relatedStateVariable>CurrentTransportActions</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>SetNextAVTransportURI</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
        <argument>
          <name>NextURI</name>
          <direction>in</direction>
          <relatedStateVariable>NextAVTransportURI</relatedStateVariable>
        </argument>
        <argument>
          <name>NextURIMetaData</name>
          <direction>in</direction>
          <relatedStateVariable>NextAVTransportURIMetaData</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
    <action>
      <name>X_LG_Seek</name>
      <argumentList>
        <argument>
          <name>InstanceID</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>
        </argument>
        <argument>
          <name>Unit</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_X_LG_SeekMode</relatedStateVariable>
        </argument>
        <argument>
          <name>Target</name>
          <direction>in</direction>
          <relatedStateVariable>A_ARG_TYPE_SeekTarget</relatedStateVariable>
        </argument>
      </argumentList>
    </action>
  </actionList>
  <serviceStateTable>
    <stateVariable sendEvents="no">
      <name>TransportState</name>
      <dataType>string</dataType>
      <defaultValue>NO_MEDIA_PRESENT</defaultValue>
      <allowedValueList>
        <allowedValue>STOPPED</allowedValue>
        <allowedValue>PAUSED_PLAYBACK</allowedValue>
        <allowedValue>PAUSED_RECORDING</allowedValue>
        <allowedValue>PLAYING</allowedValue>
        <allowedValue>RECORDING</allowedValue>
        <allowedValue>TRANSITIONING</allowedValue>
        <allowedValue>NO_MEDIA_PRESENT</allowedValue>
        <allowedValue>LG_TRANSITIONING</allowedValue>
      </allowedValueList>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>TransportStatus</name>
      <dataType>string</dataType>
      <defaultValue>OK</defaultValue>
      <allowedValueList>
        <allowedValue>OK</allowedValue>
        <allowedValue>ERROR_OCCURRED</allowedValue>
      </allowedValueList>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>PlaybackStorageMedium</name>
      <dataType>string</dataType>
      <defaultValue>NETWORK</defaultValue>
      <allowedValueList>
        <allowedValue>UNKNOWN</allowedValue>
        <allowedValue>DV</allowedValue>
        <allowedValue>MINI-DV</allowedValue>
        <allowedValue>VHS</allowedValue>
        <allowedValue>W-VHS</allowedValue>
        <allowedValue>S-VHS</allowedValue>
        <allowedValue>D-VHS</allowedValue>
        <allowedValue>VHSC</allowedValue>
        <allowedValue>VIDEO8</allowedValue>
        <allowedValue>HI8</allowedValue>
        <allowedValue>CD-ROM</allowedValue>
        <allowedValue>CD-DA</allowedValue>
        <allowedValue>CD-R</allowedValue>
        <allowedValue>CD-RW</allowedValue>
        <allowedValue>VIDEO-CD</allowedValue>
        <allowedValue>SACD</allowedValue>
        <allowedValue>MD-AUDIO</allowedValue>
        <allowedValue>MD-PICTURE</allowedValue>
        <allowedValue>DVD-ROM</allowedValue>
        <allowedValue>DVD-VIDEO</allowedValue>
        <allowedValue>DVD-R</allowedValue>
        <allowedValue>DVD+RW</allowedValue>
        <allowedValue>DVD-RW</allowedValue>
        <allowedValue>DVD-RAM</allowedValue>
        <allowedValue>DVD-AUDIO</allowedValue>
        <allowedValue>DAT</allowedValue>
        <allowedValue>LD</allowedValue>
        <allowedValue>HDD</allowedValue>
        <allowedValue>MICRO-MV</allowedValue>
        <allowedValue>NETWORK</allowedValue>
        <allowedValue>NONE</allowedValue>
        <allowedValue>NOT_IMPLEMENTED</allowedValue>
      </allowedValueList>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>RecordStorageMedium</name>
      <dataType>string</dataType>
      <defaultValue>NOT_IMPLEMENTED</defaultValue>
      <allowedValueList>
        <allowedValue>UNKNOWN</allowedValue>
        <allowedValue>DV</allowedValue>
        <allowedValue>MINI-DV</allowedValue>
        <allowedValue>VHS</allowedValue>
        <allowedValue>W-VHS</allowedValue>
        <allowedValue>S-VHS</allowedValue>
        <allowedValue>D-VHS</allowedValue>
        <allowedValue>VHSC</allowedValue>
        <allowedValue>VIDEO8</allowedValue>
        <allowedValue>HI8</allowedValue>
        <allowedValue>CD-ROM</allowedValue>
        <allowedValue>CD-DA</allowedValue>
        <allowedValue>CD-R</allowedValue>
        <allowedValue>CD-RW</allowedValue>
        <allowedValue>VIDEO-CD</allowedValue>
        <allowedValue>SACD</allowedValue>
        <allowedValue>MD-AUDIO</allowedValue>
        <allowedValue>MD-PICTURE</allowedValue>
        <allowedValue>DVD-ROM</allowedValue>
        <allowedValue>DVD-VIDEO</allowedValue>
        <allowedValue>DVD-R</allowedValue>
        <allowedValue>DVD+RW</allowedValue>
        <allowedValue>DVD-RW</allowedValue>
        <allowedValue>DVD-RAM</allowedValue>
        <allowedValue>DVD-AUDIO</allowedValue>
        <allowedValue>DAT</allowedValue>
        <allowedValue>LD</allowedValue>
        <allowedValue>HDD</allowedValue>
        <allowedValue>MICRO-MV</allowedValue>
        <allowedValue>NETWORK</allowedValue>
        <allowedValue>NONE</allowedValue>
        <allowedValue>NOT_IMPLEMENTED</allowedValue>
      </allowedValueList>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>PossiblePlaybackStorageMedia</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>PossibleRecordStorageMedia</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>CurrentPlayMode</name>
      <dataType>string</dataType>
      <defaultValue>NORMAL</defaultValue>
      <allowedValueList>
        <allowedValue>NORMAL</allowedValue>
      </allowedValueList>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>TransportPlaySpeed</name>
      <dataType>string</dataType>
      <defaultValue>1</defaultValue>
      <allowedValueList>
        <allowedValue>1</allowedValue>
        <allowedValue>1/2</allowedValue>
        <allowedValue>4</allowedValue>
        <allowedValue>-1/2</allowedValue>
        <allowedValue>-2</allowedValue>
        <allowedValue>-4</allowedValue>
      </allowedValueList>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>RecordMediumWriteStatus</name>
      <dataType>string</dataType>
      <defaultValue>NOT_IMPLEMENTED</defaultValue>
      <allowedValueList>
        <allowedValue>WRITABLE</allowedValue>
        <allowedValue>PROTECTED</allowedValue>
        <allowedValue>NOT_WRITABLE</allowedValue>
        <allowedValue>UNKNOWN</allowedValue>
        <allowedValue>NOT_IMPLEMENTED</allowedValue>
      </allowedValueList>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>CurrentRecordQualityMode</name>
      <dataType>string</dataType>
      <defaultValue>NOT_IMPLEMENTED</defaultValue>
      <allowedValueList>
        <allowedValue>0:EP</allowedValue>
        <allowedValue>1:LP</allowedValue>
        <allowedValue>2:SP</allowedValue>
        <allowedValue>0:BASIC</allowedValue>
        <allowedValue>1:MEDIUM</allowedValue>
        <allowedValue>2:HIGH</allowedValue>
        <allowedValue>NOT_IMPLEMENTED</allowedValue>
      </allowedValueList>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>PossibleRecordQualityModes</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>NumberOfTracks</name>
      <dataType>ui4</dataType>
      <defaultValue>0</defaultValue>
      <allowedValueRange>
        <minimum>0</minimum>
        <maximum>30</maximum>
      </allowedValueRange>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>CurrentTrack</name>
      <dataType>ui4</dataType>
      <defaultValue>0</defaultValue>
      <allowedValueRange>
        <minimum>0</minimum>
        <maximum>30</maximum>
        <step>1</step>
      </allowedValueRange>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>CurrentTrackDuration</name>
      <dataType>string</dataType>
      <defaultValue>00:00:00</defaultValue>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>CurrentMediaDuration</name>
      <dataType>string</dataType>
      <defaultValue>00:00:00</defaultValue>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>CurrentTrackMetaData</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>CurrentTrackURI</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>AVTransportURI</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>AVTransportURIMetaData</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>NextAVTransportURI</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>NextAVTransportURIMetaData</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>RelativeTimePosition</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>AbsoluteTimePosition</name>
      <dataType>string</dataType>
      <defaultValue>NOT_IMPLEMENTED</defaultValue>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>RelativeCounterPosition</name>
      <dataType>i4</dataType>
      <defaultValue>-1</defaultValue>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>AbsoluteCounterPosition</name>
      <dataType>i4</dataType>
      <defaultValue>0</defaultValue>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>CurrentTransportActions</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="yes">
      <name>LastChange</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>A_ARG_TYPE_SeekMode</name>
      <dataType>string</dataType>
      <allowedValueList>
        <allowedValue>TRACK_NR</allowedValue>
        <allowedValue>REL_TIME</allowedValue>
      </allowedValueList>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>A_ARG_TYPE_SeekTarget</name>
      <dataType>string</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>A_ARG_TYPE_InstanceID</name>
      <dataType>ui4</dataType>
    </stateVariable>
    <stateVariable sendEvents="no">
      <name>A_ARG_TYPE_X_LG_SeekMode</name>
      <dataType>string</dataType>
      <allowedValueList>
        <allowedValue>ABS_TRACK_NR</allowedValue>
      </allowedValueList>
    </stateVariable>
  </serviceStateTable>
</scpd>
```

</details>

**Comment by qkhanhpro** [comment]
Same issue with Emby latest build. Seems like it's a bug that Jellyfin inherits from Emby

**Comment by qkhanhpro** [comment]
This issue is already fixed in Emby at least from 3.5.3.0 onward. This can be confirmed by downloading Emby here

https://github.com/MediaBrowser/Emby.Releases/releases/tag/3.5.3.0
However, the latest code from master branch here still  have this issue
https://github.com/MediaBrowser/Emby

Someone have any idea?

**Comment by amzamzamzamz** [comment]
All works fine with latest update
https://hub.docker.com/r/linuxserver/jellyfin

**Comment by jorants** [comment]
I have the same problem when playing transcoded video to my LG webOS tv. Just recreated the docker container with the latest image (v10.7.7) for jellyfin and the problem persists. Seeking does work when using direct play. Tried many different video formats, as well as changing the advanced transcoding options under DLNA->profiles-><my profile>-> transcoding. no luck with any combination of settings. Maybe it relates to https://github.com/gerbera/gerbera/issues/839 ? I know to little about DLNA to really be a help here.

**Comment by jorants** [comment]
Reporting this capability seems to be handled in `MediaBrowser.Model/Dlna/ContentFeatureBuilder.cs`  and `MediaBrowser.Model/Dlna/DlnaMaps.cs`. There is a comment about LG TVs in the first file above an out commented part about seeking (line 160), placed by Marius Luca (@marius-luca-87 ), maybe they can shine a light on this?

I tried adding back the code and adding back `opOrg` later on, forcing time seeking to be reported as a capability. The TV assumes seeking is possible but crashes with `file format not recognized` as soon as you actually seek.

**Comment by qkhanhpro** [comment]
Thank you a lot @jorants !
I uncommented that code path and it works perfectly on my LG 55UM7600 
Seems like for _some_ other LGTV it fails , following the comment made by marius-luca-87 "TimeBasedSeek and orgPn causes the DLNA playback to fail (format not supported). Further investigations are needed before enabling the remaining code paths."

**Comment by marius-luca-87** [comment]
As mentioned in https://github.com/jellyfin/jellyfin/pull/6907 I tried myself un-commenting the code that reports SEEK support on transcoded streams and run into the `file format not recognized` issue. I would recommend keeping the particular code path as a DLNA profile option if somebody else wants to add it since it would break playback for some people.

In the Wireshark captures I didn't notice anything wrong at the DLNA headers we set.

The TV's I tested on were LG CX3 and Samsung Q6FNA .

I tried testing both Plex and Emby to see if any have DLNA seek support working for the TV's mentioned and run into the same issue.

**Comment by jorants** [comment]
I tried Emby but the TV also does not recognize the file format there (I could not get Plex to transcode). I have an LG oled48a16l, running webos 03.21.00. 

As it might be a codec/container format mismatch, @qkhanhpro can you share the format before transcoding (container, codec,audio) and the ffmpeg logs for the file that you got working this way?

**Comment by qkhanhpro** [comment]
@jorants I did not have to transcode. My target is to DirectPlay / DirectStream everything and basically the 55UM7600 can chew through most codecs without the need for transcoding. My issue was that I can not seek when I was  DirectPlay / DirectStream -ing. So I am afraid that my issue is the reverse of what you are experiencing

**Comment by marius-luca-87** [comment]
There are two cases for SEEK on DLNA.
1. when direct playing a file witch was fixed by #6907
2. when streaming a transcoded stream that would require time seeking instead of byte based seeks (audio transcoding is enough to break DLNA seek)

The remaining commented code would address issues number 2. However I was not able to get that working because of the unknown format issue.

**Comment by BubiBalboa** [comment]
The update from 10.7.7 to 10.8.1 broke this functionality again for me. Symptoms are exactly the same as described in the first post. I use Direct Play.
