### ISSUE TITLE
/DisplayPreferences/usersettings endpoint returning 500 when attempting to log in

### ISSUE THREAD

**Issue by gregoryjjb** [jellyfin/jellyfin#6413]
**Describe the bug**

When attempting to sign in the page hangs with a spinner; it specifically fails on the `/DisplayPreferences/usersettings?userId=xxx&client=emby` request, which is returning a 500. Exact error visible in logs section below. Existing sessions are currently unaffected, only new sign in attempts are broken. Sometimes refreshing the page in this stuck state will complete the login, other times it will keep me on the login screen.

**System (please complete the following information):**
 - OS: Ubuntu Server 20.04.1
 - Virtualization: Docker (official image)
 - Clients: Browser
 - Browser: Firefox 90, Chrome 92
 - Jellyfin Version: 10.7.6
 - Playback: N/A
 - Hardware Acceleration: NVENC
 - Installed Plugins: AudioDB, Fanart, Kodi Sync Queue, MusicBrainz, OMBd, Open Subtitles, TMDb Box Sets, TV Maze
 - Reverse Proxy: Caddy
 - Base URL: none
 - Networking: Bridge/NAT + IPv6
 - Storage: local

**To Reproduce**

1. Visit login page
2. Enter username & password
3. Click "Sign In"

**Expected behavior**

I should be signed in.

**Server Logs**

```
[04:41:26] [INF] [219] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 2600:1700:38d4:5550:dda4:eb03:fb9d:59c6 closed
[04:41:34] [INF] [154] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for admin has succeeded.
[04:41:34] [INF] [154] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user admin: 1/0
[04:41:34] [INF] [154] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 230335c2-a58b-47ff-ae96-dae28961e81c
[04:41:34] [ERR] [199] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL GET /DisplayPreferences/usersettings.
System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,System.String> MediaBrowser.Controller.IDisplayPreferencesManager.ListCustomItemDisplayPreferences(System.Guid, System.Guid, System.String)'.
   at Jellyfin.Api.Controllers.DisplayPreferencesController.GetDisplayPreferences(String displayPreferencesId, Guid userId, String client)
   at lambda_method388(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)
   at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)
   at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**FFmpeg Logs**

N/A

**Browser Console Logs**

```
opening web socket with url: wss://jellyfin.***.***/socket?api_key=a7b1f47……BHZWNrbykgQ2hyb21lLzkyLjAuNDUxNS4xMzEgU2FmYXJpLzUzNy4zNnwxNjI4NTcxMTA1ODAx
main.0f18378….bundle.js:2 returning instance from getOrAddApiClient
main.0f18378….bundle.js:2 Requesting url without automatic networking: https://jellyfin.***.***/DisplayPreferences/usersettings?userId=230335c…&client=emby
main.0f18378….bundle.js:2 web socket connection opened
/DisplayPreferences/…1e81c&client=emby:1 Failed to load resource: the server responded with a status of 500 ()
index.html#!/login.h…79e254ad181978295:1 Uncaught (in promise) 
    Response
    body: (...)
    bodyUsed: false
    headers: Headers {}
    ok: false
    redirected: false
    status: 500
    statusText: ""
    type: "basic"
    url: "https://jellyfin.***.***/DisplayPreferences/usersettings?userId=230335c2a58b47ffae96dae28961e81c&client=emby"
    [[Prototype]]: Response
main.0f18378….bundle.js:2 Sending web socket message: KeepAlive
```

**Screenshots**

N/A

**Additional context**

I've seen this endpoint fail with this same (or at least a very similar) error before but it's always resolved itself; having no such luck this time. Appreciate any help.

**Comment by barronpm** [comment]
Fixed in 10.7.7

**Comment by gregoryjjb** [comment]
Just upgraded and still facing the exact same issue :( it's actually worse now, refreshing the page never gets me through the login now.

**Comment by cvium** [comment]
Please provide the full log

**Comment by gregoryjjb** [comment]
More logs than provided above? Here's the full thing: https://pastebin.com/raw/GKU8YffN

You can see the error on the `/DisplayPreferences/usersettings` endpoint right at the end, from a login attempt

**Comment by cvium** [comment]
Looks like a different error. Have you tried rebooting?

**Comment by gregoryjjb** [comment]
I have rebooted yeah.

**Comment by barronpm** [comment]
It looks like this is a different issue from the known bug for display preferences. Does this occur when you have no plugins? If not, which plugin causes the error?

**Comment by gregoryjjb** [comment]
Still occurs with all plugins disabled. It's because `_displayPreferencesManager ` is null right? Can I set up any more advanced debugging on my instance?
