### ISSUE TITLE
[Issue]: Repeatedly generating backdrop.jpg

### ISSUE THREAD

**Issue by Zeusy123** [jellyfin/jellyfin#7836]
### Please describe your bug

using 10.8 nightly clean install, its still generating multiple backdrop.jpg files....looking at logs:
Even when u manually select search for missing metadata... it genreates a NEW backdrop+1.jpg
Every time the library scan is done, another backdrop+1.jpg is created

This movie has now 16 backdrop.jps in folder !!!
log:

```
[11:44:15] [ERR] [39] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for /data/movies/The themoviename/backdrop16.jpg
System.IO.FileNotFoundException: File not found
File name: '/data/movies/The Revenge of Robert (2018)/backdrop16.jpg'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5568dcd43600] stream 0, timescale not set
```

### Jellyfin Version

10.8.0

### if other:

nightly

### Environment

```markdown
- OS:Ubuntu 18.04.6 LTS
- Virtualization:docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
What are your library settings for the library that has this issue?

**Comment by Zeusy123** [comment]
I've tried default and changed all, same result

**Comment by Zeusy123** [comment]
ive enabled debugging here is se3ction from log file:
Bear in mind, all movies folders already have folder & backdrop.jpg files.  Every rescan, it will generate a NEW backdrop(+1).jpg


[2022-06-06 13:48:26.455 +01:00] [DBG] [45] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/The Last Emperor (1987)/The Last Emperor 1987 1080p BluRay DTS x264-CtrlHD.mp4"
[2022-06-06 13:48:26.665 +01:00] [DBG] [26] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/The Last Emperor (1987)/folder.jpg"
[2022-06-06 13:48:26.682 +01:00] [DBG] [19] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/The Last Emperor (1987)/backdrop2.jpg"
[2022-06-06 13:48:26.697 +01:00] [DBG] [22] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/The Last Emperor (1987)/The Last Emperor 1987 1080p BluRay DTS x264-CtrlHD.mp4"
[2022-06-06 13:48:27.178 +01:00] [DBG] [45] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/The Last Emperor (1987)/The Last Emperor 1987 1080p BluRay DTS x264-CtrlHD.mp4"
[2022-06-06 13:48:28.428 +01:00] [DBG] [44] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Natalie Wood What Remains Behind (2020)/Natalie.Wood.What.Remains.Behind.2020.1080p.WEB.H264-OPUS.mp4"
[2022-06-06 13:48:28.444 +01:00] [DBG] [26] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Natalie Wood What Remains Behind (2020)/folder.jpg"
[2022-06-06 13:48:28.459 +01:00] [DBG] [45] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Natalie Wood What Remains Behind (2020)/backdrop2.jpg"
[2022-06-06 13:48:28.460 +01:00] [DBG] [44] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Natalie Wood What Remains Behind (2020)/Natalie.Wood.What.Remains.Behind.2020.1080p.WEB.H264-OPUS.mp4"
[2022-06-06 13:48:28.474 +01:00] [DBG] [44] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Natalie Wood What Remains Behind (2020)/Natalie.Wood.What.Remains.Behind.2020.1080p.WEB.H264-OPUS.mp4"
[2022-06-06 13:48:29.345 +01:00] [DBG] [31] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Crying Freeman (1995)/Crying.Freeman.1995.1080p.BluRay.x264-USURY.mp4"
[2022-06-06 13:48:29.356 +01:00] [DBG] [26] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Crying Freeman (1995)/folder.jpg"
[2022-06-06 13:48:29.370 +01:00] [DBG] [22] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Crying Freeman (1995)/backdrop2.jpg"
[2022-06-06 13:48:29.370 +01:00] [DBG] [45] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Crying Freeman (1995)/Crying.Freeman.1995.1080p.BluRay.x264-USURY.mp4"
[2022-06-06 13:48:29.385 +01:00] [DBG] [45] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Crying Freeman (1995)/Crying.Freeman.1995.1080p.BluRay.x264-USURY.mp4"
[2022-06-06 13:48:29.897 +01:00] [DBG] [8] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Benjis Very Own Christmas Story (1978)/Benjis.Very.Own.Christmas.Story.1978.1080p.NF.WEB-DL.DD2.0.x264-AJP69.mp4"
[2022-06-06 13:48:29.912 +01:00] [DBG] [8] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Benjis Very Own Christmas Story (1978)/folder.jpg"
[2022-06-06 13:48:29.913 +01:00] [DBG] [45] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Benjis Very Own Christmas Story (1978)/Benjis.Very.Own.Christmas.Story.1978.1080p.NF.WEB-DL.DD2.0.x264-AJP69.mp4"
[2022-06-06 13:48:29.925 +01:00] [DBG] [45] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Benjis Very Own Christmas Story (1978)/Benjis.Very.Own.Christmas.Story.1978.1080p.NF.WEB-DL.DD2.0.x264-AJP69.mp4"
[2022-06-06 13:48:29.926 +01:00] [DBG] [45] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieImageProvider" for "/data/movies/Benjis Very Own Christmas Story (1978)/Benjis.Very.Own.Christmas.Story.1978.1080p.NF.WEB-DL.DD2.0.x264-AJP69.mp4"
[2022-06-06 13:48:29.982 +01:00] [DBG] [45] MediaBrowser.Providers.Movies.MovieMetadataService: Running "EmbeddedImageProvider" for "/data/movies/Benjis Very Own Christmas Story (1978)/Benjis.Very.Own.Christmas.Story.1978.1080p.NF.WEB-DL.DD2.0.x264-AJP69.mp4"
[2022-06-06 13:48:30.755 +01:00] [DBG] [13] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/G.I. Blues (1960)/G.I.Blues.1960.1080p.WEBRip.x264-RARBG.mp4"
[2022-06-06 13:48:30.771 +01:00] [DBG] [31] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/G.I. Blues (1960)/folder.jpg"
[2022-06-06 13:48:30.784 +01:00] [DBG] [31] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/G.I. Blues (1960)/backdrop2.jpg"
[2022-06-06 13:48:30.785 +01:00] [DBG] [13] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/G.I. Blues (1960)/G.I.Blues.1960.1080p.WEBRip.x264-RARBG.mp4"
[2022-06-06 13:48:30.801 +01:00] [DBG] [31] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/G.I. Blues (1960)/G.I.Blues.1960.1080p.WEBRip.x264-RARBG.mp4"
[2022-06-06 13:48:31.164 +01:00] [DBG] [52] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/For We Are Many (2019)/For.We.Are.Many.2019.1080p.WEB-DL.H264.AC3-EVO.mp4"
[2022-06-06 13:48:31.195 +01:00] [DBG] [52] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/For We Are Many (2019)/folder.jpg"
[2022-06-06 13:48:31.211 +01:00] [DBG] [13] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/For We Are Many (2019)/backdrop2.jpg"
[2022-06-06 13:48:31.211 +01:00] [DBG] [8] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/For We Are Many (2019)/For.We.Are.Many.2019.1080p.WEB-DL.H264.AC3-EVO.mp4"
[2022-06-06 13:48:31.224 +01:00] [DBG] [13] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/For We Are Many (2019)/For.We.Are.Many.2019.1080p.WEB-DL.H264.AC3-EVO.mp4"
[2022-06-06 13:48:31.225 +01:00] [DBG] [13] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieImageProvider" for "/data/movies/For We Are Many (2019)/For.We.Are.Many.2019.1080p.WEB-DL.H264.AC3-EVO.mp4"
[2022-06-06 13:48:31.237 +01:00] [DBG] [52] MediaBrowser.Providers.Movies.MovieMetadataService: Running "EmbeddedImageProvider" for "/data/movies/For We Are Many (2019)/For.We.Are.Many.2019.1080p.WEB-DL.H264.AC3-EVO.mp4"
[2022-06-06 13:48:31.527 +01:00] [DBG] [41] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Opening Night (1977)/Opening Night.(1977).Bluray-1080p.DTS+1.0.x264-RSG.mp4"
[2022-06-06 13:48:31.539 +01:00] [DBG] [13] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Opening Night (1977)/folder.jpg"
[2022-06-06 13:48:31.551 +01:00] [DBG] [15] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Opening Night (1977)/backdrop2.jpg"
[2022-06-06 13:48:31.552 +01:00] [DBG] [15] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Opening Night (1977)/Opening Night.(1977).Bluray-1080p.DTS+1.0.x264-RSG.mp4"
[2022-06-06 13:48:31.564 +01:00] [DBG] [15] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Opening Night (1977)/Opening Night.(1977).Bluray-1080p.DTS+1.0.x264-RSG.mp4"
[2022-06-06 13:48:31.572 +01:00] [DBG] [19] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "146.70.83.178" received message: WebSocketMessage`1 { MessageType: KeepAlive, MessageId: 00000000-0000-0000-0000-000000000000, ServerId: null, Data: null }
[2022-06-06 13:48:31.929 +01:00] [DBG] [43] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Art of Deception (2019)/Art.of.Deception.2019.BRRip.XviD.AC3-EVO.mp4"
[2022-06-06 13:48:31.942 +01:00] [DBG] [41] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Art of Deception (2019)/folder.jpg"
[2022-06-06 13:48:31.953 +01:00] [DBG] [41] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Art of Deception (2019)/backdrop2.jpg"
[2022-06-06 13:48:31.954 +01:00] [DBG] [19] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Art of Deception (2019)/Art.of.Deception.2019.BRRip.XviD.AC3-EVO.mp4"
[2022-06-06 13:48:31.967 +01:00] [DBG] [19] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Art of Deception (2019)/Art.of.Deception.2019.BRRip.XviD.AC3-EVO.mp4"
[2022-06-06 13:48:31.968 +01:00] [DBG] [41] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieImageProvider" for "/data/movies/Art of Deception (2019)/Art.of.Deception.2019.BRRip.XviD.AC3-EVO.mp4"
[2022-06-06 13:48:31.979 +01:00] [DBG] [41] MediaBrowser.Providers.Movies.MovieMetadataService: Running "EmbeddedImageProvider" for "/data/movies/Art of Deception (2019)/Art.of.Deception.2019.BRRip.XviD.AC3-EVO.mp4"
[2022-06-06 13:48:32.156 +01:00] [DBG] [51] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Ms. Purple (2019)/Ms. Purple.(2019).WEBDL-1080p.AC3+5.1.h264-EVO.mp4"
[2022-06-06 13:48:32.169 +01:00] [DBG] [51] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Ms. Purple (2019)/folder.jpg"
[2022-06-06 13:48:32.183 +01:00] [DBG] [38] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Ms. Purple (2019)/backdrop2.jpg"
[2022-06-06 13:48:32.184 +01:00] [DBG] [19] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Ms. Purple (2019)/Ms. Purple.(2019).WEBDL-1080p.AC3+5.1.h264-EVO.mp4"
[2022-06-06 13:48:32.196 +01:00] [DBG] [8] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Ms. Purple (2019)/Ms. Purple.(2019).WEBDL-1080p.AC3+5.1.h264-EVO.mp4"
[2022-06-06 13:48:32.197 +01:00] [DBG] [8] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieImageProvider" for "/data/movies/Ms. Purple (2019)/Ms. Purple.(2019).WEBDL-1080p.AC3+5.1.h264-EVO.mp4"
[2022-06-06 13:48:32.213 +01:00] [DBG] [8] MediaBrowser.Providers.Movies.MovieMetadataService: Running "EmbeddedImageProvider" for "/data/movies/Ms. Purple (2019)/Ms. Purple.(2019).WEBDL-1080p.AC3+5.1.h264-EVO.mp4"
[2022-06-06 13:48:32.845 +01:00] [DBG] [34] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/I Spit on Your Grave Déjà Vu (2019)/I.Spit.on.Your.Grave.Deja.Vu.2019.1080p.BluRay.DD5.1.x264-iFT.mp4"
[2022-06-06 13:48:32.858 +01:00] [DBG] [15] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/I Spit on Your Grave Déjà Vu (2019)/folder.jpg"
[2022-06-06 13:48:32.871 +01:00] [DBG] [34] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/I Spit on Your Grave Déjà Vu (2019)/backdrop2.jpg"
[2022-06-06 13:48:32.872 +01:00] [DBG] [15] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/I Spit on Your Grave Déjà Vu (2019)/I.Spit.on.Your.Grave.Deja.Vu.2019.1080p.BluRay.DD5.1.x264-iFT.mp4"
[2022-06-06 13:48:32.886 +01:00] [DBG] [15] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/I Spit on Your Grave Déjà Vu (2019)/I.Spit.on.Your.Grave.Deja.Vu.2019.1080p.BluRay.DD5.1.x264-iFT.mp4"
[2022-06-06 13:48:33.416 +01:00] [DBG] [49] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/The Crazies (2010)/The Crazies.(2010).Bluray-1080p.DTS+5.1.x264-HDC.mp4"
[2022-06-06 13:48:33.476 +01:00] [DBG] [34] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/The Crazies (2010)/folder.jpg"
[2022-06-06 13:48:33.491 +01:00] [DBG] [34] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/The Crazies (2010)/backdrop2.jpg"
[2022-06-06 13:48:33.492 +01:00] [DBG] [19] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/The Crazies (2010)/The Crazies.(2010).Bluray-1080p.DTS+5.1.x264-HDC.mp4"
[2022-06-06 13:48:33.516 +01:00] [DBG] [34] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/The Crazies (2010)/The Crazies.(2010).Bluray-1080p.DTS+5.1.x264-HDC.mp4"
[2022-06-06 13:48:33.882 +01:00] [DBG] [24] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Driven (2001)/Driven.2001.1080p.BluRay.x264-MOOVEE.mp4"
[2022-06-06 13:48:33.894 +01:00] [DBG] [19] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Driven (2001)/folder.jpg"
[2022-06-06 13:48:33.905 +01:00] [DBG] [19] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Driven (2001)/backdrop2.jpg"
[2022-06-06 13:48:33.906 +01:00] [DBG] [19] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Driven (2001)/Driven.2001.1080p.BluRay.x264-MOOVEE.mp4"
[2022-06-06 13:48:33.923 +01:00] [DBG] [24] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Driven (2001)/Driven.2001.1080p.BluRay.x264-MOOVEE.mp4"
[2022-06-06 13:48:35.111 +01:00] [DBG] [35] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Next of Kin (1989)/Next.Of.Kin.1989.1080p.BluRay.X264-FLHD.mp4"
[2022-06-06 13:48:35.132 +01:00] [DBG] [35] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Next of Kin (1989)/folder.jpg"
[2022-06-06 13:48:35.167 +01:00] [DBG] [19] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Next of Kin (1989)/backdrop2.jpg"
[2022-06-06 13:48:35.167 +01:00] [DBG] [35] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Next of Kin (1989)/Next.Of.Kin.1989.1080p.BluRay.X264-FLHD.mp4"
[2022-06-06 13:48:35.183 +01:00] [DBG] [35] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Next of Kin (1989)/Next.Of.Kin.1989.1080p.BluRay.X264-FLHD.mp4"
[2022-06-06 13:48:35.489 +01:00] [DBG] [26] Emby.Server.Implementations.Library.LibraryManager: ConvertImageToLocal item 63dca14c-7bfe-7eda-b974-4099612c9e03 - image url: "https://image.tmdb.org/t/p/original/8txEeGGlh728VMDEGTs3CjlawPn.jpg"
[2022-06-06 13:48:35.500 +01:00] [DBG] [26] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/config/metadata/People/B/Ben Gazzara/folder.jpg"
[2022-06-06 13:48:35.502 +01:00] [DBG] [49] Emby.Drawing.ImageProcessor: Getting image size for item "Person" "/config/metadata/People/B/Ben Gazzara/folder.jpg"
[2022-06-06 13:48:36.792 +01:00] [DBG] [29] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Who Am I Now (2021)/Who.Am.I.Now.2021.1080p.WEBRip.1400MB.DD2.0.x264-GalaxyRG[TGx].mp4"
[2022-06-06 13:48:36.803 +01:00] [DBG] [29] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Who Am I Now (2021)/folder.jpg"
[2022-06-06 13:48:36.814 +01:00] [DBG] [35] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Who Am I Now (2021)/backdrop2.jpg"
[2022-06-06 13:48:36.815 +01:00] [DBG] [29] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Who Am I Now (2021)/Who.Am.I.Now.2021.1080p.WEBRip.1400MB.DD2.0.x264-GalaxyRG[TGx].mp4"
[2022-06-06 13:48:36.826 +01:00] [DBG] [29] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Who Am I Now (2021)/Who.Am.I.Now.2021.1080p.WEBRip.1400MB.DD2.0.x264-GalaxyRG[TGx].mp4"
[2022-06-06 13:48:36.826 +01:00] [DBG] [29] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieImageProvider" for "/data/movies/Who Am I Now (2021)/Who.Am.I.Now.2021.1080p.WEBRip.1400MB.DD2.0.x264-GalaxyRG[TGx].mp4"
[2022-06-06 13:48:36.837 +01:00] [DBG] [29] MediaBrowser.Providers.Movies.MovieMetadataService: Running "EmbeddedImageProvider" for "/data/movies/Who Am I Now (2021)/Who.Am.I.Now.2021.1080p.WEBRip.1400MB.DD2.0.x264-GalaxyRG[TGx].mp4"
[2022-06-06 13:48:37.045 +01:00] [DBG] [45] MediaBrowser.Providers.Movies.MovieMetadataService: Running "EmbeddedImageProvider" for "/data/movies/Benjis Very Own Christmas Story (1978)/Benjis.Very.Own.Christmas.Story.1978.1080p.NF.WEB-DL.DD2.0.x264-AJP69.mp4"
[2022-06-06 13:48:37.249 +01:00] [DBG] [38] Emby.Server.Implementations.Session.SessionWebSocketListener: Watching 1 WebSockets.
[2022-06-06 13:48:37.916 +01:00] [DBG] [27] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Save the Last Dance 2 (2006)/Save.The.Last.Dance.2.2006.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES.mp4"
[2022-06-06 13:48:37.929 +01:00] [DBG] [38] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Save the Last Dance 2 (2006)/folder.jpg"
[2022-06-06 13:48:37.940 +01:00] [DBG] [35] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Save the Last Dance 2 (2006)/backdrop2.jpg"
[2022-06-06 13:48:37.941 +01:00] [DBG] [27] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Save the Last Dance 2 (2006)/Save.The.Last.Dance.2.2006.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES.mp4"
[2022-06-06 13:48:37.952 +01:00] [DBG] [27] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Save the Last Dance 2 (2006)/Save.The.Last.Dance.2.2006.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES.mp4"
[2022-06-06 13:48:37.952 +01:00] [DBG] [35] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieImageProvider" for "/data/movies/Save the Last Dance 2 (2006)/Save.The.Last.Dance.2.2006.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES.mp4"
[2022-06-06 13:48:37.963 +01:00] [DBG] [35] MediaBrowser.Providers.Movies.MovieMetadataService: Running "EmbeddedImageProvider" for "/data/movies/Save the Last Dance 2 (2006)/Save.The.Last.Dance.2.2006.1080p.AMZN.WEB-DL.DDP5.1.H.264-TEPES.mp4"
[2022-06-06 13:48:38.046 +01:00] [DBG] [39] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/They Live Inside Us (2020)/They.Live.Inside.Us.2020.1080p.WEB-DL.DD2.0.H.264-EVO.mp4"
[2022-06-06 13:48:38.057 +01:00] [DBG] [26] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/They Live Inside Us (2020)/folder.jpg"
[2022-06-06 13:48:38.068 +01:00] [DBG] [39] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/They Live Inside Us (2020)/backdrop2.jpg"
[2022-06-06 13:48:38.069 +01:00] [DBG] [51] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/They Live Inside Us (2020)/They.Live.Inside.Us.2020.1080p.WEB-DL.DD2.0.H.264-EVO.mp4"
[2022-06-06 13:48:38.080 +01:00] [DBG] [51] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/They Live Inside Us (2020)/They.Live.Inside.Us.2020.1080p.WEB-DL.DD2.0.H.264-EVO.mp4"
[2022-06-06 13:48:38.080 +01:00] [DBG] [51] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieImageProvider" for "/data/movies/They Live Inside Us (2020)/They.Live.Inside.Us.2020.1080p.WEB-DL.DD2.0.H.264-EVO.mp4"
[2022-06-06 13:48:38.091 +01:00] [DBG] [20] MediaBrowser.Providers.Movies.MovieMetadataService: Running "EmbeddedImageProvider" for "/data/movies/They Live Inside Us (2020)/They.Live.Inside.Us.2020.1080p.WEB-DL.DD2.0.H.264-EVO.mp4"
[2022-06-06 13:48:39.255 +01:00] [DBG] [23] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/The Mercy (2018)/The.Mercy.2018.BluRay.1080p.x264.DTS-HD.MA.5.1-HDChina.mp4"
[2022-06-06 13:48:39.269 +01:00] [DBG] [39] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/The Mercy (2018)/folder.jpg"
[2022-06-06 13:48:39.294 +01:00] [DBG] [26] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/The Mercy (2018)/backdrop2.jpg"
[2022-06-06 13:48:39.296 +01:00] [DBG] [26] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/The Mercy (2018)/The.Mercy.2018.BluRay.1080p.x264.DTS-HD.MA.5.1-HDChina.mp4"
[2022-06-06 13:48:39.312 +01:00] [DBG] [13] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/The Mercy (2018)/The.Mercy.2018.BluRay.1080p.x264.DTS-HD.MA.5.1-HDChina.mp4"
[2022-06-06 13:48:39.325 +01:00] [DBG] [11] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/War of the Worlds (2005)/War of the Worlds.(2005).WEBDL-1080p.DTS+5.1.x264-Radarr.mp4"
[2022-06-06 13:48:39.347 +01:00] [DBG] [23] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/War of the Worlds (2005)/folder.jpg"
[2022-06-06 13:48:39.359 +01:00] [DBG] [11] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/War of the Worlds (2005)/backdrop2.jpg"
[2022-06-06 13:48:39.361 +01:00] [DBG] [23] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/War of the Worlds (2005)/War of the Worlds.(2005).WEBDL-1080p.DTS+5.1.x264-Radarr.mp4"
[2022-06-06 13:48:39.389 +01:00] [DBG] [43] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/War of the Worlds (2005)/War of the Worlds.(2005).WEBDL-1080p.DTS+5.1.x264-Radarr.mp4"
[2022-06-06 13:48:39.721 +01:00] [DBG] [10] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/My Name Is Sam (2020)/My.Name.Is.Sam.2020.1080p.AMZN.WEB-DL.DDP2.0.x264-TEPES.mp4"
[2022-06-06 13:48:39.732 +01:00] [DBG] [10] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/My Name Is Sam (2020)/folder.jpg"
[2022-06-06 13:48:39.732 +01:00] [DBG] [10] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/My Name Is Sam (2020)/My.Name.Is.Sam.2020.1080p.AMZN.WEB-DL.DDP2.0.x264-TEPES.mp4"
[2022-06-06 13:48:39.742 +01:00] [DBG] [10] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/My Name Is Sam (2020)/My.Name.Is.Sam.2020.1080p.AMZN.WEB-DL.DDP2.0.x264-TEPES.mp4"
[2022-06-06 13:48:39.743 +01:00] [DBG] [10] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieImageProvider" for "/data/movies/My Name Is Sam (2020)/My.Name.Is.Sam.2020.1080p.AMZN.WEB-DL.DDP2.0.x264-TEPES.mp4"
[2022-06-06 13:48:39.754 +01:00] [DBG] [10] MediaBrowser.Providers.Movies.MovieMetadataService: Running "EmbeddedImageProvider" for "/data/movies/My Name Is Sam (2020)/My.Name.Is.Sam.2020.1080p.AMZN.WEB-DL.DDP2.0.x264-TEPES.mp4"
[2022-06-06 13:48:40.228 +01:00] [DBG] [36] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Because I Said So (2007)/Because.I.Said.So.2007.1080p.Bluray.X264-DIMENSION.mp4"
[2022-06-06 13:48:40.241 +01:00] [DBG] [36] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Because I Said So (2007)/folder.jpg"
[2022-06-06 13:48:40.252 +01:00] [DBG] [27] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Because I Said So (2007)/backdrop2.jpg"
[2022-06-06 13:48:40.253 +01:00] [DBG] [13] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Because I Said So (2007)/Because.I.Said.So.2007.1080p.Bluray.X264-DIMENSION.mp4"
[2022-06-06 13:48:40.268 +01:00] [DBG] [27] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Because I Said So (2007)/Because.I.Said.So.2007.1080p.Bluray.X264-DIMENSION.mp4"
[2022-06-06 13:48:40.391 +01:00] [DBG] [46] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Avengers Endgame (2019)/Avengers.Endgame.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mp4"
[2022-06-06 13:48:40.418 +01:00] [DBG] [43] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Avengers Endgame (2019)/folder.jpg"
[2022-06-06 13:48:40.492 +01:00] [DBG] [13] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Avengers Endgame (2019)/backdrop2.jpg"
[2022-06-06 13:48:40.495 +01:00] [DBG] [13] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Avengers Endgame (2019)/Avengers.Endgame.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mp4"
[2022-06-06 13:48:40.533 +01:00] [DBG] [42] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/The Muppets Wizard of Oz (2005)/The.Muppets.Wizard.of.Oz.2005.1080p.AMZN.WEB-DL.DD+5.1.H.264-alfaHD.mp4"
[2022-06-06 13:48:40.535 +01:00] [DBG] [43] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Avengers Endgame (2019)/Avengers.Endgame.2019.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTG.mp4"
[2022-06-06 13:48:40.545 +01:00] [DBG] [43] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/The Muppets Wizard of Oz (2005)/folder.jpg"
[2022-06-06 13:48:40.557 +01:00] [DBG] [11] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/The Muppets Wizard of Oz (2005)/backdrop2.jpg"
[2022-06-06 13:48:40.558 +01:00] [DBG] [43] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/The Muppets Wizard of Oz (2005)/The.Muppets.Wizard.of.Oz.2005.1080p.AMZN.WEB-DL.DD+5.1.H.264-alfaHD.mp4"
[2022-06-06 13:48:40.571 +01:00] [DBG] [43] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/The Muppets Wizard of Oz (2005)/The.Muppets.Wizard.of.Oz.2005.1080p.AMZN.WEB-DL.DD+5.1.H.264-alfaHD.mp4"
[2022-06-06 13:48:40.573 +01:00] [DBG] [43] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieImageProvider" for "/data/movies/The Muppets Wizard of Oz (2005)/The.Muppets.Wizard.of.Oz.2005.1080p.AMZN.WEB-DL.DD+5.1.H.264-alfaHD.mp4"
[2022-06-06 13:48:40.585 +01:00] [DBG] [43] MediaBrowser.Providers.Movies.MovieMetadataService: Running "EmbeddedImageProvider" for "/data/movies/The Muppets Wizard of Oz (2005)/The.Muppets.Wizard.of.Oz.2005.1080p.AMZN.WEB-DL.DD+5.1.H.264-alfaHD.mp4"
[2022-06-06 13:48:41.042 +01:00] [DBG] [53] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Hidden (2015)/Hidden.(2015).WEBDL-1080p.EAC3+5.1.x264-MXB.mp4"
[2022-06-06 13:48:41.056 +01:00] [DBG] [11] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Hidden (2015)/folder.jpg"
[2022-06-06 13:48:41.067 +01:00] [DBG] [53] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Hidden (2015)/backdrop2.jpg"
[2022-06-06 13:48:41.068 +01:00] [DBG] [11] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Hidden (2015)/Hidden.(2015).WEBDL-1080p.EAC3+5.1.x264-MXB.mp4"
[2022-06-06 13:48:41.082 +01:00] [DBG] [11] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Hidden (2015)/Hidden.(2015).WEBDL-1080p.EAC3+5.1.x264-MXB.mp4"
[2022-06-06 13:48:41.381 +01:00] [DBG] [28] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Starry Eyes (2014)/Starry.Eyes.2014.REPACK.1080p.BluRay.DD5.1.x264-NTb.mp4"
[2022-06-06 13:48:41.393 +01:00] [DBG] [28] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Starry Eyes (2014)/folder.jpg"
[2022-06-06 13:48:41.407 +01:00] [DBG] [11] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Starry Eyes (2014)/backdrop2.jpg"
[2022-06-06 13:48:41.408 +01:00] [DBG] [13] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Starry Eyes (2014)/Starry.Eyes.2014.REPACK.1080p.BluRay.DD5.1.x264-NTb.mp4"
[2022-06-06 13:48:41.465 +01:00] [DBG] [13] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Starry Eyes (2014)/Starry.Eyes.2014.REPACK.1080p.BluRay.DD5.1.x264-NTb.mp4"
[2022-06-06 13:48:42.365 +01:00] [DBG] [54] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Think Like a Dog (2020)/Think.Like.A.Dog.2020.1080p.BluRay.DD5.1.X264-PlayHD.mp4"
[2022-06-06 13:48:42.380 +01:00] [DBG] [11] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Think Like a Dog (2020)/folder.jpg"
[2022-06-06 13:48:42.395 +01:00] [DBG] [54] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Think Like a Dog (2020)/backdrop2.jpg"
[2022-06-06 13:48:42.396 +01:00] [DBG] [54] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Think Like a Dog (2020)/Think.Like.A.Dog.2020.1080p.BluRay.DD5.1.X264-PlayHD.mp4"
[2022-06-06 13:48:42.408 +01:00] [DBG] [54] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Think Like a Dog (2020)/Think.Like.A.Dog.2020.1080p.BluRay.DD5.1.X264-PlayHD.mp4"
[2022-06-06 13:48:42.518 +01:00] [DBG] [54] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was not authenticated.
[2022-06-06 13:48:42.546 +01:00] [DBG] [32] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Sorry to Bother You (2018)/Sorry to Bother You.(2018).WEBDL-1080p.AC3+5.1.h264-CMRG.mp4"
[2022-06-06 13:48:42.557 +01:00] [DBG] [32] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Sorry to Bother You (2018)/folder.jpg"
[2022-06-06 13:48:42.568 +01:00] [DBG] [32] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Sorry to Bother You (2018)/backdrop2.jpg"
[2022-06-06 13:48:42.568 +01:00] [DBG] [32] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Sorry to Bother You (2018)/Sorry to Bother You.(2018).WEBDL-1080p.AC3+5.1.h264-CMRG.mp4"
[2022-06-06 13:48:42.582 +01:00] [DBG] [54] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Sorry to Bother You (2018)/Sorry to Bother You.(2018).WEBDL-1080p.AC3+5.1.h264-CMRG.mp4"
[2022-06-06 13:48:42.736 +01:00] [DBG] [44] Emby.Server.Implementations.Library.LibraryManager: ConvertImageToLocal item 46af3820-70d9-b420-0c25-47ec0a91fa23 - image url: "https://image.tmdb.org/t/p/original/4Nq7uccj8RR3Elr1OzLhckRiEJv.jpg"
[2022-06-06 13:48:42.746 +01:00] [DBG] [44] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/config/metadata/People/N/Natasha Gregson Wagner/folder.jpg"
[2022-06-06 13:48:42.747 +01:00] [DBG] [44] Emby.Drawing.ImageProcessor: Getting image size for item "Person" "/config/metadata/People/N/Natasha Gregson Wagner/folder.jpg"
[2022-06-06 13:48:43.163 +01:00] [DBG] [40] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Tales from the Hood 2 (2018)/Tales.From.the.Hood.2.2018.BluRay.1080p.DTS.5.1.x264-BHDStudio.mp4"
[2022-06-06 13:48:43.177 +01:00] [DBG] [11] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Tales from the Hood 2 (2018)/folder.jpg"
[2022-06-06 13:48:43.189 +01:00] [DBG] [36] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Tales from the Hood 2 (2018)/backdrop2.jpg"
[2022-06-06 13:48:43.189 +01:00] [DBG] [32] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Tales from the Hood 2 (2018)/Tales.From.the.Hood.2.2018.BluRay.1080p.DTS.5.1.x264-BHDStudio.mp4"
[2022-06-06 13:48:43.201 +01:00] [DBG] [32] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Tales from the Hood 2 (2018)/Tales.From.the.Hood.2.2018.BluRay.1080p.DTS.5.1.x264-BHDStudio.mp4"
[2022-06-06 13:48:43.419 +01:00] [DBG] [37] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Sucker Punch (2011)/Sucker.Punch.2011.Extended.Cut.1080p.BluRay.DD.5.1.x264-LoRD.mp4"
[2022-06-06 13:48:43.419 +01:00] [DBG] [24] Emby.Server.Implementations.Library.LibraryManager: ConvertImageToLocal item 4783d0ca-394f-eaa4-fb94-0ea7c3d29378 - image url: "https://image.tmdb.org/t/p/original/qDRGPAcQoW8Wuig9bvoLpHwf1gU.jpg"
[2022-06-06 13:48:43.430 +01:00] [DBG] [24] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/config/metadata/People/S/Sylvester Stallone/folder.jpg"
[2022-06-06 13:48:43.431 +01:00] [DBG] [11] Emby.Drawing.ImageProcessor: Getting image size for item "Person" "/config/metadata/People/S/Sylvester Stallone/folder.jpg"
[2022-06-06 13:48:43.453 +01:00] [DBG] [36] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Sucker Punch (2011)/folder.jpg"
[2022-06-06 13:48:43.466 +01:00] [DBG] [36] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Sucker Punch (2011)/backdrop2.jpg"
[2022-06-06 13:48:43.467 +01:00] [DBG] [36] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Sucker Punch (2011)/Sucker.Punch.2011.Extended.Cut.1080p.BluRay.DD.5.1.x264-LoRD.mp4"
[2022-06-06 13:48:43.486 +01:00] [DBG] [40] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Sucker Punch (2011)/Sucker.Punch.2011.Extended.Cut.1080p.BluRay.DD.5.1.x264-LoRD.mp4"
[2022-06-06 13:48:43.584 +01:00] [DBG] [48] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Son of God (2014)/Son of God.(2014).WEBDL-1080p.AC3+5.1.x264-Radarr.mp4"
[2022-06-06 13:48:43.595 +01:00] [DBG] [24] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Son of God (2014)/folder.jpg"
[2022-06-06 13:48:43.610 +01:00] [DBG] [37] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Son of God (2014)/backdrop2.jpg"
[2022-06-06 13:48:43.636 +01:00] [DBG] [24] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Son of God (2014)/Son of God.(2014).WEBDL-1080p.AC3+5.1.x264-Radarr.mp4"
[2022-06-06 13:48:43.649 +01:00] [DBG] [24] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Son of God (2014)/Son of God.(2014).WEBDL-1080p.AC3+5.1.x264-Radarr.mp4"
[2022-06-06 13:48:44.549 +01:00] [DBG] [14] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Executive Action (1973)/Executive.Action1973.1080p.AMZN.WEB-DL.DDP2.0.H.264-ISA.mkv-xpost.mp4"
[2022-06-06 13:48:44.563 +01:00] [DBG] [24] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Executive Action (1973)/folder.jpg"
[2022-06-06 13:48:44.574 +01:00] [DBG] [36] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Executive Action (1973)/backdrop2.jpg"
[2022-06-06 13:48:44.575 +01:00] [DBG] [36] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Executive Action (1973)/Executive.Action1973.1080p.AMZN.WEB-DL.DDP2.0.H.264-ISA.mkv-xpost.mp4"
[2022-06-06 13:48:44.587 +01:00] [DBG] [36] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Executive Action (1973)/Executive.Action1973.1080p.AMZN.WEB-DL.DDP2.0.H.264-ISA.mkv-xpost.mp4"
[2022-06-06 13:48:44.588 +01:00] [DBG] [36] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieImageProvider" for "/data/movies/Executive Action (1973)/Executive.Action1973.1080p.AMZN.WEB-DL.DDP2.0.H.264-ISA.mkv-xpost.mp4"
[2022-06-06 13:48:44.599 +01:00] [DBG] [26] MediaBrowser.Providers.Movies.MovieMetadataService: Running "EmbeddedImageProvider" for "/data/movies/Executive Action (1973)/Executive.Action1973.1080p.AMZN.WEB-DL.DDP2.0.H.264-ISA.mkv-xpost.mp4"
[2022-06-06 13:48:45.587 +01:00] [DBG] [21] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Home (2015)/Home.(2015).WEBDL-1080p.AAC+2.0.h264-S4NS.mp4"
[2022-06-06 13:48:45.599 +01:00] [DBG] [14] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Home (2015)/folder.jpg"
[2022-06-06 13:48:45.613 +01:00] [DBG] [36] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Home (2015)/backdrop2.jpg"
[2022-06-06 13:48:45.614 +01:00] [DBG] [48] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Home (2015)/Home.(2015).WEBDL-1080p.AAC+2.0.h264-S4NS.mp4"
[2022-06-06 13:48:45.633 +01:00] [DBG] [48] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Home (2015)/Home.(2015).WEBDL-1080p.AAC+2.0.h264-S4NS.mp4"
[2022-06-06 13:48:45.992 +01:00] [DBG] [10] MediaBrowser.Providers.Movies.MovieMetadataService: Running "EmbeddedImageProvider" for "/data/movies/My Name Is Sam (2020)/My.Name.Is.Sam.2020.1080p.AMZN.WEB-DL.DDP2.0.x264-TEPES.mp4"
[2022-06-06 13:48:47.587 +01:00] [DBG] [50] MediaBrowser.Providers.Movies.MovieMetadataService: Running "MovieNfoProvider" for "/data/movies/Ski Patrol (1990)/Ski.Patrol.1990.1080p.STARZ.WEBRip.DD2.0.x264-V3T0.mp4"
[2022-06-06 13:48:47.587 +01:00] [DBG] [49] Emby.Server.Implementations.Library.LibraryManager: ConvertImageToLocal item 4b886982-9814-0d1b-3f63-8d3fa6f8e83e - image url: "https://image.tmdb.org/t/p/original/s2jdLZ53csCtTtDebKYno7xECPG.jpg"
[2022-06-06 13:48:47.599 +01:00] [DBG] [49] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/config/metadata/People/J/Joan Blondell/folder.jpg"
[2022-06-06 13:48:47.621 +01:00] [DBG] [48] Emby.Drawing.ImageProcessor: Getting image size for item "Person" "/config/metadata/People/J/Joan Blondell/folder.jpg"
[2022-06-06 13:48:47.623 +01:00] [DBG] [49] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Ski Patrol (1990)/folder.jpg"
[2022-06-06 13:48:47.655 +01:00] [DBG] [51] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/data/movies/Ski Patrol (1990)/backdrop1.jpg"
[2022-06-06 13:48:47.656 +01:00] [DBG] [14] MediaBrowser.Providers.Movies.MovieMetadataService: Running "TmdbMovieProvider" for "/data/movies/Ski Patrol (1990)/Ski.Patrol.1990.1080p.STARZ.WEBRip.DD2.0.x264-V3T0.mp4"
[2022-06-06 13:48:47.688 +01:00] [DBG] [22] Emby.Server.Implementations.Library.LibraryManager: ConvertImageToLocal item 2c2c119c-1dc1-5209-b507-eb894215d980 - image url: "https://image.tmdb.org/t/p/original/trOACuJz1KzhB51qe6asaxRuxrh.jpg"
[2022-06-06 13:48:47.703 +01:00] [DBG] [51] MediaBrowser.Providers.Manager.ProviderManager: Saving image to "/config/metadata/People/M/Mark Dacascos/folder.jpg"
[2022-06-06 13:48:47.707 +01:00] [DBG] [14] Emby.Drawing.ImageProcessor: Getting image size for item "Person" "/config/metadata/People/M/Mark Dacascos/folder.jpg"
[2022-06-06 13:48:47.791 +01:00] [DBG] [51] MediaBrowser.Providers.Movies.MovieMetadataService: Running "OmdbItemProvider" for "/data/movies/Ski Patrol (1990)/Ski.Patrol.1990.1080p.STARZ.WEBRip.DD2.0.x264-V3T0.mp4"

**Comment by Zeusy123** [comment]
![multibackdropback](https://user-images.githubusercontent.com/24862324/173180800-ae0106fa-8115-492f-8245-d8d915e8ee5a.png)
As you can see it just keeps on generating:(

**Comment by Zeusy123** [comment]
just updatre to latests linserver.io docker running 10.8
Still doing the same, from log:

[10:09:32] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks,
[10:12:59] [ERR] [41] MediaBrowser.Providers.Movies.MovieMetadataService: Error in ffprobe,
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.,
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken),
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalStreamsAsync(Video video, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache, CancellationToken cancellationToken),
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.AddExternalSubtitlesAsync(Video video, List`1 currentStreams, MetadataRefreshOptions options, CancellationToken cancellationToken),
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.Fetch(Video video, CancellationToken cancellationToken, MediaInfo mediaInfo, BlurayDiscInfo blurayInfo, MetadataRefreshOptions options),
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken),
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken),
file:/data/movies/Oh Ramona! (2019)/Oh, Ramona!.(2019).WEBDL-1080p.EAC3+5.1.x264-KAMIKAZE.eng.srt: Invalid data found when processing input,
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x562bd3c706c0] stream 0, timescale not set,
[10:12:31] [INF] [34] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.,
[10:12:31] [INF] [34] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.,
[10:11:35] [ERR] [21] MediaBrowser.Providers.Movies.MovieMetadataService: Error in ffprobe


So fustrating:(

**Comment by cvium** [comment]
Did you change this value?
![image](https://user-images.githubusercontent.com/675118/173186427-c3f06a67-3f89-4059-9bd2-ab6335fc95bc.png)

**Comment by Zeusy123** [comment]
Ive tried multiple installs, and tried changing maximum backdrops..... it currently 1.
![backnumber](https://user-images.githubusercontent.com/24862324/173186772-ff22baa5-4420-49ad-8ff4-fb53321f3db1.png)

**Comment by cvium** [comment]
What's in the movie folder (the full list)? Is it all movies that exhibit this?

**Comment by Zeusy123** [comment]
![amovie](https://user-images.githubusercontent.com/24862324/173187004-9f114d1e-992c-436d-8054-4e1a88eee816.png)

**Comment by cvium** [comment]
What's in the nfo?

**Comment by Zeusy123** [comment]
its radarr generated...ive renamed to log extension
[Oh, Ramona!.(2019).WEBDL-1080p.EAC3+5.1.x264-KAMIKAZE.log](https://github.com/jellyfin/jellyfin/files/8883803/Oh.Ramona.2019.WEBDL-1080p.EAC3%2B5.1.x264-KAMIKAZE.log)

**Comment by cvium** [comment]
It is caused by your nfo.

**Comment by Zeusy123** [comment]
thank god you identified it, thankyou:)

Any way i can fix my end?

**Comment by cvium** [comment]
The only workaround is to delete the nfo or change the urls in the nfo to point to your local image

**Comment by Zeusy123** [comment]
Any idea when a fix will come out?

Can i use any other metadata generators in radarr so jellyfin identifies for sure the movie?
![metaoptions](https://user-images.githubusercontent.com/24862324/173188531-00fe46a7-77e4-4554-8dbc-6c084e5bba55.png)

**Comment by cvium** [comment]
Hard to say when 10.8.1 will be out. We only support the Kodi NFO format.

**Comment by Zeusy123** [comment]
Well even if i edit the urls in the radarr generated nfo.  Radarr, will rewrite nfo back to what is was every day. :(

**Comment by stevetz** [comment]
I have the exact issue as OP, pretty much the same environment including radarr nfos except mines installed from apt on an ubuntu LXC. Let me know if my logs or more detail might help?

**Comment by stevetz** [comment]
Thanks - is there anything I can do to stop it in the meantime, beyond reverting to 10.7? since the last message 6 days i have about 10,000 new backdropN.jpg files!

**Comment by Zeusy123** [comment]
> Thanks - is there anything I can do to stop it in the meantime, beyond reverting to 10.7? since the last message 6 days i have about 10,000 new backdropN.jpg files!

Im the same situation:)

**Comment by Zeusy123** [comment]
seems to been fixed in [nightly-20220620.23-unstable-ls950](https://github.com/linuxserver/docker-jellyfin/releases/tag/nightly-20220620.23-unstable-ls950)
thankyou to the devs you do a brilliant job:)

**Comment by MainServerSpace** [comment]
Seems like this bug is back for me. I'm using Docker and my posters etc seems to randomly get deleted. Seems relevant to the blurhash issue as it is trying to hash a file that has been redownloaded and can't. Not sure If I should remove back to 10.6 version or 10.7 version until issue gets fixed in full. Very annoying and irritating bug to scan all of it to be deleted again.

![image_picker_49922CD4-2D9C-4099-81C5-2F157FC3E80D-11269-0000019A54EA6F00](https://user-images.githubusercontent.com/86547540/208322131-9449807f-5d91-458c-9b14-9e53ea5e7223.jpg)

**Comment by cvium** [comment]
> Seems like this bug is back for me. I'm using Docker and my posters etc seems to randomly get deleted. Seems relevant to the blurhash issue as it is trying to hash a file that has been redownloaded and can't. Not sure If I should revert back to 10.6 version or 10.7 version until issue gets fixed in full. Very annoying and irritating bug to scan all of it to be deleted again. I have tried the inotify solution and also someone said RAM on the other comment from another active issue and it seems that inotify is already set to the proper value and my system has plenty of free ram.
> 
> ![image_picker_49922CD4-2D9C-4099-81C5-2F157FC3E80D-11269-0000019A54EA6F00](https://user-images.githubusercontent.com/86547540/208322131-9449807f-5d91-458c-9b14-9e53ea5e7223.jpg)

This does not sound related to this issue at all.

**Comment by cvium** [comment]
Closing as this bug should be fixed and we have received no further reports.
