### ISSUE TITLE
[Issue]: HEVC Vaapi transcoding doesn't work on chromecast

### ISSUE THREAD

**Issue by Vitorvlv** [jellyfin/jellyfin#7899]
### Please describe your bug

Hi! If I try to cast a hevc file to a chromecast while using vaapi then playback doesn't work.

I've attached the ffmpeg logs. 

Some useful info:
Vaapi hevc transcoding works as expected on web.
AMD AMF HEVC transcoding works as expected if I try to cast to a chromecast.
This is not a recent issue caused by the 10.8 release, it's been happening since 10.7.
I've already tried updating to the latest mesa inside the container, it doesn't make any difference.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Endeavour OS
- Virtualization: Docker - linuxserver image
- Clients: Chromecast
- FFmpeg Version: ffmpeg 5
- Hardware Acceleration: VAAPI
```

### FFmpeg logs

```shell
/videos/37e8e034-4079-3815-87dd-2e333f7c975e/stream.mkv

{"Protocol":0,"Id":"37e8e0344079381587dd2e333f7c975e","Path":"/data/M\u00EDdia/V\u00EDdeos/TV/The Mandalorian (2019)/Season 01/The Mandalorian (2019) - S01E03 - Chapter 3 The Sin [WEBRip-1080p Proper][10bit][x265][AAC 5.1].mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":366150208,"Name":"The Mandalorian (2019) - S01E03 - Chapter 3 The Sin [WEBRip-1080p Proper][10bit][x265][AAC 5.1]","IsRemote":false,"ETag":"dbbc6af9448905a6b592f1d0103a0668","RunTimeTicks":21048199168,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"hevc","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"1080p HEVC SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":1391663,"BitDepth":null,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":800,"Width":1920,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"Main 10","Type":1,"AspectRatio":"2.40:1","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":120,"IsAnamorphic":null},{"Codec":"aac","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"English - AAC - 5.1","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"5.1","BitRate":187493,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":6,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"HE-AAC","Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"dan","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Danish - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"ger","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Ger - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":3,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"SDH","VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"SDH - English - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":4,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"spa","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Spanish - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":5,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"spa","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Spanish - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":6,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"fre","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Fre - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":7,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"ita","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Italian - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":8,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"dut","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Dut - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":9,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"nob","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Norwegian Bokm\u00E5l - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":10,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"pol","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Polish - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":11,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"por","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Portuguese - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":12,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"por","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Portuguese - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":13,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"fin","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Finnish - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":14,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"swe","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Swedish - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":15,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"srt","CodecTag":null,"Language":"pob","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":null,"CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Indefinido","LocalizedDefault":"Padr\u00E3o","LocalizedForced":"For\u00E7ado","LocalizedExternal":"Externo","DisplayTitle":"Pob - SRT - Externo","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":16,"Score":null,"IsExternal":true,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/data/M\u00EDdia/V\u00EDdeos/TV/The Mandalorian (2019)/Season 01/The Mandalorian (2019) - S01E03 - Chapter 3 The Sin [WEBRip-1080p Proper][10bit][x265][AAC 5.1].pt-BR.srt","PixelFormat":null,"Level":null,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":1579156,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -init_hw_device vaapi=va:/dev/dri/renderD128 -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:"/data/Mídia/Vídeos/TV/The Mandalorian (2019)/Season 01/The Mandalorian (2019) - S01E03 - Chapter 3 The Sin [WEBRip-1080p Proper][10bit][x265][AAC 5.1].mkv" -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -force_key_frames "expr:gte(t,n_forced*5)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12" -copyts -avoid_negative_ts disabled -start_at_zero -rc_mode VBR -b:v 5798597 -maxrate 5798597 -bufsize 11597194 -profile:v:0 high -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 libfdk_aac -ac 2 -ab 187493 -ar 48000 -af "volume=2" -y "/config/data/transcodes/5b1c41089e8a352af7c7689f6e447741.mkv"


ffmpeg version 5.0.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3 --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Input #0, matroska,webm, from 'file:/data/Mídia/Vídeos/TV/The Mandalorian (2019)/Season 01/The Mandalorian (2019) - S01E03 - Chapter 3 The Sin [WEBRip-1080p Proper][10bit][x265][AAC 5.1].mkv':
  Metadata:
    title           : The.Mandalorian.S01E03.Chapter.3.The.Sin.2160p.WEB-DL.DDP5.1.x265-TEPES  [1080p x265 10bit Joy][UTR]
    encoder         : libebml v1.3.10 + libmatroska v1.5.2
    creation_time   : 2020-11-11T02:37:55.000000Z
  Duration: 00:35:04.82, start: 0.000000, bitrate: 1391 kb/s
  Chapters:
    Chapter #0:0: start 3.003000, end 68.003000
      Metadata:
        title           : Recap start
    Chapter #0:1: start 68.003000, end 2104.820000
      Metadata:
        title           : Recap end
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv), 1920x800, SAR 1:1 DAR 12:5, 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS-eng         : 1201644
      DURATION-eng    : 00:35:04.770000000
      NUMBER_OF_FRAMES-eng: 50464
      NUMBER_OF_BYTES-eng: 316148140
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: aac (HE-AAC), 48000 Hz, 5.1, fltp
    Metadata:
      BPS-eng         : 187493
      DURATION-eng    : 00:35:04.789000000
      NUMBER_OF_FRAMES-eng: 49331
      NUMBER_OF_BYTES-eng: 49329227
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(dan): Subtitle: subrip
    Metadata:
      BPS-eng         : 21
      DURATION-eng    : 00:34:49.006000000
      NUMBER_OF_FRAMES-eng: 153
      NUMBER_OF_BYTES-eng: 5635
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(ger): Subtitle: subrip
    Metadata:
      BPS-eng         : 22
      DURATION-eng    : 00:34:48.881000000
      NUMBER_OF_FRAMES-eng: 184
      NUMBER_OF_BYTES-eng: 5864
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(eng): Subtitle: subrip
    Metadata:
      title           : SDH
      BPS-eng         : 36
      DURATION-eng    : 00:32:10.556000000
      NUMBER_OF_FRAMES-eng: 277
      NUMBER_OF_BYTES-eng: 8713
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(spa): Subtitle: subrip
    Metadata:
      BPS-eng         : 21
      DURATION-eng    : 00:34:48.881000000
      NUMBER_OF_FRAMES-eng: 172
      NUMBER_OF_BYTES-eng: 5667
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:6(spa): Subtitle: subrip
    Metadata:
      BPS-eng         : 21
      DURATION-eng    : 00:34:48.881000000
      NUMBER_OF_FRAMES-eng: 173
      NUMBER_OF_BYTES-eng: 5627
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:7(fre): Subtitle: subrip
    Metadata:
      BPS-eng         : 19
      DURATION-eng    : 00:34:48.881000000
      NUMBER_OF_FRAMES-eng: 173
      NUMBER_OF_BYTES-eng: 5218
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:8(ita): Subtitle: subrip
    Metadata:
      BPS-eng         : 20
      DURATION-eng    : 00:34:48.881000000
      NUMBER_OF_FRAMES-eng: 173
      NUMBER_OF_BYTES-eng: 5438
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:9(dut): Subtitle: subrip
    Metadata:
      BPS-eng         : 22
      DURATION-eng    : 00:34:48.881000000
      NUMBER_OF_FRAMES-eng: 163
      NUMBER_OF_BYTES-eng: 5777
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:10(nob): Subtitle: subrip
    Metadata:
      BPS-eng         : 19
      DURATION-eng    : 00:34:48.881000000
      NUMBER_OF_FRAMES-eng: 173
      NUMBER_OF_BYTES-eng: 5126
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:11(pol): Subtitle: subrip
    Metadata:
      BPS-eng         : 20
      DURATION-eng    : 00:34:48.881000000
      NUMBER_OF_FRAMES-eng: 172
      NUMBER_OF_BYTES-eng: 5343
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:12(por): Subtitle: subrip
    Metadata:
      BPS-eng         : 22
      DURATION-eng    : 00:34:48.881000000
      NUMBER_OF_FRAMES-eng: 172
      NUMBER_OF_BYTES-eng: 5872
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:13(por): Subtitle: subrip
    Metadata:
      BPS-eng         : 22
      DURATION-eng    : 00:34:48.881000000
      NUMBER_OF_FRAMES-eng: 172
      NUMBER_OF_BYTES-eng: 5887
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:14(fin): Subtitle: subrip
    Metadata:
      BPS-eng         : 19
      DURATION-eng    : 00:34:48.881000000
      NUMBER_OF_FRAMES-eng: 173
      NUMBER_OF_BYTES-eng: 5116
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:15(swe): Subtitle: subrip
    Metadata:
      BPS-eng         : 21
      DURATION-eng    : 00:34:48.881000000
      NUMBER_OF_FRAMES-eng: 151
      NUMBER_OF_BYTES-eng: 5635
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-11-11 02:37:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (aac (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[h264_vaapi @ 0x562d913e6180] Driver does not support some wanted packed headers (wanted 0xd, found 0).
[h264_vaapi @ 0x562d913e6180] Driver does not support packed sequence headers, but a global header is requested.
[h264_vaapi @ 0x562d913e6180] No global header will be written: this may result in a stream which is not usable for some purposes (e.g. not muxable to some containers).
Could not write header for output file #0 (incorrect codec parameters ?): Invalid data found when processing input
Error initializing output stream 0:0 -- 
[libfdk_aac @ 0x562d913ed4c0] 2 frames left in the queue on closing
Conversion failed!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nyanmisaka** [comment]
duplicate of #7642

**Comment by Vitorvlv** [comment]
Any chance this could be reopened? I'm using this ffmpeg https://github.com/jellyfin/jellyfin-ffmpeg/actions/runs/2490393422

It still doesn't work, but the error message is slightly different.
[ffmpeg.log](https://github.com/jellyfin/jellyfin/files/8895253/ffmpeg.log)

**Comment by Vitorvlv** [comment]
Using this version: https://github.com/jellyfin/jellyfin-ffmpeg/actions/runs/2492031971

A little variation, now it's not complaining about "the driver not supporting some wanted packed headers", but still doesn't work.

```
[h264_vaapi @ 0x55c9c5690580] Failed to create encode pipeline configuration: 25 (an invalid/unsupported value was supplied).
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[libfdk_aac @ 0x55c9c56f9ac0] 2 frames left in the queue on closing
Conversion failed!
```
[ffmpeg.log](https://github.com/jellyfin/jellyfin/files/8895738/ffmpeg.log)

**Comment by nyanmisaka** [comment]
Should be fixed by https://github.com/jellyfin/jellyfin-ffmpeg/pull/158/commits/e6dfc6b596e533845afda6f2e17570859f5b02ae

**Comment by nyanmisaka** [comment]
Let me know if the commit linked above works for you, so as I can merge that PR and tag a new release.

**Comment by markokruijer** [comment]
i'm having the same issue, thought it was related to the docker setup so then ran Jellyfin in the native OS but the issue remains. Is there a way I can test the above commit @nyanmisaka ? Happy to help out

**Comment by Vitorvlv** [comment]
Can confirm that this latest one: https://github.com/jellyfin/jellyfin-ffmpeg/actions/runs/2496453886

works for me, thanks for solving it so quickly, really appreciate it!

[log.txt](https://github.com/jellyfin/jellyfin/files/8904344/log.txt)
