### ISSUE TITLE
[Issue]:user has assess to Block items

### ISSUE THREAD

**Issue by Monirzadeh** [jellyfin/jellyfin#8339]
### Please describe your bug

If you set a tag (for example `hide`) in `Block items with tags` for user `jack` it hides content with `hide` tag for user `jack`.
But `jack` still can see and access content with `hide` tag. 
if content show in this section, it is not hide for `jack`
- Next Up
- Last Shows

user can see and play them

Last Movies section work fine and hide content with `hide` tag correctly.

### Jellyfin Version

Other

### if other:

10.8.4

### Environment

```markdown
- OS:Debian
- Virtualization:Docker
- Clients:Browser
- Browser:Firefox, Chrome, Safari
- Networking:Host
- Storage:local
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shadowghost** [comment]
Might be fixed by #8526

**Comment by Trezamere** [comment]
This is still broken in 10.8.9, makes parental access basically pointless if you have older movies as they have incorrect or "old" parental ratings. For example, I have my content ratings set to PG and lower but movies like Gallipoli were apparently rated PG, so trying to block "War" but it still shows up.

**Comment by Bond-009** [comment]
@Trezamere Did you try the master branch (unstable)?

**Comment by Trezamere** [comment]
> @Trezamere Did you try the master branch (unstable)?

No, can you reference a commit?

**Comment by Shadowghost** [comment]
Just try the current commit. Should have been fixed by #8526 and the likes.

**Comment by hutcheon** [comment]
Ran into this problem today.  Wanted to block someone from accessing a TV show.

Tried adding a blocked tag to the Show + Seasons, which successfully removed it from the TV Show listing for the blocked user, but using their profile, they could still watch episodes from the "Continue Watching" and "Next Up" lists.  When they selected an episode from either of those lists, Jellyfin would helpfully give links to previous episodes and next episodes in the season that they could browse to.  They could also watch the forbidden show, and if they watched the episode, it would auto-start the next episode in the season.  It would also let them find episodes in Search too -- not the Series, but some of the individual episodes (not sure why only some show up there?).

I also tried to change the Custom Parental Rating to a higher rating (again, on the Show + Seasons), which had the same experience.

I could successfully block it by editing the metadata of a "Continue Watching" episode, and adding a blocking tag, or custom parental rating to that specific episode.  It would then disappear from the list.  However, this isn't a solution because this series has many hundreds of episodes, and without bulk editing tools, it's a fool's errand.

Ended up pulling the offending series from the library and refreshing the library.

**Comment by Shadowghost** [comment]
This is fixed in current master and will be released to the public in stable release 10.9.

**Comment by veqryn** [comment]
Is this fixed for TV shows, where I've marked the whole TV show (but not each episode) with a tag to block it, but the individual episodes still show up under "Next Up"?

**Comment by Shadowghost** [comment]
Only if all of this is still happening in a current master build.
