### ISSUE TITLE
High CPU Load only with Live-TV, TV-Record OK!

### ISSUE THREAD

**Issue by Otako77** [jellyfin/jellyfin#8746]
Hello everyone,
My problem is the high CPU load and the film jerking when transcoding live TV programs (M3U) from my satellite receiver.

I have the following system: Ubuntu Linux native, currently 22.04.01, Jellyfin 10.8.7, I3-6100, 8GB RAM, 1650 GTX 5.20 driver, the M3U server is for IPTV is a VU+ Duo 4K SE with OpenATV 7.

Scenario 1:
I record a movie (UHD HEVC HDR Main 10) on the VU+ box (MPEG-TS) and transcode down to 1080 with 10Mbi. I have a frame rate of 250-300 fps, so great. The CPU sleeps at 10%, 

scenario 2
I'm watching the same show Live, TS Mpeg Stream (UHD HEVC HDR Main 10) my CPU goes up to 100% and I've only got 46-52 fps. The GPU is also at 30% The video contains errors and stutters.

What can I do. Does anyone have an idea why LIVE TV is not transcoded as quickly and well? Everything else works great. A Blu Ray is transcoded at 600+ fps. I can transcode several HD Streams. The System runs perfekt. 

I can watch Live-TV in FullHD but with a very high CPU load (50-60%). UHD ist 100% Load and jerks
When I record the same show, all transcoding is done with GPU. Very high FPS rate and CPU load is practically non-existent.

This Problems is on every Client. At the Moment my Client is Mac OS 11, M1 2020 Mac Air, Media Player 1.7.1 
I transcode because the bit rate should not exceed 10 Mbit.
Both Logs are from my M1 Air:

Work Perfekt: 
[perfekt.txt](https://github.com/jellyfin/jellyfin/files/10006829/perfekt.txt)

Live-TV-High CPU Load:

[live-high-CPU-Load.txt](https://github.com/jellyfin/jellyfin/files/10006839/live-high-CPU-Load.txt)

<img width="1148" alt="Live-TV-High-CPU" src="https://user-images.githubusercontent.com/88830944/201760224-b400fe75-7ed6-48e4-be5a-e62f086d0612.png">

<img width="1148" alt="Recorded-Film" src="https://user-images.githubusercontent.com/88830944/201760253-76b9ccb8-3729-41e4-84d9-c5f9c5e03923.png">

**Media Info of the file**

**Logs**

**FFmpeg Logs**

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: [e.g. Docker on Linux, Docker on Windows, Debian, Windows]
 - Jellyfin Version: [e.g. 10.0.1]
 - Hardware settings & device: [e.g. NVENC on GTX1060, VAAPI on Intel i7 8700K]
 - Reverse proxy: [e.g. no, nginx, apache, etc.]
 - Other hardware notes: [e.g. Media mounted in CIFS/SMB share, Media mounted from Google Drive]
 
**Client System (please complete the following information):**
 - Device: [e.g. Apple iPhone XS, Xbox One S, LG OLED55C8, Samsung Galaxy Note9, Custom HTPC]
 - OS: [e.g. iOS, Android, Windows, macOS]
 - Client: [e.g. Web/Browser, webOS, Android, Android TV, Electron]
 - Browser (if Web client): [e.g. Firefox, Chrome, Safari]
 - Client and Browser Version: [e.g. 10.3.4 and 68.0]

**Comment by nyanmisaka** [comment]
Fixed by #9430

**Comment by hugoamvieira** [comment]
I'm still seeing this same behaviour with 10.8.10. Watching live tv spikes the docker container's usage to over 100% as reported by cadvisor.

Using fedora server 38 as the host OS and proxmox as the hypervisor.

**Comment by srcrist** [comment]
Original submitter's issue closed by https://github.com/jellyfin/jellyfin/pull/9430. If anyone is still experiencing an issue, please submit a new issue with your details and logs so that your issue can be debugged.
