### ISSUE TITLE
Jellyfin 10.2.0 on docker always transcodes

### ISSUE THREAD

**Issue by drago-96** [jellyfin/jellyfin#926]
I am trying the new 10.2.0 version on docker; I made a clean install, and scan my movies library.
But when I started playing a movie, I noticed that jellyfin was transcoding due to "unsupported video profile", while on the 10.1.0 version I can DirectPlay that same movie.

The only thing I noticed is that on 10.2.0 the video codec profile is "100", while on 10.1.0 is "high".

If needed I can provide logs of both servers.

**Comment by JustAMan** [comment]
Can you provide mediainfo of the failing file?

**Comment by drago-96** [comment]
[Here](https://pastebin.com/Xg5F3iFy) are the outputs of `ffprobe` in both containers, and they seem pretty much the same.

The problem is that _every_ movie is transcoding, even when in the previous version it wasn't needed (it's h264/aac, and browsers can play it).
And every movie has "100" as profile instead of "High"...

**Comment by JustAMan** [comment]
@drago-96 could you please post more verbose `ffprobe` outputs?
Cmdline to get them should be `ffprobe -i /path/to/video.mkv -threads 0 -v info -print_format json -show_streams -show_chapters -show_format`

So far I have a suspicion that we were bitten by change of ffmpeg provider.

**Comment by drago-96** [comment]
It seems you are right: in the new container `ffprobe` returns `profile: 100` and `codec_long_name: unknown`!

https://pastebin.com/PKrDcs4Y

**Comment by cvium** [comment]
https://github.com/jrottenberg/ffmpeg/issues/78

**Comment by cvium** [comment]
From what I can tell, it's because of the build flag `--enable-small`, which means it doesn't load all the profiles https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/profiles.c#L24

This is not related to VAAPI, but jrottenberg's builds in general.

**Comment by hawken93** [comment]
I believe it's better to optimize for speed rather than size anyway

**Comment by JustAMan** [comment]
Can we submit a PR to jrottenberg upstream?

**Comment by EraYaN** [comment]
The other option is to include the correct tables in the server itself. FFmpeg.AutoGen will have those I believe, not sure if it will have the correct numerical values, but it should. And since we target a specific build of ffmpeg anyway...

**Comment by hawken93** [comment]
At least let sanely compiled ffmpegs still work if you do that, please make it handle both outputs in that case.. Otherwise pretty much any other ffmpeg will break with jf..

**Comment by cvium** [comment]
I think the plan is to create our own build without that flag. AutoGen seems overkill.

**Comment by joshuaboniface** [comment]
Should be fixed now with 10.2.1 and its custom Docker ffmpeg image, if not please let us know.

**Comment by drago-96** [comment]
Yes, now DirectPlaying works again!

**Comment by sauerj** [comment]
@joshuaboniface I still see this issue on Jellyfin 10.2.2 from  `jellyfin/jellyfin:latest` image.

What information do you need for further debugging?

**Comment by JustAMan** [comment]
What does transcode reasons in web ui say?

**Comment by sauerj** [comment]
> What does transcode reasons in web ui say?

The UI does not provide any information about the reason.

**Comment by JustAMan** [comment]
Then where did you see it's transcoding? Some relevant logs maybe? Also what client are you using?

**Comment by sauerj** [comment]
> Then where did you see it's transcoding? Some relevant logs maybe? Also what client are you using?

The UI indicates that it is transcoding, but states no reason. The picture quality is slightly reduced to the original and I see `ffmpeg` task with high cpu load. Also there are transcoding logs appearing.

Tested Clients so far:

- Mozilla Firefox 60 ESR Linux
- Chrome Android latest
- Mozilla Firefox Android latest

Notice here video codec H264 100 which @drago-96 mentioned above:
![transcoding-1](https://user-images.githubusercontent.com/14033792/54109154-24c1eb80-43de-11e9-9c9e-2841f236253c.png)
From admin ui:
![transcoding-2](https://user-images.githubusercontent.com/14033792/54109167-2ab7cc80-43de-11e9-862d-fb389a7cadb5.png)

First log entries after starting the video:
```
[2019-03-11 08:11:57.257 +00:00] [INF] "HTTP POST" "http://media.example.com:8096/emby/Items/80af07dacd658024bb3b8fa32540c809/PlaybackInfo?UserId=03a0390238ff46788c185b5ebf7b5a83&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&AudioStreamIndex=2&MediaSourceId=80af07dacd658024bb3b8fa32540c809&MaxStreamingBitrate=140000000". UserAgent: "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
[2019-03-11 08:11:57.259 +00:00] [INF] User policy for "Jens". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2019-03-11 08:11:57.259 +00:00] [INF] Profile: "Unknown Profile", Path: "/media/videos/movies/Movie 1/Movie 1.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-03-11 08:11:57.259 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/media/videos/movies/Movie 1/Movie 1.mkv"
[2019-03-11 08:11:57.259 +00:00] [INF] Profile: "Unknown Profile", Path: "/media/videos/movies/Movie 1/Movie 1.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-03-11 08:11:57.259 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/media/videos/movies/Movie 1/Movie 1.mkv"
[2019-03-11 08:11:57.259 +00:00] [INF] Profile: "Unknown Profile", Path: "/media/videos/movies/Movie 1/Movie 1.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2019-03-11 08:11:57.260 +00:00] [INF] Profile: "Unknown Profile", No direct play profiles found for Path: "/media/videos/movies/Movie 1/Movie 1.mkv"
[2019-03-11 08:11:57.260 +00:00] [INF] HTTP Response 200 to "10.79.64.45". Time: "3""ms". "http://media.example.com:8096/emby/Items/80af07dacd658024bb3b8fa32540c809/PlaybackInfo?UserId=03a0390238ff46788c185b5ebf7b5a83&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&AudioStreamIndex=2&MediaSourceId=80af07dacd658024bb3b8fa32540c809&MaxStreamingBitrate=140000000" ""
[2019-03-11 08:11:57.296 +00:00] [INF] "HTTP GET" "http://media.example.com:8096/emby/Items/80af07dacd658024bb3b8fa32540c809/Images/Backdrop?quality=100&tag=0cf617ab206945e6f76243ccf69e1fdc". UserAgent: "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
[2019-03-11 08:11:57.297 +00:00] [INF] HTTP Response 200 to "10.79.64.45". Time: "1""ms". "http://media.example.com:8096/emby/Items/80af07dacd658024bb3b8fa32540c809/Images/Backdrop?quality=100&tag=0cf617ab206945e6f76243ccf69e1fdc" ""
[2019-03-11 08:11:57.631 +00:00] [INF] HTTP "GET" "http://media.example.com:8096/emby/videos/80af07da-cd65-8024-bb3b-8fa32540c809/master.m3u8?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo1Mi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzUyLjB8MTUzMTMwNzE0OTI1MA11&MediaSourceId=80af07dacd658024bb3b8fa32540c809&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=2&VideoBitrate=139680000&AudioBitrate=320000&PlaySessionId=66938cfba048459f9026b8af11fdfadb&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=00606501a051b250f8f56ba03fb1478c&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51". "Host=media.example.com, User-Agent=Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0, Accept=*/*, Accept-Encoding=gzip, deflate, br, Accept-Language=de,en-US;q=0.7,en;q=0.3, Cookie=ajs_user_id=null; ajs_group_id=null; ajs_anonymous_id=%2200000000000000000000000000%22, Dnt=1, Referer=https://media.example.com/web/index.html, X-Forwarded-For=10.79.64.45, X-Forwarded-Host=media.example.com, X-Forwarded-Port=443, X-Forwarded-Proto=https, X-Forwarded-Server=114a00c38743, X-Real-Ip=10.79.64.45"
[2019-03-11 08:11:57.633 +00:00] [INF] HTTP Response 200 to "10.79.64.45". Time: "2""ms". "http://media.example.com:8096/emby/videos/80af07da-cd65-8024-bb3b-8fa32540c809/master.m3u8?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo1Mi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzUyLjB8MTUzMTMwNzE0OTI1MA11&MediaSourceId=80af07dacd658024bb3b8fa32540c809&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=2&VideoBitrate=139680000&AudioBitrate=320000&PlaySessionId=66938cfba048459f9026b8af11fdfadb&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=00606501a051b250f8f56ba03fb1478c&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51" ""
[2019-03-11 08:11:57.654 +00:00] [INF] HTTP "GET" "http://media.example.com:8096/emby/videos/80af07da-cd65-8024-bb3b-8fa32540c809/main.m3u8?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo1Mi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzUyLjB8MTUzMTMwNzE0OTI1MA11&MediaSourceId=80af07dacd658024bb3b8fa32540c809&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=2&VideoBitrate=139680000&AudioBitrate=320000&PlaySessionId=66938cfba048459f9026b8af11fdfadb&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=00606501a051b250f8f56ba03fb1478c&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51". "Host=media.example.com, User-Agent=Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0, Accept=*/*, Accept-Encoding=gzip, deflate, br, Accept-Language=de,en-US;q=0.7,en;q=0.3, Cookie=ajs_user_id=null; ajs_group_id=null; ajs_anonymous_id=%2200000000000000000000000000%22, Dnt=1, Referer=https://media.example.com/web/index.html, X-Forwarded-For=10.79.64.45, X-Forwarded-Host=media.example.com, X-Forwarded-Port=443, X-Forwarded-Proto=https, X-Forwarded-Server=114a00c38743, X-Real-Ip=10.79.64.45"
[2019-03-11 08:11:57.664 +00:00] [INF] HTTP Response 200 to "10.79.64.45". Time: "11""ms". "http://media.example.com:8096/emby/videos/80af07da-cd65-8024-bb3b-8fa32540c809/main.m3u8?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo1Mi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzUyLjB8MTUzMTMwNzE0OTI1MA11&MediaSourceId=80af07dacd658024bb3b8fa32540c809&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=2&VideoBitrate=139680000&AudioBitrate=320000&PlaySessionId=66938cfba048459f9026b8af11fdfadb&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=00606501a051b250f8f56ba03fb1478c&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51" ""
[2019-03-11 08:11:57.720 +00:00] [INF] HTTP "GET" "http://media.example.com:8096/emby/videos/80af07da-cd65-8024-bb3b-8fa32540c809/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo1Mi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzUyLjB8MTUzMTMwNzE0OTI1MA11&MediaSourceId=80af07dacd658024bb3b8fa32540c809&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=2&VideoBitrate=139680000&AudioBitrate=320000&PlaySessionId=66938cfba048459f9026b8af11fdfadb&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=00606501a051b250f8f56ba03fb1478c&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51". "Host=media.example.com, User-Agent=Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0, Accept=*/*, Accept-Encoding=gzip, deflate, br, Accept-Language=de,en-US;q=0.7,en;q=0.3, Cookie=ajs_user_id=null; ajs_group_id=null; ajs_anonymous_id=%2200000000000000000000000000%22, Dnt=1, Referer=https://media.example.com/web/index.html, X-Forwarded-For=10.79.64.45, X-Forwarded-Host=media.example.com, X-Forwarded-Port=443, X-Forwarded-Proto=https, X-Forwarded-Server=114a00c38743, X-Real-Ip=10.79.64.45"
[2019-03-11 08:11:57.723 +00:00] [INF] /usr/local/bin/ffmpeg -f matroska,webm -i file:"/media/videos/movies/Movie 1/Movie 1.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:2 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 139680000 -bufsize 279360000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -copyts -vsync -1 -codec:a:0 copy -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/config/transcoding-temp/6f9499ccf00b749cf4c954b9dd4ae2b7.m3u8" -y "/config/transcoding-temp/6f9499ccf00b749cf4c954b9dd4ae2b7%d.ts"
[2019-03-11 08:11:58.382 +00:00] [INF] returning "/config/transcoding-temp/6f9499ccf00b749cf4c954b9dd4ae2b70.ts"
[2019-03-11 08:11:58.387 +00:00] [INF] HTTP Response 200 to "10.79.64.45". Time: "667""ms". "http://media.example.com:8096/emby/videos/80af07da-cd65-8024-bb3b-8fa32540c809/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo1Mi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzUyLjB8MTUzMTMwNzE0OTI1MA11&MediaSourceId=80af07dacd658024bb3b8fa32540c809&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=2&VideoBitrate=139680000&AudioBitrate=320000&PlaySessionId=66938cfba048459f9026b8af11fdfadb&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=00606501a051b250f8f56ba03fb1478c&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51" ""
[2019-03-11 08:11:58.491 +00:00] [INF] HTTP "GET" "http://media.example.com:8096/emby/videos/80af07da-cd65-8024-bb3b-8fa32540c809/hls1/main/1.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo1Mi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzUyLjB8MTUzMTMwNzE0OTI1MA11&MediaSourceId=80af07dacd658024bb3b8fa32540c809&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=2&VideoBitrate=139680000&AudioBitrate=320000&PlaySessionId=66938cfba048459f9026b8af11fdfadb&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=00606501a051b250f8f56ba03fb1478c&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51". "Host=media.example.com, User-Agent=Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0, Accept=*/*, Accept-Encoding=gzip, deflate, br, Accept-Language=de,en-US;q=0.7,en;q=0.3, Cookie=ajs_user_id=null; ajs_group_id=null; ajs_anonymous_id=%2200000000000000000000000000%22, Dnt=1, Referer=https://media.example.com/web/index.html, X-Forwarded-For=10.79.64.45, X-Forwarded-Host=media.example.com, X-Forwarded-Port=443, X-Forwarded-Proto=https, X-Forwarded-Server=114a00c38743, X-Real-Ip=10.79.64.45"
[2019-03-11 08:11:58.617 +00:00] [INF] "HTTP POST" "http://media.example.com:8096/emby/Sessions/Playing". UserAgent: "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
[...]
```
ffmpeg-transcoding log:
```
http://media.example.com:8096/emby/videos/80af07da-cd65-8024-bb3b-8fa32540c809/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo1Mi4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzUyLjB8MTUzMTMwNzE0OTI1MA11&MediaSourceId=80af07dacd658024bb3b8fa32540c809&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=2&VideoBitrate=139680000&AudioBitrate=320000&PlaySessionId=66938cfba048459f9026b8af11fdfadb&api_key=5f9546ac33194dd68ce3575a5ed924e3&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=00606501a051b250f8f56ba03fb1478c&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51

{"Protocol":"File","Id":"80af07dacd658024bb3b8fa32540c809","Path":"/media/videos/movies/Movie 1/Movie 1.mkv","Type":"Default","Container":"mkv,webm","Size":6699127296,"Name":"Movie 1","IsRemote":false,"ETag":"00606501a051b250f8f56ba03fb1478c","RunTimeTicks":99229343744,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"h264","TimeBase":"1/1000","CodecTimeBase":"1001/48000","VideoRange":"SDR","DisplayTitle":"1080P H264","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"BitRate":5400924,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":800,"Width":1920,"AverageFrameRate":23.9760246,"RealFrameRate":23.9760246,"Profile":"100","Type":"Video","AspectRatio":"2.40:1","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":41},{"Codec":"aac","Language":"ger","TimeBase":"1/1000","CodecTimeBase":"1/48000","Title":"Surround","DisplayTitle":"Ger AAC 5.1 Default","IsInterlaced":false,"ChannelLayout":"5.1","BitRate":320000,"Channels":6,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Profile":"1","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"aac","Language":"eng","TimeBase":"1/1000","CodecTimeBase":"1/48000","Title":"Surround","DisplayTitle":"Eng AAC 5.1","IsInterlaced":false,"ChannelLayout":"5.1","BitRate":320000,"Channels":6,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Profile":"1","Type":"Audio","Index":2,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0}],"Formats":[],"Bitrate":6040924,"RequiredHttpHeaders":{}}

/usr/local/bin/ffmpeg -f matroska,webm -i file:"/media/videos/movies/Movie 1/Movie 1.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:2 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 139680000 -bufsize 279360000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames "expr:gte(t,n_forced*3)" -copyts -vsync -1 -codec:a:0 copy -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "/config/transcoding-temp/6f9499ccf00b749cf4c954b9dd4ae2b7.m3u8" -y "/config/transcoding-temp/6f9499ccf00b749cf4c954b9dd4ae2b7%d.ts"


ffmpeg version 4.0.3 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-vaapi --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gnutls --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libxvid --enable-libx264 --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-cuvid --enable-nvenc --enable-version3 --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[...]
```

**Comment by sauerj** [comment]
So I just started a new instance of jellyfin with a fresh database, the issue was gone.
Back to the old database, issue appears again.

After rescanning the library with "replace all metadata" the Profile shows now "High" instead of "100" and DirectStream works again.

So it was only a "corrupted" database.

**Comment by JustAMan** [comment]
Good to know that.
So all entries that got scanned using `ffprobe` with numerical profile were badly recognized and were in need of re-scanning.

**Comment by Exist2Resist** [comment]
This is still an issue, I deployed a new instance of jellyfin and the media is transcoding, when I disable transcoding in user profile the media plays fine and CPU usage drops.

**Comment by cvium** [comment]
This issue is 2 years old. Please don't necro-post, thanks.
