### ISSUE TITLE
[Issue]: Grouped version count is not changed when a version is deleted from the file system

### ISSUE THREAD

**Issue by boblinthewild** [jellyfin/jellyfin#9281]
### Please describe your bug

After grouping one or more versions, the group count is displayed on the poster that is displayed for that group. As well, Media Info shows all the versions in that group, and it's possible to select which version to play.

Subsequently deleting one or more versions from the file system and rescanning the library, the deleted versions are correctly removed from Media Info and version selection from Play. However, the version count that is displayed on the poster is not decremented to account for the deleted version(s).

Example/steps to reproduce:

[**_NOTE_**: this applies to multiple versions stored in their own individual folders, rather than multiple versions stored within the same folder]

1. Group two items/versions of the same movie, verifying that the poster count = 2
2. In the file system, delete one of the items that had been grouped in Jellyfin
3. Rescan the library containing the original group for changed/updated media
4. The poster count still = 2, even though Media Info now shows only one item
5. The Split function is no longer available, so there is no way to change the count shown on the poster

### Jellyfin Version

10.8.0

### if other:

10.8.9

### Environment

```markdown
- OS: Windows 11
- Virtualization: None
- Clients: Browser
- Browser: MS Edge
- FFmpeg Version: n/a
- Playback Method: n/a
- Hardware Acceleration: n/a
- Plugins: None
- Reverse Proxy: n/a
- Base URL: n/a
- Networking: n/a
- Storage: n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by srcrist** [comment]
I was able to reproduce this issue in a testing environment as well, with some additional steps and some other buggy behavior observed.

With a fresh instance on Windows 10, I added a copy of a movie and verified that it was scanned and imported correctly by Jellyfin. Then I duplicated the movie and changed the file name and moved it to a new directory corresponding to the new "version." The second copy was also scanned and imported correctly. I then used the Jellyfin web UI to group the two versions together and it merged correctly and showed two versions correctly on the poster in the UI.

When I then moved one copy from the library storage and re-scanned, it correctly removed the deleted version and showed only one copy in the UI.

The first buggy behavior then surfaced when I added the exact same file and folder BACK to the library storage. After a scan, it put the re-integrated copy back into the listing for the existing movie, and both versions were accessible from the version select dropdown. However, the option to ungroup the two versions was no longer functional. They were seemingly forever grouped together without the ability to split them. There was also no indication on the poster in the UI that there were two grouped items in this listing.

I then removed the clone again, modified the file and folder names again to create another "new" movie/version and this time after a scan Jellyfin added a second copy, as expected, but BOTH listings in the UI displayed the indicator for two versions even though there were only two versions in storage and neither of them had been grouped.

![image](https://user-images.githubusercontent.com/29871690/217672974-25cfe645-6eef-4683-b5f0-c7ce6fdaa040.png)

When both of these items were grouped using the UI, it grouped both listings together, but now with an indicator that there were three items in the group. When I removed one of the items from the library storage, the poster continued to indicate that there were two items in the group, even though there was only one movie on storage.

![image](https://user-images.githubusercontent.com/29871690/217673231-55ff379e-3ef4-4b35-bb6d-4814939a73de.png)

I archived the library.db for this small test instance. Feel free to comment if it would be of assistance.

**Comment by srcrist** [comment]
This previous issue is poorly documented, but also appears relevant: https://github.com/jellyfin/jellyfin/issues/8766

**Comment by JPVenson** [comment]
go away bot

**Comment by dinosmm** [comment]
I thought I had an issue with the Merge Versions plugin, but it turns out I am having the exact same issue as described here. 

I removed the alternate version of all episodes of a TV show, and now got stuck with the counter showing '2' on every episode, even though there is only one version remaining in the filesystem and everywhere else on the UI.

**Comment by boblinthewild** [comment]
[FYI, I'm the OP] It doesn't seem like the developers think this is much of a problem since they let the bug go 'stale.' And perhaps in the grand scheme of things it doesn't jump to the top of the priority list, but to me it represented the sort of thing that a well-performing application should not do. I found a few other similar problems and eventually concluded Jellyfin isn't really ready for prime time.

**Comment by JPVenson** [comment]
> [FYI, I'm the OP] It doesn't seem like the developers think this is much of a problem since they let the bug go 'stale.' And perhaps in the grand scheme of things it doesn't jump to the top of the priority list, but to me it represented the sort of thing that a well-performing application should not do. I found a few other similar problems and eventually concluded Jellyfin isn't really ready for prime time.

Hey there. I am actively observing this bug. We saw it. However as you said, no dev took it yet and spend his _free time_ to fix it. You are welcome to fix it and contribute. Please report any bug you found here or ask in our chat if you need help with it. We are aware that JF has issues but we already spend much time fixing other stuff and all of us pick what we like. If you dont want Jellyfin anymore there are two mayor alternatives: Plex and Emby you can check out.

**Comment by boblinthewild** [comment]
> Hey there. I am actively observing this bug. We saw it. However as you said, no dev took it yet and spend his _free time_ to fix it. You are welcome to fix it and contribute. Please report any bug you found here or ask in our chat if you need help with it. We are aware that JF has issues but we already spend much time fixing other stuff and all of us pick what we like. If you dont want Jellyfin anymore there are two mayor alternatives: Plex and Emby you can check out.

Hi, glad to know someone is watching it. I understand the open development model, but decided stuff like this would probably live on for too long in such a model and so abandoned my attempt to use it. I've been using Plex for many years, and was hoping JF might be a good alternative. I ran them in parallel for a couple of months, but unfortunately it didn't pan out.

**Comment by dinosmm** [comment]
> You are welcome to fix it and contribute

I'm nowhere near the skill level required for something like this, but, assuming I could pump up my C# skills, and being unfamiliar with the Jellyfin codebase, is there any indication where I might need to start looking in the code to study this bug and to try to think of a potential solution?

**Comment by JPVenson** [comment]
> > You are welcome to fix it and contribute
> 
> I'm nowhere near the skill level required for something like this, but, assuming I could pump up my C# skills, and being unfamiliar with the Jellyfin codebase, is there any indication where I might need to start looking in the code to study this bug and to try to think of a potential solution?

Well thats a bit of a catch22. JF has a pretty ... diverse code base and is not really what i would recommend for C# beginners. But just taken from the top of the list
https://github.com/jellyfin/jellyfin/issues/10309
might be a good point to investigate and look into.

**Comment by theshoeshiner** [comment]
For anyone following this - I just reported a dup of this issue which led me to this. I plan to take a look at the code sometime in the next few days. I haven't specifically worked on the code that manages versions, but I've worked on other pieces of the server codebase so I think it's within the realm of possibility that I can come up with a fix in the next couple weeks.

**Comment by thedagnode** [comment]
Hi. I just encountered this same issue myself. I fixed it by lifting out the movie from the library, then rescanned library, pasted the movie back in and rescanned the library. Not sure if that helps with the investigation.

**Comment by slmingol** [comment]
Confirming I'm seeing this same bug at the moment as well.
![image](https://github.com/jellyfin/jellyfin/assets/15072/0fc365ea-64dd-4cb5-9ace-de550422b5d0)

**Comment by AurelienMarchand** [comment]
I confirm this issue is still happening with version 10.10.6

**Comment by JPVenson** [comment]
@AurelienMarchand could you check the current master if this bug still persists?

**Comment by Nekzuris** [comment]
Still in 10.11.0-r8.
I fixed it by regrouping the movie with another and then the split button was available and fixed the count.

**Comment by ireun** [comment]
@JPVenson I can still confirm that on version 10.11.3 this issue still persists
