### ISSUE TITLE
Playback and transcoding stops near end of file, jellyfin-ffmpeg exits with code 139 

### ISSUE THREAD

**Issue by sks316** [jellyfin/jellyfin#9743]
**Media Info of the file**
```
Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost)
Container: mkv
Path: /home/raid/Media/TV/Tom & Jerry (1940)/Season 1/Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv
Size: 204 MB

Video
Title: 1080p HEVC SDR
Codec: HEVC
Profile: Main 10
Level: 120
Resolution: 1478x1080
Aspect ratio: 4:3
Interlaced: No
Framerate: 23.976025
Bitrate: 3069 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: Mono - English - AAC - Default
Language: eng
Codec: AAC
Profile: LC
Layout: mono
Channels: 1 ch
Bitrate: 192 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

Audio
Title: Commentary w/animator Mark Kausler - English - AAC - Mono
Language: eng
Codec: AAC
Profile: LC
Layout: mono
Channels: 1 ch
Bitrate: 191 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: Commentary w/historian Earl Kress & comedienne Nicole Parker - English - AAC - Mono
Language: eng
Codec: AAC
Profile: LC
Layout: mono
Channels: 1 ch
Bitrate: 192 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Subtitle
Title: English - PGSSUB
Language: eng
Codec: PGSSUB
Default: No
Forced: No
External: No

Subtitle
Title: Fre - PGSSUB
Language: fre
Codec: PGSSUB
Default: No
Forced: No
External: No
```

**Logs**
```
[2023-05-08 23:24:55.550 -05:00] [INF] User policy for "lillie". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2023-05-08 23:24:55.551 -05:00] [INF] StreamBuilder.BuildVideoItem( Profile="Anonymous Profile", Path="/home/raid/Media/TV/Tom & Jerry (1940)/Season 1/Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=VideoCodecNotSupported, AudioCodecNotSupported ) "media:/videos/c26c4e12-ab62-f689-fbe5-f499b6de1432/master.m3u8?MediaSourceId=c26c4e12ab62f689fbe5f499b6de1432&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139808000&AudioBitrate=192000&AudioSampleRate=48000&MaxFramerate=23.976025&api_key=<token>&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=d02c18b21d1fdfa200d892c0ed7d28ab&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&hevc-level=120&hevc-videobitdepth=10&hevc-profile=main10&hevc-audiochannels=1&aac-profile=lc&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported"
[2023-05-08 23:24:56.375 -05:00] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2023-05-08 23:24:56.376 -05:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:\"/home/raid/Media/TV/Tom & Jerry (1940)/Season 1/Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv\" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 3069629 -maxrate 3069629 -bufsize 6139258 -force_key_frames:0 \"expr:gte(t,0+n_forced*3)\" -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24\" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f.m3u8\""
[2023-05-08 23:24:57.032 -05:00] [WRN] Slow HTTP Response from "http://192.168.0.2:8096/videos/c26c4e12-ab62-f689-fbe5-f499b6de1432/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgQ3JPUyB4ODZfNjQgMTQ1NDEuMC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTEyLjAuMC4wIFNhZmFyaS81MzcuMzZ8MTY4MzU4ODg2MzM4NA11&MediaSourceId=c26c4e12ab62f689fbe5f499b6de1432&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139808000&AudioBitrate=192000&AudioSampleRate=48000&MaxFramerate=23.976025&PlaySessionId=561292c947ba4c68a2e6e5689408fad0&api_key=f8fe9b7cb0324e87b16197cd730b493a&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=d02c18b21d1fdfa200d892c0ed7d28ab&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&hevc-level=120&hevc-videobitdepth=10&hevc-profile=main10&hevc-audiochannels=1&aac-profile=lc&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported&runtimeTicks=0&actualSegmentLengthTicks=30000000" to "192.168.0.226" in 0:00:00.6593978 with Status Code 200
[2023-05-08 23:24:58.020 -05:00] [INF] Stopping ffmpeg process with q command for "/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f.m3u8"
[2023-05-08 23:24:58.104 -05:00] [INF] FFmpeg exited with code 0
[2023-05-08 23:24:58.104 -05:00] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2023-05-08 23:24:58.105 -05:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -ss 00:04:39.000 -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:\"/home/raid/Media/TV/Tom & Jerry (1940)/Season 1/Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv\" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 3069629 -maxrate 3069629 -bufsize 6139258 -force_key_frames:0 \"expr:gte(t,279+n_forced*3)\" -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24\" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 93 -hls_segment_filename \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f.m3u8\""
[2023-05-08 23:24:58.932 -05:00] [WRN] Slow HTTP Response from "http://192.168.0.2:8096/videos/c26c4e12-ab62-f689-fbe5-f499b6de1432/hls1/main/93.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgQ3JPUyB4ODZfNjQgMTQ1NDEuMC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTEyLjAuMC4wIFNhZmFyaS81MzcuMzZ8MTY4MzU4ODg2MzM4NA11&MediaSourceId=c26c4e12ab62f689fbe5f499b6de1432&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139808000&AudioBitrate=192000&AudioSampleRate=48000&MaxFramerate=23.976025&PlaySessionId=561292c947ba4c68a2e6e5689408fad0&api_key=f8fe9b7cb0324e87b16197cd730b493a&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=d02c18b21d1fdfa200d892c0ed7d28ab&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&hevc-level=120&hevc-videobitdepth=10&hevc-profile=main10&hevc-audiochannels=1&aac-profile=lc&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported&runtimeTicks=2790000000&actualSegmentLengthTicks=30000000" to "192.168.0.226" in 0:00:00.9207101 with Status Code 200
[2023-05-08 23:25:15.508 -05:00] [INF] FFmpeg exited with code 0
[2023-05-08 23:27:13.988 -05:00] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2023-05-08 23:27:13.988 -05:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -ss 00:07:24.000 -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:\"/home/raid/Media/TV/Tom & Jerry (1940)/Season 1/Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv\" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 3069629 -maxrate 3069629 -bufsize 6139258 -force_key_frames:0 \"expr:gte(t,444+n_forced*3)\" -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24\" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 148 -hls_segment_filename \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f.m3u8\""
[2023-05-08 23:27:15.022 -05:00] [WRN] Slow HTTP Response from "http://192.168.0.2:8096/videos/c26c4e12-ab62-f689-fbe5-f499b6de1432/hls1/main/148.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgQ3JPUyB4ODZfNjQgMTQ1NDEuMC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTEyLjAuMC4wIFNhZmFyaS81MzcuMzZ8MTY4MzU4ODg2MzM4NA11&MediaSourceId=c26c4e12ab62f689fbe5f499b6de1432&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139808000&AudioBitrate=192000&AudioSampleRate=48000&MaxFramerate=23.976025&PlaySessionId=561292c947ba4c68a2e6e5689408fad0&api_key=f8fe9b7cb0324e87b16197cd730b493a&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=d02c18b21d1fdfa200d892c0ed7d28ab&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&hevc-level=120&hevc-videobitdepth=10&hevc-profile=main10&hevc-audiochannels=1&aac-profile=lc&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported&runtimeTicks=4440000000&actualSegmentLengthTicks=30000000" to "192.168.0.226" in 0:00:01.0348848 with Status Code 200
[2023-05-08 23:27:21.198 -05:00] [INF] FFmpeg exited with code 0
[2023-05-08 23:27:21.887 -05:00] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2023-05-08 23:27:21.887 -05:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -ss 00:08:30.000 -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:\"/home/raid/Media/TV/Tom & Jerry (1940)/Season 1/Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv\" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 3069629 -maxrate 3069629 -bufsize 6139258 -force_key_frames:0 \"expr:gte(t,510+n_forced*3)\" -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24\" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 170 -hls_segment_filename \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f.m3u8\""
[2023-05-08 23:27:22.809 -05:00] [WRN] Slow HTTP Response from "http://192.168.0.2:8096/videos/c26c4e12-ab62-f689-fbe5-f499b6de1432/hls1/main/170.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgQ3JPUyB4ODZfNjQgMTQ1NDEuMC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTEyLjAuMC4wIFNhZmFyaS81MzcuMzZ8MTY4MzU4ODg2MzM4NA11&MediaSourceId=c26c4e12ab62f689fbe5f499b6de1432&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139808000&AudioBitrate=192000&AudioSampleRate=48000&MaxFramerate=23.976025&PlaySessionId=561292c947ba4c68a2e6e5689408fad0&api_key=f8fe9b7cb0324e87b16197cd730b493a&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=d02c18b21d1fdfa200d892c0ed7d28ab&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&hevc-level=120&hevc-videobitdepth=10&hevc-profile=main10&hevc-audiochannels=1&aac-profile=lc&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported&runtimeTicks=5100000000&actualSegmentLengthTicks=30000000" to "192.168.0.226" in 0:00:00.9241929 with Status Code 200
[2023-05-08 23:27:24.878 -05:00] [INF] FFmpeg exited with code 0
[2023-05-08 23:27:25.380 -05:00] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2023-05-08 23:27:25.380 -05:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -ss 00:08:57.000 -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:\"/home/raid/Media/TV/Tom & Jerry (1940)/Season 1/Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv\" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 3069629 -maxrate 3069629 -bufsize 6139258 -force_key_frames:0 \"expr:gte(t,537+n_forced*3)\" -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24\" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 179 -hls_segment_filename \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f.m3u8\""
[2023-05-08 23:27:26.302 -05:00] [WRN] Slow HTTP Response from "http://192.168.0.2:8096/videos/c26c4e12-ab62-f689-fbe5-f499b6de1432/hls1/main/179.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgQ3JPUyB4ODZfNjQgMTQ1NDEuMC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTEyLjAuMC4wIFNhZmFyaS81MzcuMzZ8MTY4MzU4ODg2MzM4NA11&MediaSourceId=c26c4e12ab62f689fbe5f499b6de1432&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139808000&AudioBitrate=192000&AudioSampleRate=48000&MaxFramerate=23.976025&PlaySessionId=561292c947ba4c68a2e6e5689408fad0&api_key=f8fe9b7cb0324e87b16197cd730b493a&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=d02c18b21d1fdfa200d892c0ed7d28ab&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&hevc-level=120&hevc-videobitdepth=10&hevc-profile=main10&hevc-audiochannels=1&aac-profile=lc&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported&runtimeTicks=5370000000&actualSegmentLengthTicks=30000000" to "192.168.0.226" in 0:00:00.9230514 with Status Code 200
[2023-05-08 23:27:26.672 -05:00] [INF] FFmpeg exited with code 0
[2023-05-08 23:27:27.389 -05:00] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2023-05-08 23:27:27.389 -05:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -ss 00:09:09.000 -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:\"/home/raid/Media/TV/Tom & Jerry (1940)/Season 1/Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv\" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 3069629 -maxrate 3069629 -bufsize 6139258 -force_key_frames:0 \"expr:gte(t,549+n_forced*3)\" -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24\" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 183 -hls_segment_filename \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f.m3u8\""
[2023-05-08 23:27:27.884 -05:00] [INF] FFmpeg exited with code 0
[2023-05-08 23:27:27.911 -05:00] [WRN] Slow HTTP Response from "http://192.168.0.2:8096/videos/c26c4e12-ab62-f689-fbe5-f499b6de1432/hls1/main/183.ts?DeviceId=TW96aWxsYS81LjAgKFgxMTsgQ3JPUyB4ODZfNjQgMTQ1NDEuMC4wKSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTEyLjAuMC4wIFNhZmFyaS81MzcuMzZ8MTY4MzU4ODg2MzM4NA11&MediaSourceId=c26c4e12ab62f689fbe5f499b6de1432&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139808000&AudioBitrate=192000&AudioSampleRate=48000&MaxFramerate=23.976025&PlaySessionId=561292c947ba4c68a2e6e5689408fad0&api_key=f8fe9b7cb0324e87b16197cd730b493a&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=d02c18b21d1fdfa200d892c0ed7d28ab&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&hevc-level=120&hevc-videobitdepth=10&hevc-profile=main10&hevc-audiochannels=1&aac-profile=lc&TranscodeReasons=VideoCodecNotSupported,%20AudioCodecNotSupported&runtimeTicks=5490000000&actualSegmentLengthTicks=30000000" to "192.168.0.226" in 0:00:00.523676 with Status Code 200
[2023-05-08 23:27:28.068 -05:00] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2023-05-08 23:27:28.068 -05:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -ss 00:09:12.000 -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:\"/home/raid/Media/TV/Tom & Jerry (1940)/Season 1/Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv\" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 3069629 -maxrate 3069629 -bufsize 6139258 -force_key_frames:0 \"expr:gte(t,552+n_forced*3)\" -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24\" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 184 -hls_segment_filename \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f.m3u8\""
[2023-05-08 23:27:28.469 -05:00] [INF] FFmpeg exited with code 0
[2023-05-08 23:27:28.616 -05:00] [INF] Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2023-05-08 23:27:28.616 -05:00] [INF] "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -ss 00:09:15.000 -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:\"/home/raid/Media/TV/Tom & Jerry (1940)/Season 1/Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv\" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 3069629 -maxrate 3069629 -bufsize 6139258 -force_key_frames:0 \"expr:gte(t,555+n_forced*3)\" -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24\" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 185 -hls_segment_filename \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f.m3u8\""
[2023-05-08 23:27:28.927 -05:00] [ERR] FFmpeg exited with code 139
[2023-05-08 23:27:28.941 -05:00] [ERR] Error processing request. URL "GET" "/videos/c26c4e12-ab62-f689-fbe5-f499b6de1432/hls1/main/185.ts".
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 139
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
   at lambda_method1373(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2023-05-08 23:27:41.728 -05:00] [INF] Deleting partial stream file(s) "/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f.m3u8"
[2023-05-08 23:27:43.252 -05:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.8.10" playing "Puss Gets The Boot". Stopped at "0" ms
```

**FFmpeg Logs**
```
/videos/c26c4e12-ab62-f689-fbe5-f499b6de1432/hls1/main/170.ts

{"Protocol":0,"Id":"c26c4e12ab62f689fbe5f499b6de1432","Path":"/home/raid/Media/TV/Tom \u0026 Jerry (1940)/Season 1/Tom \u0026 Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":213563728,"Name":"Tom \u0026 Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost)","IsRemote":false,"ETag":"d02c18b21d1fdfa200d892c0ed7d28ab","RunTimeTicks":5565850112,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"hevc","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","VideoRangeType":"SDR","VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"1080p HEVC SDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":3069629,"BitDepth":10,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":1080,"Width":1478,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"Main 10","Type":1,"AspectRatio":"4:3","Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":120,"IsAnamorphic":null},{"Codec":"aac","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"Mono","VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"Mono - English - AAC - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"mono","BitRate":192000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":1,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"LC","Type":0,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"aac","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"Commentary w/animator Mark Kausler","VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"Commentary w/animator Mark Kausler - English - AAC - Mono","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"mono","BitRate":191999,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":1,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"LC","Type":0,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"aac","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"Commentary w/historian Earl Kress \u0026 comedienne Nicole Parker","VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"Commentary w/historian Earl Kress \u0026 comedienne Nicole Parker - English - AAC - Mono","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"mono","BitRate":192000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":1,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"LC","Type":0,"AspectRatio":null,"Index":3,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"PGSSUB","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","DisplayTitle":"English - PGSSUB","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":4,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"PGSSUB","CodecTag":null,"Language":"fre","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","DisplayTitle":"Fre - PGSSUB","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":5,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":3645628,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 00:08:30.000 -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -hwaccel vaapi -hwaccel_output_format vaapi -autorotate 0 -i file:"/home/raid/Media/TV/Tom & Jerry (1940)/Season 1/Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 3069629 -maxrate 3069629 -bufsize 6139258 -force_key_frames:0 "expr:gte(t,510+n_forced*3)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24" -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 170 -hls_segment_filename "/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f.m3u8"


ffmpeg version 6.0-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[matroska,webm @ 0x55e001f78fc0] Could not find codec parameters for stream 4 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (200000000) and 'probesize' (5000000) options
[matroska,webm @ 0x55e001f78fc0] Could not find codec parameters for stream 5 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (200000000) and 'probesize' (5000000) options
Input #0, matroska,webm, from 'file:/home/raid/Media/TV/Tom & Jerry (1940)/Season 1/Tom & Jerry (1940) - S01E01 - Puss Gets The Boot (1080p BluRay x265 Ghost).mkv':
  Metadata:
    encoder         : libebml v1.3.10 + libmatroska v1.5.2
    creation_time   : 2020-05-02T17:56:02.000000Z
    Writing frontend: StaxRip v1.7.0.6
  Duration: 00:09:16.59, start: 0.000000, bitrate: 3069 kb/s
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv), 1478x1080, SAR 1080:1109 DAR 1478:1109, 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS-eng         : 2498429
      DURATION-eng    : 00:09:13.595000000
      NUMBER_OF_FRAMES-eng: 13273
      NUMBER_OF_BYTES-eng: 172889755
      _STATISTICS_WRITING_APP-eng: mkvmerge v42.0.0 ('Overtime') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-02 17:56:02
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: aac (LC), 48000 Hz, mono, fltp (default)
    Metadata:
      title           : Mono
      BPS-eng         : 192000
      DURATION-eng    : 00:09:16.565000000
      NUMBER_OF_FRAMES-eng: 26089
      NUMBER_OF_BYTES-eng: 13357570
      _STATISTICS_WRITING_APP-eng: mkvmerge v42.0.0 ('Overtime') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-02 17:56:02
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Audio: aac (LC), 48000 Hz, mono, fltp
    Metadata:
      title           : Commentary w/animator Mark Kausler
      BPS-eng         : 191999
      DURATION-eng    : 00:09:16.565000000
      NUMBER_OF_FRAMES-eng: 26089
      NUMBER_OF_BYTES-eng: 13357548
      _STATISTICS_WRITING_APP-eng: mkvmerge v42.0.0 ('Overtime') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-02 17:56:02
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Audio: aac (LC), 48000 Hz, mono, fltp
    Metadata:
      title           : Commentary w/historian Earl Kress & comedienne Nicole Parker
      BPS-eng         : 192000
      DURATION-eng    : 00:09:16.565000000
      NUMBER_OF_FRAMES-eng: 26089
      NUMBER_OF_BYTES-eng: 13357583
      _STATISTICS_WRITING_APP-eng: mkvmerge v42.0.0 ('Overtime') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-02 17:56:02
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(eng): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS-eng         : 8650
      DURATION-eng    : 00:06:44.529000000
      NUMBER_OF_FRAMES-eng: 46
      NUMBER_OF_BYTES-eng: 437429
      _STATISTICS_WRITING_APP-eng: mkvmerge v42.0.0 ('Overtime') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-02 17:56:02
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(fre): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS-eng         : 4413
      DURATION-eng    : 00:08:47.110000000
      NUMBER_OF_FRAMES-eng: 38
      NUMBER_OF_BYTES-eng: 290830
      _STATISTICS_WRITING_APP-eng: mkvmerge v42.0.0 ('Overtime') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-02 17:56:02
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_vaapi))
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
Output #0, hls, to '/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f.m3u8':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0: Video: h264 (High), vaapi(tv, bt709, progressive), 1478x1080 [SAR 1080:1109 DAR 1478:1109], q=2-31, 3069 kb/s, 23.98 fps, 90k tbn (default)
    Metadata:
      BPS-eng         : 2498429
      DURATION-eng    : 00:09:13.595000000
      NUMBER_OF_FRAMES-eng: 13273
      NUMBER_OF_BYTES-eng: 172889755
      _STATISTICS_WRITING_APP-eng: mkvmerge v42.0.0 ('Overtime') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-02 17:56:02
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      encoder         : Lavc60.3.100 h264_vaapi
  Stream #0:1(eng): Audio: aac (LC), 48000 Hz, mono, fltp (default)
    Metadata:
      title           : Mono
      BPS-eng         : 192000
      DURATION-eng    : 00:09:16.565000000
      NUMBER_OF_FRAMES-eng: 26089
      NUMBER_OF_BYTES-eng: 13357570
      _STATISTICS_WRITING_APP-eng: mkvmerge v42.0.0 ('Overtime') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-05-02 17:56:02
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
frame=    0 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
[hls @ 0x55e002265800] Opening '/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f170.ts' for writing
frame=  180 fps=0.0 q=-0.0 size=N/A time=00:00:07.65 bitrate=N/A speed=12.2x    
[hls @ 0x55e002265800] Opening '/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f171.ts' for writing
frame=  360 fps=319 q=-0.0 size=N/A time=00:00:15.23 bitrate=N/A speed=13.5x    
[hls @ 0x55e002265800] Opening '/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f172.ts' for writing
[hls @ 0x55e002265800] Opening '/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f173.ts' for writing
frame=  546 fps=335 q=-0.0 size=N/A time=00:00:22.95 bitrate=N/A speed=14.1x    
[hls @ 0x55e002265800] Opening '/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f174.ts' for writing
[hls @ 0x55e002265800] Opening '/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f175.ts' for writing
frame=  735 fps=345 q=-0.0 size=N/A time=00:00:30.74 bitrate=N/A speed=14.4x    
[hls @ 0x55e002265800] Opening '/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f176.ts' for writing
frame=  927 fps=352 q=-0.0 size=N/A time=00:00:38.80 bitrate=N/A speed=14.7x    
[hls @ 0x55e002265800] Opening '/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f177.ts' for writing
[hls @ 0x55e002265800] Opening '/var/lib/jellyfin/transcodes/3049671199f1873439690317c9fdf84f178.ts' for writing
frame= 1045 fps=356 q=-0.0 Lsize=N/A time=00:00:45.80 bitrate=N/A speed=15.6x    
video:15298kB audio:1211kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

**Server System (please complete the following information):**
 - OS: openmediavault Debian Linux
 - Jellyfin Version: 10.8.10
 - Hardware settings & device: VA-API on Intel Core i5-10400
 - Reverse proxy: caddy
 - Other hardware notes: Folder is shared to other devices in SMB share, primarily for uploading new media
 
**Client System (please complete the following information):**
 - Device: Acer Chromebook Spin 15
 - OS: Chrome OS
 - Client: Web
 - Browser (if Web client): Chrome
 - Client and Browser Version: 112.0.5615.134

**Comment by dotbanana** [comment]
I have exactly the same error on quite a lot of files.  
It happens always in the last couple of minutes

**Comment by Shadowghost** [comment]
Is there a specific reason you're using VA-API instead of QSV?

**Comment by sks316** [comment]
> Is there a specific reason you're using VA-API instead of QSV?

I tried to use QSV, but it simply wouldn't work. Transcoding would always fail. VA-API worked fine though, so I used it instead.

**Comment by Shadowghost** [comment]
Do you mind trying again and sharing the logs? Might give us some more info on if it's a general ffmpeg/driver issue or something within Jellyfin

**Comment by dotbanana** [comment]
Yesterday in my viewing session i could reproduce the crash in every affected file. It crashed always at exactly the same time. 
Now today the specific files affected yesterday work without problem. 
I had exactly the same output in my log as the OT.   
My CPU is Intel Core i7-8700.  
I use VA-API because of Linux. In the guides i followed installing Jellyfin it was mentioned that for Linux QSV has no drivers. 

Info of the Media:
`
VIDEO

Titel 1080p H264 SDR
Codec H264
AVC Yes
Profil High
Level 40
Auflösung 1920x1080
Seitenverhältnis16:9
Zeilensprungverfahren No
Bildrate 25
Bitrate 10672 kbps
Bit-Tiefe 8 bit
Videobereich SDR
Video range type SDR
Farbraumbt 709
Farbübertragung bt709
Primärfarben bt709
Pixelformat yuv420p
Referenz-Frames 1
NAL 4

AUDIO 

Titel Ger - Dolby Digital - Stereo - Default
Sprache ger
Codec AC3
Darstellung stereo
Kanäle 2 ch
Bitrate 224 kbps
Abtastrate 48000 Hz
Standard Yes
Erzwungen No
Extern No`

**Comment by Shadowghost** [comment]
We ship the required drivers with out ffmpeg, so you should be able to use QSV just fine.

**Comment by olebittner** [comment]
I have the same problem when encoding using VA-API. For some (not all) videos: transcoding and playback stops near the end of file with ffmpeg error code 139.

I was using VA-API because at the time I was setting up my instance I was having problems getting QSV to work. But that was years ago. So while reading through this issue, I switched to QSV and it works fine and solved the problem for me.

**Comment by Nerexbcd** [comment]
I'm also having this problem, the episode is stopping suddenly with ffmpeg error 139.

I'm using VA-API, and when i did the configuration i was also not able to use QSV, like @sks316, maybe something to do with the CPU generation? I say this because I have an Intel Core i5-8400.

At the moment this only happen to me with a specific series that the episodes are encoded in 1080p HVEC SDR.
The suddenly stop is not even consistent, on the same episode it can stop 1 minute before the end of it, but if i restart the episode and set the episode time to a bit after, it starts working again for some seconds, but ends up stopping again.

This is the error on the log:
```
file:\"/mnt/Media/Series/[Redacted]/S4/[Redacted].mkv\" -autoscale 0 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 7345753 -maxrate 7345753 -bufsize 14691506 -force_key_frames:0 \"expr:gte(t,1293+n_forced*3)\" -vf \"setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale_vaapi=format=nv12:extra_hw_frames=24\" -codec:a:0 libfdk_aac -ac 2 -ab 384000 -ar 48000 -af \"volume=2\" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 431 -hls_segment_filename \"/var/lib/jellyfin/transcodes/023bf7395773e17a84f3b94cf4a1cf34%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/var/lib/jellyfin/transcodes/023bf7395773e17a84f3b94cf4a1cf34.m3u8\""
[2024-04-13 22:16:18.169 +01:00] [ERR] FFmpeg exited with code 139
[2024-04-13 22:16:18.268 +01:00] [ERR] Error processing request. URL "GET" "/videos/4fad3ead-6efd-c8ea-8371-3da8da70893f/hls1/main/431.ts".
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 139
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
   at lambda_method1269(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-04-13 22:16:23.315 +01:00] [WRN] Slow HTTP Response from "https://[Redacted]/Sessions/Playing/Progress" to "[Redacted]" in 0:00:01.6321131 with Status Code 204
```

**Comment by ErikTellas** [comment]
Also having the same issue. Also near the end of a video file.

**Comment by jordan-dalby** [comment]
I'm getting this same error. Started with the latest Jellyfin update (10.9.2), previous major release did not have this issue. Also using VAAPI, though QSV does the same.

**Comment by jordan-dalby** [comment]
This issue seems to have been resolved by upgrading to 10.9.3.

**Comment by felix920506** [comment]
comments say fixed, please open new issue if still happening
